### ISSUE TITLE
Purging caches programatically

### ISSUE THREAD

**Issue by 5u623l20** [cirruslabs/cirrus-ci-docs#1004]
# Description
Currently there is no option to purge caches programmatically other than invalidating them from the web console. So if we could add caches early after they are being used that would reduce a lot of carbon footprint. :)

# Context
We are using the the caches in between multiple tasks. While the generated caches are being used on the next dependent task there is no use of it but it's still taking the space. So if we could invalidate them early with an option like `purge_after_download: yes` that would be great.
Currently we are using some caches in between build and test tasks with the ID $CIRRUS_CHANGE_IN_REPOS and some other strings. On the next build we don't have any usage of this cache but it's still being hold by the cache server and giving us the option to invalidate them in the web console.

# Anything Else
We can do it manually but if we can do it from the configs that would be great.

This might be related to https://github.com/cirruslabs/cirrus-ci-docs/issues/988

**Comment by fkorotkov** [comment]
I think it will make sense to add `DELETE` option [Cirrus HTTP Cache](https://cirrus-ci.org/guide/writing-tasks/#http-cache) so users will have full control over the lifecycle.

Ideally we'd have a custom TTL per cache entry but services like S3, GCS and others don't support it unfortunetly.
