### ISSUE TITLE
Unable to trigger job on private repository with compute credits

### ISSUE THREAD

**Issue by bcecchinato** [cirruslabs/cirrus-ci-docs#1008]
## Expected Behavior

My repository is private on Github, which means that I need to use a paid plan or compute credits.
I've enabled use_compute_credits in my job, but the build is still blocked.

## Real Behavior

The job is blocked with a warning (payment required).

# Related Info

The job is here : https://cirrus-ci.com/build/6105273927467008.

**Comment by fkorotkov** [comment]
Hey @bcecchinato, you don't need compute credits for **personal** private repositories. With the [Private Personal Repositories](https://github.com/marketplace/cirrus-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45OTI=#pricing-and-setup) you'll get unlimited minutes for your builds and **twice** the [concurrency limits](https://cirrus-ci.org/faq/#are-there-any-limits) for all public and private builds initiated by your account.

Improving the docs in #1009

**Comment by bcecchinato** [comment]
@fkorotkov Yes I agree, but I don't have the [Private Personal Repositories](https://github.com/marketplace/cirrus-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45OTI=#pricing-and-setup) on my account ;) I'm on the free tier which is why I use compute credits.

**Comment by fkorotkov** [comment]
Free tier with compute credits only works for organizational private repositories. We added it because some of our customers have non engineers committing changes like translations to repositories. It didn't make sense for them to pay for their seats on monthly basis.

**Comment by bcecchinato** [comment]
> Free tier with compute credits only works for organizational private repositories.

Has it changed recently ? Because It was working until the 24/05 without having my repo in an organization.

**Comment by fkorotkov** [comment]
It's not recent. If it worked before it must've been a bug. 😪  Sorry for the confusion. Please let us know if you'd like a refund for your credits.

**Comment by bcecchinato** [comment]
No problems :) I'll use the credits with my free account, I'm not about 20$ since the service is worth it.

BTW if one day you consider allowing compute credits for individuals I'm interested (i'm using about 5 minutes of CI per day, the private plan is not really worth the use for me).
