### ISSUE TITLE
adjust cache size limit

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#1010]
# Description

I'd like to be able to increase the default cache size limit can be increased beyond 2GB via some property.

# Context

We have a bunch of Rust builds whose compressed cache size exceeds 2GB.
This may sound big but reusing the cache is still faster than recompiling the project from scratch.
On Github Actions this is possible

# Anything Else

I only need this for caching using GCS (self-hosted) if you're concerned about cost.

**Comment by fkorotkov** [comment]
Hey @geekflyer, is should've been already possible. Removing the legacy agent size check in https://github.com/cirruslabs/cirrus-ci-agent/pull/231

**Comment by fkorotkov** [comment]
Should be working now.
