### ISSUE TITLE
Report in progress status in GitHub check run when re-run is triggered

### ISSUE THREAD

**Issue by jack1142** [cirruslabs/cirrus-ci-docs#1015]
# Description

Right now, after the task fails it reports the failed status to GitHub which makes sense. However, if a re-run of the task is triggered (definitely happens for a manual re-run done both by a hook through API and by a user through UI, not sure about the automatic one), the check run continues to have its status set to `failed` until Cirrus CI finishes the whole re-run of that task.

What I would like to request is that once the re-run is triggered, the check run should have the updated in-progress status instead of the failed conclusion.
Ideally, for an automatic re-run, as well as for a manual re-run done by a hook, the `failed` status would never be reported in the first place to avoid potentially triggering the whole check suite conclusion (which could trigger GH Actions) but as long as the core of this feature request is implemented, the check run would only be marked as failed for few seconds so it probably wouldn't be that big a deal.

# Context

I have set up [the Email Action from Cirrus CI docs](https://cirrus-ci.org/guide/notifications/#email-action)  in order to send out build failure emails. However, if a hook reruns the task, I would like to not receive email notifications about the failed build. Considering I run a bunch of tasks (some of which run into intermittent network errors), generally, it should be enough that the check run is updated when the re-run is triggered as there will still be other tasks running, and the check suite won't be marked as completed though as I said, ideally it just would never report the `failed` status when a re-run is triggered automatically.

# Anything Else

I haven't played with task execution dependencies so I'm unsure how those interact with re-runs, it is possible that the logic that would need to be implemented for this could also benefit that use case in some way.

**Comment by fkorotkov** [comment]
The UI part is a known GitHub bug that affects not only Cirrus but any app that uses Checks API including Actions. Also Cirrus is actually doing this:

> for an automatic re-run, as well as for a manual re-run done by a hook, the failed status would never be reported in the first place

So for the automatically re-runable tasks it's alredy should work as you expect. Sorry for late reply, if you still experiencing the issue prease re-open with a lint to a task that got reported as failed but was automatically re-run.
