### ISSUE TITLE
Windows container `Failed to start: FAILED_PRECONDITION: Async operation failed with provisioning state: Failed`

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-docs#102]
Hello, since 3 weeks I've discovered for my cirrus-ci integrations the following behavior:
All of my Windows-based builds fail with the message 

`Failed to start: FAILED_PRECONDITION: Async operation failed with provisioning state: Failed`

Was there a change of the Windows-based container handling? 
As a task/job reference, see: https://cirrus-ci.com/task/5199234603155456

**Comment by fkorotkov** [comment]
@ppaulweber there were no changes to Windows builds recently. This error comes directly from Azure API and it wasn't marked as retryable. Have you tried to re-run the task? In the meantime let me add such error to a list of retryable failures.

**Comment by ppaulweber** [comment]
@fkorotkov thanks for the fast reply. Yes I've tried several times. In very rare cases the build succeeds but most of the time the same error message appears. Could it be a resource consumption issue/problem/restriction?

**Comment by fkorotkov** [comment]
Interesting. I saw a similar behavior of failing to start a container on Azure when a container is pretty outdated. Azure stores locally 3 latests versions of `microsoft/windowsservercore:ltsc2016` so they perform the best. `cirrusci/windowsservercore:2016` is also updated frequently enough to catch up with `microsoft/windowsservercore:ltsc2016`. If your container is big and was built a long time ago it will be worth to rebuild it just to  update the base layers.

**Comment by fkorotkov** [comment]
BTW I've just rebuilt `cirrusci/windowsservercore:2016` to update the base layer. 😅

**Comment by fkorotkov** [comment]
@ppaulweber could you please try to rebuild the base image and re-open the issue if it won't help?

**Comment by ppaulweber** [comment]
@fkorotkov sorry for the delay ... thanks for the quick hint regarding the updating of the base layers. I'm already in the process of doing it, and will retry then to rebuild the tasks/jobs in question and report here back to you.

**Comment by ppaulweber** [comment]
@fkorotkov the task/job builds are running again :tada: thanks again :clap:

**Comment by fkorotkov** [comment]
Wonderful news! 🎉🎉🎉
