### ISSUE TITLE
Possibility to include [skip ci] or [skip cirrus] in the commit message body

### ISSUE THREAD

**Issue by fxlb** [cirruslabs/cirrus-ci-docs#1025]
# Description

Add a flag in the YAML configuration like:
`check_skip_in_message_body: true|false`
(default to `false`to keep current behavior.)
or
`check_skip: title|body|both` ?
(default to `title` to keep current behavior.)

# Context

The need to include [skip ci] or [skip cirrus] in the first line of the commit message is a little ugly.
This title/summary line should be reserved to the project code.
Thus the possibility to include [skip ci] or [skip cirrus] in the body of the message would be useful.

**Comment by infrastation** [comment]
I would also like to see this feature implemented.

**Comment by fkorotkov** [comment]
What do you think of checking the last line? I've seen messages formatted in a way to have kind of "tags" as the last line of the message.

**Comment by fxlb** [comment]
Checking the last line for [skip ci] / [skip cirrus] could be a good alternative.

**Comment by fxlb** [comment]
Thank you!

**Comment by infrastation** [comment]
Confirmed working, thank you.
