### ISSUE TITLE
RFE: AWS EC2 AMI search vs direct reference

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#1039]
(I'm not sure if this is the correct repo. for this or not)

A very handy feature of GCE is that we're able to name our own VM images at (image) creation time.  This makes is very easy for humans to tell at a glance, what image is used in CI and even employ custom (helpful) naming schemes.  The other option is to use the Family-name (handy sometimes), but again it's a user-defined value at image-creation time - so it can be made human-friendly.

However, when using Cirrus with AWS EC2, the only option is to reference Amazon generated AMI IDs.  These things are horribly unfriendly to humans.  It's impossible to tell at a glance what it is, represents, or even if it's the right image.  I propose that Cirrus-CI support a tag search for AMI's, with an enforced 1-item result.  Such that less than or greater than 1 result causes a "image not found" error.

My inspiration for this is how [Packer addresses this same problem in `source_ami_filter` (docs).](https://www.packer.io/plugins/builders/amazon/ebs#source_ami_filter).  Though honestly I don't think something even that extensive is necessary.  Even a match against a few tag name/value pairs would probably be good enough.  Bonus points for allowing `*`-style wild-card matches to tag values :smile:

**Comment by cevich** [comment]
This is working beautifully for podman CI.  SO MUCH easier than fussing with the silly and unreadable AMI ID's.  THANK YOU!

**Comment by fkorotkov** [comment]
Wonderful! Great to hear that!
