### ISSUE TITLE
Script documentation doesn't warn that commands are run with "call" on Windows

### ISSUE THREAD

**Issue by guyharris** [cirruslabs/cirrus-ci-docs#1044]
## Expected Behavior

A script command `cl/?` should, if it can find the `cl` command, get it to print its help message.

## Real Behavior

The `call` command printed *its* help message.

# Related Info

This is a (tick one of the following):

- [x ] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/#script-instruction

That section says "A script instruction executes commands via `shell` on Unix or `batch` on Windows."  On Windows, commands are executed by 

    call {text of command}

[Microsoft's documentation for that command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/call) says that it "Calls one batch program from another without stopping the parent batch program.".  Microsoft's documentation really explain very well what the syntax is, but, for example, if you try to run a "batch program" (which appears to include built-in commands as well as .bat files) with the `/?` flag, the `/?` flag is processed by `call`.

Perhaps the documentation should warn that if you want a command or command executed exactly as typed, you should put it into a .bat file and run that.

(BTW, what is the purpose of the `call` command in cmd.exe, and why is it being used?  Is it that if you just use a .bat file's name as a command, it's run inside the cmd.exe instance other than in a separate process, and `call` should be used if it should be run in a separate process?  I.e., is `batchfile` in cd.exe equivalent `. shellscript` in a UN\*X shell, and `call batchfile` equivalent to just `shell script` in a UN\*X shell?)

**Comment by fkorotkov** [comment]
The reason is to be able to stop execution upon first command failing. [Cirrus Agent is modifying the script](https://github.com/cirruslabs/cirrus-ci-agent/blob/d10b879023a4a8158aa650648c3526d79897fa1d/internal/executor/cmd_windows.go#L36) in a way  to fail fast with:

```batch
if %errorlevel% neq 0 exit /b %errorlevel%
```

Documenting the caveat in #1077
