### ISSUE TITLE
manual tasks are aborted when next build runs

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#1048]
Hi,

I have a few tasks defined as trigger_type: manual, because they're to expensive / slow to run all the time. I also have set up email notification for failed builds. Whenever I push the next commit, tasks from the prior build are marked as aborted, which then triggers email notifications.

See e.g. https://cirrus-ci.com/build/5472469027913728 - all the aborted tasks are manual tasks. They were marked as such until the subsequent push https://cirrus-ci.com/build/5793407590203392 auto cancelled them.

This does not happen entirely reliably. See e.g. https://cirrus-ci.com/build/6241600127893504 - half the manual tasks are marked as failed, the others still have the 'paused' icon. I've so far only seen this with pull requests.

Regards,

Andres

**Comment by fkorotkov** [comment]
A fix should be propagated to production in about hour or two.
