### ISSUE TITLE
Support custom audience for CIRRUS_OIDC_TOKEN

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#1057]
# Description

I don't entirely understand the technical details of how it works, but from what I do understand, in order to support "trusted" publishing to npm, additional steps will be required on Cirrus CI's end to ensure that it works.

Note: *the RFC is still pending*, just opening this issue so that the team can be aware of it.

# Context

https://github.com/npm/rfcs/pull/626
Rendered version: https://github.com/npm/rfcs/blob/link-packages-to-source-and-build/accepted/0000-link-packages-to-source-and-build.md

# Anything Else

Proposal is still in the discussion phase it appears, will update this issue as needed.

**Comment by fkorotkov** [comment]
This is fixed in https://github.com/cirruslabs/cirrus-ci-docs/pull/1058
