### ISSUE TITLE
The container group 'cirrus-ci-task-5469608679047168' does not exist.

### ISSUE THREAD

**Issue by pzahemszky** [cirruslabs/cirrus-ci-docs#106]
I got the following error for [one of my Cirrus CI tasks](https://cirrus-ci.com/task/5469608679047168) (that uses `windows_container` with the `python:3.7` image).

`
Failed to start: FAILED_PRECONDITION: The container group 'cirrus-ci-task-5469608679047168' does not exist.
`

I would have expected that task to succeed, since I can see in the log that the scripts have finished successfully. The error disappeared after I clicked "Re-run".

I assume the failure is unrelated to the commit that triggered the task. What happened here?

**Comment by fkorotkov** [comment]
It was a race condition. Container finished too fast. Fixed the race condition and deployed the fix. Thanks for reporting!
