### ISSUE TITLE
Include Java on Apple Silicon images

### ISSUE THREAD

**Issue by stuartmorgan** [cirruslabs/cirrus-ci-docs#1060]
# Description

(I'm not sure if this is a feature request or a bug report; filing as a feature request.)

Currently the Apple Silicon images don't have a Java runtime, unlike the Intel macOS images; it would be helpful if they did.

# Context

The lack of JRE means that we can't trivially move Flutter tasks involving Android over to the new architecture (https://github.com/flutter/flutter/issues/109821).

I'm not aware of a trivial way to install the JRE via scripts, so it would be very convenient if the images (or some provided image variant) already had it installed.

**Comment by fkorotkov** [comment]
The Intel VMs previously installed Android SDK and therefore JVM. But Android emulators were not quite working on M1 so we removed it. Do you only need Java or full blown Android SDK with emulators?

**Comment by stuartmorgan** [comment]
We don't need emulators, but we do need the SDK. Our use case running Flutter builds targeting Android (and some Java unit tests of generated code).

**Comment by fkorotkov** [comment]
@stuartmorgan PTAL at https://github.com/cirruslabs/macos-image-templates/pull/50 and test out `ghcr.io/cirruslabs/macos-ventura-xcode:14-beta-5` VM. If that works for you, we'll rebuild the Monterey version as well with Xcode 13.4.1 if you need it.

**Comment by stuartmorgan** [comment]
> nd test out `ghcr.io/cirruslabs/macos-ventura-xcode:14-beta-5` VM

Yep, that successfully ran the tests that failed with the current image, so an updated version of the non-beta image with that change should be perfect.

**Comment by fkorotkov** [comment]
Will close the issue once ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1 is updated.

**Comment by fkorotkov** [comment]
Please try ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1

**Comment by stuartmorgan** [comment]
I'm having issues with that image:
```
Persistent worker failed to start the task: tart isolation failed: failed to create VM cloned from "ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1": tart command returned non-zero exit code: "2022-08-23 11:45:07.925 tart[32124:15972057] *** Terminating app due to uncaught exception 'NSFileHandleOperationException', reason: '*** -[NSConcreteFileHandle writeData:]: No space left on device'"
```

In one case I was able to re-run successfully, but it seems persistent for another (https://cirrus-ci.com/task/4960624370253824). Maybe an agent-level issue?

**Comment by stuartmorgan** [comment]
Hm, we're actually seeing this with existing runs using `ghcr.io/cirruslabs/macos-monterey-xcode:13.4` so it looks like it's not the new image. I'll contact support separately.

**Comment by jmagman** [comment]
> Please try ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1

Thank you @fkorotkov!
