### ISSUE TITLE
Don't Auto Cancel the Build if PR closes

### ISSUE THREAD

**Issue by Sushrut1101** [cirruslabs/cirrus-ci-docs#1061]
Hi!
Is it possible to not cancel the PR build if the PR Closes?

I get the error "PR was Closed!"

Maybe I need to do something related to `auto_cancellation:` ?

**Comment by fkorotkov** [comment]
I don't believe this is configurable at the moment. What is your use case? Seems reasonable to cancel tasks when PRs are closed.

**Comment by Sushrut1101** [comment]
> I don't believe this is configurable at the moment. What is your use case? Seems reasonable to cancel tasks when PRs are closed.

I have a Telegram Bot that creates a PR to e Repo to launch a CI Build.
If someone else runs the command before the Old Build is Complete, the PR Gets Deleted and the Build gets cancelled

**Comment by Sushrut1101** [comment]
> > I have a Telegram Bot that creates a PR to e Repo to launch a CI Build.
> 
> Please be aware that it might violate our Term of Services and your repository might get [blocked](https://cirrus-ci.org/faq/#repository-is-blocked) in this case.
> 
> As for the original issue of canceling build upon PR closure. Seems reasonable overall and your use case is in gray area IMO. Unless there are more legit use cases we won't change the behaviour.

Hey!
One of my repo just got blocked today after your reply.
May I know the reason please?

Repo: https://github.com/DumprX/DumprX-CI.git

It's neither a Crypto Mining repo nor an Android Building repo.
It just extracts the firmware and push it on GitLab.

**Comment by fkorotkov** [comment]
> Dump Android ROMs/Firmwares Online, via a PR, for free!

Looks like you use Cirrus CI as a powerhouse for arbitrary CPU-intensive calculations: create a PR to process something and upload somewhere. Doesn't look like you use for testing of code in the repository itself.
