### ISSUE TITLE
Error while loading tasks: RESOURCE_EXHAUSTED: PR mergability state is not yet calculated!!

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#1064]
We are seeing this a lot lately, meaning we have to manually trigger the CI on each push.

For example: https://cirrus-ci.com/build/4629720997298176

![Screen Shot 2022-08-24 at 10 26 04](https://user-images.githubusercontent.com/6399679/186369254-5b9196b2-4d73-47c1-bd3d-2c375ab6cdb3.png)

**Comment by fkorotkov** [comment]
Seems like slowness on GitHub side. Fixed it on Cirrus side so it will wait up to 5 minutes for the mergability state.

**Comment by fkorotkov** [comment]
You can simply retrigger build manually

**Comment by MarcoFalke** [comment]
Thanks! I'd say 30 or 60 seconds should be enough, but 5 minutes work as well.
