### ISSUE TITLE
mac: available space for tasks is too low

### ISSUE THREAD

**Issue by kasperk81** [cirruslabs/cirrus-ci-docs#1065]
The initial space available to tasks is 29% of total size (8.0 out of 27 Gi) on mac VMs.

```sh
admin@admins-Virtual-Machine cirrus-ci-build % df -h $(pwd)
Filesystem     Size   Used  Avail Capacity iused    ifree %iused  Mounted on
/dev/disk2s5   27Gi  4.2Gi  8.0Gi    35%  168922 83885400    0%   /System/Volumes/Data
```

installing a few dependencies and building a medium to large size project run out of space quick. How can we claim more space (from total of 27Gi)?

**Comment by fkorotkov** [comment]
Which image are you using? And how much more space you'd like?

**Comment by kasperk81** [comment]
It was `ghcr.io/cirruslabs/macos-monterey-base:latest`.

Having <30% is not ideal. If we have ~ 50% 60% of total size, I'd be a happy camper. :slightly_smiling_face:

**Comment by fkorotkov** [comment]
Should be available with the next rebuild of the images via https://github.com/cirruslabs/macos-image-templates/pull/51

**Comment by kasperk81** [comment]
Thanks for fixing it so fast Fedor!

Can I see somewhere when the new images are ready?

**Comment by fkorotkov** [comment]
We usually update them once there is a new version of macOS. In the meantime you can try to use the xcode variant which has 30+Gb free.
