### ISSUE TITLE
Cirrus is not reporting the correct build status for flutter/packages post-submit CI

### ISSUE THREAD

**Issue by keyonghan** [cirruslabs/cirrus-ci-docs#1067]
## Expected Behavior

The CI should be green based on the build status: https://cirrus-ci.com/build/5031166657953792

## Real Behavior

The tree is still red: https://github.com/flutter/packages/runs/8140901913?check_suite_focus=true
![Screen Shot 2022-09-01 at 3 36 42 PM](https://user-images.githubusercontent.com/54558023/188024398-ae4dfa0d-2562-4fd6-85f3-ad6e925f61aa.png)

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue

Related: https://github.com/flutter/flutter/issues/110810

**Comment by keyonghan** [comment]
From the explorer, it returns two builds: https://cirrus-ci.com/build/6311195392081920 (`EXECUTING`) and https://cirrus-ci.com/build/5031166657953792 (`COMPLETED`). But neither is `FAILURE`.
```
{
  "data": {
    "searchBuilds": [
      {
        "id": "6311195392081920",
        "branch": "main",
        "pullRequest": 2543,
        "changeIdInRepo": "fa9b71a3da60129237f257c61a147f7c538ad2d9",
        "changeTimestamp": 1662052942636,
        "status": "EXECUTING"
      },
      {
        "id": "5031166657953792",
        "branch": "main",
        "pullRequest": null,
        "changeIdInRepo": "fa9b71a3da60129237f257c61a147f7c538ad2d9",
        "changeTimestamp": 1662046887000,
        "status": "COMPLETED"
      }
    ]
  }
}
```

**Comment by fkorotkov** [comment]
Moved discussion to https://github.com/flutter/flutter/issues/110810
