### ISSUE TITLE
windows: Don't start tasks with SEM_NOGPFAULTERRORBOX set

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#1068]
Hi,

due to go's defaults windows tasks get started with error mode set to a non-default value of 0x8003:
https://github.com/golang/go/blob/master/src/runtime/os_windows.go#L553
https://github.com/golang/go/blob/master/src/runtime/signal_windows.go#L22
0x8003 is SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX
whereas the normal windows default appears to be 0x8001 these days.

I've configured our CI with a JIT debugger so we can collect stack traces of failures. But right now that only works for processes (or their children) that do SetErrorMode() to remove SEM_NOGPFAULTERRORBOX, because, as unintuitive as that may sound, SEM_NOGPFAULTERRORBOX prevents invocation of the JIT debugger as well as windows-error-reporting.

There's afaict no easy way to change the error mode of an existing cmd.exe, making it quite hard to change this for script steps in cirrus _script blocks.

It would be nice if cirrus's agent could call SetErrorMode() before starting the job.

It might not be a good idea to do so by default, because those stupid crash windows also prevented by SEM_NOGPFAULTERRORBOX can cause CI to hang. Perhaps cirrus's base image could do something like
```
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v DontShowUI /t REG_DWORD /d 1
```
which should prevent that problem?

Or perhaps it could be configurable with some CIRRUS_ variable?

Regards,

Andres

**Comment by edigaryev** [comment]
You can now use `CIRRUS_WINDOWS_ERROR_MODE` environment variable to set your own desired `SetErrorMode()` value.

**Comment by anarazel** [comment]
Awesome!
