### ISSUE TITLE
Deleting or archiving failed tests

### ISSUE THREAD

**Issue by cjdb** [cirruslabs/cirrus-ci-docs#107]
Would it be possible for Cirrus to support deleting or at least archiving failed tests, specifically those that are failed because of bad Cirrus config scripts?

## Motivation

Because I can't test my `.cirrus.yml` script locally, I can sometimes spend many commits trying to remotely debug. While I don't mind doing this, it would be nice if I could somehow nuke those from my log of failed builds, as they make up a large portion of my failed builds 🙁 

## Proposal 1

I often rebase my branch so that my Cirrus-related commits are reduced to one commit, so if it'd be nice to add a something like a `[cirrus-config]` tag to my commit message that could be used to indicate "hey, this commit might disappear, let's look for it in the next commit and remove the build log if it isn't present".

## Proposal 2

Have an archive button that lets one archive or delete failed builds. I suspect this is the easier route, and makes it possible to hide config tests that are sitting in the logs right now.

## Other

If you're concerned that this feature might be abused to pretend that a project is perfect, then perhaps it could be extended so that this tag works if `.cirrus.yml` is the only modified file. (This is probably orthogonal to the functionality anyway).

**Comment by AlexWayfer** [comment]
> Because I can't test my .cirrus.yml script locally, I can sometimes spend many commits trying to remotely debug. While I don't mind doing this, it would be nice if I could somehow nuke those from my log of failed builds, as they make up a large portion of my failed builds slightly_frowning_face

You described the reason, not the goal.

**Comment by cjdb** [comment]
>> Because I can't test my .cirrus.yml script locally, I can sometimes spend many commits trying to > remotely debug. While I don't mind doing this, it would be nice if I could somehow nuke those from my log of failed builds, as they make up a large portion of my failed builds slightly_frowning_face
>
> You described the reason, not the goal.

That's my motivation for asking for this feature (I've now added the 'motivation' heading to make this clearer). If I understand you correctly, the goal you're looking for can be found in the first paragraph: I'd like to remove particular failed builds from my logs.

**Comment by AlexWayfer** [comment]
No. It's look like [XY Problem](http://xyproblem.info/) for me.

You don't want to see failed by config builds. But why? Do they interfere? Hurt the eyes? Compromise?

**Comment by AlexWayfer** [comment]
I think, online Config Lint tool is better, than deleting failed jobs…

**Comment by cjdb** [comment]
>I think with the CLI described above deleting of such "bad" builds will be obsolete.

Thank you! I agree.

> BTW did you know that you can append a branch name to repository link to get only builds for a particular branch. Very useful for checking health of the default branch. Here is an example: https://cirrus-ci.com/github/cirruslabs/cirrus-ci-web/master

I wasn't aware of this: I'll take a look into that ASAP.
