### ISSUE TITLE
Repository Metadata

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#1078]
# Description

Let's allow to store arbitrary key/value metadata within a repository and display it on the repository page.

# Context

This is useful, for example, for reporting test coverage. Some more advance use case might be using GraphQL API to maintain "build number" like #305 via Starlark helpers https://github.com/cirrus-modules/graphql

**Comment by fkorotkov** [comment]
We can probably also create some default metadata like cache hit rate over the last 100 builds (see #31).

**Comment by fkorotkov** [comment]
```python
load("github.com/cirrus-modules/graphql", "generate_build_number")

def main(ctx):
  return { 
    "env": {
       "CIRRUS_BUILD_NUMBER": generate_build_number()
    }
  }
```

**Comment by fkorotkov** [comment]
Another [use case by @lucperkins](https://twitter.com/lucperkins/status/1586822221921718274) is to be able to pass some simple values between tasks. This might be a stretch a bit since once can already do pretty much the same with the [HTTP Cache](https://cirrus-ci.org/guide/writing-tasks/#http-cache) by prefixing with :

```bash
# task A
curl -s -X POST --data "this is raw data" http://$CIRRUS_HTTP_CACHE_HOST/$CIRRUS_BUILD_ID/nix-sha
# task B
export NIX_SHA="$(curl -fs http://$CIRRUS_HTTP_CACHE_HOST/$CIRRUS_BUILD_ID/nix-sha)"
```

But there is a good point about TTL. I think we can easily include a TTL option since [Datastore natively supports it](https://cloud.google.com/datastore/docs/ttl). I think we can do the regular metadata first and then follow up with the TTL option.

**Comment by fkorotkov** [comment]
Let's keep it open until TTL is implemented

**Comment by edigaryev** [comment]
Closing since the TTL was implemented and deployed (see `RepositorySetMetadataInput`'s `ttlSeconds` field in GraphQL schema).
