### ISSUE TITLE
Conditional decryption of environment variables

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#1081]
# Description

Add either a special case for releases, or just allow a condition somewhere on the UI (see context)

# Context

So I have a repository where 20-30 people have write access to it, all trusted, but as a security measure, there is one environment variable that should only be decryptable when `$CIRRUS_TAG != ''`.  This way, releases can be published, but not just anyone can move the environment variable into the push tasks and use it in a normal commit.  Instead, a theoretical malicious actor would have to trigger a release for this environment variable to be used, which would alert us to it much quicker than would be otherwise possible.

**Comment by fkorotkov** [comment]
This will be possible via upcoming integration with an external secret management via #1079.

A workaround will be to change config resolution strategy to always use config from the default branch and add branch protection rules to avoid someone overriding it without a review.
