### ISSUE TITLE
Branch failing to build, git says "object not found"

### ISSUE THREAD

**Issue by timwoj** [cirruslabs/cirrus-ci-docs#1086]
I have a build off a branch that recently started failing because of git not being able to find the commits on clone. The commits exist on Github, and new commits to the branch don't seem to fix it. An example of the build is https://cirrus-ci.com/task/5949549760479232?logs=clone#L211. The related commit is https://github.com/zeek/zeek/commit/ed820a7b7ae3212ea09464d78c78dbe4f794a438, which clearly exists.

Merging the same commits over to another branch and then running a build off that branch works fine, but not off the original one.

**Comment by fkorotkov** [comment]
I guess we should revert the logic. IMO the `merge` ref thing is weird and I've also seen couple of failures like that on my builds but they were transient and an automatic re-run recovered it. 

Reverting the logic in https://github.com/cirruslabs/cirrus-ci-agent/pull/252 but keeping a fallback to `merge` ref in case of a similar GH incident.
