### ISSUE TITLE
Support colored terminal output

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-ci-docs#1089]
Some tools use colors to emit important information:

<img width="1145" alt="Screenshot 2022-10-27 at 10 26 35" src="https://user-images.githubusercontent.com/85709/198207545-366bd8cf-1165-435b-98f7-30e777d3f1d3.png">

<img width="831" alt="Screenshot 2022-10-27 at 10 26 57" src="https://user-images.githubusercontent.com/85709/198207610-aa68bb84-97a8-4ff2-b5aa-6460fe5407f7.png">

**Comment by fkorotkov** [comment]
The web view [supports colored output if the output is ANSI](https://github.com/cirruslabs/cirrus-ci-web/blob/f682291164fa24abd753faff6826b89e76383812/src/components/logs/Logs.tsx#L92). Many tools only use colors for interactive output mode.

**Comment by RDIL** [comment]
Other tools need environment variables like `SUPPORTS_COLOR` and `FORCE_COLOR`.
