### ISSUE TITLE
Cannot select/copy encrypted variable on Firefox 64.0

### ISSUE THREAD

**Issue by pzahemszky** [cirruslabs/cirrus-ci-docs#109]
When I go to the repository's settings page, enter an environment variable into the "Secured Variables" section, and click "Encrypt", then I can see the encrypted environment variable in grey. However, I'm unable to select and copy the long alphanumeric token (neither by using the mouse nor by pressing keyboard shortcuts).

On the other hand, doing the same steps on a different browser allows selection as expected.

(Using Firefox 64.0 on Windows 10.)

**Comment by fkorotkov** [comment]
I can repro it on macOS 🙌
