### ISSUE TITLE
Docker Builder VM on arm64 fails

### ISSUE THREAD

**Issue by adelton** [cirruslabs/cirrus-ci-docs#1091]
Comparing the amd64 (https://cirrus-ci.org/guide/docker-builder-vm/#__tabbed_1_1) and arm64 (https://cirrus-ci.org/guide/docker-builder-vm/#__tabbed_1_2) instructions at https://cirrus-ci.org/guide/docker-builder-vm/#docker-builder-vm, the only difference is the addition of
```
  env:
    CIRRUS_ARCH: arm64
```
to the arm64 test.

However, when trying that with https://cirrus-ci.com/task/4862321200726016, I get (formatting mine)
```
Failed to start an instance: INVALID_ARGUMENT: Bad Request
400 Bad Request POST https://compute.googleapis.com:443/compute/v1/projects/cirrus-ci-community/zones/us-central1-b/instances
{ "error":
  { "code": 400,
    "message": "Invalid value for field 'resource.disks[0].initializeParams.architecture': 'ARM64'. Requested architecture must be the same as the source resource architecture (X86_64).",
    "errors": [
      { "message": "Invalid value for field 'resource.disks[0].initializeParams.architecture': 'ARM64'. Requested architecture must be the same as the source resource architecture (X86_64).",
        "domain": "global",
        "reason": "invalid"
      } ]
    }
 } 
```

Since I don't specify the `resource.disks[0].initializeParams.architecture` nor the `source resource architecture (X86_64)` values, it seems like the Cirrus CI logic needs to be fixed to properly handle the `CIRRUS_ARCH: arm64` on all levels.

**Comment by fkorotkov** [comment]
Sorry for the inconveniences. Indeed, it broke on the server side. A fix has been deployed and I've [re-run your task](https://cirrus-ci.com/task/6081350829604864).

**Comment by adelton** [comment]
Thank you!
