### ISSUE TITLE
FreeBSD 11.1: Shared object "libdl.so.1" not found

### ISSUE THREAD

**Issue by pzahemszky** [cirruslabs/cirrus-ci-docs#110]
Having run `pkg install python3` I would have expected the `freebsd-11-1-release-amd64` virtual machine to install `python3` with all its dependencies. However, when invoking `python3` I get the following error:
```
Shared object "libdl.so.1" not found, required by "python3"
```

See the related CI task [here](https://cirrus-ci.com/task/4954925215776768).

I'm not sure this is an issue with Cirrus CI, so I'm just opening a ticket for reference. Feel free to close this if it's not useful to keep it around.

**Comment by emaste** [comment]
The FreeBSD package collection targets the oldest supported release on the branch - i.e., 11.2 for the 11.x branch. So `pkg install python3` installs a python built for 11.2, which picked up a dependency on libdl.so.1 not found in 11.1.

**Comment by fkorotkov** [comment]
@emaste thank you for explanation! I don't think Cirrus CI can do anything about it Will close the issue.

**Comment by zagadum** [comment]
#  python -V
Shared object "libdl.so.1" not found, required by "python"


resolve for me (freebsd):
ln -sf /lib/libc.so.7 /usr/lib/libdl.so.1

**Comment by deanet** [comment]
> python -V
> Shared object "libdl.so.1" not found, required by "python"
> 
> resolve for me (freebsd):
> ln -sf /lib/libc.so.7 /usr/lib/libdl.so.1

solved for me too:


rabbitmqctl status
Shared object "libdl.so.1" not found, required by "beam.smp"

os version:
FreeBSD 11.1-STABLE #0 r327234: Wed Dec 27 16:10:53 UTC 2017
