### ISSUE TITLE
Agent is not responding with Windows Docker(Generated by Packer)

### ISSUE THREAD

**Issue by nbyavuz** [cirruslabs/cirrus-ci-docs#1104]
Hi,

I am trying to create Windows docker images with Packer but when I used these images([nbyavuz/mingw-images](https://hub.docker.com/repository/docker/nbyavuz/mingw-images)) on Cirrus CI, task errors with: 'Agent is not responding' after 15 minutes. There is a similar issue: https://github.com/cirruslabs/cirrus-ci-docs/issues/947. Is the thing I am experiencing similar to this issue or is there something else?

I am using[ this packer config](https://github.com/nbyavuz/pg-vm-images/blob/local-add-windows-docker/packer/windows_docker.pkr.hcl) for creating Windows docker images.

## Expected Behavior

The container should start.

## Real Behavior
The container is terminated after 15 minutes of wait time with the error message 'Agent is not responding': https://cirrus-ci.com/task/5850061943341056

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Windows
  - Task name: [Windows - Server 2019, MinGW64 - Meson - Cirrus CI](https://cirrus-ci.com/task/4816974602043392)
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
I think it might be similar issue to https://github.com/cirruslabs/cirrus-ci-docs/issues/970#issuecomment-1054300770

Are you sure your VM is respecting startup/shutdown scripts?

**Comment by nbyavuz** [comment]
I thought we needed to respect startup/shutdown scripts when we created custom VM images but in this case we are using official Windows docker images(mcr.microsoft.com/windows/servercore:ltsc2022), running some scripts, then publishing Windows docker images to the dockerhub (could this be the problem? We are not pushing images to the Google Cloud, instead we pushed them to dockerhub) like you did at https://github.com/cirruslabs/docker-images-windows. However instead of using docker commands, we are doing these with the help of Packer.

**Comment by fkorotkov** [comment]
Oh. Got it. Than it seems the image is so huge it's not getting downloaded or unarchived in 15 minutes (that's the timeout). Or maybe ltsc2022 [which is not cached](https://github.com/cirruslabs/vm-images/blob/edfd36d995a6f01af211fe590b565e9ada77849c/googlecompute/windows_images.json#L66). We do run windows containers on 2019 hosts and haven't still upgraded to 2022.

Let me check if we now can add 2022 support. Last time I checked it in July it was supproted pretty bad.

**Comment by nbyavuz** [comment]
Thanks!
