### ISSUE TITLE
`[ci skip]` breaks https://api.cirrus-ci.com/v1/artifact/github/

### ISSUE THREAD

**Issue by probonopd** [cirruslabs/cirrus-ci-docs#1108]
## Expected Behavior

What should have happened is that when `[ci skip]` is used, the artifacts of the last successful build are still available under  https://api.cirrus-ci.com/v1/artifact/github/helloSystem/helloDesktop/pkg/binary/FreeBSD:13:amd64/index.html.

For example, when making small documentation changes I don't want to run the task in oder to save resources, but I dont want the last built artifacts to disappear.

## Real Behavior

What ended up happening was that when `[ci skip]` was used, the API gives `{"code":404,"message":"Can't find artifacts containing file FreeBSD:13:amd64/index.html"}`.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: FreeBSD
  - Task name: pkg
  - Script/cache name (if applies): https://github.com/helloSystem/helloDesktop/blob/main/.cirrus.yml

**Comment by cevich** [comment]
Thanks!
