### ISSUE TITLE
`nproc` returns number of host CPUs instead of what's available to container

### ISSUE THREAD

**Issue by SomberNight** [cirruslabs/cirrus-ci-docs#1115]
The `nproc` GNU coreutils tool is supposed to "print the number of processing units available".
This makes it convenient e.g. to do `make -j$(nproc)`.

When running a [Cirrus CI task](https://cirrus-ci.com/task/5249045828993024) in a Linux container with 2 CPUs, `nproc` returns `32`, presumably the number of host CPUs.

I've found [similar request for Circle CI](https://circleci.canny.io/cloud-feature-requests/p/have-nproc-accurately-reporter-number-of-cpus-available-to-container), which btw mentions that on Travis CI `nproc` returns the num CPUs available to the container.

As in that request, it would be great if either the behaviour of nproc could be changed (to make the standard tool useful), or alternatively a `CIRRUS_NUM_CPUS` (name tbd) environment variable could be injected.

**Comment by SomberNight** [comment]
Is there currently a practical way to figure out the number of available CPUs when running inside a container?

**Comment by fkorotkov** [comment]
You can use `CIRRUS_CPU`. Documenting it in #1116.
