### ISSUE TITLE
Cannot download artifacts using api.cirrus-ci.com/v1/artifact: Failed to find tasks!

### ISSUE THREAD

**Issue by probonopd** [cirruslabs/cirrus-ci-docs#1122]
## Expected Behavior

What should have happened is that https://api.cirrus-ci.com/v1/artifact/github/helloSystem/helloDesktop/packages/binary/ works

## Real Behavior

`{"code":404,"message":"Failed to find tasks!"}`

# Related Info

* https://github.com/helloSystem/helloDesktop/blob/507109e3ea7b8bf6229f761ca72ce648ed798835/.cirrus.yml - note `alias: packages` and `binary_artifacts:`
* https://cirrus-ci.com/build/5749165041385472

The artifacts did get uploaded:

![image](https://user-images.githubusercontent.com/2480569/206857371-fcb64b93-cae6-4c19-8817-a8d632bc0b00.png)

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name: `packages`
  - Script/cache name (if applies):

**Comment by probonopd** [comment]
Could this possibly have something to do with the changes made to fix https://github.com/cirruslabs/cirrus-ci-docs/issues/1108?

**Comment by fkorotkov** [comment]
Indeed it was affected by #1108. Just deployed a fix but you might need to wait for an hour since Google's CDN is caching 404s.

**Comment by probonopd** [comment]
Thank you very much for your prompt response and fast fix. Can't recommend Cirrus CI enough! :+1:

**Comment by probonopd** [comment]
Could there possibly a regression? I am unable to use https://api.cirrus-ci.com/v1/artifact/github/b-aaz/xlibre-ports/pkgs/ to access artifacts from https://cirrus-ci.com/github/b-aaz/xlibre-ports/master even though e.g., https://api.cirrus-ci.com/v1/artifact/task/6317486045396992/pkgs/pkgs/FreeBSD:14:amd64/index.html exists.
