### ISSUE TITLE
Unexpected red delivery of payloads on status code >200

### ISSUE THREAD

**Issue by erichirlemann** [cirruslabs/cirrus-ci-docs#113]
I believe the Cirrus WebHooks have the following behavior:
- when payload is properly delivered and got 200 as a response status code, everything is fine, Cirrus marks the delivery of the payload in green.
- when payload is delivered and the response status code is >200 and <300, Cirrus marks the delivery in red.
To my humble opinion, this last behavior is undesirable. Since any HTTP status code >=200 and <300 is a successful response.

**Comment by fkorotkov** [comment]
Whoops. It was a UI bug. 😅 BTW Cirrus CI [stores the exact response status](https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L515-L519).
