### ISSUE TITLE
Support for AWS EC2 spot instances

### ISSUE THREAD

**Issue by inikep** [cirruslabs/cirrus-ci-docs#1132]
# Description
AWS EC2 spot instances (https://aws.amazon.com/ec2/spot/) are much cheaper than normal instances.

Please add support for spot instances in `ec2_instance`:
```
ec2_instance:
   preemptible: true
```
or
```
ec2_instance:
   spot: true
```

**Comment by fkorotkov** [comment]
You can now try to use `spot: true` for your `ec2_instance`.

**Comment by inikep** [comment]
It doesn`t work for me at https://cirrus-ci.com/task/6314590741463040 :
```
Failed to start: FAILED_PRECONDITION: The request with type 'one-time' is not supported when instanceInterruptionBehavior is set to 'STOP'. (Service: Ec2, Status Code: 400, Request ID: 2a068a5c-b566-47c8-9209-45f00ce43bd4)
```
