### ISSUE TITLE
Access PR title and message for subsequent pushes to branch

### ISSUE THREAD

**Issue by awelzel** [cirruslabs/cirrus-ci-docs#1138]
# Description

Provide CIRRUS_PR_TITLE / CIRRUS_PR_MESSAGE that consistently provides the description of the PR.

# Context

We had a discussion about adding `[fullci]` or `[windowsci]` to the PR description to opt-into broader CI coverage for PRs that would usually only run on the main branch.

Matching on CIRRUS_CHANGE_MESSAGE in `skip:`, this works when initially creating a PR: The first pipeline has title and message set to the PR's description. However, on subsequent pushes to the PR's branch, the CIRRUS_CHANGE_TITLE and CIRRUS_CHANGE_MESSAGE variables refer to the just pushed commit rather than the PR.

For evaluating skip/only_if conditions using the original PR's description, new environment variables referring to these would be useful.

# Anything Else

We can use CIRRUS_PR_LABELS as an alternative. These appear to also be updated and conditions re-evaluated when modified on the PR and a new pipeline is started through a commit.

If there's something I've overlooked that's already there, happy to hear, too.

Thanks!

**Comment by saadbitcoin** [comment]
اذا حسب الرساله انه خاص فيتعدين البيتكوين لا غير
