### ISSUE TITLE
CIRRUS_CLONE_DEPTH break re-running a task on a branch

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#1143]
`CIRRUS_CLONE_DEPTH` breaks the clone command when a task is re-run that is not from the top commit.

1) For example on a branch, https://cirrus-ci.com/task/5760638778081280?logs=clone#L2 :

```
Using built-in Git...
Limiting clone depth to 1!
Cloning refs/heads/master...
...
HEAD is at 357d750cab5221695d718e6d3e8ce63fa2b5ab3a.
Hard resetting to ceb74b844caff459a8747ef013e61476e73a3c48...
Failed to force reset to ceb74b844caff459a8747ef013e61476e73a3c48: object not found!
```

I think this can be fixed by passing the commit that is needed to the clone function (ceb74b844caff459a8747ef013e61476e73a3c48).

Maybe some CI task rely on the branch name, but the name should be possible to re-set after the clone.

2) This will also happen on pull requests, but I am not sure if it is worth to fix there, as pull requests that have been pushed to are likely not re-run on a not-top commit.

**Comment by fkorotkov** [comment]
Unfortunately there is nothing we can do here. I'd suggest to change the depth to something like 50 so you have some history.

**Comment by MarcoFalke** [comment]
Is there a reason why this can't be fixed (or the commit can't be fetched)?

In the web view, Cirrus is aware of the commit. For example: "Commit ceb74b8 on branch master." (right next to the "Automatic Re-Run" badge)

**Comment by fkorotkov** [comment]
Tying the knowledge between `CIRRUS_CLONE_DEPTH` and other components seems like and overcomplicating. Ideally we could've clone a particular commit of a branch but it seems not supported by Git protocol. At least it's not supported by a library which Cirrus Agent is using for Git. See https://github.com/go-git/go-git/issues/441

**Comment by MarcoFalke** [comment]
Ah thanks for the answer. I incorrectly assumed, since `git fetch` allows to fetch a sha1 commit at depth 1, `git clone` would too, but it does not.
