### ISSUE TITLE
Pre-defined timestamp environment variable

### ISSUE THREAD

**Issue by nbyavuz** [cirruslabs/cirrus-ci-docs#1151]
# Description

Pre-defined timestamp environment variable which will be same for the all tasks in the same build.

# Context

We are creating images using Cirrus CI and we want to have same timestamp for the all images in the same build but this isn't possible now.

**Comment by fkorotkov** [comment]
What do you think about `CIRRUS_CHANGE_TIMESTAMP` which is not quite timestamp of when the build was created but when the corresponding commit was pushed? It will be the same value as [`changeTimestamp` in the GraphQL API](https://github.com/cirruslabs/cirrus-ci-web/blob/cd8fbdbff9714cd00459760a58a8ff1a88a3c9c7/schema.gql#L73).

**Comment by nbyavuz** [comment]
It means couple of seconds before build created, right? If it is, that solves our problem.
