### ISSUE TITLE
Strange `???????` characters at the end of log in GitHub Actions

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-ci-docs#1155]
## Expected Behavior

No strange row of question marks is visible.

## Real Behavior

![Screenshot 2023-03-29 at 5 42 16 PM](https://user-images.githubusercontent.com/40357511/228593301-81069356-9a5a-4745-b451-63be3b1a6429.png)

My workflow is pretty standard: https://github.com/leancodepl/patrol/blob/cirrus_ci/.cirrus.yml

# Related Info

This is a (tick one of the following):

Workflow run link: https://github.com/leancodepl/patrol/pull/1129/checks?check_run_id=12366584058

**Comment by fkorotkov** [comment]
That's weird. Seems there are bunch of NULL characters in the end of your raw log file here https://api.cirrus-ci.com/v1/task/6688092824797184/logs/patrol_test.log

These characters are properly rendered by our logs but GitHub's Markdown is not handling them. Let us filter such characters for GitHub on our side.

**Comment by bartekpacia** [comment]
Thanks for such a quick response!

BTW, I've gotta say CirrusCI is the best of all CI services I've ever used - no BS, just works and is fast and reliable. Thank you for supporting open-source!

**Comment by fkorotkov** [comment]
Very glad to hear that! We are trying our best!

This issue should be fixed now. 👌

**Comment by bartekpacia** [comment]
As of now, nothing is showing:

![Screenshot 2023-03-30 at 2 37 13 AM](https://user-images.githubusercontent.com/40357511/228698404-8cead1a8-2777-4bd6-9f33-50455b6079f2.png)

Run link: https://github.com/leancodepl/patrol/pull/1129/checks?check_run_id=12380867917
