### ISSUE TITLE
Add deferred failure mode

### ISSUE THREAD

**Issue by emaste** [cirruslabs/cirrus-ci-docs#1158]
# Description

Provide a way to have failure reported at the end but have following scripts/tasks continue after the failure.

# Context

In FreeBSD we have a task that builds a kernel and userland that takes quite a while, with a number of test scripts that depend on the build and run after it is complete. The scripts are independent of each other. If one of them fails we'd like the task to report failure, but would still like the remaining scripts to run.

# Anything Else

A FreeBSD code review where this came up: https://reviews.freebsd.org/D39682

> I wish Cirrus had a way to allow scripts to fail and let the overall job continue with a final error...

**Comment by brooksdavis** [comment]
For an example of things I'd like to treat this way, see make_sysent, include_ldirs, and makeman in https://cirrus-ci.com/task/5347068105981952

FWIW Ideally I'd be able to do this with background scripts since these could run alongside a single-threaded portion of the build.
