### ISSUE TITLE
macOS: Regular "Failed to clone because of a timeout from Git server!" 

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/cirrus-ci-docs#1160]
I can only find this example right now, but we've seen this a few times in the past weeks on macOS:
https://cirrus-ci.com/task/5474289692966912

edit: Here's another network failure (with a different error message):
https://cirrus-ci.com/task/6580115660865536

**Comment by fkorotkov** [comment]
GitHub lately has a fair amount of incidents. We'll try to collect some data to see on which end the issue is.

In the meantime such failures should be automatically re-run. Do automatic re-runs succeed? Also don't hesitate to provide more links to failing tasks.

**Comment by real-or-random** [comment]
Yes, re-runs typically succeed. It's just a bit annoying because there's a lot of scheduling pressure on macOS.  

Random idea: Perhaps it would be a useful optimization to retry just the clone command instead of the entire task?

**Comment by fkorotkov** [comment]
Actually the agent should retry it. But seems it wasn't handling all the retriable cases. Fixing in https://github.com/cirruslabs/cirrus-ci-agent/pull/286

**Comment by fkorotkov** [comment]
A retry was added and we also applied all the latest macOS and [Tart](https://github.com/cirruslabs/tart) updates. Please reopen if the issue persists.

**Comment by real-or-random** [comment]
Here's another one that doesn't seem to be covered by the retry: https://cirrus-ci.com/task/4575075920248832

**Comment by edigaryev** [comment]
The timeouts were not respected because the Persistent Worker was using a slightly outdated agent version (see "Agent logs" in the task's "Debugging View"), now it should be fixed.

**Comment by real-or-random** [comment]
Here's another one that wasn't restarted: https://cirrus-ci.com/task/6316539322826752

**Comment by real-or-random** [comment]
One more: https://cirrus-ci.com/task/6512232461238272
