### ISSUE TITLE
Builds are failing with "Errored" status immediately after triggering

### ISSUE THREAD

**Issue by truelecter** [cirruslabs/cirrus-ci-docs#1169]
## Expected Behavior

Builds are starting

## Real Behavior

On every build triggered manually or automatically (after a push in my particular case) builds are failing with the status "Errored": 
<img width="1262" alt="image" src="https://github.com/cirruslabs/cirrus-ci-docs/assets/5520406/c488657e-1648-45d3-87b6-696e71ee2e78">

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.com/github/truelecter/hive

**Comment by fkorotkov** [comment]
Here is a fix for you config https://github.com/truelecter/hive/pull/49

And here is a fix on our side to improve the error message https://github.com/cirruslabs/cirrus-cli/pull/623

**Comment by truelecter** [comment]
Thanks a lot!
