### ISSUE TITLE
Linux pipeline erroring with Failed to start an instance! Failed to pull null image!

### ISSUE THREAD

**Issue by ericoporto** [cirruslabs/cirrus-ci-docs#1174]
## Expected Behavior

The Linux pipeline should work fine like it did before. If it fails, it should indicate with an error message that better describes what to do.

## Real Behavior

Failed to start an instance! Failed to pull null image! Repository does not exist or may require authentication.
Container errored with 'ImagePullBackOff: Back-off pulling image "gcr.io/cirrus-ci-community/ericoporto/ags/ci/linux/dockerfile:hash"'

# Related Info

It's this Linux task here: https://cirrus-ci.com/task/5301377564409856 .

I see it happening in different repositories too, like here https://cirrus-ci.com/task/6262552858984448, see the screenshot below

![image](https://github.com/cirruslabs/cirrus-ci-docs/assets/2244442/778c5b40-4e59-40d4-a43a-4fb142e9b68f)

You can see the dockerfile has a green tick but it's complaining it failed to pull, which is also inconsistent - but perhaps that green is only about building?

**Comment by fkorotkov** [comment]
When Cirrus checks if an image is already pre-built for `Prebuild ...` tasks it used to only checked for existence of a manifest. Seems your image was partially garbage collected when manifest existed but some layer did not. Cirrus only stores the cached images for up to 60 days.

We've improved the cache checking logic to optimistically verify that first few layers exists. This change was just deployed so new builds should properly check for image existence.

**Comment by ericoporto** [comment]
> Seems your image was partially garbage collected when manifest existed but some layer did not.

Is this really needed? This is breaking using the emscripten docker image. In theory the image exists - it works locally in a clean environment.

**Comment by fkorotkov** [comment]
This is only related to [Dockerfile as a CI environment](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment). Similar to `cache` instructions such images are cached for period of 60 days. If your Dockerfile is not reproducible, you can separately build it at your convenience, push it to something like GitHub Container Registry and use it with Cirrus in `image` field directly instead of `dockerfile`.

**Comment by ericoporto** [comment]
I think [Dockerfile as a CI environment](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment) is the killer feature in Cirrus CI, as in example, in GitHub Actions you have to maintain your own images manually and when using it in the CI you either fetch from that manually prebuilt/pushed (even if automatic, it's through a different pipeline, which is slow), and if you just use a Dockerfile directly it gets built in every action.

From what I understand of this policy change what it does is, it removes the possibility of using [multi-stage](https://docs.docker.com/build/building/multi-stage/) docker images as a dependency in Dockerfiles when using Dockerfile as a CI environment. I am not sure if this was an intended consequence of the change.

**Comment by fkorotkov** [comment]
Everything should work as expected. You can build images for each commit and use them. Such cached images just get cleaned up 60 days later which doesn't seem like an issue in your scenario.

**Comment by ericoporto** [comment]
Below is the offending image Dockerfile I can no longer depend

https://github.com/emscripten-core/emsdk/blob/main/docker/Dockerfile

On the upper level they explain how they build - I didn't build, I had a Dockerfile using from and pointing to their docker image.

My solution was to unroll from the multi-stage into a single stage and build that in Cirrus.

**Comment by ericoporto** [comment]
My solution stopped working, it builds

https://cirrus-ci.com/task/4520764490121216

But now I get the same error with it

https://cirrus-ci.com/task/6321939774439424

**Comment by fkorotkov** [comment]
I'll check what's going on. In the meantime I've rerun your task to rebuild the image.

**Comment by ericoporto** [comment]
Don't know if related but our Windows builds aren't starting anymore

https://cirrus-ci.com/build/5932580369858560

**Comment by ericoporto** [comment]
Hi, I have the issue with Windows builds again

https://cirrus-ci.com/task/5755161579094016

None of them are working and now I am afraid they are eating compute credits while still not working...
