### ISSUE TITLE
Is it possible to support 32-bit mode on ARM Linux runners again?

### ISSUE THREAD

**Issue by taiki-e** [cirruslabs/cirrus-ci-docs#1179]
# Description

Support for 32-bit mode in ARM Linux runners seems to have stopped working a few days ago, is it possible to support this again?

# Context

Since the ARM Linux runner was [switched from AWS to GCP a few days ago](https://twitter.com/cirrus_labs/status/1668724692969046017), it appears that 32-bit mode support has been removed from the ARM Linux runner.

2023-06-11: https://cirrus-ci.com/task/5311164117155840?logs=setup#L4

```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
```

2023-06-17: https://cirrus-ci.com/task/5219104697614336?logs=setup#L4

```
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
```

In fact, when I try to run the armhf binary, I get [an error](https://cirrus-ci.com/task/5219104697614336?logs=test#L291).

# Anything Else

This is not such a serious problem for me as I can also use QEMU, but it would have been nice to have an announcement about this.

As mentioned above, this is not such a serious problem for me, so feel free to close this issue if you have difficulty supporting this again.

**Comment by fkorotkov** [comment]
Unfortunately, it's a [limitation of the new instances](https://cloud.google.com/compute/docs/general-purpose-machines#t2a_limitations) that we didn't foresee will affect users. Apologies for the breaking changes but we won't migrate back to AWS. The GCP setup is faster and more cost-efficient. It is still possible to use Graviton instance or any other Arm machines if you bring your own infrastructure.
