### ISSUE TITLE
Cannot run pkg in FreeBSD 14 snapshot

### ISSUE THREAD

**Issue by jiegec** [cirruslabs/cirrus-ci-docs#1199]
## Expected Behavior

It should be able to use `pkg` to install packages.

## Real Behavior

It failed with the following error:

```
pkg install -y bash git autoconf automake libtool groff pkgconf
ld-elf.so.1: Shared object "libssl.so.30" not found, required by "pkg"
```

You can find logs at [cirrus ci](https://cirrus-ci.com/task/5016670356373504?logs=install#L2).

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: FreeBSD
  - Task name: 5016670356373504
  - Script/cache name (if applies):

**Comment by asomers** [comment]
BTW, this is fixed as of yesterday.
