### ISSUE TITLE
Document GraphQL and Websocket APIs

### ISSUE THREAD

**Issue by yschimke** [cirruslabs/cirrus-ci-docs#12]
wss://api.cirrus-ci.com/ws and https://api.cirrus-ci.com/graphql

support for auth tokens would be nice also

**Comment by yschimke** [comment]
n.b. found https://github.com/cirruslabs/cirrus-ci-web/blob/09bf5344ea5e455f99f3b53cca896ea5154ee9b7/schema.graphql, will use this for now

**Comment by fkorotkov** [comment]
would you like a per-repository token authorization? And maybe per-organization on GitHub?

**Comment by yschimke** [comment]
Good point.  I think first thing is per user, matching my privileges. But organization tokens make a lot of sense also.

I wasn't sure where you are going in this direction, but I think at this point this is expected functionality for a CI server for integration into workflows, so I raised it to suggest starting early and getting feedback after use.

**Comment by fkorotkov** [comment]
Was added here: https://cirrus-ci.org/api
