### ISSUE TITLE
Update FAQ to document usage limits

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#1207]
Hi,

https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/ documents there are/will be monthly usage limits, but https://cirrus-ci.org/faq/#are-there-any-limits says there aren't any.

Regards,

Andres

**Comment by fkorotkov** [comment]
Yes, at the moment that are still no limits. We'll update the FAQ on September 1st.
