### ISSUE TITLE
Run task by change in code area

### ISSUE THREAD

**Issue by ericoporto** [cirruslabs/cirrus-ci-docs#1212]
# Description

The main use-case of CI for me is to check that nothing broke between commits. Some files like markdown files (e.g. readme change) don't need to trigger a CI build, and sometimes a piece of code is changed that doesn't really propagate, building and testing only this piece would be enough.

If there was a way to perceive what the area of code or have some gitignore like way of describing, it would be possible to not trigger parts of a build depending of the change.

# Context

Looking into reducing compute credits.

**Comment by fkorotkov** [comment]
Please take a look at [`changesInclude` function](https://cirrus-ci.org/guide/writing-tasks/#supported-functions).

**Comment by ericoporto** [comment]
That is EXACTLY what I wanted but I couldn't find it! Thank you!
