### ISSUE TITLE
Agent not responding in all Windows tasks

### ISSUE THREAD

**Issue by ericoporto** [cirruslabs/cirrus-ci-docs#1213]
## Expected Behavior

Our Windows tasks used to work fine, so I expect them to keep running.

## Real Behavior

Since the weekend we are getting Agent not responding in all our Windows tasks, and there is no actionable debug information.

https://cirrus-ci.com/task/5692315671461888

https://cirrus-ci.com/build/5932580369858560

https://cirrus-ci.com/build/4888699792523264

This one executed partially and then stopped with agent not responding only in some tasks

https://cirrus-ci.com/build/6643208076132352

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.com/task/5692315671461888
- [x] Task issue
  - OS: Windows
  - Task name: build_windows

**Comment by fkorotkov** [comment]
Seems it's the same issue as #1174. Docker Image cache got expired but it wan't picked up by the logic that checks cache availability. I've [manually re-ran](https://cirrus-ci.com/task/6429559222960128) your task to rebuild the image and [re-ran `build_windows` task that is now executing](https://cirrus-ci.com/task/5413676530794496).

We'll see what we can do about improving the logic even more.

**Comment by ericoporto** [comment]
Sorry, I wrote in the wrong issue

https://cirrus-ci.com/task/5755161579094016

Agents are not working again in the Windows builds.

**Comment by mayeut** [comment]
Same issue on a different repo:
https://cirrus-ci.com/task/5809060465868800

**Comment by ericoporto** [comment]
@fkorotkov I think it's the silent docker cache drop again

**Comment by ericoporto** [comment]
Uhm, apparently it's something else...
