### ISSUE TITLE
Account Suspended Even If I Have 10$ Plan

### ISSUE THREAD

**Issue by RT1648** [cirruslabs/cirrus-ci-docs#1222]
Please Help Me To Get My Account Back. I tried To Contact To Support But No Response

**Comment by fkorotkov** [comment]
Our system indicates that your account used Cirrus CI as a ["powerhouse" for not CI related compute workloads](http://cirrus-ci.org/faq/#repository-is-blocked).

**Comment by RT1648** [comment]
> Our system indicates that your account used Cirrus CI as a ["powerhouse" for not CI related compute workloads](http://cirrus-ci.org/faq/#repository-is-blocked).

Dam! I don't think so
