### ISSUE TITLE
"socket: Operation not permitted" error while running in a Linux container

### ISSUE THREAD

**Issue by seladb** [cirruslabs/cirrus-ci-docs#1229]
## Expected Behavior

We're running tests in Linux container (based on Ubuntu 20.04) that involve accessing the container's network interface via libpcap and capturing packets. These tests used to work perfectly fine but started to fail a few days ago with a "socket: Operation not permitted" error. Here is an example run: https://cirrus-ci.com/task/5557256498970624?logs=test_pcapplusplus#L236

Other tests that use macOS or FreeBSD still work and pass: https://cirrus-ci.com/build/6631637971107840

We didn't change anything in the library or the Linux docker container, so it must be something with the docker environment running this test. Has anything changed? 

## Real Behavior

Described above

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Linux Docker
  - Task name: Test Zstd Linux
  - Script/cache name (if applies): https://github.com/seladb/PcapPlusPlus/blob/master/.cirrus.yml

**Comment by fkorotkov** [comment]
Could you please give it another go? We've made some infrastructure changes as of 9am EST today.

**Comment by fkorotkov** [comment]
x86 Linux containers were always on GCP. The main container does have `NET_RAW` and `SYS_PTRACE` capabilities.

**Comment by seladb** [comment]
It looks like it's working again! Thank you so much @fkorotkov ! 🙏
