### ISSUE TITLE
Document disk space limits

### ISSUE THREAD

**Issue by davidchisnall** [cirruslabs/cirrus-ci-docs#1235]
Limits on the disk space should be documented [under limits](https://cirrus-ci.org/faq/#are-there-any-limits).

I have been trying to move the CHERIoT LLVM CI to using Cirrus CI but the jobs kept dying after half an hour or so.  The most recent one told me the reason was that the disk limit for containers was 10 GiB and was exhausted.  Is the limit the same for VMs?  Is there a way of adding additional storage?

Similarly, the memory limits are not documented.  I haven't tried seeing how much I can increase requested memory, I presume it's some multiple of the number of CPUs?

**Comment by fkorotkov** [comment]
We've reverted the disk limit as of 9am EST today. Sorry for the temporary inconveniences.
