### ISSUE TITLE
My account Suspended Without Any Reason 

### ISSUE THREAD

**Issue by SpesUnderworld** [cirruslabs/cirrus-ci-docs#1237]
## Expected Behavior

As I am not aware How much time it will take for New Organisation to do builds on Cirrus So I am regular after some time checking That Is I am able to do builds or not 

## Real Behavior

It's 3rd day now and My account was suspended. Is building AOSP Rom is Illigal. Then why my account suspended. Or is this is automatically Suspended by Script. 

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page: https://cirrus-ci.com/build/6028164799922176
- [ ✓] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name: Aosp Build 
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Building ROM is considered as using Cirrus CI as a build farm for arbitrary CPU tasks which is [prohibited](https://cirrus-ci.org/faq/#repository-is-blocked).

**Comment by JaswantTeja** [comment]
> Building ROM is considered as using Cirrus CI as a build farm for arbitrary CPU tasks which is [prohibited](https://cirrus-ci.org/faq/#repository-is-blocked).

Any way of unban? Like, if we promise to don't repeat it.
