### ISSUE TITLE
GitHub Enterprise: Neither GitHub Marketplace purchase exists nor Auto Pay is configured for the organization!

### ISSUE THREAD

**Issue by leshik** [cirruslabs/cirrus-ci-docs#1251]
After adding our organization to GitHub Enterprise, things became broken with the "Neither GitHub Marketplace purchase exists nor Auto Pay is configured for the organization!" error. In fact, the GitHub app is in place, and it shows that all permissions are in place.

## Expected Behavior

Everything should continue working as before.

## Real Behavior

CirrusCI doesn't see the paid subscription.

# Related Info

N/A

**Comment by fkorotkov** [comment]
GitHub Enterprise doesn’t support GitHub Marketplace so you should enable auto-payment as the error message suggests.
