### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-ci-docs#1284]
I didn't find it explained anywhere in the docs: when I remove Cirrus CI GitHub App from my account, is all my data removed?

(Not that I want to do it, I'm just curious)

**Comment by RDIL** [comment]
No, it doesn't. I don't think GitHub actually lets apps know when they are uninstalled (might be wrong on this part) but either way, data is retained even if you remove the app, you just won't be able to sign in until you re-authorize it.

**Comment by fkorotkov** [comment]
@RDIL is right about Cirrus not handling uninstallation. You'll need to manually delete your repositories one by one or email support@ for batch deletion for your organization.

**Comment by bartekpacia** [comment]
I see, thanks!

So now, I deleted a repository from Cirrus CI's web console. The repo is no longer visible. How can I "get it back" on Cirrus? It still exists on GitHub, of course, and my Cirrus CI app installation is granted access to all my repositories.

**Comment by fkorotkov** [comment]
You can request a restore via support@ email. If it's not too late (within 90 days I think) we can restore it.
