### ISSUE TITLE
Undocumented timeout?

### ISSUE THREAD

**Issue by Wetitpig** [cirruslabs/cirrus-ci-docs#129]
With reference to [this build](https://cirrus-ci.com/build/5657431217537024), is there a 2 hour hard limit timeout to all builds (regardless of the timeout set in YAML)? Thanks!

**Comment by fkorotkov** [comment]
There is a limit indeed. Added the documentation.

BTW did you know that you can [use Dockerfile as build environment](https://cirrus-ci.org/guide/docker-builder/#dockerfile-as-a-ci-environment)? Seems termux packages provide [it](https://github.com/termux/termux-packages/blob/master/scripts/Dockerfile).
