### ISSUE TITLE
UX feedback on download logs button

### ISSUE THREAD

**Issue by drautureau-sonarsource** [cirruslabs/cirrus-ci-docs#130]
Hi,
When we have a bunch of logs in a task, it's quite annoying to scroll a long way before we can access the download button.
Would it be possible to display the button on the task title (close to the collapse/uncollapse button)?
Thanks

**Comment by fkorotkov** [comment]
What do you think about the following change:

<img width="1137" alt="screen shot 2019-01-28 at 8 54 45 am" src="https://user-images.githubusercontent.com/989066/51840579-6c7f2e80-22da-11e9-8497-0b567ea27e5c.png">

Just have a floating button right under the expansion icon?

**Comment by Evangelink** [comment]
Hi @fkorotkov,

This looks nice but when the task contains a lot of logs it takes (quite) some time before the logs are displayed and I assume this button will pop-in.

**Comment by fkorotkov** [comment]
What do you mean by "pop-in"? There will be a progress bar that loads the tail of logs as well as the button that you can click to download full logs.

**Comment by fkorotkov** [comment]
@Evangelink, yeah. It will be available before the logs are downloaded. Let me merge a change so you can try it...

**Comment by fkorotkov** [comment]
Deployed the change, PTAL. You might need to hard refresh if you don't want to wait for a few hours until the caches expire.

**Comment by Evangelink** [comment]
@fkorotkov,

Looks good although it is a bit weird to have the overlay over the inner scrollbar (see screenshot)
![image](https://user-images.githubusercontent.com/11340282/51853297-3f596d00-2328-11e9-848b-29e3c9ab5df7.png)

**Comment by Evangelink** [comment]
You are right I am on windows. The screenshot was done on the Chrome browser. But I have the exact same behavior with Firefox, Edge and IE.

Hope it will help you!

**Comment by Evangelink** [comment]
All good!
