### ISSUE TITLE
Build failed with ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS

### ISSUE THREAD

**Issue by gnzlbg** [cirruslabs/cirrus-ci-docs#131]
rust-lang/libc cirrus builds (e.g. https://github.com/rust-lang/libc/pull/1231) are sometimes failing with:

```
Failed to start: UNKNOWN: ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS The zone 'projects/cirrus-ci-community/zones/us-central1-f' does not have enough resources available to fulfill the request. '(resource type:pd-standard)'.
```

Is this temporary? Did we configure something incorrectly?

**Comment by fkorotkov** [comment]
This is some new error code that GCP throws. Added handling of it. 👌Thanks for reporting and sorry for the inconvenience! 🙌

**Comment by gnzlbg** [comment]
That was quick, thank you!
