### ISSUE TITLE
Where are we manage users occupy seats?

### ISSUE THREAD

**Issue by januswel** [cirruslabs/cirrus-ci-docs#132]
My org is starting to use CirrusCI.

But my name is shown twice in the dialog from "VIEW ACTIVE USERS".
<img width="292" alt="active-users" src="https://user-images.githubusercontent.com/43239/51877331-31026400-23af-11e9-80e8-b0c771c718cb.png">

I want to manage users to use CirrusCI.
I searched screens get my desire but no results.
Tell us how we remove / add users.

**Comment by fkorotkov** [comment]
Hey @januswel, this is a list of users that pushed a change to at least one private repository where Cirrus CI is installed in the last 30 days. This list is automatically calculated. You can adjust the number of seats by changing your subscription on GitHub Marketplace: https://github.com/marketplace/cirrus-ci

You should see *Add More Seats* button on the settings page which will redirect to the exact GitHub Markeplace page to configure it.

<img width="1016" alt="screen shot 2019-01-28 at 11 33 47 pm" src="https://user-images.githubusercontent.com/989066/51884419-30d57a80-2355-11e9-8edf-9f94001b2a08.png">

**Comment by fkorotkov** [comment]
Closing the issue. @januswel please let me know if you have any other questions.

**Comment by januswel** [comment]
Hi, @fkorotkov 
Thank you for your response!!
I understood user model of CirrusCI. All our questions have been solved, we are currently finding best way with CirrusCI.
