### ISSUE TITLE
FreeBSD instances frequently die with "Signaled to exit".

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#137]
FreeBSD instances very frequently die mid-test with the error message "Signaled to exit!".  Restarting usually fixes the problem.  Here's one example https://cirrus-ci.com/task/5743425975484416 .  Is there any way to prevent this?  If it's a GCE resource limitation, could you put the job back into the queued state rather than simply failing it?

**Comment by RDIL** [comment]
Can you link your .cirrus.yml please so I can take a look @asomers

**Comment by asomers** [comment]
Here's on.  But I've seen it on other projects too.  https://github.com/nix-rust/nix/blob/master/.cirrus.yml

**Comment by RDIL** [comment]
Hmm, from a first glance I don’t see any problems.

**Comment by fkorotkov** [comment]
I think I know what's going on. Let me verify my guess...

**Comment by fkorotkov** [comment]
Identified the issue. Working on a fix and a test. Will deploy later today or first thing tomorrow... Will let you know here once it's deployed. Sorry for the inconvenience and thanks for reporting!
