### ISSUE TITLE
View logs during build

### ISSUE THREAD

**Issue by Wetitpig** [cirruslabs/cirrus-ci-docs#138]
During a page reload, all logs of an unfinished task would be deleted. Is there a way of retaining them or viewing them before the task is finished? Thanks!

**Comment by fkorotkov** [comment]
Hey @Wetitpig, sorry about that! Right now only new log lines are available while task is progressing. Added this enhancement to a roadmap. 🙌

**Comment by Wetitpig** [comment]
@fkorotkov Also could console output highlighting be enabled? Thank you!

**Comment by fkorotkov** [comment]
@Wetitpig do you have an example where it doesn't work quite well? Cirrus CI already tried to highlight ansi output.

**Comment by Wetitpig** [comment]
For example, words like `warning` and `note` in [this build](https://cirrus-ci.com/task/5858758254133248) should be highlighted, as seen [here.](https://travis-ci.org/termux/termux-packages/jobs/488377956) Thanks!

**Comment by RDIL** [comment]
I’m interested to see if we could implement methods like the ones the python library colorama does.

**Comment by fkorotkov** [comment]
@Wetitpig @RDIL created #155 about the coloring issue.

**Comment by cevich** [comment]
@Wetitpig I'm not an expert on the CIrrus internals.  I examined this behavior from the POV from what is logged into the google storage buckets.  It appears the updates only happen after the run finishes. That implies Cirrus-CI is caching the output internally before recording to persistent storage.  To me, that means it may be a heavy-ask, for Cirrus to track per-client indexes into that cache.  It's also likely to be similarly difficult to sync. the internal cache with the bucket object (for direct monitoring).  Though I agree the current situation is less than ideal, it does encourage keeping your script-sections short and quick, which seems to be a general "best practice" anyway :smile:   Point is...I don't expect a solution in this space to happen any time soon.

**Comment by am11** [comment]
Live logs seldom work. If we expand the step node while tasks are running, it rarely shows anything until the task is over (we often need to refresh the page to see the content of log).
Sometimes, however, I see `[object Object]` while waiting for live logs:

![image](https://user-images.githubusercontent.com/3840695/55800736-15b58280-5add-11e9-83df-be1c1ba3ccb0.png)

**Comment by simonbrandhof** [comment]
Hi @fkorotkov IMO the lack of logs during execution is a critical issue for the steps requiring live information. That's for example the case for continuous deployment pipelines.

**Comment by fkorotkov** [comment]
@simonbrandhof agreed. Will prioritize it. 🙌

**Comment by fkorotkov** [comment]
Cirrus now caches last 100Kb of logs of currently running tasks and when you expand the logs they will be loaded while new logs continue to appear as they come. 🙌

**Comment by RDIL** [comment]
Super

**Comment by probonopd** [comment]
I still do not see the logs while the task is running.

**Comment by fkorotkov** [comment]
@probonopd is it always not working for you or occasionally?

**Comment by probonopd** [comment]
Now that you are saying it: Occasionally... Will keep watching it.

**Comment by bartekpacia** [comment]
I'm encountering this issue. After I refresh the page, and expand the logs of the instruction that's being currently executed, then these logs are empty.
