### ISSUE TITLE
Cancelled jobs have a failed status

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#139]
If you cancel a Cirrus job, it will post a red "failed" status to Github.  It should post the gray "cancelled" status instead.  I observed this on a FreeBSD instance; I don't know if the same applies to other instance types.
https://cirrus-ci.com/task/4821605097144320

**Comment by fkorotkov** [comment]
It should work and in GitHub UI it should be shown as a grey icon like this:

<img width="458" alt="screen shot 2019-01-31 at 7 34 04 pm" src="https://user-images.githubusercontent.com/989066/52094980-48984300-258f-11e9-8f0f-c9220601188e.png">

In your particular case, it seems there was a race condition. A VM was creating when it got canceled which made the initial start request to fail and get the task into a failed state.
