### ISSUE TITLE
Consider adding a light theme for the site

### ISSUE THREAD

**Issue by php-coder** [cirruslabs/cirrus-ci-docs#14]
Maybe I'm alone who feel uncomfortable to read a white text on the black background but I'd like to share my experience with you. Please, consider adding classic, black-on-white, theme to your site (and especially to the documentation).

**Comment by fkorotkov** [comment]
@php-coder I was in the process of moving https://cirrus-ci.org website to use McDocs which generates static website. Just deployed it and I hope you'll enjoy the new look and feel.

**Comment by php-coder** [comment]
Thanks!
