### ISSUE TITLE
Broken images on Quickstart page

### ISSUE THREAD

**Issue by zmitchell** [cirruslabs/cirrus-ci-docs#141]
If I go to [Quickstart](https://cirrus-ci.org/guide/quick-start/) using Firefox or Safari, none of the images load.

**Comment by RDIL** [comment]
Hi, thanks for noticing.  I will take care of this in about 30 mins.

**Comment by RDIL** [comment]
@fkorotkov beat me to it 🥇 
@zmitchell after the docs rebuild this should be fixed.  Please close this issue.

**Comment by fkorotkov** [comment]
It's because pngs are stored in Git LFS and GitHub pages don't support them. Fixed by re-commiting them without LFS.

**Comment by fkorotkov** [comment]
@zmitchell sorry for the inconvenience and thank for reporting!
