### ISSUE TITLE
Adding an additional organization repository

### ISSUE THREAD

**Issue by dfandrich** [cirruslabs/cirrus-ci-docs#146]
The documentation talks about setting up Cirrus CI on an organization repository, but not how to add an additional repository after the initial setup step. I have Cirrus enabled for some personal and some organization repos, but I can't for the life of me now figure out how to add an additional organization repository. Under "configure access" I can "Select repositories" but only my personal ones show up, not the ones under my organization. None of the other configuration or enabling options lead me to a place where i can add more organization repos. How does one accomplish this?

**Comment by dfandrich** [comment]
N.B., I was finally able to do it by uninstalling Cirrus then going through the whole setup step again from scratch, but that sounds like a workaround, not the recommended procedure.

**Comment by fkorotkov** [comment]
Hey @dfandrich, sorry for the troubles. You can always edit your plan from Cirrus CI's Marketplace page but I've added a direct link to Quick Start guide. 👌

**Comment by dfandrich** [comment]
Thanks! In all my clicking (and I did a lot), I don't think I ever managed to find that link.

**Comment by fkorotkov** [comment]
@dfandrich yeah, GitHub Apps are not the most intuitive but still much better than the previous OAuth method. 😅
