### ISSUE TITLE
Sliding menu doesn't work in Firefox with a high zoom

### ISSUE THREAD

**Issue by php-coder** [cirruslabs/cirrus-ci-docs#15]
**Steps to reproduce:**
- open https://cirrus-ci.org in Firefox
- zoom a page to 175% (Ctrl+Mouse Wheel)
- in this mode right menu became invisible
- click on the picture at the left top corner
- menu will appear on the left side
- click on item "User Guide" or "About"

**Actual result:**
Menu blinked and stayed the same.

**Expected result:**
Menu show show sub-items.

**Environement:**
Firefox 54 on Fedora 25

**Comment by fkorotkov** [comment]
Tried to reproduce on Firefox 58 and Firefox 54 on a Mac without success. Will try to get my hands on a Fedora VM probably.

**Comment by php-coder** [comment]
You can wait until other users will face the issue. Also I'm going to update my Fedora and Firefox next week, so maybe the bug will be fixed.

**Comment by fkorotkov** [comment]
Hey @php-coder, I didn't have time to check the issue on a Fedora machine so I was wondering if you had a chance to update your workstation and if you still see the issue?

**Comment by php-coder** [comment]
@fkorotkov Hi, thanks for reminding me but I didn't update laptop yet.

**Comment by fkorotkov** [comment]
Closing as out of date. Sorry I haven't tried it on a Fedora machine, please re-open if there is still an issue.
