### ISSUE TITLE
[Bug] duplicate status checks

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#151]
For some reason this check ran twice: ![bc65ea2e-742f-4d24-9aa1-15e78e84651e](https://user-images.githubusercontent.com/34555510/52184806-3d8b2000-27e6-11e9-9a08-0adb4bc42921.png)

**Comment by fkorotkov** [comment]
This is actually a GitHub issue that I reported a while ago. There is already a linearization mechanism on Cirrus CI side to atomically update statuses but still sometimes GitHub creates a duplicate.

**Comment by RDIL** [comment]
👍
