### ISSUE TITLE
Don't count compute credits powered tasks agains organization seats

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#154]
Right now any user that creates a build for a private repository is counted as a seat. We should not do it if the build only consists of tasks with [compute credits](https://cirrus-ci.org/pricing/#compute-credits). Basically, **compute credits should include orchestration costs**.

**Comment by RDIL** [comment]
Agreed.  I also think there should be an option that you can put in the config file like `compute_credit_account: octocat` or `compute_credit_account: cirruslabs` so you can choose to take from a certain user's or organization's supply of credits.
