### ISSUE TITLE
Better log coloring

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#155]
See example here: https://github.com/cirruslabs/cirrus-ci-docs/issues/138#issuecomment-461648283

Right now Cirrus sets only `TERM` environment variable to indicate ANSI support. In the example above it's not enough.

**Comment by fkorotkov** [comment]
Not quite sure why ascii special symbols are missing from the Cirrus CI logs. 🤔

**Comment by RDIL** [comment]
maybe the characters need to be escaped?

**Comment by Wetitpig** [comment]
Some [builds](https://cirrus-ci.com/task/5968947426885632) actually successfully show coloured output.

Moreover, my build is actually run in a subshell, so I doubt if it is the problem of the shell.

**Comment by fkorotkov** [comment]
@Wetitpig I've tried to understand `build-package.sh` but I got lost. 😅Seems something is not passing through. I've checked environment variables of your Travis build and haven't noticed anything suspicious. There is definitely something preventing the ANSI from being used. Cirrus CI will highlight the output with them. I will try to debug it once again a little bit later today. 🙌

**Comment by fkorotkov** [comment]
Closing the issue since coloring is working as expected but the script doesn't produce ANSI logs.
