### ISSUE TITLE
Failed to start an instance! failed

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#159]
A recent FreeBSD run failed with the error message `Failed to start an instance! failed`.  Can Cirrus-CI please learn to recover from this type of error and requeue the job?

https://cirrus-ci.com/task/6194253215563776

**Comment by RDIL** [comment]
Hey @asomers!  
You can find a solution to the fix for that [here](https://cirrus-ci.org/faq/#instance-failed-to-start) :)
If that does not answer your question, please elaborate.

**Comment by asomers** [comment]
Well, the FAQ says to contact support immediately, since this happened on the FreeBSD community cluster.  Are you part of support, @RDIL ?

**Comment by RDIL** [comment]
No, you will need to ask @fkorotkov about it in that case.

**Comment by fkorotkov** [comment]
@asomers the instance got preempted and hit a race condition. It should've been automatically restarted. Thanks for reporting! 🙌It helped to discover the race condition, deploying a fix as typing this comment. Should be available soon...

**Comment by asomers** [comment]
Gracias!
