### ISSUE TITLE
Suggestion list

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#161]
So I don’t forget any of my suggestions and so that they can be possibly implemented, I’m going to write them all down here:
* [ ] Auto open drawer when that script is executing (example: if mycoolscript is running, the mycoolscript accociated drawer opens then when it finishes it auto closes)
* [ ] Premade scripts that can be accessed.  Example: 
foo_task: 
  - git_checkout_script
  - empty_temp_dir_script
* [ ] being able to run scripts before the clone phase is executed. 
I will write more down as I remember them or as they come to me.

**Comment by fkorotkov** [comment]
What are the use cases for premade scripts and ability to run command before `clone`?

**Comment by RDIL** [comment]
For premade scripts, you could put a bunch of commonly used commands so they don’t have to be typed over and over again, as for running tasks before clone, this would be helpful for me personally so that I can configure git the way it is needed for my projects before cloning.

**Comment by RDIL** [comment]
- Continue on error config option (example: if process returns code 1, don't stop the build)

**Comment by fkorotkov** [comment]
^^ will be fixed in https://github.com/cirruslabs/cirrus-ci-docs/issues/55

**Comment by RDIL** [comment]
* CIRRUS_TAG env variable - null for regular builds but the version for builds on tags (for example: 3.0.0 or 2019.1.2)

**Comment by RDIL** [comment]
Oh wait that already exists🤦🏻‍♂️
