### ISSUE TITLE
CirrusCI doesn't run checks

### ISSUE THREAD

**Issue by artemirq** [cirruslabs/cirrus-ci-docs#162]
See PR's

https://github.com/artemirq/zero-scriptsjs/pulls
or
https://github.com/artemirq/zero-scriptsjs/pull/155

**Comment by RDIL** [comment]
Hi,  
Have you confirmed you   
a. Have Cirrus installed   
b. It is authorized to the repo  
c. You have made a config file  
?

**Comment by artemirq** [comment]
@RDIL

![image](https://user-images.githubusercontent.com/17342159/52981527-4a686000-33f1-11e9-9ce1-6cb7ed7598b4.png)
--
![image](https://user-images.githubusercontent.com/17342159/52981538-55bb8b80-33f1-11e9-901b-791b06098278.png)

**Comment by RDIL** [comment]
Is Cirrus in your `Authorized GitHub Apps` also?  Thanks for your quick reply.

**Comment by artemirq** [comment]
@RDIL No
![image](https://user-images.githubusercontent.com/17342159/52981777-e9da2280-33f2-11e9-89e3-26644f8f2e3b.png)

**Comment by artemirq** [comment]
@RDIL How to add to `Authorized GitHub Apps`?

**Comment by RDIL** [comment]
I’m not quite sure.  I believe it has to be in there for it to work.  Try uninstalling the app and cancelling your plan, then try to reinstall it.

**Comment by artemirq** [comment]
@RDIL How to cancel plan?)

**Comment by artemirq** [comment]
@RDIL I authorize on https://cirrus-ci.com. But no repositories shows. Then I reinstall (removed then installed) Cirrus CI. On https://cirrus-ci.com no repositories too
![image](https://user-images.githubusercontent.com/17342159/52982050-be583780-33f4-11e9-9402-e60d5b7594cd.png)

**Comment by RDIL** [comment]
Commiting to the repo you want to add now

**Comment by RDIL** [comment]
@artemirq I found the issue and fixed it. See my PR.

**Comment by artemirq** [comment]
@RDIL Thanks so much. I didn't know, what `_task` append is required

**Comment by artemirq** [comment]
@RDIL Functionality at `cirrus-ci.com` just not implemented yet? Sorry, I thought it was a bug. Sorry for this

**Comment by fkorotkov** [comment]
@artemirq which functionality are you referring to? Cirrus CI has lazy initialization so until you commit `.cirrus.yml` config file to your repository it won't appear on cirrus-ci.com (BTW now I see build for your repository on https://cirrus-ci.com/github/artemirq/zero-scriptsjs). 

@RDIL thank you for digging into the issue!

**Comment by artemirq** [comment]
@fkorotkov Now I see too. Thanks =)
