### ISSUE TITLE
Batching of reattempted jobs in web UI

### ISSUE THREAD

**Issue by am11** [cirruslabs/cirrus-ci-docs#164]
If a job is failed due to, for example, "Instance failed to start" error, it gets reattempted automatically. User can also rerun the passed or failed jobs number of times.

In the CirrusCI web application, the reattempt job produces a new entry, instead of updating the existing one.

https://cirrus-ci.com/build/4730596090707968
![image](https://user-images.githubusercontent.com/3840695/53070321-6e0dd200-34e7-11e9-9f37-e58384493ebf.png)

Please consider batching previous attempts (manual or automatic) in the job list page.
Source of inspiration is VSTS, where we can reattempt release jobs number of times and the UI batches them under a single title:

![image](https://user-images.githubusercontent.com/3840695/53069860-102cba80-34e6-11e9-8c8c-7b3781656b57.png)

**Comment by am11** [comment]
Wow great! Thank you so much @fkorotkov! 🎉 
Would it be possible that we could also access the logs from previous attempts of failed jobs?

**Comment by fkorotkov** [comment]
@am11 if you click on a task you'll see a list of previous runs. This changed only affected how tasks are listed on a build page. Agreed that it was confusing to see a green build with some red tasks. 😅

**Comment by am11** [comment]
@fkorotkov, ops, somehow I missed the "All Other Runs" section in details page. Thanks again for super fast fix! 🌮
