### ISSUE TITLE
Instance got rescheduled!

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#165]
A recent run of the rust-lang/libc repository failed with the error message `Instance got rescheduled!`.  Could Cirrus please requeue the job in this case, rather than fail it?
https://cirrus-ci.com/task/5085993225945088

**Comment by RDIL** [comment]
I believe this was already requested/planned.

**Comment by fkorotkov** [comment]
The task got automatically re-run: https://cirrus-ci.com/task/5198918922010624

Cirrus CI shows all runs of a task for transparency of what Cirrus CI is doing.
