### ISSUE TITLE
Github author(s) in environment?

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-docs#166]
Is it possible to get the Github author(s) of a commit in an environment?  Perhaps as a comma separated list?

**Comment by RDIL** [comment]
You could use `git log` I believe and split the output.  A python example I can think of is:  
```python
import os
log: str = os.system("git log").split("{0} AUTHORS: hello world".format(os.getenv("CIRRUS_CHANGE_MESSAGE")))
```
Note that this will not work as this is not how git logs are actually formatted.

**Comment by dnfield** [comment]
Ahhh that's right.  I was forgetting I get the whole git repo available.  Thanks!

**Comment by RDIL** [comment]
Glad to hear this helped :)
