### ISSUE TITLE
Pull requests with custom clone_script

### ISSUE THREAD

**Issue by anuejn** [cirruslabs/cirrus-ci-docs#172]
The solution, you propose to use the official git command (https://github.com/cirruslabs/cirrus-ci-docs/blob/master/docs/guide/writing-tasks.md#custom-clone-command) works just fine in most cases.
However, for pull requests it fails to clone, as the environment variables do not represent an existing repo / branch combination.

Example: https://github.com/apertus-open-source-cinema/axiom-beta-firmware/runs/68918559
Thanks :)

**Comment by fkorotkov** [comment]
Created https://github.com/apertus-open-source-cinema/axiom-beta-firmware/pull/61 in your repo.

**Comment by anuejn** [comment]
thanks, appreciated :)
