### ISSUE TITLE
Set user to run container in?

### ISSUE THREAD

**Issue by SeanTAllen** [cirruslabs/cirrus-ci-docs#178]
I'm trying to get started with using containers for Linux CI. Our containers have everything installed as a non-root user: `pony`. 

How to I get checkout and commands to run as that user?

I tried:

```
container:
  image: ponylang/ponyc-ci:cross-llvm-7.0.1-arm
  user: pony
```

but that didn't work. I've looked through the docs and can't see an answer.

**Comment by RDIL** [comment]
Hey,  
`user` is not a supported field to the extent of my knowledge.  I don't believe there is a way to use a certain container user right now.  I'm assuming this is now a feature request.

**Comment by SeanTAllen** [comment]
Yes, if it currently isn't supported than this would be a feature request.

**Comment by fkorotkov** [comment]
@SeanTAllen Cirrus should respect `USER` instruction in your `Dockerfile`. And seems it's working. See my testing task: https://cirrus-ci.com/task/5122275905896448
