### ISSUE TITLE
behavior when using :latest images

### ISSUE THREAD

**Issue by rickypai** [cirruslabs/cirrus-ci-docs#184]
The examples in uses `:latest` images for many builds.

https://github.com/cirruslabs/cirrus-ci-docs/blob/e91b67c8df1e2deb692a1c3cfad80476d1a7461a/docs/examples.md#bazel

However, it seems like the image is cached on the worker. That and the nature of `:latest` tags means the build behaviors can be inconsistent.

For example, I have two builds with the identical code, which builds locally on the latest Bazel release (0.23.1). However, for my cirrus builds:

- it does not build with `l.gcr.io/google/bazel:latest` ([build](https://cirrus-ci.com/task/5077828973363200))
- but builds with `l.gcr.io/google/bazel:0.23.1` after setting the image explicitly in https://github.com/rickypai/golang-boilerplate/commit/030fa2b611a25b87af9f26dd9c8c37ac7f53ba56 ([build](https://cirrus-ci.com/task/5386399422349312))

CI should either always pull images `:latest` or the doc should document/discourage the use of `:latest` and encourage using a specific tag like `:0.23.1`. Also, the builds should display the SHA of the resolved images.

Another potential idea is to have an image pull policy like Kubernetes to make the behavior configurable: https://kubernetes.io/docs/concepts/configuration/overview/#container-images

also hi

**Comment by fkorotkov** [comment]
Hey, Ricky! 🙌

Under the hood `:latest` tag actually sets `imagePullPolicy` to `Always`. Otherwise it will be `IfNotPresent`.

Your build seems to fail with a network error though:

> fatal: unable to access 'https://go.googlesource.com/text/': The requested URL returned error: 502

**Comment by rickypai** [comment]
opps sorry about that... maybe just document the behavior and the caveats of `:latest` then...

I just assumed it was a Bazel version error since pinning the version worked (I've been too deep into different Bazel versions lately so kind of just automatically assumed it was the case)
