### ISSUE TITLE
SHA based URL for builds

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-docs#186]
I'd like to find a specific commit made to flutter/flutter/master.

Is there a way to do this today?  It no longer appears on the page of results (it's ~a week or two old).

**Comment by fkorotkov** [comment]
At the moment you can do it from [GitHub UI](https://github.com/flutter/flutter/commits/master). Just find a commit and click on status checks.

![image](https://user-images.githubusercontent.com/989066/53985203-0bbcf000-40e9-11e9-970e-6271f1540475.png)

**Comment by RDIL** [comment]
A search bar could be quite nice.  You could always look for it on the commit list on GitHub, and open the build logs from there.

**Comment by RDIL** [comment]
Grr you commented just before me :|

**Comment by dnfield** [comment]
Is there a way to find it for the merge commit though?

**Comment by dnfield** [comment]
Ahh I see, I have to find it in the commits list rather than from the PR.  Thanks.

**Comment by RDIL** [comment]
Was the commit squashed?

**Comment by fkorotkov** [comment]
And this issue will be about supporting the following URL format: `https://cirrus-ci.com/build/flutter/flutter/SHA`
