### ISSUE TITLE
[Question] Log location

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#188]
Where are the text file logs located locally on the Linux build machine?

**Comment by fkorotkov** [comment]
They are streamed to Cirrus CI master but a backup log file stored in `$TEMP` for each script (log file is deleted after uploading though).

**Comment by RDIL** [comment]
Okay.  I'm setting up my own log uploading system which will have logs commented on new pull requests and I needed to know for that.  Thanks 😄
