### ISSUE TITLE
Hardware exposition

### ISSUE THREAD

**Issue by cjdb** [cirruslabs/cirrus-ci-docs#192]
Is the kind of hardware that Cirrus uses documented anywhere? I'm writing software that needs to know the what the underlying hardware is, so that its output can be checked against the correct valid output.

It's important to know the platform being used (e.g. Intel, AMD, ARM), the architecture (e.g. i386, amd64), and how many hardware threads are available, and how many threads the OS provides. If it's possible to know the specific chipset, that would also be beneficial, but not essential.

**Comment by fkorotkov** [comment]
It varies of a platform as well. For Linux/FreeBSD builds Cirrus CI is using custom machine types on Google Cloud which has a [variety of platforms](https://cloud.google.com/compute/docs/cpu-platforms). Cirrus on the other hand doesn't specify a minimum CPU platform so your builds can end up on any of them. All of them are Intel though.

Windows containers are executed on Azure Container Instances. I wasn't able to find documentation about which platform is it using though but I believe it's Intel too.

And finally for macOS the latest Mac Minis are used with i7 *Coffee Lake* Intel CPUs.

**Comment by fkorotkov** [comment]
Could you please tell me more a little bit about the project you are working on and what kind of hardware you'd like to see?

**Comment by RDIL** [comment]
I know the Python3 `os` and `sys` built-in modules can flush out some of these details.

**Comment by fkorotkov** [comment]
Closing the issue due to inactivity and since Cirrus doesn't yet have that much of variativity of hardware. 😅
