### ISSUE TITLE
[Enhancement] Improve cache script names

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#193]
The drawer for uploading caches at the end of the task is named fine, but the drawer that populates/downloads/fingerprints a cache should be renamed.  

`insertnamehere_cache` or `prepare_insertnamehere_cache` instead of just the cache name would both be great.

**Comment by fkorotkov** [comment]
You can do something like that:

```yaml
cache:
  name: Super Fancy
  folder: foo
```

I've also changed default upload instruction name from `upload_Super Fancy_cache` to `Upload 'Super Fancy' cache`. Should be nicer now.
