### ISSUE TITLE
CIRRUS_LAST_SUCCESSFUL_CHANGE

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#196]
Add new `CIRRUS_LAST_SUCCESSFUL_CHANGE` which will point to the last sha on the same branch where all Cirrus tasks finished successfully.

This can be very useful for incremental builds.

**Comment by RDIL** [comment]
this should have been closed automatically by GitHub

**Comment by fkorotkov** [comment]
Thank you!

**Comment by RDIL** [comment]
Reporting the fact that `and` doesn't close the second issue listed as a bug to the GitHub team now
