### ISSUE TITLE
Compute Credits for Personal Accounts

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#209]
# Description

Support compute credits for personal repositories to allow prioritization and no concurrency limits for power users.

**Comment by fkorotkov** [comment]
This will require a little bit more work than were anticipated originally. In the meantime macOS community cluster grew by 50% which should eliminate long scheduling times which motivated this feature request. Will put this ticket in a backlog for now.

**Comment by RDIL** [comment]
Not sure if this is related, but I'm experiencing linux containers taking longer to get started.

**Comment by fkorotkov** [comment]
@RDIL metrics are not showing anything abnormal. Are you referring to macOS tasks?

**Comment by RDIL** [comment]
No.  Just normal `container: image: dockerimage:version` tasks.  I think that the number of machines being used is growing 😅

**Comment by fkorotkov** [comment]
It shouldn't affect Linux builds where it's possible to scale up and down. With Macs it's a different story unfortunately. 😔

**Comment by fkorotkov** [comment]
It is available now on user profile page: https://cirrus-ci.com/settings/profile/

**Comment by duckinator** [comment]
As a note for anyone else encountering issues with it, I'll explain what I had to do to use the "Payment Request API" that requires.

The good news is, for anything using the Payment Request API, you won't need to do it again for the credit/debit card you use.

1. Install Chromium (Chrome should also work).
2. In Chromium/Chrome, navigate to `about:flags`.
3. Enable the "Web Payments" experimental feature.
4. Click the big blue "Relaunch Now" button that showed up when you did that.
5. Navigate to `about:settings`.
6. Under "Autofill", click "Payment Methods".
7. Click "Add", fill in the form, and click save.
8. Go back to the main settings page.
9. Click "Addresses and more".
7. Fill in the name/address associated with the card from step \#7. Click save.

Now, we finally get to the part specific to Cirrus CI:

8. Navigate to https://cirrus-ci.com/settings/profile/
9. Click the "Add More Credits" button.
10. Enter the number of compute credits you want (I went with 10).
11. Click the "BUY $x CREDITS" button (where $x = the number from \#10). 
12. In the new browser dialog from Chromium/Chrome itself, choose your payment method, contact info, etc.
13. Click "Pay".

At this point, all the dialogs should be closed. (Unless I missed a step.) If they are, reload the page to view updated information.

**Comment by duckinator** [comment]
As for why I installed Chromium: I just couldn't get it to work in Firefox. At all.

And even in Chromium, it's not documented. I found out that it uses the autofill information purely by luck.

And nothing else is likely to support this on Linux.

**Comment by duckinator** [comment]
Anyway! Sorry for so many comments, and thank y'all for adding this. Hopefully my comment helps until the browsers streamline their implementations a bit more.

@fkorotkov I don't think there's a way you can streamline this setup while still using the Payment Request API, but it's probably worth adding some notes explaining it.

I also noticed that the frontend is open-source, so if you (or someone else) could give me some pointers on where/how it'd make sense to add that information, I'd be happy to make an attempt at documenting it either this weekend or next week. :slightly_smiling_face:

**Comment by duckinator** [comment]
On second thought, it may make more sense to add that to this repo and add a link to it, and I should definitely go to bed now. Either way. lmk what your thoughts are and I'd be happy to contribute that.

**Comment by duckinator** [comment]
Also, as a note: there's a chance Firefox may do the same thing Chromium does, where it uses the autofill information.

I only discovered that in Chromium by accident, so hadn't thought to try it in Firefox.

**Comment by RDIL** [comment]
#190 should improve this.

**Comment by fkorotkov** [comment]
Yeah, using fancy [Request API](https://stripe.com/docs/payment-request-api) wasn't a wise decisions but integration was super easy and straightforward. I think it will make sense to migrate to Stripe's [Checkout](https://stripe.com/docs/payments/checkout) which should handle every current available payment method (and any new that w) on a separate page.

**Comment by duckinator** [comment]
Yeah, Stripe + PayPal should cover a pretty much everything. :+1: 

I do look forward to a time when the Payment Request API is as simple for end-users as developers, though. :sweat_smile:
