### ISSUE TITLE
Create Access tokens for Personal Accounts

### ISSUE THREAD

**Issue by ened** [cirruslabs/cirrus-ci-docs#212]
# Description

Would like to create access tokens for non-organization accounts.

https://cirrus-ci.org/api/#authorization only mentions GH organizations.

# Context

While I do not have a GH organization, I'd still like to utilize parts of the GraphQL API to automate various deployment tasks. Access tokens are needed for that.

**Comment by ened** [comment]
@fkorotkov When will the feature be deployed to cirrus-ci.com?

**Comment by fkorotkov** [comment]
@ened auto-deployed failed so I  poked it. Should be available now [here](https://cirrus-ci.com/settings/profile/). 😅

**Comment by ened** [comment]
@fkorotkov Thank you!
