### ISSUE TITLE
Testing lua

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#214]
# Question

Anybody know an easy way to test Lua?

**Comment by fkorotkov** [comment]
Do you have a repo where you want to add it? Seems you can use container from here: https://github.com/SuperPaintman/docker-lua

**Comment by RDIL** [comment]
Thanks. Was going to add it to https://GitHub.com/RDIL/macncheese
Yeah I was bored when I made that 🤕
