### ISSUE TITLE
Add ARM support for Linux

### ISSUE THREAD

**Issue by j8r** [cirruslabs/cirrus-ci-docs#218]
# Description

The ARM architecture, aarch64 and eventually armhf, are gaining traction since the raise of Raspberry PIs and recently cheap ARM offerings in various clouds.
Several projects now fully supports ARM, thus needing a CI.

# Context

The Crystal Language aims to fully support Linux [aarch64](https://github.com/crystal-lang/crystal/issues/7587), and eventually armhf. That's not easy since the current CI doesn't support this architecture.

# Anything Else

Thanks to have suggested us [to file a feature request in our issue tracker](https://github.com/crystal-lang/crystal/issues/7587#issuecomment-476259742), I don't know how you have found our thread :sweat_smile:

**Comment by RDIL** [comment]
For FreeBSD?

**Comment by j8r** [comment]
That's mainly to support Linux aarch64, and eventually armhf. FreeBSD aarch64 is a plus, but since Crystal doens't support it at tier 2 unlike Linux aarch64 that's not a high priority.

**Comment by fkorotkov** [comment]
@j8r I'm spending too much time on GitHub and Twitter. Sorry, it it creeped you out. 😅

**Comment by emaste** [comment]
I'm very much interested in seeing aarch64 (arm64) support for FreeBSD

**Comment by ped7g** [comment]
For my current use case I would need in ideal case 32bit ARMv6 target (Raspberry Pi0), but even any 32b ARM (v7+) would already help a lot to make sure that v6 variant is highly likely buildable too.

And finally even 64b ARM would be nice just to have another target platform, in case it would uncover some weird bugs in project. (I'm not sure if the 64b ARM is already available? I think it is not, but I didn't research the current situation thoroughly, so just ignore this, if it's already available, I will eventually find out... :) )

**Comment by fkorotkov** [comment]
Work on #397 might help to run arm containers via emulation. 🤔

**Comment by ped7g** [comment]
Actually meanwhile it occurred to me, that `qemu` can emulate ARM CPUs (with quite some wide range of choice), i.e. I guess it *may* be possible to run qemu in ARM configuration on community instance of x86_64 linux box.

But I'm in the stage of "idea" at this moment, would have to experiment first locally if I can configure qemu to emulate at least partially also quite specific environment (Pi0 running custom minimal linux distribution, with some custom drivers) and run binaries inside that and extract results of such runs.

And I would ideally build the binaries first, with x86_64 gcc cross-compiling for arm, but I'm not sure if the official gcc docker images contain also cross-variants...

I.e. many technical details to research, verify and reconsider, and right now I'm busy with different things.

Adding KVM support may help to widen the choice of possible emulators, so nonetheless thank you for your effort, it certainly helps to move this one step closer.

**Comment by fkorotkov** [comment]
@ped7g yes! But my understanding is that you'll need nested virtualization enabled which comes with #397 🤷‍♂

**Comment by j8r** [comment]
Why not directly using ARM hardware?

**Comment by fkorotkov** [comment]
Google Cloud where Linux, FreeBSD and Windows community tasks are executed is not supporting ARM yet. BTW #263 will allow to have persistent worker for any architecture.

**Comment by dankegel** [comment]
Google cloud now offers a couple ARM processors: https://cloud.google.com/compute/docs/cpu-platforms

**Comment by Minoru** [comment]
@dankegel I see a number of Intel CPUs and one AMD, but no ARM. You sure you aren't mixing up the names?

**Comment by dankegel** [comment]
Aw, foo, wishful thinking.

**Comment by MarcoFalke** [comment]
I think travis is using https://www.packet.com/ to spin up their arm machines, maybe cirrus ci could use them as well?

**Comment by fkorotkov** [comment]
I'm also pretty bored waiting for GCP so probably we'll go with [AWS Graviton](https://aws.amazon.com/ec2/graviton/). 😅Will give GCP the last chance on July 14th when they have [Google Cloud Next conference](https://cloud.withgoogle.com/next/sf).

**Comment by MarcoFalke** [comment]
It is possible to use self-hosted arm via persistent workers: https://cirrus-ci.org/guide/persistent-workers/

**Comment by fkorotkov** [comment]
Arm support is shaping and first we will only support non-privileged arm64 containers. If you are interested in beta testing the feature please reach out to support@cirruslabs.org.

**Comment by fkorotkov** [comment]
For anyone interested please take a look at #905 and give `arm_container` a try.

**Comment by emaste** [comment]
> probably we'll go with AWS Graviton

Is this likely to be Linux containers only for the foreseeable future, or is there a chance we can run (FreeBSD) VM images on Graviton?

**Comment by fkorotkov** [comment]
Just linux containers for now. Please create a separate feature request for FreeBSD. Seems there AMIs for FreeBSD 12 and 13 for ARM so it's feasible to be able to add the support.

**Comment by emaste** [comment]
Thanks, added #906

**Comment by asomers** [comment]
Thanks for adding aarch64 support!  Now Nix is tested on real aarch64 hardware, at least for Linux.
https://github.com/nix-rust/nix/pull/1506

**Comment by fkorotkov** [comment]
@asomers, awesome! Did you notice any performance gains?

**Comment by asomers** [comment]
@fkorotkov previously we tested Linux/aarch64 using user mode emulation with QEMU in a 1-CPU `compute_engine_instance`.  Now we're using the `arm_container`.  The build+test time decreased from 1m33s to 1m12s, a modest improvement.  But the setup time decreased all the way from 2m13s to 1s, since we no longer have to install QEMU and the cross-toolchain.  Not bad!
