### ISSUE TITLE
CIRRUS_WORKING_DIR docs are incomplete

### ISSUE THREAD

**Issue by gspencergoog** [cirruslabs/cirrus-ci-docs#22]
On the [writing tasks](https://cirrus-ci.org/guide/writing-tasks/) page, the CIRRUS_WORKING_DIR docs are incomplete:

```
CIRRUS_WORKING_DIR | Working directory where
```

Also, is HOME one of the variables that is pre-defined?

**Comment by fkorotkov** [comment]
@gspencergoog Cirrus CI doesn't define `$HOME`. It will depend of whether or not your container defines it. Some containers are very minimalistic. 😅
