### ISSUE TITLE
Include builds with collaborator role

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#225]
# Description
In addition to builds with owner role, include the builds with collaborator role.

# Context
A user often collaborates in other projects (not the owner, or just a contributor). This user can benefit from seeing a complete list of projects that include the user as owner or collaborator.
...

**Comment by RDIL** [comment]
Include where?

**Comment by fkorotkov** [comment]
Did you see the Active Repositories list in the left side panel. Does it look like what you are looking for?

<img width="568" alt="Screen Shot 2019-03-27 at 7 42 37 PM" src="https://user-images.githubusercontent.com/989066/55119530-9b423700-50c8-11e9-8fd5-59d4b6993ab2.png">

**Comment by mmcc007** [comment]
✅👍...Include in list of 'Active Repositories'.
(see travis implementation for comparison)

**Comment by RDIL** [comment]
ew travis bad

**Comment by mmcc007** [comment]
it makes it easier to use for those who are collaborators (I'm guessing a smaller percentage)

**Comment by mmcc007** [comment]
For example, in my 'Active Repositories' I can see:
https://github.com/mmcc007/flutter_architecture_samples (forked, role: owner)
But not
https://github.com/brianegan/flutter_architecture_samples (role: collaborator)

Food for thought 😀

**Comment by RDIL** [comment]
I see.

**Comment by mmcc007** [comment]
As collaborator I can restart builds, but have to exit my console and find the other console to do restarts.

**Comment by fkorotkov** [comment]
@mmcc007 you should see both repositories in the list. Probably need to wait for a change authored by you to be merged to `brianegan/flutter_architecture_samples`. 🤔

**Comment by mmcc007** [comment]
I started as a contributor and have been a collaborator for several months. Have never seen `brianegan/flutter_architecture_samples` listed in 'Active Repositories' (whereas I do in travis).

**Comment by fkorotkov** [comment]
Have any of your changes landed to `brianegan/flutter_architecture_samples` **after** Cirrus got enabled?

**Comment by mmcc007** [comment]
Last commit was about 6 days ago:
https://github.com/brianegan/flutter_architecture_samples/commits?author=mmcc007
So that was a few days before.

**Comment by fkorotkov** [comment]
That makes sense then! `brianegan/flutter_architecture_samples` will appear on the active repositories list once there will be a Cirrus build for that repository authored by you. 👌

**Comment by mmcc007** [comment]
ah, cool

thnx!
