### ISSUE TITLE
Retry tasks

### ISSUE THREAD

**Issue by ened** [cirruslabs/cirrus-ci-docs#226]
# Description

Is it possible that a failed task is **automatically** retried for n times (perhaps with some backoff criteria?)

# Context

One of my tasks uploads a IPA file to the App Store but fails when the store servers are unavailable, busy etc..

It would be great if I could set a single task to auto-retry N times (with some algorithm criteria perhaps on how to increase the interval over time).

**Comment by RDIL** [comment]
I see why, but personally I think that this may be hard on queues.  My thought is for each rerun should be an amount of compute credits.  
Just my thinking.

**Comment by ened** [comment]
It would be worth it, to me at least. :-)

**Comment by fkorotkov** [comment]
@ened I've being thinking about something similar but more complex... Like having criterias when to re-run a task:

- Only when a particular command failed (for example `publish`).
- When logs for a failed command contains a certain expression (for example `Timed out!`).
- ...

Maybe some other criterias...

My only concern is that **people will misuse it** to cover the actual problems in their CI tasks. Like adding a simple retry within a script and not rely on CI. Or highlighting the issue to upstream so it can fixed (for example [Gradle recently added download retries by default](https://docs.gradle.org/5.0-rc-5/release-notes.html#http-retries-during-dependency-resolution)).

Do you use Fastlane for uploading the IPA? Seems you can add a retry to Fastlane logic: https://github.com/fastlane/fastlane/issues/6995

**Comment by fkorotkov** [comment]
Will be covered by #226

**Comment by duckinator** [comment]
@fkorotkov you said this is covered by #226, but that's _this_ issue, and I can find no documentation of this functionality. Was the ability to retry certain tasks ever actually implemented?

**Comment by edigaryev** [comment]
> Was the ability to retry certain tasks ever actually implemented?

You can use Cirrus Hooks for that, [there's an example](https://cirrus-ci.org/guide/programming-tasks/#hooks) in the documentation that shows how to re-run a failed task based on its log contents.

**Comment by duckinator** [comment]
Thanks for the info. I hadn't read the Starlark sections in detail because I'm still using the YAML config. I suspect that's why I missed it.

Does this mean there's no option to basically say "wait a bit then try this a second time if it fails" if you're using YAML to configure it?

**Comment by edigaryev** [comment]
> Does this mean there's no option to basically say "wait a bit then try this task a second time if it fails" if you're using YAML to configure Cirrus CI?

It seems so, see https://github.com/cirruslabs/cirrus-ci-docs/issues/238 for more details.

**Comment by fkorotkov** [comment]
@duckinator the beauty of Startlark configuration is that you can have new part in it next to your YAML configuration.

For example, here is `.cirrus.start` file that you can put in your repository that will re-run tasks in case a task fails and logs cotain "Time out" string:

```python
load("github.com/cirrus-modules/graphql", "rerun_task_if_issue_in_logs")

def on_task_failed(ctx):
  if ctx.payload.data.task.automaticReRun:
    print("Task is already an automatic re-run! Won't even try to re-run it...")
    return
  rerun_task_if_issue_in_logs(ctx.payload.data.task.id, "Time out")
```
