### ISSUE TITLE
Provide IPs for build nodes

### ISSUE THREAD

**Issue by iskakaushik** [cirruslabs/cirrus-ci-docs#228]
# Description

Provide a list of IPs or subnet ranges of the build nodes. For reference travis ci has them like so: https://docs.travis-ci.com/user/ip-addresses/ 

# Context

For applications that query external APIs, (e.g tests that use google maps or firebase) it is good to restrict the ip ranges that can make the requests using the said API keys.

cc: @amirh, @cyanglaz, @collinjackson

**Comment by fkorotkov** [comment]
@iskakaushik it will require some infrastructure upgrades. I will prepare everything next week and will do the upgrades over the next weekend since the upgrades will disturb task execution. Sorry for the inconveniences! I hope it can wait on your side.

**Comment by fkorotkov** [comment]
@iskakaushik Linux containers now use `35.222.255.190` IP for all the requests. You can also check `A` record for `gcp.community.nat.cirrus-ci.com`.

Upgrade appeared to be a little more complicated so Linux/FreeBSD VMs, Windows and macOS upgrade will follow in the coming weeks.

**Comment by iskakaushik** [comment]
Thanks @fkorotkov , eagerly waiting fore macOS support! 👍

**Comment by fkorotkov** [comment]
@iskakaushik working with MacStadium folks on it. In the meantime you can test the Linux side. 🙌

**Comment by fkorotkov** [comment]
`macstadium.community.nat.cirrus-ci.com` is also now available with value of `207.254.42.60`.

Windows workloads will be coming next.
