### ISSUE TITLE
GCE Instance Failed to Start

### ISSUE THREAD

**Issue by liyuqian** [cirruslabs/cirrus-ci-docs#23]
Here are some example failures:

https://cirrus-ci.com/task/5166072017715200

https://cirrus-ci.com/task/5659668516962304

https://cirrus-ci.com/task/6490844211183616

BTW, I'm trying to compile flutter/engine in a GCE instance with a lot of CPUs. Starting a GCE instance in 1 minute seems to me much faster than start a container instantly but then spend 4 minutes to download all the tools.

**Comment by fkorotkov** [comment]
Hey @liyuqian,

Sorry for a long response. Please email support@cirruslabs.org for quicker responses. 😅

Does `flutter-engine-ubuntu1604` have `wget` or `curl` installed? Can you provide a little more info about this image?

BTW you can see instance created in your Compute Engine tab on GCP. Console log might give you additional information about the problem:

![image](https://user-images.githubusercontent.com/989066/43329216-9e10bd9e-9174-11e8-93db-912321ff1367.png)

**Comment by liyuqian** [comment]
@fkorotkov I confirm that `wget` and `curl` are installed. No VM instances are created by cirrus in my project.

**Comment by fkorotkov** [comment]
@liyuqian I actually did a little bit of investigation and seems something changed in how GCP treats Service Accounts. It appeared that now you need explicitly assign `iam.serviceAccountUser` role so the service account can act as a service account. I've updated the docs and here is a snippet you need to run:

```bash
gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:cirrus-ci@$PROJECT_ID.iam.gserviceaccount.com \
    --role roles/iam.serviceAccountUser
```

**Comment by liyuqian** [comment]
Thank you @fkorotkov ! That fixes it and now I can see the VM instance. BTW, yesterday I also noticed that `zone: us-west1-b` will make Cirrus not run so I changed to `zone: us-central1-a`. Is that expected?
