### ISSUE TITLE
Rerun job on git fetch timeout?

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-docs#237]
We occasionally see the `clone` step timeout (e.g. a `git fetch` or `git pull` timeout).  This seems like something that should be automatically rerun.  Is this possible?

**Comment by fkorotkov** [comment]
Interesting. It actually retried once but with no success. 🤔I think it makes sense to add auto re-try on a `clone` failure. Also shaped my thoughts about a more generic policy in #238

**Comment by fkorotkov** [comment]
`clone`s should be auto-retryable now. More work will be done in #238
