### ISSUE TITLE
AWS EC2 region names are incorrect for Europe and possibly other non-us regions

### ISSUE THREAD

**Issue by Jnewbon** [cirruslabs/cirrus-ci-docs#239]
Running an EC2 instance on eu-west-2 gives the following error

> FAILED_PRECONDITION: java.lang.IllegalArgumentException: Only eastus, europe-west1, europe-west2, europe-west3, europe-west4, us-central1, us-east-1, us-east-2, us-west-1, us-west-2, westus regions are supported!
[Link](https://cirrus-ci.com/build/5661151856689152)

When updated to europe-west2 the following error is produced

> Failed to start: FAILED_PRECONDITION: Unable to execute HTTP request: ec2.europe-west2.amazonaws.com
[Link](https://cirrus-ci.com/task/6427006282498048)

The URI for ec2 is wrong according to AWS guide [Here](https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region)

**Comment by fkorotkov** [comment]
Those regions is a mix of all supported from GCP, Azure and AWS. Fixed the error message and added support for all EU AWS regions. Please try `eu-west-2` again.
