### ISSUE TITLE
Request: Option to make Powershell the default on Windows

### ISSUE THREAD

**Issue by kne42** [cirruslabs/cirrus-ci-docs#24]
Setting some sort of environment variable/yaml option to be able to choose whether scripts are executed with `cmd` or `powershell` would be great. Also the `ps: MY_COMMAND` syntax expanding to `powershell -Command "MY_COMMAND"` would be really useful.

Being able to make powershell the default is really powerful because since powershell is shipped with a lot of bash-style commands, it allows you streamline the configuration file for OSX, Linux, and Windows together, ie for example you can use `$VAR` everywhere, `cat MY_FILE` everywhere, `ls` everywhere, etc.

Perhaps the `CIRRUS_SHELL` environment variable might be the most intuitive thing to bind this to.

**Comment by fkorotkov** [comment]
Awesome suggestion! Will work on it this week! 👌
