### ISSUE TITLE
Incorrect text rendering of square brackets in index view

### ISSUE THREAD

**Issue by am11** [cirruslabs/cirrus-ci-docs#240]
# Expected Behavior

Commit message with text in square bracket should not be treated as link, if it is not followed by parenthesis. For example, the following text to be rendered as is on the index page https://cirrus-ci.com/:

raw view:
```
Update manifest files for [pre]release branches
```

rendered as is:
Update manifest files for [pre]release branches

# Real Behavior

rendered as:
Update manifest files for [pre]()release branches

as if the raw commit message was:

```
Update manifest files for [pre]()release branches
```

# Related Info

- [x] Website issue
  - Link to page: https://cirrus-ci.com/ (push a commit with aforementioned message to see the text on list view)
  ![image](https://user-images.githubusercontent.com/3840695/55968610-04a77580-5c85-11e9-8a60-6d4e9be684b8.png)

**Comment by RDIL** [comment]
`ReactMarkdown` issue.  I will take care of this.
