### ISSUE TITLE
Support %FOO% syntax in expressions and environment variables

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#250]
# Description

Allow to use %FOO% syntax in `.cirrus.yml`.

# Context

Related to https://github.com/cirruslabs/cirrus-ci-docs/pull/247

**Comment by fkorotkov** [comment]
This change should get deployed and propagated fully in about an hour. 🙌

**Comment by RDIL** [comment]
Thanks!
