### ISSUE TITLE
download all artifacts

### ISSUE THREAD

**Issue by carlwgeorge** [cirruslabs/cirrus-ci-docs#254]
Thanks for adding support for retaining artifacts!

Is there a way to download all artifacts from a build?  I'm exploring using Cirrus to build RPM packages.  Sometimes these builds produce multiple RPM files.  As a workaround I could put the RPMs in a tar file at the end of the build, but I'd prefer not to have to do that.

Please add a way to download all artifacts from a build via a predictable and documented URL.  A button for this in the web interface would also be useful.

Since the current URL for an artifact from the latest build is:
`https://api.cirrus-ci.com/v1/artifact/github/<USER OR ORGANIZATION>/<REPOSITORY>/<TASK NAME>/<ARTIFACTS NAME>/<PATH>`

I could imagine a URL like this to get all artifacts from the latest build:
`https://api.cirrus-ci.com/v1/artifact/github/<USER OR ORGANIZATION>/<REPOSITORY>/<TASK NAME>/<ARTIFACTS NAME>`

**Comment by carlwgeorge** [comment]
Thank you so much for implementing this so quickly!

I do have a follow up question.  I'm using a matrix build, and the zip archive only contains one of the matrix permutations.  I think I could work around this by not using matrix and just having two separately named tasks, which would give me two unique URLs for zip files of each task.  But with matrix, the tasks have the same name, so it's not clear how to get artifacts from all matrix permutations.  Any suggestions?

**Comment by fkorotkov** [comment]
I think it makes sense to combine all the artifacts it you don't have `taskId` in the URL. Could you please create a separate issue with your matrix build example and link if it's a public repository?

**Comment by carlwgeorge** [comment]
[Done](https://github.com/cirruslabs/cirrus-ci-docs/issues/265), thanks!
