### ISSUE TITLE
Zero config Docker builder potential bug

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#257]
# Expected Behavior

Locally, I get no errors when trying to build my container.

# Real Behavior

On Cirrus, I get this error at the top of my logs:
```dockerfile
ERROR: logging before flag.Parse: E0421 11:44:20.593356      29 metadata.go:142] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
ERROR: logging before flag.Parse: E0421 11:44:20.595833      29 metadata.go:159] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
2019/04/21 11:44:20 No matching credentials were found, falling back on anonymous
```
NOTE: this does not break the build, it is just ugly to see. I don't think this is an issue with Cirrus, but I'm going to report it just in case.

# Related Info

- [ ] Website issue
  - Link to page: https://cirrus-ci.com/task/5701561048104960
- [X] Task issue
  - OS: DockerLinux ()
  - `$CIRRUS_SHELL` - `direct`
  - Task name: `Docker Build`
  - Script/cache name (if applies): `build`

**Comment by fkorotkov** [comment]
I think it's fine. It just tells that there are no credentials to push an image but don't really plan to push anything in the zero config builds. 🤷‍♂️

**Comment by RDIL** [comment]
Okay.  Thanks.
