### ISSUE TITLE
Artifact extension bugged

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#258]
# Expected Behavior

Jar files should be `.jar` files when downloaded

# Real Behavior

When I download the file, it ends up being a `.jar.html`

# Related Info

- [X] Website issue
  - Link to page: Api
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Do you have an example task?

**Comment by RDIL** [comment]
Once https://cirrus-ci.com/task/5098080629161984 finishes in a min or 2 it should show the behavior.

**Comment by RDIL** [comment]
Strange, now I get the JSON response:
```json
code: 500
message: "blob.contentType must not be null"
```

**Comment by fkorotkov** [comment]
Should be fixed now

**Comment by RDIL** [comment]
Yes, it downloads as a normal Jar now, thank you so much!
