### ISSUE TITLE
Adding Valid Google Regions/Zones to Docs

### ISSUE THREAD

**Issue by ccavolt** [cirruslabs/cirrus-ci-docs#266]
I created a GKE cluster in Northern Virginia (us-east4), and then tried to use it with Cirrus CI.  The build gave me the following error:

FAILED_PRECONDITION: java.lang.IllegalArgumentException: Only zones from europe-west1, europe-west2, europe-west3, europe-west4, us-central1 regions are supported!

I created a cluster in us-central1, so the problem is solved for me.  However, for newcomers such as myself, I was thinking it might be a good idea to list the valid regions/zones in the docs, probably in the Google Cloud section of the "Supported Computing Services" page.  Is this possible?  I'd create a pull request for it, but I'm not 100% sure where the appropriate place for it is in the documentation.

**Comment by RDIL** [comment]
I would put it in the supported compute services page

**Comment by fkorotkov** [comment]
I'll add support for the regions. But I think it's worth to mention the available regions such as

- us-central1
- us-east1
- us-east4
- us-west1
- us-west2
- europe-west1
- europe-west2
- europe-west3
- europe-west4

Either I or you should create a PR to add it to *Google Cloud* section. Thanks for suggestion!

**Comment by ccavolt** [comment]
Haha, looks like I was about a day early, since the region I initially used is now supported.  Oh well, Iowa's cheaper anyway.  I'll take a look at the docs tomorrow to see if I can find a good place for it.
