### ISSUE TITLE
Maven Cache

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#271]
# Question

Anybody know how to cache on Cirrus with maven?

**Comment by fkorotkov** [comment]
Have you tried simply to cache `$HOME/.m2`?

```yaml
maven_cache:
  folder: $HOME/.m2
```

**Comment by RDIL** [comment]
Thanks.  Trying that out now.

**Comment by RDIL** [comment]
Works like a charm, took 12 seconds off the build time 😍

**Comment by fkorotkov** [comment]
You can add it to #260 ;-)
