### ISSUE TITLE
Track injected files when caching Docker builds

### ISSUE THREAD

**Issue by nbraud** [cirruslabs/cirrus-ci-docs#273]
# Description

Currently, Docker image builds are cached based on (a hash of) the `Dockerfile`'s contents.
By opposition, Docker's canonical cache recognise `ADD` instructions, and will only reuse a built layer if the same file is being added.

Please consider aligning the behaviour with Docker's.
This can be done by tracking `ADD`ed files and directory during the build, hashing them, and making that manifest part of the hash that identifies a specific build.

# Context

When using Dockerfiles as CI environments, it is common to inject files that describe dependencies (Python's requirements files, Maven project files, ...) and preinstall all necessary dependencies.

With the current behaviour, Cirrus doesn't invalidate the cached build, resulting in CI environments that do not have the correct dependencies installed.

**Comment by fkorotkov** [comment]
Yeah. I've though about it and that might be a bit tricky. The solution I came up comes to the following new flow: when a Dockerfile contains `COPY` or `ADD` always try to build the container with a Docker builder that supports caching. I'm thinking about one of these options:

1. https://github.com/uber/makisu with [HTTP cache](https://github.com/uber/makisu#using-cache)
2. https://github.com/GoogleContainerTools/kaniko if https://github.com/GoogleContainerTools/kaniko/issues/463 will be implemented.

**Comment by fkorotkov** [comment]
Created https://github.com/cirruslabs/cirrus-cli/issues/222 to track implementation of this feature.

**Comment by fkorotkov** [comment]
BTW there is a potential danger or using `COPY` and `ADD` instruction at the moment. See #760 for details.

**Comment by edigaryev** [comment]
Implemented in https://github.com/cirruslabs/cirrus-cli/pull/452.

**Comment by nbraud** [comment]
Thanks a bunch!  I look forward to using that, and/or the new Skylark support, to speed up our CI dramatically.

Back when I tested this, I could get Linux & Windows CI times below 5s w/ prebuilt containers, and the issue was that we had no good way to make it work properly when dependencies changed (either updates in PyPI, or changes in the requirements files)

**Comment by fkorotkov** [comment]
@nbraud under 5 seconds!? Wow! Would love to see your confit if it will be public. 💪
