### ISSUE TITLE
Enable pipefail option by default for bash scripts

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#274]
# Description

With using ``CIRRUS_SHELL: "/bin/bash"``, script-section commands end up being executed via an intermediate script file on the VM or container.  If the script command contains any pipes, then they will be subject to a peculiar bash-ism which often catches people off-guard.  From the bash man page:

> The  return  status  of  a pipeline is the exit status of the last command, unless the pipefail option is enabled.  If pipefail is enabled, the pipeline's return status is the  value  of  the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully.

I would like Cirrus-CI to automatically add 'set -o pipefail' to the head of the intermediate script pushed to the VM/Container.  That alters the default behavior so that _ANY_ failing command in the pipeline will pass along it's exit code - which most people (incorrectly) assume is the default.

# Context

For the vast majority of cases, 'pipefail' (on) is likely desirable behavior.  If by chance the non-pipefail (default) behavior is desired, it may be re-enabled by explicitly adding ``set +o pipefail`` in a `script` section.  This has the added benefit of making the (odd) default behavior obvious to anyone debugging `.cirrus.yml`.

# Anything Else

Example of current behavior (this task will always **pass** - unless `sort` somehow breaks):

```yaml
env:
     CIRRUS_SHELL: "/bin/bash"

some_task:
     some_script:
         - '/bin/false |& sort'
         - ...
```

With Cirrus-CI automatically adding `set -o pipefail`, the above script would fail (as most people would expect on first glance).

**Comment by fkorotkov** [comment]
It should default `set -o pipefail` now. Thanks for the suggestion! 🙌

**Comment by cevich** [comment]
@fkorotkov :+1:     works perfectly :smile:
