### ISSUE TITLE
Install step started failing on FreeBSD without changes to .cirrus.yml

### ISSUE THREAD

**Issue by plicease** [cirruslabs/cirrus-ci-docs#275]
# Expected Behavior

install step completes on FreeBSD as it did before.

# Real Behavior

I get this in the install step:

```
set: Illegal option -o pipefail
Exit status: 2
```

https://cirrus-ci.com/task/5108964982259712

This doesn't seem to be related to any changes in my git repository.  I definitely haven't changed my `.cirrus.yml` file.

# Related Info

Could this be related to #274?

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: FreeBSD
  - Task name: 
  - Script/cache name (if applies):

**Comment by RDIL** [comment]
**Can reproduce**.
Side effect of #274 
@fkorotkov

**Comment by fkorotkov** [comment]
Wow. It should be fixed now. Unfortunately integration tests were only for Linux, Windows and Mac. 😪

**Comment by plicease** [comment]
Thank you for the quick fix 👍

**Comment by fkorotkov** [comment]
First of all, sorry for breaking it!😅 As a follow up will make integration tests to run on FreeBSD. 🙌

**Comment by cevich** [comment]
@RDIL @plicease I'm sorry for my hand in this as well.  I'm glad it's resolved, and it sounds like coverage is also improved FreeBSD.
