### ISSUE TITLE
Failed to upload artifact file

### ISSUE THREAD

**Issue by carlwgeorge** [cirruslabs/cirrus-ci-docs#281]
I ran across an error while building some RPM artifacts in Cirrus.

```
Failed to upload artifact file /tmp/cirrus-ci-build/mariadb102-debuginfo-10.2.22-2.el7.ius.x86_64.rpm: EOF
```

https://cirrus-ci.com/task/4840886495084544

Is there a file size limit on artifacts?  ~I'd estimate this artifact was roughly 40MB in size.~  I built it locally and that RPM is bigger than I expected.  It is 135MB in size.

**Comment by fkorotkov** [comment]
Yeah. There is a 100Mb limit. I wonder why the error message didn't report it. Anyways I've bumped it to 1G since 100Mb seems to be too small for artifacts.

**Comment by carlwgeorge** [comment]
Amazing, thank you!
