### ISSUE TITLE
Proper badge support with shields.io

### ISSUE THREAD

**Issue by abitrolly** [cirruslabs/cirrus-ci-docs#283]
I am hitting GitHub caches issue described in #223. https://api.cirrus-ci.com/github/yakshaveinc/linux.svg shows as passing, but repository status is "not found" ![](https://camo.githubusercontent.com/5a8dfc699427ef47b722f387be2e556085ce78d2/68747470733a2f2f6170692e6369727275732d63692e636f6d2f6769746875622f79616b7368617665696e632f6c696e75782e737667)

The solution is to add first hand support to https://shields.io which may better work around GitHub caching requests https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by RDIL** [comment]
Related:
#279 
#223

**Comment by RDIL** [comment]
I can create the badges on shields's end if you are able to add an API URL that responds with passing or failing.

**Comment by fkorotkov** [comment]
There is now a JSON endpoint to get the badge information. Simply change `.svg` to `.json`. For example, https://api.cirrus-ci.com/github/yakshaveinc/linux.json

@RDIL do you still have bandwidth to take a loot at submitting a PR to https://github.com/badges/shields to add the support?

**Comment by RDIL** [comment]
Yeah, taking the weekend off though. I’ll look into it on Monday.

**Comment by fkorotkov** [comment]
Thank you!

**Comment by RDIL** [comment]
Okay going to take a look at this now

**Comment by RDIL** [comment]
Okay, PR is open, feel free to help out :)

**Comment by awnumar** [comment]
I'm experiencing the same issue but both the svg and json links are returning `not+found`: ![badge](https://api.cirrus-ci.com/github/awnumar/memguard.svg)

https://api.cirrus-ci.com/github/awnumar/memguard.svg
https://api.cirrus-ci.com/github/awnumar/memguard.json

So I'm not sure if the proposed shields.io solution would work since it pulls from the json endpoint.

**Comment by fkorotkov** [comment]
@awnumar there are no master builds for the repository. You can specify branch via `?branch=cirrus` query like this: https://api.cirrus-ci.com/github/awnumar/memguard.svg?branch=cirrus

**Comment by awnumar** [comment]
@fkorotkov Heyy nice one thanks!

**Comment by fkorotkov** [comment]
@RDIL do you still have time to follow up on https://github.com/badges/shields/pull/3502? Or should I take over?

**Comment by RDIL** [comment]
Honestly, I really have to get something done before Tuesday, so I can't really right now.  If you comment suggestions, I'll accept them though.

**Comment by calebcartwright** [comment]
> There is now a JSON endpoint to get the badge information. Simply change `.svg` to `.json`. For example, https://api.cirrus-ci.com/github/yakshaveinc/linux.json
> 
> @RDIL do you still have bandwidth to take a loot at submitting a PR to https://github.com/badges/shields to add the support?

Hi, Shields maintainer here :wave: It seems this endpoint was dropped ~2 days ago or has otherwise become unavailable, as it's returning a 404 response for all projects:

```
$ curl -I https://api.cirrus-ci.com/github/cirruslabs/cirrus-ci-web.json
HTTP/2 404 
date: Fri, 01 Oct 2021 23:31:43 GMT
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
content-type: application/json
content-length: 43
via: 1.1 google
alt-svc: clear
```

I see that there's now a GraphQL (https://cirrus-ci.org/api/) endpoint, so curious whether the dropping of the json endpoint was intentional?

**Comment by fkorotkov** [comment]
@calebcartwright sorry for the delayed response just saw the mention. Please don't hesitate to email support for quicker turn around next time.

This REST path was not covered with tests and a recent refactoring broke it. I've fixed the issue and added tests for the endpoint. Sorry for the inconveniences! Everything should be working now.

**Comment by calebcartwright** [comment]
No worries @fkorotkov, thanks for the quick fix!
