### ISSUE TITLE
Available MacOS simulator runtime versions changes across MacOS instances

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#285]
According to https://cirrus-ci.com/build/5167476017987584 some macOS instances have a different list of available simulator runtimes from others. 

I expected:
```
iOS 12.0 (12.0 - 16A366) - com.apple.CoreSimulator.SimRuntime.iOS-12-0 
iOS 12.1 (12.1 - 16B91) - com.apple.CoreSimulator.SimRuntime.iOS-12-1 
```
as in https://cirrus-ci.com/task/6153403209089024 but sometimes get:
```
iOS 12.0 (12.0 - 16A366) - com.apple.CoreSimulator.SimRuntime.iOS-12-0 
iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2 
```
as in https://cirrus-ci.com/task/5708745741434880.

I have been able to work around this by reverting to the common version, but thought you should know. Perhaps there is a macOS version specifier I am not using? If there is, I'm guessing there should probably be a default for build consistency.

**Comment by mmcc007** [comment]
BTW: you can see the fix here: https://github.com/brianegan/flutter_architecture_samples/pull/133

**Comment by fkorotkov** [comment]
That is very weird since identical VMs should be used for both tasks. Thanks for reporting! I'll investigate!

**Comment by fkorotkov** [comment]
@mmcc007 I've poked VM caches so I think `iOS-12-2` should work now. 🤔 Seems there was some instances with old VMs cached. Could you please try again?

**Comment by mmcc007** [comment]
I did a quick scan on https://cirrus-ci.com/build/5170891550359552 and the list of available simulator runtimes is consistent.
```
iOS 12.0 (12.0 - 16A366) - com.apple.CoreSimulator.SimRuntime.iOS-12-0 
iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2
```
Looks like the transition from an old macOS image to the next macOS image was in progress while the build was running (this was about a month ago)
https://cirrus-ci.com/build/5167476017987584

**Comment by fkorotkov** [comment]
Awesome! Glad it worked for you!
