### ISSUE TITLE
GCS Buckets are created as multi-regional - regional is probably better

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#287]
Currently it seems cirrus creates multi-regional GCS buckets for logs and caching.
Does it really require multi-regional buckets? I'd assume regional buckets regional buckets in the region of the GCE instances / GKE cluster which executes the jobs should be sufficient. Regional buckets are both cheaper and faster and totally should serve the purpose of cirrus.

**Comment by fkorotkov** [comment]
I does make sense, people usually work within one region but many zones. Cirrus is usually goes with the defaults which is multi-region for GCS. I'll think about it for a little while to see if we don't miss anything. Will also to try to find out why GCS has such defaults. 🤔

**Comment by fkorotkov** [comment]
It should be fixed now. 🙌
