### ISSUE TITLE
Cache instruction chokes up when cache contains broken symlinks

### ISSUE THREAD

**Issue by dotdoom** [cirruslabs/cirrus-ci-docs#288]
# Expected Behavior

Broken symlinks are cached (as symlinks) regardless of where they point to: file outside the `cache_folder`, file within `cache_folder` or nonexistent file.

# Real Behavior

"Upload cache" reports failure and does not store cache (next build reports "Cache miss").

Failed to calculate hash of /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/SDK! open /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/SDK/symlink: no such file or directorySkipping uploading of /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/SDK!

# Related Info

* https://github.com/dotdoom/onfailure
* https://cirrus-ci.com/task/5684879681912832

  - OS: (DockerLinux, macOS)
  - Task name: symlinks
  - Script/cache name (if applies): main

**Comment by RDIL** [comment]
**Can reproduce**
@fkorotkov we had a private conversation about this earlier this year

**Comment by dotdoom** [comment]
Real world case:

[This Flutter directory](https://github.com/flutter/flutter/tree/master/dev/integration_tests/ios_add2app/Pods/Headers/Public/Flutter/Flutter/) is full of non-existent symlinks until iOS tests for the Flutter framework itself run (which doesn't happen on derived project build / test run).

A portable workaround is to run:

```shell
$ find /directory/with/flutter -type l -exec test ! -e {} \; -print -delete
```

**Comment by fkorotkov** [comment]
Thank you for the example! I was able to reproduce it in a test and fixed it. Your example should be working now. Could you please try once again on your project now?

**Comment by dotdoom** [comment]
Great! It works perfectly now, the cache is being uploaded without error messages, and then downloads for the next build. Thank you!
