### ISSUE TITLE
Support parentheses in boolean statements

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#289]
# Description

In statements like `only_if`, Cirrus throws `java.lang.IllegalArgumentException` if you have something like this:
```yaml
only_if: ($CIRRUS_PR == '' || $CIRRUS_TAG != '') && $CIRRUS_USER_COLLABORATOR == 'true'
```
the above statement should only run if this is not a PR, is a tag, and the author has write
disclaimer: **I know how the no-pr check is useless, its the first thing that came to mind as an example**

# Context

Improved condition checking

**Comment by fkorotkov** [comment]
Parentheses are supported. Did you mean to use `CIRRUS_USER_PERMISSION` instead of `CIRRUS_USER_COLLABORATOR`?

**Comment by RDIL** [comment]
Oh huh, maybe that was it 🤷‍♂
