### ISSUE TITLE
Support conditions for cache uploads

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#292]
# Description

Right now, it is not possible to use `always` and `on_failure` on the cache uploads as the YAML is autogenerated.  It would be nice to have something like `always_upload: true`

# Reasoning

Would be nice to have faster builds after failures (when you don't have a matching cache)

**Comment by fkorotkov** [comment]
Execution behaviour of the upload is the same as for the download so the following should work:

```yaml
always:
  my_cache:
    folder: foo
```
