### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#293]
# Expected Behavior

Should work normally

# Real Behavior

* Backend not reporting statuses to github
* API calls are bouncing back with no data

# Anything else

have noticed this on multiple repos

**Comment by RDIL** [comment]
Queue just started working, API still being odd.

**Comment by fkorotkov** [comment]
What do you mean by the queue?

Do you have a concrete issue with the API?

**Comment by RDIL** [comment]
Queue as in whatever module is used to schedule tasks.
Edit: API working again

**Comment by fkorotkov** [comment]
👍 feel free to ping support@cirruslabs.org next time for quicker response. 🙌
