### ISSUE TITLE
Rate limit / day limit for CI?

### ISSUE THREAD

**Issue by robertguetzkow** [cirruslabs/cirrus-ci-docs#297]
# Question

I've started experimenting with Cirrus CI today and noticed that it doesn't build new commits anymore. Is there a limit of builds per day using the free version? In case there isn't, any idea how to get the builds working again (I've already reinstalled the GitHub Cirrus CI App)?

BTW I really like your service, great to have all major operating systems available!

**Comment by fkorotkov** [comment]
There is no daily limit. There are some internal mechanism to see if people are mining coins or just simply abusing free usage. In this case there will be an error with a message to contact support but we'll probably contact you first.

In you case it's the currently going GitHub incident: https://www.githubstatus.com/ Once it's resolved Cirrus will catch up.

**Comment by RDIL** [comment]
**Can reproduce**.
Yeah, its happening to me as well, issue on the GitHub backend.  You can get around this for now by using the new `Manual Tasks` feature.

**Comment by robertguetzkow** [comment]
Thanks! Yes looks like there is/was a problem with the webhooks.

**Comment by fkorotkov** [comment]
@RDIL correction: not the [manual tasks](https://cirrus-ci.org/guide/writing-tasks/#manual-tasks) but manual creation of tasks from a repository page via `+` button.

**Comment by RDIL** [comment]
Almost the same thing...
