### ISSUE TITLE
Task specific badges show a passing build although it failed

### ISSUE THREAD

**Issue by robertguetzkow** [cirruslabs/cirrus-ci-docs#301]
# Expected Behavior

The tasks should display the actual build status.

# Real Behavior

For failing Windows build I have a passing badge displayed in this [README.md](https://github.com/robertguetzkow/libtrashcan/blob/master/README.md).

# Related Info

This error seems to be different than #294 because the build in question was never successful, so this shouldn't be a cached result.

**Comment by RDIL** [comment]
Definitely something going on with badges that needs to be looked into.

**Comment by fkorotkov** [comment]
@robertguetzkow thank you for reporting! There is indeed a bug in badge calculation for a task in this case. I've identified the issue, already fixed it and it will be deployed shortly.

**Comment by fkorotkov** [comment]
@robertguetzkow have you just delete the repository? The fix is deployed but I cannot verify it on your repo (new tests are passing though).

**Comment by robertguetzkow** [comment]
@fkorotkov Yes, sorry I've deleted the test repository. The link is now fixed and points to the actual repository.

**Comment by robertguetzkow** [comment]
Could it be that the fix broke something? ATM it doesn't find the build badges "CI not+found".

**Comment by fkorotkov** [comment]
@robertguetzkow which one? where?

**Comment by robertguetzkow** [comment]
[These](https://github.com/robertguetzkow/libtrashcan/blob/master/README.md).

**Comment by fkorotkov** [comment]
Works for me. 😲

<img width="697" alt="Screen Shot 2019-05-23 at 10 43 39 AM" src="https://user-images.githubusercontent.com/989066/58262125-a7084d80-7d47-11e9-814d-adf292f6b25f.png">

**Comment by RDIL** [comment]
thats ironic, it says macos yet that screenshot was taken on a mac 😆

**Comment by robertguetzkow** [comment]
What you're screenshot show is correct. This is what I see (in an incognito window to avoid caching issues):

![screenshot](https://user-images.githubusercontent.com/25986807/58262426-89081080-7d7a-11e9-91aa-59dc9948c2b2.jpg)

**Comment by RDIL** [comment]
petition to redo the badge system
press thumbs up to sign

**Comment by fkorotkov** [comment]
I see the same in an incognito windows. 🤔 Will investigate further

**Comment by fkorotkov** [comment]
@robertguetzkow since I can't reproduce. Could you please check the readme again?

**Comment by robertguetzkow** [comment]
It's currently showing "Ci not+found" for all entries.

**Comment by fkorotkov** [comment]
I've also tried website like https://www.url2png.com/ but see an expected result:

<img width="1170" alt="Screen Shot 2019-05-23 at 12 47 24 PM" src="https://user-images.githubusercontent.com/989066/58270990-0458ca80-7d59-11e9-8880-9071f99290bc.png">

**Comment by robertguetzkow** [comment]
🤷‍♀️ Not sure what is causing this. Do you use some form of CDN that might give different results depending on geographic location? Both computer I tested this on are in Germany.

**Comment by robertguetzkow** [comment]
I've tested this over a proxy (US) and get the same result as in the first screenshot with macOS passing and BSD not found. With another proxy (Germany) the result is correct. Another one has all set to "not found" as well. Seems like either one of these three states is occurring. Apparently this behavior is not linked to the physical location of the computer.

**Comment by RDIL** [comment]
VPN to Australia has same results as mac screenshot

**Comment by fkorotkov** [comment]
Very weird. I'm currently rewriting badge serving for #294. Let's see if it will help. There is no CDN for badges except GitHub's internal caching of pre-rendered Markdown. I also don't see any internal exceptions for your repository. 😪

**Comment by robertguetzkow** [comment]
Looks like this issue is happening at GitHub, because if I copy & paste the [URL ](https://api.cirrus-ci.com/github/robertguetzkow/libtrashcan.svg?task=macOS)(instead of visiting the page where it loads them through camo.githubusercontent.com) everything is displayed correctly.

**Comment by fkorotkov** [comment]
Seems like #294 then. I wonder why it started happening all of the sudden when the badge delivering mechanism was there from day 0 for almost two years. 😢

**Comment by robertguetzkow** [comment]
Thank you for your help and good luck with the patch for #294 !
