### ISSUE TITLE
failed to upload logs and artifacts

### ISSUE THREAD

**Issue by carlwgeorge** [cirruslabs/cirrus-ci-docs#306]
Since yesterday I'm consistently getting the error "Failed to upload some logs!" with my Cirrus builds.  Artifacts are also not being uploaded.

- https://cirrus-ci.com/task/5449627218739200
- https://cirrus-ci.com/task/6230240997670912

That first is showing the results_artifacts step failing.  The second one passes, but there are no artifacts.  Neither have logs for me to investigate.

**Comment by fkorotkov** [comment]
Should work now! Sorry for the inconvenience!

**Comment by carlwgeorge** [comment]
Re-running those worked, thank you so much!  I continue to be blown away by your level of support, even for non-paying open source users!  :+1:
