### ISSUE TITLE
Customizable CIRRUS_HTTP_CACHE_HOST

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#310]
The doc says that port 12321 will be used to start a caching server on localhost. (https://cirrus-ci.org/guide/writing-tasks/#http-cache)

Is there a way to disable it or assign it to a different port? Some test suites might use a large port range (e.g. from 10000 to 20000) and assume that none of the ports are taken.

**Comment by fkorotkov** [comment]
If you don't need the caching at all you can disable it by providing a fake `CIRRUS_HTTP_CACHE_HOST` environment variable. If there is `CIRRUS_HTTP_CACHE_HOST` specified then Cirrus won't start an internal cache. **Note:** that [cache instructions](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction) will stop working as well. Does it work for you?

**Comment by MarcoFalke** [comment]
I am using the regular cache (`folder` cache) and don't need the http cache.

I understand that my test suite should query if the port is accessible and use a different one if not. Though, I can also see the argument that a fresh spun up ci system shouldn't use ports that are not needed (at least provide a way to opt out).

**Comment by fkorotkov** [comment]
It's not possible in the current design to opt out of the http cache without opting out from caching folders (folder caching mechanism uses HTTP cache to upload and download caches).

What we can do here is to make `CIRRUS_HTTP_CACHE_HOST` actionable. If `CIRRUS_HTTP_CACHE_HOST` will be provided by a user and will point to a `localhost` or `127.0.0.1` and there is nothing running on the port then Cirrus agent will use port from `CIRRUS_HTTP_CACHE_HOST`.

BTW are you facing the issue in your tests? Most of the libraries/tools I know can pass port `0` to dynamically allocate an available port.

**Comment by MarcoFalke** [comment]
> BTW are you facing the issue in your tests? Most of the libraries/tools I know can pass port 0 to dynamically allocate an available port.

It is a bit complicated:

* We spin up several nodes per test (each node gets its own port)
* We run several tests in parallel

So to avoid nodes from different tests colliding on ports, the port assignment must be deterministic (can not be dynamic).

I will fix it on our side by making the port assignment seed configurable by the user.

https://github.com/bitcoin/bitcoin/pull/16918

I don't think this is an issue on your side, so I am closing this.
