### ISSUE TITLE
OpenBSD Support

### ISSUE THREAD

**Issue by awnumar** [cirruslabs/cirrus-ci-docs#311]
I see you support FreeBSD which is amazing! OpenBSD support in addition to this would be great as it's one of the main *BSDs and the most sound from a security perspective. Ensuring builds work on it properly is important.

Is this possible with the current infrastructure on Google Cloud?

Related: #65 #101

**Comment by fkorotkov** [comment]
Cirrus CI agent is written in Go so it's possible to compile it for OpenBSD. The only thing that is missing is OpenBSD images for Google Compute Engine like [FreeBSD has](https://console.cloud.google.com/marketplace/details/freebsd-cloud/freebsd-12). It's similar to DragonFlyBSD issue #101 in that sense.

**Comment by awnumar** [comment]
That's unfortunate. I did however find [this](https://dev.to/nabbisen/openbsd-vm-on-gcegcp---12-local-part-gp3) resource on building a custom image for OpenBSD on GCE.

**Comment by fkorotkov** [comment]
Sorry about that. There is simply no bandwidth and expertise at the moment to support such VMs on our side. 😪
