### ISSUE TITLE
OSX: cache download routinely corrupted

### ISSUE THREAD

**Issue by dotdoom** [cirruslabs/cirrus-ci-docs#312]
# Expected Behavior

Cache is downloaded to osx container and is restored normally.

# Real Behavior

About 4 times of 20 (on a real project), the cache download is incomplete.

## Upload

```
SHA for /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/cache is 'b902af4c187aeaefafb2e733c04176c9330d76226840e85d411b06ac7f42ec84'
test cache size is 495Mb.
Uploading cache test...
```

## Download

Note the size of the download: **~70Mb smaller**.

```
Downloaded 426Mb.
Cache hit for test-21356f059533b7faf57e85468c9c876001da0e50ddca8d5b8120157acb8c9034!
Failed to unarchive test cache because of /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/cache/6705: writing file after 859529 bytes: unexpected EOF!
Treating this failure as a cache miss! Cleaning up /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/cache...
```

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: macOS
  - Task name: https://github.com/dotdoom/onfailure/blob/9b466fe579ba80483a3f01cdaee3ec136c0cf4d9/.cirrus.yml
  - Script/cache name (if applies): test

Re-running the same build with 500Mb cache:

1. https://cirrus-ci.com/task/6291437738524672: cache is created for the first time, upload OK
1. https://cirrus-ci.com/task/6282363747696640: cache download crippled :negative_squared_cross_mark:, upload OK 
1. https://cirrus-ci.com/task/5198866777899008: cache download OK :heavy_check_mark:, upload OK
1. https://cirrus-ci.com/task/5634364260483072: cache download OK :heavy_check_mark:, upload OK
1. [**removed the script that was changing cache, to make things faster**](https://github.com/dotdoom/onfailure/commit/0acacb87539404283c85900d6ba8b43887e4306f)
   https://cirrus-ci.com/task/5958359413424128: cache download crippled :negative_squared_cross_mark:, upload OK
1. https://cirrus-ci.com/task/5700815994486784: cache download crippled :negative_squared_cross_mark:, upload OK
1. https://cirrus-ci.com/task/5707987381911552: cache download crippled :negative_squared_cross_mark:

**Comment by fkorotkov** [comment]
Thank you for a reproducible example! This was happening because of a big cache size and slower download speed from the Mac infrastructure. I've tweaked some settings and can no longer reproduce the issue.

**Comment by dotdoom** [comment]
It's getting back (see "flutter" cache task):

* https://cirrus-ci.com/task/6200322357198848?command=flutter#L5
  "Failed to unarchive flutter cache because of /Users/anka/flutter/bin/cache/dart-sdk/model/lexeme/model.tflite: writing file after 143453125 bytes: unexpected EOF!"

* https://cirrus-ci.com/task/6311673175998464?command=flutter#L5
  "Failed to unarchive flutter cache because of /Users/anka/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/platform_strong.dill.S: writing file after 461311 bytes: unexpected EOF!"

* https://cirrus-ci.com/task/6601223244873728?command=flutter#L5
  "Failed to unarchive flutter cache because of /Users/anka/flutter/bin/cache/dart-sdk/model/lexeme/model.tflite: writing file after 113367951 bytes: unexpected EOF!"

* https://cirrus-ci.com/task/5386689624670208?command=flutter#L5
  "Failed to unarchive flutter cache because of /Users/anka/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester: writing file after 4375957 bytes: unexpected EOF!"

**Comment by fkorotkov** [comment]
@dotdoom I've just added some additional debug information upon such failures. Plus tweaked some things that might have caused the issue. Will keep an eye on your builds to see if it helped.

**Comment by fkorotkov** [comment]
There was a similar issue from a project that had a cache that was always changing and therefore Cirrus was re-uploading the entity. There were some index files that were always changed. You can now disable reupload via #568
