### ISSUE TITLE
Re-order some parts of docs

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#314]
I think that the `writing tasks` page is way too long right now.

I think it should be considered that some changes be made, like for example badges be moved to API doc.

**Comment by fkorotkov** [comment]
I think we'll create a separate *Tips and Tricks* page for that after #313

**Comment by RDIL** [comment]
Now I can't connect, it throws ERR_TOO_MANY_REDIRECTS

**Comment by fkorotkov** [comment]
😮I've checked from multiple machines and from a phone as well. Are you under a firewall?

**Comment by RDIL** [comment]
That might be it.
