### ISSUE TITLE
Longest Path Report

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#315]
# Description

A report that illustrates the paths thru the tasks of a build, highlighting the [longest path](https://en.wikipedia.org/wiki/Critical_path_method). Something like:
![image](https://user-images.githubusercontent.com/1980785/58659118-fe259980-82d6-11e9-8724-7eb5bfa6dde4.png)
with the longest path highlighted. 

It would be useful to include an analysis of the longest path showing which type of VMs were used. Also useful, would be to include a recommendation (if any) on how increasing [the limits](https://cirrus-ci.org/faq/#are-there-any-limits) would be anticipated to improve build time.

# Context
It is difficult for a user to determine what, in the build environment or in the .cirrus.yml, is limiting the build time.
This report could be used to improve build times by fine-tuning the .cirrus.yml (including the containers/VMs sizes), and how to better use [the limits](https://cirrus-ci.org/faq/#are-there-any-limits).

# Anything Else

...

**Comment by fkorotkov** [comment]
I think [recently added Gantt charts](https://twitter.com/fedor/status/1360411865269096451) should show it.
