### ISSUE TITLE
Build time-out is unexpected

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#320]
# Expected Behavior
Build should complete successfully
Closely equivalent build on travis of same commit succeeded:
https://travis-ci.org/brianegan/flutter_architecture_samples/builds/540887794

# Real Behavior
Build is consistently timing out in unit tests:
https://cirrus-ci.com/build/5769554161041408
(plus oddly enough, the rest of the build never runs)

Other examples of unit tests timing out:
https://cirrus-ci.com/task/5101550817509376
https://cirrus-ci.com/task/5765580901056512
https://cirrus-ci.com/task/6311207196164096

**Comment by mmcc007** [comment]
Looks like we are still on v1.2.1-stable on travis
https://github.com/brianegan/flutter_architecture_samples/blob/9c99d2d6d3ec8734c1db599dca7c8e0fd97f3bb1/.travis.yml#L3-L4
and v1.5.4-hotfix.2 (latest) on cirrus
https://github.com/cirruslabs/docker-images-flutter/blob/5b8b57f2cc658c96f2b580108a6a07563da8a138/.cirrus.yml#L8-L9

I'm able to reproduce the timeout locally on v1.5.4-hotfix.2. So am closing.

Should be able to fix by using 1.2.1 docker tag in .cirrus.yml for now (hopefully).

**Comment by mmcc007** [comment]
I'm trying to revert to v1.2.1-stable. Looks like I can do it on linux using cirrusci/flutter:v1.2.1 from docker hub. But can't find a way to do the same on `mojave-flutter`. Do you preserve the old Anka images to access via a tag like docker hub, or do I have to install flutter explicitly to over-ride the existing flutter? Is there somewhere in the docs that describe the flutter version on `mojave-flutter`?

**Comment by fkorotkov** [comment]
@mmcc007 sorry for a delayed response. When you initially posted the issue I did some investigation but without any conclusions and that's why didn't post anything. Glad you found the issue!

For mojave you'll need manually switch the version. According to https://github.com/flutter/flutter/pull/26840 this should work: `flutter version 1.2.1`

**Comment by mmcc007** [comment]
No problem, sorry for what turned-out to be a bogus bug report.

I quickly forget how things work when things continue to work. Resulting in loosing some context when attempting to diagnose. Ended-up explicitly pinning flutter version (wasn't sure whether would run into problems on Anka images, so did what I was most familiar with for a CI/CD env by doing an install of the flutter version and setting the PATH). 

Thanks for the tip on `flutter version 1.2.1` (I've been using it recently a lot locally but for some reason didn't think it would work in an Anka image. I'll use it next time).

For those more forgetful among us, might want to consider adding a tag-like suffix to `mojave-flutter` to remind reviewers that it is the latest stable release (and is not pinned). Something like `mojave-flutter_latest` and a note about `flutter version <version tag>` if you want to pin the flutter version. The equivalent note about pinning for `cirrusci/flutter:latest` might be helpful also.

Of course, pinning is not a great practice in CI/CD but is common when there is no mechanism for auto-updating-to-latest provided by the hosted continuous integration service (for example, more common on travis). Cirrus setup has the advantage of this mechanism for flutter but no documented way to pin.

**Comment by mmcc007** [comment]
For example, I forgot/was not aware of Cirrus's auto-update-to-latest feature for flutter -- on both linux and macOS -- when accepting a PR (while unit tests were mysteriously timing out on flutter latest on Cirrus). 

This resulted in backing-out PR while attempting to pin flutter on Cirrus (PR was dependent on flutter latest, plus flutter upgrades can sometimes result in dependency conflicts as in this case):
https://github.com/brianegan/flutter_architecture_samples/pull/139

Pinning on cirrus is working now. Still have to resolve timeout issue on latest flutter (possibly code-coverage related). Can then re-apply PR.

**Comment by fkorotkov** [comment]
Make sense. Anka does support some kind of tagging. Will get it to work in with the next flutter release. Created #324 for tracking.
