### ISSUE TITLE
HTML Linux embedded in logs

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#321]
# Description

Set `Content-Type` from `text/plain` to something like `text/html` on stored logs.

# Context

We would like to have our testing scripts output in-line HTML tags, which render properly when viewing logs via a ``https://api.cirrus-ci.com/v1/task/$BUILD/logs/$WHATEVER.log``.

For example, to add anchors around test details, then add links from the testing summary back to the details.  Though there are plenty of other uses.

# Anything Else

My understanding is the `Content-Type` is coming from the google storage bucket where Cirrus stores our build's logs.  If changing that (when the logs get uploaded) is painful another idea could be to proxy the content as ``text/html`` from an alternate end-point, for example: ``https://api.cirrus-ci.com/v1/html/task/$BUILD/logs/$WHATEVER.log``

**Comment by fkorotkov** [comment]
What kind of test runner are you using? It is able to produce machine readable output? In this case another idea might be to support your use case via [annotations](https://medium.com/cirruslabs/github-annotations-support-227d179cde31).

**Comment by cevich** [comment]
We're using GinkGO and BATS, from a Makefile, driven by our scripts.

**Comment by cevich** [comment]
Uggg wrong button.

**Comment by cevich** [comment]
annotations could work I think, but I'm not sure how good the jUnit XML is from Ginkgo.  We'd have to generate our own from the BATS output (TAP format).

**Comment by fkorotkov** [comment]
We can add support for the format produced by BATS in https://github.com/cirruslabs/cirrus-ci-annotations. 🤔 Could you please provide an example of the TAP output?

**Comment by cevich** [comment]
That would be cool!  It's a very simplistic [format with an actual standard and specification.](https://testanything.org/).  Not nearly as wide-spread as jUnit is, but there are at least a handful of users.  If it's not worth your time, it's not a big issue.  Somewhere in an old mountain of code I have a closed PR containing a TAP -> jUnit converter.  So I could resurrect that, but...

...taking a step back here:  The fundamental/immediate problem we're trying to solve is this:

How to share a reference to a particular place in a loooooong log with another developer, such that they don't need to manually search for things.  For example this could be as simple as line-numbers prefixed to each line of output, or as fancy as what github does for linking to selections of code lines in a file.

So this RFE is a means to an end, such that we could implement the line-linking thing ourselves, but there are other uses as well.  For example, perhaps a job running on master could output an HTML link in the output to something, like a container image it just pushed to a repository.

**Comment by fkorotkov** [comment]
Seems your use case will be covered by https://github.com/cirruslabs/cirrus-ci-web/issues/63. Will prioritize it. 👍
