### ISSUE TITLE
Website doesn't force https

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#323]
# Expected Behavior

SSL/HTTPS should be auto redirected to from http

# Real Behavior

https is not enforced

**Comment by fkorotkov** [comment]
GitHub page setting is set and http://cirrus-ci.org/ for me redirects to the HTTPS version. What do you see 🤷‍♂

**Comment by RDIL** [comment]
I meant the .COM - in my experience, forcing SSL increases customer confidence.

**Comment by fkorotkov** [comment]
http://cirrus-ci.com/ also redirects for me. Which browser are you using?

**Comment by RDIL** [comment]
Chrome

**Comment by fkorotkov** [comment]
Can you be more specific? OS and version information will be appreciated.

**Comment by RDIL** [comment]
ChromeOS Dev Channel Update 76.0.3807.0 (Platform version: 12236.0.0) but also confirmed on Windows 10 with Firefox.
