### ISSUE TITLE
FAILED_PRECONDITION: Unknown field null on 'container' YAML node!

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#325]
Can you please tell me what this error means?  It's not obvious.
```
FAILED_PRECONDITION: Unknown field null on 'container' YAML node!
```
https://cirrus-ci.com/build/6312161723285504

**Comment by RDIL** [comment]
Hello,
I believe this is an issue in your `.cirrus.yml`.  I will investigate further.

**Comment by RDIL** [comment]
Please see https://github.com/nix-rust/nix/pull/1070#pullrequestreview-247123081

**Comment by fkorotkov** [comment]
Answered by @RDIL
