### ISSUE TITLE
PR's with [skip ci] should automatically get passing status.

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#329]
# Description

PR's with `[skip ci]` should automatically get passing status.

# Context

The `[skip ci]` feature added by #64 is nice, but there's a problem with it.  If all of a GitHub PRs are skipped, then the PR's Cirrus status indicator will permanently be yellow.  That means that bots like bors and homu won't merge the PR, and if the branch is protected then even maintainers can't merge the PR.  In order for `[skip ci]` to be usable with protected branches, then Cirrus must automatically give passing status to such PRs.

**Comment by fkorotkov** [comment]
This should be working now.
