### ISSUE TITLE
Tasks Skipped

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#330]
# Expected Behavior

When merging a PR to master all tasks should run

# Real Behavior

Only the task designed to run in the PR runs. The other tasks are skipped.

# Related Info
This started today:
https://cirrus-ci.com/build/5707329362722816
https://cirrus-ci.com/build/5660756683522048
I tried re-running one of the skipped tasks and it started:
https://cirrus-ci.com/task/4831486746820608

The most recent change to .cirrus.yml
https://github.com/brianegan/flutter_architecture_samples/commit/68138cc026514474aac596007221b5597981ac7a#diff-0f7067c31caedf7df2739c9b07efa122
ran correctly:
https://cirrus-ci.com/build/5111026622660608

**Comment by fkorotkov** [comment]
Isn't it expected though? See https://github.com/brianegan/flutter_architecture_samples/blob/master/.cirrus.yml#L20

You change only contained spelling fixes so there is no need to run tasks.

**Comment by mmcc007** [comment]
Ah, I get it now. I didn't examine the skip condition carefully enough (kinda figured it just worked, since you added this line, nice feature btw 👍 ). May add a comment to it next time as a reminder to myself. 

Thnx!
