### ISSUE TITLE
Unable to set custom working directory

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#332]
Hi,
for some reason, even after setting `CIRRUS_WORKING_DIR` in `frontend_tests_task` to my custom directory, it is still using the default.

Am I forgetting something?

Config: https://github.com/annieapp/annie/blob/master/.cirrus.yml

Thanks all!

**Comment by fkorotkov** [comment]
You still need manually 'cd frontend'. This environment variable simply tells where to come the repo.

**Comment by RDIL** [comment]
It’s still not working.

**Comment by fkorotkov** [comment]
`$PWD` is not saved between instructions. You'll need to do it for each instruction.

**Comment by RDIL** [comment]
👌
