### ISSUE TITLE
New GitHub permissions

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#335]
I just noticed GitHub added new permissions (in beta), which include:
* **Maintain** - Basically admin but without collaborator invite permissions
* **Triage** (I think is what it is called) - Basically colaborator without write, *meaning they can pretty much only label issues and PRs*

I believe the backend may need to be updated to 'understand' the new permissions.

**Comment by fkorotkov** [comment]
These are supported now.
