### ISSUE TITLE
FreeBSD 11-2-release-amd64 sets $HOME to `/` not `/root`

### ISSUE THREAD

**Issue by fnichol** [cirruslabs/cirrus-ci-docs#337]
# Expected Behavior

When checking the home directory of the root user, with `getent passwd root`, the home directory reports as `/root`, as would be expected on FreeBSD:

```console
$ getent passwd root
root::0:0:Charlie &:/root:/bin/csh
```
# Real Behavior

What ended up happening was the `$HOME` environment variable seems to now be set to `/`. At some point in the last 2-3 weeks, `$HOME` was set to `/root`. In my case, I'm installing Rust and the default `$CARGO_HOME` tends to be `$HOME/.cargo`. I've cached a couple of Cargo plugins which are installed under `$CARGO_HOME` but when I ran a CI job today, I noticed that the `$HOME` is different.

Has something perhaps changed in the FreeBSD environment recently?

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: FreeBSD
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Nothing has changed on Cirrus side but I see that there was an update to FreeBSD images on `06/10/2019` https://console.cloud.google.com/marketplace/details/freebsd-cloud/freebsd-11. Let me check what was updated there...

**Comment by fkorotkov** [comment]
Don't see any changes to `freebsd-11-2-release-amd64` image either... 🤔

**Comment by fkorotkov** [comment]
My only guess is that FreeBSD images started booting differently on GCP side and startup script is no longer run with proper environment variables. 

Closing the issue since not sure what we can do on our side. Nothing has changed about how Cirrus starts FreeBSD tasks and we don't control the images and how they boot. 😪

**Comment by fnichol** [comment]
Ah, that is good info anyway, thank you! For the time being, I'll simply not rely on `$HOME` on FreeBSD as linked above.
