### ISSUE TITLE
Q: How to detect a task re-run?

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#342]
# Question

Within a task or a build, is it possible to determine how many times any task was re-run?

Non-real-time solutions acceptable: i.e. trolling through our cirrus-ci storage objects/logs.

# Background
For CI on a well-established open-source project, testing-flakes (vs outright failures) become more and more of an issue.  Where a "Flake" refers to one or more tasks with somewhat rare race-conditions, often dependent on external resources|networking.

I would like to develop a flake-o-meter for my team, whereby we can know at a glance across all branches and PRs, how many times folks are pressing the "re-run" button en-mass.  Especially valuable, would be a way to compare this vs the total number of tasks (`$CI_NODE_TOTAL`?).  Since nearly all our re-runs are due to flakes, this would permit calculating a percent-flakes value and then nagging appropriately.

**Comment by fkorotkov** [comment]
Hey @cevich, there is no easy way to get information if a task was a flake from the API or get the original task id if it's a re-run. We are planning to get similar flake-o-meter as part of #326 which will show a percentage of flaked builds (builds that ended up in a successful state even though some tasks failed).

**Comment by cevich** [comment]
API meaning Cirrus or Github?

Am I correct in understanding the assigned task-id changes on a re-run, but the build-id stays the same?

I'm wondering if I could use these two, for tracking re-runs in cloud-storage or a database.  i.e. increment a counter indexed by the `$CIRRUS_BUILD_ID` and `$CI_NODE_INDEX`.  That would allow me to setup a simple re-run-o-meter graph for my team.

#326 looks interesting as well, thanks! _subscribed_

**Comment by fkorotkov** [comment]
> API meaning Cirrus or Github?

Cirrus API

> Am I correct in understanding the assigned task-id changes on a re-run, but the build-id stays the same?

Correct

> I'm wondering if I could use these two, for tracking re-runs in cloud-storage or a database. i.e. increment a counter indexed by the $CIRRUS_BUILD_ID and $CI_NODE_INDEX. That would allow me to setup a simple re-run-o-meter graph for my team.

`CI_NODE_INDEX` of a re-run will be the same so test sharding if used will work the same way. Note that are sometimes automatic re-runs in case of some internal issues or preemption of VMs. Automatic re-runs are exposed via [automaticReRun field on a Task object](https://github.com/cirruslabs/cirrus-ci-web/blob/0f157cc44b3e81e784c9b4412232f63687f758b2/schema.graphql#L418).

#326 is targeted by the end of the next week so not sure if it worth your time building it on your own. 😅

**Comment by cevich** [comment]
Thanks, yes I'll see what y'all come up with first, it may be just what we need for now.  Otherwise,  rolling our own would bring some benefits specific to our projects.  Like adjusting timelines to track releases, sprints, or accounting for flake retries built into our testing framework.  So it sounds like there's a somewhat clear way forward to accomplish that.  But we'll see what you provide first, glad to hear it's already in the works.  Thanks :smile:
