### ISSUE TITLE
Trigger tasks based on label(s)

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-docs#343]
As we're scaling up our CI usage, we frequently see contributions that take several commits to get into a good state. It'd be really nice if we could conditionally run jobs based on labels on 
the issue.

The things I'm concerned about are:

- Contributors often need multiple commits to address review comments.  
- We want to use compute credits but also want to avoid spending compute time on experimentation
- We want to avoid the CI system getting thrashed by an unwitting contributor (or, worse, an intentionally malicious contributor).

For example, a workflow that seems good would be something like this:

1. Contributor opens PR. A subset of CI jobs run (code linting/analysis, a small-ish set of smoke tests , ideally based on the files that have changed in the patch).
2. Contributor makes changes to the patch in response to review or perhaps in response to the smoke tests being run.
3. Someone with permissions to add labels eventually adds label to the issue that asks for all tests to be run. This is done when the patch is deemed as being (closer to) ready for submission, and is already passing the smoke tests. This triggers all presubmit tests and allows them to run with compute credits.
4. Additional commits from that point on run all presubmit tests.

**Comment by fkorotkov** [comment]
Indeed, an amazing idea! 💪

**Comment by fkorotkov** [comment]
There is some complication around non-PR builds since they won't have labels at all. In order to make it generic I'm proposing to add a new `pause_until` field similar to [`skip`](https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution) as well as support for `hasLabel` function in conditions inside `.cirrus.yml`. For example, the following example:

```yaml
task:
  name: Integration Tests
  pause_until: hasLabel('initial-review') || $CIRRUS_PR == ''
  # ...
```

will **pause** `Integration Tests` task on PRs **until** someone assigns `initial-review` label to the PR. What do you think? Is it transparent enough?

**Comment by dnfield** [comment]
That seems like it would get us most of what we want. 

That said, maybe it could be made a little bit easier to work with by having a field like `required_pr_labels:` which would take a list of labels and pause only for PRs - that way, no one makes some strange mistake with the conditions that gets missed and is hard to test without trying it.

**Comment by fkorotkov** [comment]
Yeah, I was debating between this and `required_pr_labels`. My only concern was that eventually we'd like to support BitBucket and it [doesn't have labels yet](https://bitbucket.org/site/master/issues/11976/labels-for-pull-requests). But this will be still an issue for `hasLabel`. Let's then stick with just `required_pr_labels`. 🙌

**Comment by fkorotkov** [comment]
PTAL #351
