### ISSUE TITLE
Bazel OOM

### ISSUE THREAD

**Issue by mposa** [cirruslabs/cirrus-ci-docs#344]
# Expected Behavior

Successful build and test.

# Real Behavior

Bazel builds are OOMKilled. 

This is a new error, as of yesterday, where master and our branch builds are all running out of memory. Re-running old, previously successful, CI checks also results in this error.

# Related Info
https://cirrus-ci.com/github/DAIRLab/dairlib

**Comment by fkorotkov** [comment]
I think you are hitting this issue: https://github.com/bazelbuild/bazel/issues/3886

We've upgraded underlying hardware yesterday from using 14 CPUs VMs to VM with 32 CPUs. Let's see if https://github.com/DAIRLab/dairlib/pull/78 will help.

**Comment by mposa** [comment]
Perfect, thank you.
