### ISSUE TITLE
How to start a build via the API?

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-docs#347]
# Question

I noticed #90 was closed, which implies that using the GraphQL API to initiate a build is possible. However, I've been unable to find any documentation for it.

So my questions are just:

1. Is it actually possible?
2. If so, what would the GraphQL request look like?

**Comment by fkorotkov** [comment]
You can check documentation API about how to authorize and use the API: https://cirrus-ci.org/api/

Plus you can check the web client which uses a corresponding mutation to manually create builds in a dialog: https://github.com/cirruslabs/cirrus-ci-web/blob/master/src/components/CreateBuildDialog.js#L21-L29. Here is a comment with a screenshot of how it looks: https://github.com/cirruslabs/cirrus-ci-docs/issues/90#issuecomment-489638090

**Comment by RDIL** [comment]
I’ll add a section about this soon

**Comment by stumpylog** [comment]
Is there documentation on this now?
