### ISSUE TITLE
Cirrus skips multi-commit pushes if the last was [skip ci]

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#348]
# Expected Behavior

If several commits are pushed at once and any of them are *not* tagged with `[skip ci]`, then Cirrus should try to build them.  It should build either the latest revision, or the latest revision that isn't marked `[skip ci]`.

# Real Behavior

I pushed two commits, and the last was marked `[skip ci]`.  Cirrus didn't build either.

# Related Info

See the commit log here: https://github.com/asomers/mockall/commits/master .  Commits 604e6a3 and 53c784c were pushed at the same time.  The latter was marked `[skip ci]`, so Cirrus built neither.

**Comment by fkorotkov** [comment]
Unfortunately this is how all the GitHub integrations are working as far as I know. GitHub itself sends a [request for Check Suite](https://developer.github.com/v3/activity/events/types/#checksuiteevent) providing only a reference to the `head_commit` basically assuming workflow on only reacting to the head commit upon a push. 

In your case `head_commit` had `[skip ci]` and was skipped accordingly.
