### ISSUE TITLE
Cirrus CI not running on PR?

### ISSUE THREAD

**Issue by njsmith** [cirruslabs/cirrus-ci-docs#352]
We're testing out Cirrus CI in this PR: https://github.com/python-trio/trio/pull/1128

We "installed" the app on the organization, and if you look at the checks on the first few commits, Cirrus CI did run. But on the latest commit, it doesn't show up at all in the list of checks. I also tried closing/reopening the PR, since that tends to work to wake up all the other CI systems I've used, but it didn't make any difference.

Any idea why Cirrus CI would just... not run?

**Comment by fkorotkov** [comment]
Not sure what's going on there. I don't see any logs or webhook events for the SHA. Will try to dig logs around the time of the SHA to see if anything weird happend. In the meantime you can try to re-push. Sorry for the inconvenience!

**Comment by njsmith** [comment]
Huh, interesting.

Is closing/reopening supposed to trigger a Cirrus CI run, or is it expected that you actually have to push a new revision?

**Comment by fkorotkov** [comment]
I didn't find anything suspicious in the logs around the time of the push. GitHub requests [Status Check](https://help.github.com/en/articles/about-status-checks) from apps like Cirrus on the last commit for every push and on creation of new PRs. So you'll need to push.

I saw that you've pushed and status checks appeared. That's great! And once again sorry for the inconvenience!
