### ISSUE TITLE
Allow zip download of task artifacts during the build

### ISSUE THREAD

**Issue by morganwillcock** [cirruslabs/cirrus-ci-docs#354]
# Description

Requested feature:

Using the download URL `https://api.cirrus-ci.com/v1/artifact/github/<USER OR ORGANIZATION>/<REPOSITORY>/<TASK NAME>/<ARTIFACTS NAME>.zip` should work when the task `<TASK NAME>` has completed but the build is still running.

# Context

Given some tasks that generate lots of artifacts (via matrices) across different platforms, and a release that requires additional packaging of artifacts to generate a final 'release binary' (e.g. an installer that incorporates all artifacts), it seems that it isn't currently possible to use the task artifact zip downloads because the URLs return 404 until the entire build has finished.

As an example, these URLs return 404 within the upload_release task and externally, but become valid as soon as the build ends:

```
build_windows_task:
  windows_container:
  matrix:
    ...
  binaries_artifacts:
    ...

build_linux_task:
  container:
  matrix:
    ...
  binaries_artifacts:
    ...

upload_release_task:
  only_if: $CIRRUS_RELEASE != ''
  depends_on:
    - build_windows
    - build_linux
  download_script: |
    mkdir packaging
    win_url=https://api.cirrus-ci.com/v1/artifact/github/$CIRRUS_REPO_FULL_NAME/build_windows/binaries.zip?branch=$CIRRUS_BRANCH
    curl -fLsS "$win_url" | tar -f - -xvzC packaging
    linux_url=https://api.cirrus-ci.com/v1/artifact/github/$CIRRUS_REPO_FULL_NAME/build_linux/binaries.zip?branch=$CIRRUS_BRANCH
    curl -fLsS "$linux_url" | tar -f - -xvzC packaging
```

# Anything Else

~~I've not found a good way to work around this other than hard-coding the artifact names in the packaging tasks. Is there an API query which would return all of the individual artifact URLs per task?~~
Edit: I've managed to construct a GraphQL query which returns the artifact names for the build that matches the release tag, so I think this will work in the mean time.

Thanks!

**Comment by fkorotkov** [comment]
We'll add new new endpoints where you need to specify `BUILD_ID` like this:

```
https://api.cirrus-ci.com/v1/artifact/build/BUILD_ID/<TASK NAME>/<ARTIFACTS NAME>.zip
```

In that case you'll be able to use `CIRRUS_BUILD_ID` environment variable in your script.

**Comment by fkorotkov** [comment]
This endpoint is available now.
