### ISSUE TITLE
FreeBSD 11.3 instance failed to start.

### ISSUE THREAD

**Issue by igsilya** [cirruslabs/cirrus-ci-docs#359]
Fresh freebsd-11-3-release-amd64 images available on GCE, but cirrus is not able to use them.
https://cirrus-ci.com/task/6222248652832768

**Comment by fkorotkov** [comment]
I can see that Google VM is actually not finishing booting fully successful.

> Starting google_instance_setup.
> ...
> pkg_resources.DistributionNotFound: The 'boto' distribution was not found and is required by google-compute-engine

This leads to startup scripts not being executed and therefore Cirrus CI agent is not starting.

**Comment by fkorotkov** [comment]
@lrosenman, I remember you were writing about similar issue with pre-release FreeBSD 13 and seemed you had some insight about whom to ping about such issues. Could you please advise here?

BTW on the bright side I've tried `freebsd-13-0-current-amd64-v20190712` and FreeBSD 13 started working. 🎉

**Comment by igsilya** [comment]
This looks like something related: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238122

**Comment by fkorotkov** [comment]
Yes! I wonder when images are going to be updated. 🤔

**Comment by fkorotkov** [comment]
[Asked on the issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238122) to see if they have an ETA on when the patch will be available on GCP.

**Comment by igsilya** [comment]
> [Asked on the issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238122) to see if they have an ETA on when the patch will be available on GCP.

Thanks!

**Comment by asomers** [comment]
I've asked the relevant people to rebuild the image.  Hopefully it should be done soon.

**Comment by fkorotkov** [comment]
@asomers thank you!

**Comment by asomers** [comment]
Release engineering says that for various reasons they aren't going to do it.  Instead, Cirrus users should just switch to a stable/11 image.  I'm using freebsd-11-3-stable-amd64-v20190801 .

**Comment by igsilya** [comment]
Hmm. How often these stable/11 images are released? I'm asking because it's not very convenient to frequently update CI config files in order to have more recent stable build.

Another question is how can I found which stable images are available if I'm not a GCE user? I'm only using the public CI. 'release' images has predictable naming unlike 'stable' ones.
Maybe there is some image name alias that points to the latest stable image? Something like freebsd-11-3-stable-amd64-latest?

**Comment by asomers** [comment]
They're released weekly, but in a CI application there's probably no compelling reason to update that often.  And there's no alias that I can see.  Does GCE even have a concept of an image alias?

**Comment by igsilya** [comment]
From what I found in docs, GCE has a concept of image-family. The image family always points to the latest image in a family. For example, all the freebsd-11-3-stable* images are in freebsd-11-3-snap family.
However, cirrus doesn't support running from the family.  Special option '--image-family' should be used for 'gcloud create' instead of simple '--image':
https://cloud.google.com/compute/docs/images#image_families
https://cloud.google.com/sdk/gcloud/reference/compute/instances/create#--image-family

@fkorotkov , is it possible to add ability to specify image-family instead of bare image in cirrus config?

**Comment by fkorotkov** [comment]
It's possible with [`gce_instance`](https://cirrus-ci.org/guide/supported-computing-services/#custom-vm-images). For `freebsd_instance` the family is defaulted to `freebsd-org-cloud-dev`.

This task worked for me:

```yaml
task:
  freebsd_instance:
    matrix:
      image: freebsd-11-3-stable-amd64-v20190808
  echo_script: echo $PATH 
```

**Comment by fkorotkov** [comment]
Updated the docs: 1287ca6e6f289ee846dea237376e1da2496d8eee

**Comment by igsilya** [comment]
@fkorotkov, 'freebsd-org-cloud-dev' is a project, not the image family.

**Comment by fkorotkov** [comment]
Right. Haven't got my morning coffee yet. 😅 Providing a family as an option makes sense. Worth creating a separate feature request 😉

**Comment by emaste** [comment]
Bug report for the image problem is [PR242303](https://bugs.freebsd.org/242303)
