### ISSUE TITLE
A macOS image tagged to the latest stable version of Xcode

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-docs#361]
# Description

A macOS image that just runs the latest stable version of Xcode rather than requiring changes to get the latest.

# Context

https://github.com/flutter/flutter/pull/36205#discussion_r305564706

**Comment by fkorotkov** [comment]
Forgot to close the issue. There is now `catalina-xcode` and `catalina-flutter` images pointing to the latest images.
