### ISSUE TITLE
timestamps in UI

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#363]
Currently the UI only displays how long a task / step / pipeline has taken but it displays nowhere WHEN (i.e. date/time/timestamp) a task / step / pipeline was started or completed.
We're considering to use cirrus ci for some lightweight continuous deployment pipeline where it is important to know when some deployment job has happened.
Please add a feature to do so :)

**Comment by fkorotkov** [comment]
Added the following tip:

<img width="299" alt="Screen Shot 2019-07-20 at 10 17 10 AM" src="https://user-images.githubusercontent.com/989066/61579793-c9181500-aad7-11e9-8491-18bada00ce73.png">
