### ISSUE TITLE
When depends_on is set to non existing task it's depends_on is fulfilled immediately instead of showing error

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#365]
Consider this example:
```
foo_task:
  script: echo foo

bar_task:
  depends_on: fooo
  script: echo bar
```

As you can see task `bar` depends_on `fooo`, but `fooo` does not exist, only `foo` does.
Because of this cirrus ci executes cirrus executes task B immediately.
I think instead cirrus should show a error during config parsing in such cases.

Currently whenever I work / refactor cirrus yamls it happens that mistype tasks in `depends_on` clause, especially when task is being renamed. Cirrus then simply executes this task immediately which is somewhat surprising and harder to debug compared to cirrus just telling the user that there is an invalid dependency.

**Comment by fkorotkov** [comment]
This should be validating properly now. 👍

**Comment by geekflyer** [comment]
ok cool thanks!
