### ISSUE TITLE
(cache) Can't upload _build directory in an elixir project

### ISSUE THREAD

**Issue by syfgkjasdkn** [cirruslabs/cirrus-ci-docs#366]
👋

# Expected Behavior

`_build` folder would get cached.

# Real Behavior

From the command output:

> Failed to calculate hash of /tmp/cirrus-ci-build/_build! read /tmp/cirrus-ci-build/_build/test/lib/cirrus_demo/priv: is a directorySkipping uploading of /tmp/cirrus-ci-build/_build!

# Related Info

Command: https://cirrus-ci.com/task/5685834097885184?command=Upload%20%27build%27%20cache#L0 (I guess you can access it?)
Repo: https://github.com/syfgkjasdkn/cirrus-ci-demo/pull/1

**Comment by fkorotkov** [comment]
I've tweaked handling of symlinks. Could you please try to re-run the task?

**Comment by syfgkjasdkn** [comment]
@fkorotkov thank you! Will try it today.

**Comment by fkorotkov** [comment]
@syfgkjasdkn have you had a chance to try it?

**Comment by fkorotkov** [comment]
Closing the issue. Please re-open if the issue persists. 🙌
