### ISSUE TITLE
How to use bash as shell on windows containers when MSYS2 is installed?

### ISSUE THREAD

**Issue by abravalheri** [cirruslabs/cirrus-ci-docs#368]
Related to cirruslabs/docker-images-windows#5

(First of all, I would like to thank you guys for the great product. I have started using Cirrus recently, and it feels amazing!)

Since Msys2 is installed in `cirrusci/windowsservercore:cmake`, in theory it is possible to use `bash` as the shell to execute the commands in `.cirrus.yml`. However, it seems that the scripts will be compiled to BATCH, not bash.

Is there a way of changing it? How would it be possible to use `bash` from Msys2 as the shell for windows containers?

**Comment by fkorotkov** [comment]
Hey @abravalheri, thank you the appreciation!

I think the easiest way will be just to put all you commands in one or several bash scripts and call them from BATCH. 

Setting [`CIRRUS_SHELL`](https://cirrus-ci.org/guide/writing-tasks/#environment-variables) won't help since the script still be generate for BATCH. 😪

**Comment by abravalheri** [comment]
Hi @fkorotkov, thank you very much for the quick response. Sounds a reasonable approach.

Do you have any example of that? I have being trying to do that this morning and failing miserably 😩 
Despite of using the cmake image that have Msys2 installed, it seems that neither `bash` or `sh` are in the path (which in my case seems to be `C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;C:\tools\msys64`)

**Comment by fkorotkov** [comment]
Seems you can use: `C:\tools\msys64\usr\bin\bash -lc 'printenv'`. My task [passed](https://cirrus-ci.com/task/4777676886245376?command=printenv#L1).

**Comment by abravalheri** [comment]
Thank you very much @fkorotkov
