### ISSUE TITLE
consider setting github check status for manual approval actions to "Neutral"

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#369]
Currently cirrus ci sets the github checks status for manual approval actions to "Action Required" which from github as interpreted as a failure.

I.e. see
![image](https://user-images.githubusercontent.com/1221897/61598518-e9c59500-abd3-11e9-8ec8-982b5ef564c9.png)

Judging from githubs docs there seems to be also a "Neutral" state. I.e.:
https://developer.github.com/v3/checks/runs/
as seen here:
![image](https://user-images.githubusercontent.com/1221897/61598533-22fe0500-abd4-11e9-9e60-8237572b7227.png)

Could you please set the status to "Neutral" for pending manual approval actions, since this is more appropriate?

Thanks

**Comment by fkorotkov** [comment]
Cirrus actually sets status to `completed` and conclusion to `action_required`. I'll raise the question with GitHub folks about more netrual color.

**Comment by geekflyer** [comment]
ok, what I meant is setting conclusion to Neutral.

**Comment by fkorotkov** [comment]
Oh! It seems you are able to attach actions to neutral checks as well. Yeah, neutral will be nicer in that case. This change just got deployed.

<img width="513" alt="Screen Shot 2019-07-21 at 10 01 23 PM" src="https://user-images.githubusercontent.com/989066/61601399-2492f180-ac03-11e9-876f-daff351de8ae.png">

**Comment by geekflyer** [comment]
awesome! This seems to work exactly as intended:

![image](https://user-images.githubusercontent.com/1221897/61606285-65d4d280-abfe-11e9-97f7-44c6858e3643.png)

Thanks for the quick response and fix again!
