### ISSUE TITLE
Invalid hostname of example in Encrypted Variables 

### ISSUE THREAD

**Issue by granoeste** [cirruslabs/cirrus-ci-docs#37]
> In order to encrypt a variable go to repository's settings page via clicking settings icon  on a repository's main page (for example https://cirrus-ci.org/github/my-organization/my-repository) and follow instructions.

https://cirrus-ci.org -> https://cirrus-ci.com

**Comment by fkorotkov** [comment]
Thank you!

**Comment by tunnckoCore** [comment]
And still, there is no Settings icon? Can you give the direct link to the settings page? Is it `/settings` or `/edit`..?
