### ISSUE TITLE
task status badges don't work when the name contains a dash

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#370]
consider this .cirrus.yml:

```yaml
do-stuff_task:
  my_script: echo foo
```

As per the docs the following badge in markdown should work:

`[![Build Status](https://api.cirrus-ci.com/github/myorg/myrepo.svg?task=do-stuff)](https://cirrus-ci.com/github/myorg/myrepo?task=do-stuff)`

But what I'm actually seeing markdown is this:

![image](https://user-images.githubusercontent.com/1221897/61607156-40e25e80-ac02-11e9-8fba-42e362850fd0.png)

Via try and error I found that it seemingly is because of the dash `-` in the task name.

**Comment by fkorotkov** [comment]
It should be working now. 🙌
