### ISSUE TITLE
CI was not triggered

### ISSUE THREAD

**Issue by dewyatt** [cirruslabs/cirrus-ci-docs#371]
# Expected Behavior

Unless I'm missing something, Cirrus CI should have run.
https://github.com/dewyatt/rnp/commits/master
You can see commit d49ef20 triggered Travis CI, but not Cirrus CI for some reason.

# Real Behavior

Cirrus CI did not run any tasks.

**Comment by RDIL** [comment]
Config looks fine.  Have you installed the app through GitHub Marketplace and ensured it has access to the repo?

**Comment by dewyatt** [comment]
> Config looks fine. Have you installed the app through GitHub Marketplace and ensured it has access to the repo?

Yes, and if you scroll down to commit a3d5a82 you can see that Cirrus was triggered there with no problems.

**Comment by dewyatt** [comment]
Looking at the app in the marketplace though, I do see two permissions update requests for Cirrus CI:
* Read & write access to Content references
*  Write access to attach content to the following domain:
    cirrus-ci.com

Do you think one of these is the cause? It would be pretty confusing as an end-user to have it silently stop working because of newly requested permissions.

**Comment by RDIL** [comment]
Shouldn’t be, those are only for new features.  I would approve them and try again though.

**Comment by dewyatt** [comment]
> Shouldn’t be, those are only for new features. I would approve them and try again though.

Ok I'll give that a try. I'm also getting a lot of 500 errors on GitHub now, so maybe the fault lies there.

**Comment by fkorotkov** [comment]
@dewyatt it's not related to the settings.

Something weird is going on though 👇

<img width="966" alt="Screen Shot 2019-07-22 at 11 38 15 AM" src="https://user-images.githubusercontent.com/989066/61645752-5f357200-ac75-11e9-9f44-281a69f361ae.png">

**Comment by fkorotkov** [comment]
@dewyatt it's not related to the settings.

Something weird is going on though 👇

<img width="966" alt="Screen Shot 2019-07-22 at 11 38 15 AM" src="https://user-images.githubusercontent.com/989066/61645752-5f357200-ac75-11e9-9f44-281a69f361ae.png">

**Comment by dewyatt** [comment]
> Shouldn’t be, those are only for new features. I would approve them and try again though.

Ok I'll give that a try. I'm also getting a lot of 500 errors on GitHub now, so maybe the fault lies there.

**Comment by dewyatt** [comment]
Ok github's status page is now finally showing issues. I'll try again when things stabilize and will close if all is well.

**Comment by RDIL** [comment]
No response from GitHub on Twitter yet

**Comment by RDIL** [comment]
No response from GitHub on Twitter yet

**Comment by RDIL** [comment]
Ok yeah GitHub is most likely about to experience downtime

**Comment by dewyatt** [comment]
Ok I think it's likely this was github. I pushed a new commit and the Cirrus check was correctly triggered.
Thanks guys!
