### ISSUE TITLE
wait for additional containers

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#377]
We're running a lot of docker builds on GKE following https://cirrus-ci.org/guide/docker-builds-on-kubernetes/.

Now occasionally builds wail with an error message like below:

```
docker pull gcr.io/my-project/$APP:$CIRRUS_LAST_GREEN_CHANGE || true
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
docker build --cache-from=gcr.io/my-project/$APP:$CIRRUS_LAST_GREEN_CHANGE --build-arg=GEMFURY_TOKEN=$GEMFURY_TOKEN -t gcr.io/my-project/$APP:$CIRRUS_CHANGE_IN_REPO -f $DOCKERFILE .
time="2019-07-23T23:03:00Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial tcp 127.0.0.1:2375: connect: connection refused"
time="2019-07-23T23:03:00Z" level=error msg="Can't add file /tmp/cirrus-ci-build/resolve/argo/train_one_org.yaml to tar: io: read/write on closed pipe"
time="2019-07-23T23:03:00Z" level=error msg="Can't close tar writer: io: read/write on closed pipe"
context canceled
```

My guess is that happens when the main container starts before the `additional_container` . Could you perhaps add some sort of wait mechanism to avoid this (i.e. waiting for the additional containers to be up).

Just fyi kubernetes seems to add a native "sidecar" container feature which would resolve this, however this is only coming with 1.16 and only in alpha. https://github.com/kubernetes/enhancements/issues/753

So it would be good if cirrus in the meantime can implement some workaround on top and switch to the k8s native solution underneath once k8s has it available. The user API doesn't have to change.

**Comment by fkorotkov** [comment]
Yeah, I'm watching for that enhancement. I wonder if just checking that Cirrus Agent can open a TCP connection to the port will be good enough since something can be already running but not ready for traffic. It definitely will make things better though 🤔

**Comment by geekflyer** [comment]
yeah i think that is already better than nothing.
Another idea, thats is arguable though more complex would be if the agent watches the `status` field of the sidecar containers via the kubernetes api.
You can inject pod name etc. via the k8s downlevel api etc.

**Comment by fkorotkov** [comment]
The agent now waits for ports to be dialable before starting execution of the instructions.

**Comment by fkorotkov** [comment]
BTW @geekflyer, have you noticed any improvement after the agent started to wait for ports to be available?

**Comment by geekflyer** [comment]
well the issue only occurred sporadically, so I can't say for sure, but as far as i know the issue didn't occur in the last 5 days :)

**Comment by fkorotkov** [comment]
Great! 🤞
