### ISSUE TITLE
Bazel build with cache failing

### ISSUE THREAD

**Issue by mposa** [cirruslabs/cirrus-ci-docs#378]
We have a PR that's failing to build, and it seems directly related to an issue with the bazel cache. If I remove the command to use a cache, it builds successfully. With the cache, we see errors like this: https://cirrus-ci.com/task/4565301557985280?command=test#L25

Is there any way to clear the cache?

**Comment by geekflyer** [comment]
I have the same question.
@mposa I had this issue in past and I resolved it by deleting the GCS bucket that it is associated with the repository in your GCP project. This obviously only works if you run cirrus builds in your own cloud and not the community one.
So the question holds: What's the official way to clear the cache?

**Comment by RDIL** [comment]
As is, there is no direct button or anything to do that, you will need to upload an empty cache and then upload a brand new one if you want to get rid of everything in it.

**Comment by mposa** [comment]
Any idea how that's done on the community cloud?

**Comment by fkorotkov** [comment]
Right now the easiest way to invalidate a cache is to append something to `fingerprint_script` in order to change the key. But it won't work for Bazel case.

I've created #379, in the meantime @mposa do you want me to clear the whole cache for your repository?

**Comment by mposa** [comment]
Please do. Thank you.

**Comment by fkorotkov** [comment]
@mposa deleted almost 30,000 cached files. 😅 Please let me know if it fixed the issue.

**Comment by mposa** [comment]
Thanks. It fixed the issue very briefly, but we're still having all sorts of caching issues with PRs.

https://cirrus-ci.com/github/DAIRLab/dairlib/cp-controller
