### ISSUE TITLE
UI for cache invalidation

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#379]
# Description

It will be nice to have a UI similar to artifacts view for managing caches for a repository.

# Context

Right now the only way to clear caches on community cluster is to append something to `fingerprint_script` so it changes.

**Comment by fkorotkov** [comment]
On the second though it doesn't make sense to have UI similar to Artifacts view. There should be two options for caches: either invalidate all caches for a repository or check information for a particular cache key and be able to invalidate this particular cache entry (there might be 1000s of cache files with not pretty names for humans).

**Comment by AlexWayfer** [comment]
> Right now the only way to clear caches on community cluster is to append something to `fingerprint_script` so it changes.

Excuse me, but if I have something like `echo hack-1` in `fingerprint_script`, what is behavior with `reupload_on_changes`? I mean, is it still `true` by default? Would the cache be re-uploaded with the same `fingerprint_script` output, but with changes inside `folder`?

**Comment by RDIL** [comment]
> > Right now the only way to clear caches on community cluster is to append something to `fingerprint_script` so it changes.
> 
> Excuse me, but if I have something like `echo hack-1` in `fingerprint_script`, what is behavior with `reupload_on_changes`? I mean, is it still `true` by default? Would the cache be re-uploaded with the same `fingerprint_script` output, but with changes inside `folder`?

I believe that reupload on changes only effects file changes.

**Comment by AlexWayfer** [comment]
@fkorotkov, sorry for bothering you, but it's an important detail about described work-around.

**Comment by AlexWayfer** [comment]
I faced with it again: https://cirrus-ci.com/task/5884900168433664

😔
