### ISSUE TITLE
Some files get pulled from wrong commit

### ISSUE THREAD

**Issue by sbaranov** [cirruslabs/cirrus-ci-docs#38]
https://cirrus-ci.com/task/6596254498816000

This log shows failure related to 'compilationTraceFilePath' code that was NOT in associated commit:
https://github.com/flutter/flutter/commit/393f9276ca079e15de5f97cf902d4ef8181e50c0

The 'compilationTraceFilePath' code was introduced in a later commit:
https://github.com/flutter/flutter/commit/2c0329a103860cb2c14eead0d4e1aafc8e5f9c1b

Moreover, it seems that only one file (gradle.dart) from the later commit got pulled into the earlier run, otherwise this log would be showing more of similar errors.

P.S. I guess I could imagine a problem with the specific build task itself that it always pulls certain file(s) from HEAD regardless of what Cirrus tell it to? I don't know enough about Cirrus yet to tell if something like this would be possible.

**Comment by fkorotkov** [comment]
Weird. Logs for `clone` command clearly indicates that the right SHA was cloned. It cloned a newer SHA but then hard reseted to the right one. Cirrus CI is using [`go-git`](https://github.com/src-d/go-git) for cloning purpose. `go-git` is pretty sophisticated and widely used. I will try to reproduce the issue.

**Comment by fkorotkov** [comment]
@sbaranov I was able to reproduce the failure on my fork but I also added `git status` in [`git_fetch_script`](https://github.com/flutter/flutter/blob/master/.cirrus.yml#L11-L13) and it showed:

```
git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working tree clean
```

So seems Cirrus Agent cloned and reseted the repository correctly. Now I wonder if Flutter's setup scripts accidentally do `git pull` but I don't know these scripts good enough. Maybe @gspencergoog can help?

Just a little bit more details for @gspencergoog: there were two merges to master within 3 minutes. So when Windows Containers from the first commit finally started the second commit was already on master, so Cirrus CI Agent cloned the latest master and hard reseted to the first SHA. But according to the logs from @sbaranov some of the files remained from the later commit.

**Comment by fkorotkov** [comment]
My fix for the edge case got merged and Cirrus CI agent got also updated. There was a bug in respecting `.gitignore`. The issue should be fixed now.

Thanks for reporting!

**Comment by gspencergoog** [comment]
Sorry, I didn't see this sooner: I'm pretty sure we don't do any "pull".  The only thing we do is to call 'git fetch' to set the FETCH_HEAD, but there are no resets, merges, rebases, or pulls anywhere in our setup code (that I can find, or know of).

Sounds like you found something that may have caused the problem, though.
