### ISSUE TITLE
Dependabot PRs sometimes cancel both commit run and PR run

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#382]
# Expected Behavior

What should happen is the PR run should not be cancelled because it will always happen after the commit run

# Real Behavior

Sometimes both are cancelled

# Related Info

- [ ] Website issue
  - Link to page:
- [X] Task issue
  - OS: dockerlinux
  - Task name: n/a
  - Script/cache name (if applies): n/a

**Comment by fkorotkov** [comment]
Do you have links to builds that experienced it? Is there a way to reproduce it?

**Comment by RDIL** [comment]
Honestly it happens every now and then on dependency bumping PRs.  Looking through the history of RDIL/Gatsby-app , you should be able to find some instances of it.

**Comment by fkorotkov** [comment]
Fix should be auto-deployed in ~45 minutes
