### ISSUE TITLE
Error while loading tasks: FAILED_PRECONDITION: No tasks found to start!!

### ISSUE THREAD

**Issue by dewyatt** [cirruslabs/cirrus-ci-docs#383]
# Expected Behavior

We should have a `build` check show up on PRs.

# Real Behavior

We have our `build` check but also an extraneous `Cirrus CI` check that shows up on PRs and always fails with the message in the title.

# Related Info

See the checks on this PR for example:
https://github.com/riboseinc/rnp/pull/891

**Comment by RDIL** [comment]
Not really sure whats going on here...
![uh](https://user-images.githubusercontent.com/34555510/61811508-9b043f00-ae0f-11e9-8c00-2c9f7c0b6a80.PNG)
😕

**Comment by fkorotkov** [comment]
It's because you have 

```yaml
only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH =~ 'release/.*' || $CIRRUS_PR != ''
```

in your `.cirrus.yml`. So you pushed the banch which caused the error get attached to the SHA and then you opened a PR which led to the green build.

Just deployed a change that fixes this corner case. Sorry for the inconvenience.

**Comment by dewyatt** [comment]
Thanks @fkorotkov! That makes sense!
