### ISSUE TITLE
Github checks status is not updated

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#385]
Occasionally we face the issue that cirrus CI fails to properly report the task result to github and a task remains in status "Queued" on github, while it actually successfully completed in cirrus-ci.

This task is one such example: 

#### github:
![image](https://user-images.githubusercontent.com/1221897/61981844-b0b06a80-afaf-11e9-8b73-424d07d92f08.png)

#### cirrus-ci: 

![image](https://user-images.githubusercontent.com/1221897/61981867-cb82df00-afaf-11e9-85f6-eb1634bc6ed6.png)
 
Here's a link to the task in cirrus: https://cirrus-ci.com/task/5523728186736640 

This is just one example - I've seen this other times as well.

**Comment by RDIL** [comment]
Can confirm.

**Comment by fkorotkov** [comment]
@geekflyer what is the check run id that you see for this pending check? I can see from the logs that for that task this check run was updated: https://github.com/solvvy/solvvy-apis/runs/177506228 (Cannot see it since it's a private repository).

@RDIL maybe you have an example on a public repository then?

**Comment by geekflyer** [comment]
the check run id is `177506228`.

**Comment by geekflyer** [comment]
oops, it's actually `177506243` after it's updated. However even the updated run id shows the status for this task as pending.

**Comment by geekflyer** [comment]
Fyi the updated run id is probably just because I "triggered" a few minutes ago a manual approval task belonging to that run. This is probably unrelated to the failure to report the status of that task.

**Comment by RDIL** [comment]
Can't think of any off the top of my head, sorry!

**Comment by fkorotkov** [comment]
I found a race condition which seems to caused the issue. Fixed it. Please reopen if you'll see it again.
