### ISSUE TITLE
docker pipe on GKE

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#387]
After a bit of try and error I found that apparently docker pipe cannot be executed on your own GKE cluster. So where / how is docker pipe actually executed?
The docs are not very clear on the whole execution environment / limitations of docker pipe imho: https://cirrus-ci.org/guide/docker-pipe/

Would it be possible to add support for docker pipe on GKE?

**Comment by fkorotkov** [comment]
You are right that it's not possible to have pipes on your own GKE yet. Will be pretty easy to add since the implementation of pipes doesn't require any additional modifications to your cluster (initially there was an idea to implement pipes via tekton project).
