### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by honorarac** [cirruslabs/cirrus-ci-docs#389]
# Expected Behavior

What should have happened is ...

# Real Behavior

What ended up happening was ...

# Related Info

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by RDIL** [comment]
Dude please stop
