### ISSUE TITLE
Failed to decrypt some organization level environment variables

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#392]
We have an organization level variable that for some reason cannot be decrypted in one of our repositories and the build fails with `Failed to decrypt some environment variables`. This is a link to a task affected by this bug: https://cirrus-ci.com/task/5136522221715456

The very same organization level environment variable works just fine in other repositories in the same org.

I'm not sure how much of the ci config you can see since it's a private repo, but it's basically the variable `GOOGLE_CREDENTIALS` in line 11 of cirrus yml.

**Comment by fkorotkov** [comment]
I don't see the config so if you don't mind you can send it over to support@cirruslabs.org

Fron the logs I can see that the error is:

> NOT_FOUND: Secured variable Make PreloaderRedirectLauncher use same window

Seems it's using `$CIRRUS_CHANGE_MESSAGE` as a name of the variables inside `ENCRYPTED`. 🤔

**Comment by geekflyer** [comment]
Just sent you an email with the config.
Some more context:

The failing task is `BuildAndPushChromeImage_task`.
The failing task is from a PR / branch. The authoring and approving users both have admin permissions to the repo.
The build seems to work on master (or at least the last build on master a few days ago with the exact same config succeeded).

**Comment by geekflyer** [comment]
@aaronroyer

**Comment by fkorotkov** [comment]
Just deployed a fix. Parser was hitting a corner case and got confused. Thanks for providing `.cirrus.yml`. A re-run will work now. Sorry for the inconvenience!
