### ISSUE TITLE
duplicate repository

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#394]
Just got another case of a repository showing up twice (similar to the case I sent you 11 days ago by mail @fkorotkov ).

![image](https://user-images.githubusercontent.com/1221897/62161946-13657700-b2cc-11e9-9cf7-7e7ff00b7cfc.png)

Is there still this case condition of repo creation possible?
I guess the repo creation needs to be an atomic op ;-)

**Comment by fkorotkov** [comment]
Interesting. This is a for a repository that Cirrus just got enabled for? There is a lock around the repository creation though. 😅

**Comment by geekflyer** [comment]
yeah i just enabled that repo for cirrus

**Comment by RDIL** [comment]
Maybe add a check, something like
```python
if new_repo_name in repos:
    return
```

**Comment by fkorotkov** [comment]
@RDIL that's not that simple. 😅

**Comment by fkorotkov** [comment]
I think the issue was that even though Datastore writes are strongly consistent, lookups by non-id column is eventually consistent. I've merged the repos and put additional consistency checks around it.

**Comment by geekflyer** [comment]
time to upgrade ;-) https://cloud.google.com/datastore/docs/upgrade-to-firestore

**Comment by fkorotkov** [comment]
Seems like it! Will do. 🤔 

I was kind of always ignoring updates about Firebase products since it's interesting but very client oriented. It's a pity that there is only one way of *Datastore* to *Firestore in Datastore mode* but there is no way to migrate further from *Datastore mode* to *Native mode*. 😪
