### ISSUE TITLE
HTTP Content-Encoding issues on file downloads

### ISSUE THREAD

**Issue by morganwillcock** [cirruslabs/cirrus-ci-docs#399]
# Expected Behavior
Web server should indicate that artifact downloads are gzipped in transit.

# Real Behavior
Web server is mistakenly gzipping gzip content and not indicating that it did so.

Depending on the tool used, downloading a gzipped artifact seems to result in an additional layer of gzip compression being left in-place. You can see this by downloading with Firefox, where the outer compression is left in-place, vs downloading with Chrome where you won't notice the difference (the files will open as normal).

Example artifact:
https://api.cirrus-ci.com/v1/artifact/task/5131941622317056/binaries/ags_linux_3.5.0.14.tar.gz

If you download this file using Firefox the file which is saved has the additional gzip compression still in-place:
<pre>
$ sha256sum ~/Downloads/ags_linux*
7e08d2393e794b10392b2e1f3d1aa000e0359bbbb353031e498c986972acb1b1  /home/mwillcock/Downloads/ags_linux_3.5.0.14_chrome.tar.gz
7a4b2adfa3f1d9d4be554a3f5acfb4b2921ad7560c197b32bd46ff5990d02718  /home/mwillcock/Downloads/ags_linux_3.5.0.14_firefox.tar.gz

$ file ~/Downloads/ags_linux*
/home/mwillcock/Downloads/ags_linux_3.5.0.14_chrome.tar.gz:  gzip compressed data, last modified: Sat Aug  3 19:57:27 2019, from Unix
/home/mwillcock/Downloads/ags_linux_3.5.0.14_firefox.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)

$ gunzip ~/Downloads/ags_linux_3.5.0.14_firefox.tar.gz
$ sha256sum ~/Downloads/ags_linux*
7e08d2393e794b10392b2e1f3d1aa000e0359bbbb353031e498c986972acb1b1  /home/mwillcock/Downloads/ags_linux_3.5.0.14_chrome.tar.gz
7e08d2393e794b10392b2e1f3d1aa000e0359bbbb353031e498c986972acb1b1  /home/mwillcock/Downloads/ags_linux_3.5.0.14_firefox.tar
</pre>

I would imagine this is a config issue on your webserver (muddling the filetype with the transfer compression), as the file is having extra gzip compression applied whilst not indicating in the response that this compression is present.

# Related Info
Example download:
<pre>
wget --debug https://api.cirrus-ci.com/v1/artifact/task/5131941622317056/binaries/ags_linux_3.5.0.14.tar.gz
DEBUG output created by Wget 1.18 on linux-gnu.

Reading HSTS entries from /home/mwillcock/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'ags_linux_3.5.0.14.tar.gz' (UTF-8) -> 'ags_linux_3.5.0.14.tar.gz' (UTF-8)
--2019-08-03 22:20:47--  https://api.cirrus-ci.com/v1/artifact/task/5131941622317056/binaries/ags_linux_3.5.0.14.tar.gz
Certificates loaded: 151
Resolving api.cirrus-ci.com (api.cirrus-ci.com)... 35.190.41.13
Caching api.cirrus-ci.com => 35.190.41.13
Connecting to api.cirrus-ci.com (api.cirrus-ci.com)|35.190.41.13|:443... connected.
Created socket 3.
Releasing 0x0000559d1897bce0 (new refcount 1).

---request begin---
GET /v1/artifact/task/5131941622317056/binaries/ags_linux_3.5.0.14.tar.gz HTTP/1.1
User-Agent: Wget/1.18 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: api.cirrus-ci.com
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Date: Sat, 03 Aug 2019 21:20:48 GMT
Content-Type: application/octet-stream
Content-Disposition: attachment; filename="ags_linux_3.5.0.14.tar.gz"
Vary: Accept-Encoding
Transfer-Encoding: chunked
Via: 1.1 google
Alt-Svc: clear

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: unspecified [application/octet-stream]
Saving to: ‘ags_linux_3.5.0.14.tar.gz’
</pre>

Note that Content-Encoding is not present in the response.

**Comment by fkorotkov** [comment]
Seems we need to set `Content-Type` to `application/gzip` 🤔

**Comment by morganwillcock** [comment]
I think it depends on what each application requests (Accept-Encoding), but perhaps these things are too inconsistent to have on by default. A default Apache installation disables AddEncoding:

```
#
# AddEncoding allows you to have certain browsers uncompress
# information on the fly. Note: Not all browsers support this.
#
#AddEncoding x-compress .Z
#AddEncoding x-gzip .gz .tgz
#
# If the AddEncoding directives above are commented-out, then you
# probably should define those extensions to indicate media types:
#
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz
```

**Comment by fkorotkov** [comment]
Removed `Content-Type` completely until you specify `type` field on the `artifact`. Browsers are smart enough to figure how to deal with files by their names. 🤷‍♂

**Comment by morganwillcock** [comment]
This doesn't seem to fix it for me, and now the content type is incorrectly set:
`content-type: text/html`

Which webserver is this using?

**Comment by ericoporto** [comment]
Hey @fkorotkov , is the content type specified here -> https://github.com/cirruslabs/cirrus-ci-web ?

**Comment by fkorotkov** [comment]
@ericoporto this is controlled on the Cirrus server side which is not yet open sourced. Is it still not working? I think I missed @morganwillcock's response after I closed the issue. Sorry about that!

**Comment by morganwillcock** [comment]
Example from Firefox 83.0, downloading this:
https://api.cirrus-ci.com/v1/artifact/task/4821647758721024/binaries/Solutions/.build/Release/acwin.exe

Response header:
```
HTTP/2 200 OK
date: Sun, 13 Dec 2020 16:27:25 GMT
content-disposition: attachment; filename="acwin.exe"
content-type: text/html
vary: Accept-Encoding
content-encoding: gzip
via: 1.1 google
alt-svc: clear
X-Firefox-Spdy: h2
```

^ content-type says it is a webpage

**Comment by fkorotkov** [comment]
Sorry about that! Should be working now.
