### ISSUE TITLE
Any MacOS X support? 

### ISSUE THREAD

**Issue by aslushnikov** [cirruslabs/cirrus-ci-docs#4]
MacOS X, specifically with retina displays, would be really cool to have

**Comment by gedw99** [comment]
me too :)

**Comment by aslushnikov** [comment]
@fkorotkov any ETA for this?

**Comment by fkorotkov** [comment]
@aslushnikov ambitious estimate is the end of April. It depends on how testing of different Mac cloud providers will go.

**Comment by gedw99** [comment]
This would be great for testing Flutter Desktop.

**Comment by fkorotkov** [comment]
@gedw99 @aslushnikov it took a little bit longer than anticipated, but now [Cirrus CI support macOS builds powered by very interesting technology](https://cirrus-ci.org/guide/macOS/).
