### ISSUE TITLE
Support European regions of Google Cloud Kubernetes clusters

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#40]
Connecting cirrus-ci to a European Google K8s cluster currently fails with message `FAILED_PRECONDITION: java.lang.IllegalArgumentException: Not supported at the moment zone europe-west1-b!`. Only `us-central1-a` is supported for the time being.

Supporting [European regions](https://cloud.google.com/about/locations/?region=europe#region) would be much appreciated.

**Comment by fkorotkov** [comment]
`europe-west3` region is supported now. 🙌

**Comment by simonbrandhof** [comment]
Excellent, thanks.
