### ISSUE TITLE
Show more kubernetes scheduling info, for example pod events

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#402]
Currently when running things on a kubernetes it sometimes can take a while until a job really starts or cirrus acknowledges that it cannot be started. During this time the cirrus ci only displays "scheduled".

Some issues that I encounter for example:
- if a container cannot be started due to non existing image, cirrus takes multiple minutes to display the error, whereas in kubernetes the ImagePullBackOff status and a bunch of other kubernetes events already get displayed from the beginning.
- If a pod triggered a scale up it also can take more than a minute until a job starts.
- If a pod cannot be started at all due to some other constraint missing (pod wouldn't fit, even after scale up, sandbox failure etc.) cirrus takes 10 minutes to timeout

Generally speaking I think it would be good cirrus shows some more details on what is going on in kubernetes. The most complete solution would be probably if it simply displays all the k8s events that are shown when `kubectl describe <pod>` which in most situations can tell one precisely what is going on (or what is not) and whether there is a permanent failure or the cluster just takes a few seconds to scale up etc.

**Comment by fkorotkov** [comment]
I think it will worth to add such debug events to execution information that will include resource utilization for #93. 🤔
