### ISSUE TITLE
tasks stuck in "triggered" state

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#406]
I noticed a few instances where cirrus ci tasks get stuck in the "triggered" state for a very long time.

Here's one such example:
https://cirrus-ci.com/task/5260476269723648

For context:
- this is running on our own GKE cluster which has autoscaling enabled to up to 50 nodes and hundreds of CPUs, so more than enough capacity
- I cannot see a corresponding cirrus-ci pod being created by cirrus ci in kubernetes (which I would expect)
- the task is in a big monorepo. Currently when making a commit to master this triggers about 45 tasks + 15 trigger_type:manual tasks.
- even clicking "re-run" doesn't seem to help. the new task created also gets stuck.

**Comment by geekflyer** [comment]
@fkorotkov  ok in fact none of our pipelines work at all anymore. Seems like something is broken with cirrus in general?

**Comment by geekflyer** [comment]
hmm now the issue seems gone. I would say cirrus ci didn't work for like 15-30 minutes at all for us. Can you check what was the problem there?

**Comment by fkorotkov** [comment]
Looking into it. Sorry, didn't see GitHub notifications. Feel free to use support+urgent@cirrulabs.org next time there is an issue that requires urgent care.

**Comment by fkorotkov** [comment]
@geekflyer logs are saying that GKE was returning 500s when trying to create a pod so Cirrus was retrying. 🤔

**Comment by geekflyer** [comment]
I see. Well I thought first something is wrong with the cluster but while the issue persisted I was still able to inspect the cluster via kubectl etc.
I guess this is another instance where #402 would come in handy.

**Comment by fkorotkov** [comment]
Was there an auto-upgradr at this time by any chance?

**Comment by geekflyer** [comment]
Nope, that I can see. Also during an auto upgrade of the master I would not be able to reach the cluster via kubectl anymore. In case of node auto upgrades cirrus should still be able to create pods (which it didnt'), even though it may take a little longer until they go into running state.
I'm also not sure if you would even get a 500 during master upgrades because the master becomes completely unreachable during an upgrade and then you typically don't get an http code but rather some socket / connect timeout etc.

**Comment by geekflyer** [comment]
the issue seems to be happening again. right now.

**Comment by geekflyer** [comment]
https://cirrus-ci.com/task/5642303425740800

**Comment by fkorotkov** [comment]
This task seems to be paused. Have you triggered it?

**Comment by geekflyer** [comment]
yeah well, the as you can see there are multiple task instances. The first one I eventually cancelled / clicked re-run since it seemed stuck. Possible that the other instances haven't been "triggered".

Actually now I'm realizing that the UX on manual approval tasks is also a bit unintuitive. When one clicks "re-run" on on a manual approval task one has to click again "trigger" even if the previous task instance had been already "triggered". I think when clicking re-run a task should immediately go into triggered state even if it is a manual approval task. The user clicking the "re-run" button is de-facto giving him consent.

**Comment by fkorotkov** [comment]
Fixed the re-run logic so now you won't need to extra-trigger a re-run of a manual task. 🙌 

Closing this issue in favor of #402
