### ISSUE TITLE
How long are REPO_CLONE_TOKENS valid?

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#409]
I'm working on a library of tests for a group of developers, and one of the tests requires a listing of all branches and their commit SHAs from the repository. I've set up the test to automatically fetch all heads from `origin` so downstream developers don't need to modify their `cirrus-ci.yml`, but fetching from `origin` frequently fails with an authentication error. Tests for the repository take about ten minutes to run. Is the expiration time for `REPO_CLONE_TOKEN` around ten minutes?

**Comment by fkorotkov** [comment]
The token expires in 1 hour but Cirrus caches it so you can expect it to be valid from 0 minutes to 60 minutes for a random task depending on when Cirrus did cache it. This seems not ideas for your use case. We can't also completely remove the caching but I think we can make the less optimal for just 20 minutes out of 1 hour so you'll have the token valid from 40 to 60 minutes from the start of the task. What do you think about the compromise?

**Comment by connorbrinton** [comment]
That sounds great! 🙂

**Comment by fkorotkov** [comment]
This is being deployed. Once current tokens will expire in up to an hour, new token will be cached only for 20 minutes.
