### ISSUE TITLE
Container tasks on VMs

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#412]
For some use cases we want to run resource intensive one-time jobs that we cannot or don't want to run on our regular main cirrus GKE cluster (both due to resource requirements or because we want to run a particular job in a different project or network than the others, but without having to setup multiple GKE clusters).

Technically VMs (in our GCE) would be convenient for that, however it would mean we are losing some of cirrus' container abstractions and one would have to interact with the docker API directly and carefully select or create a custom VM image that has docker already pre installed. I think it would be cool if cirrus directly supports launching docker containers (and in a later stage docker_pipe's) with the same syntax that is used for gke / eks containers. Maybe call this task type `gce_container` etc. You could probably provide a standard cirrus image that is always used for those kind of tasks to make this work reliably.

**Comment by fkorotkov** [comment]
This is actually how `windows_container`s are working now until GKE doesn't support Windows. 😅So it's definitely possible. I think we can just add `container_image` field to `gce_instance` similar to `--container-image` flag when you create a VM with `gcloud` CLI.
