### ISSUE TITLE
REGARDING CURRENT DOWNTIME

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#414]
Hello everyone!

## TL;DR
Unfortunately, yesterday at approximately 11:30 PM, EST, parts of Cirrus CI started experiencing downtime.

## Services Effected

Right now, *only* the following services are down:

* Linux tasks

**Tasks for other platforms are not effected.**

## The issue

The issue seems to be with the Kubernetes cluster and/or the CDN.

-----------

> Subscribe to this issue for updates.

**Comment by fkorotkov** [comment]
It's been just resolved. The underlying issue was caused by weirdly broken NAT 😪

**Comment by RDIL** [comment]
@fkorotkov what is the queue looking like 😢

**Comment by fkorotkov** [comment]
Cirrus uses auto-scaling for Linux, Windows and FreeBSD. Should handle the load. 🤞
