### ISSUE TITLE
question: Scheduling takes about 5 minutes

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#417]
# Question

For some of my tasks the scheduling takes about 5 minutes:

* https://cirrus-ci.com/task/5124470526705664

Even compute credits don't speed this up:

* https://cirrus-ci.com/task/5171116748832768

Is there a way to speed this up?

**Comment by RDIL** [comment]
iirc I don’t think that FreeBSD has that many machines, that may be the cause.

**Comment by MarcoFalke** [comment]
Ok, I switched to the `container` env https://cirrus-ci.org/guide/writing-tasks/#execution-environment

**Comment by fkorotkov** [comment]
As a side note. This scheduling time delays are related to how weirdly time to boot a FreeBSD VM different from task to task.
