### ISSUE TITLE
Cannot use multiple GCP credentials in one project

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#420]
We have a repo where some of the tasks need to run in one gcp project (GKE cluster) and some in another GCP project.

In the cirrus.yml I set the gcp creds on the global level via:
```yaml
gcp_credentials: ENCRYPTED[!asdf!]
```

and then on the task level i'm attempting to override it:
```yaml

needstoruninanotherproject_task:
  gcp_credentials: ENCRYPTED[!bnmv!]
```

However this doesn't seem to work, i.e. cirrus still tries to use the global credentials and the task fails with:

```
Failed to start: 404 Not Found { "code" : 404, "errors" : [ { "domain" : "global", "message" : "Not found: projects/my-project/zones/us-west1-c/clusters/job-cluster-b.", "reason" : "notFound" } ], "message" : "Not found: projects/my-project-/zones/us-west1-c/clusters/job-cluster-b.", "status" : "NOT_FOUND" }

```

Is this a bug or is this not even supported? Either way we need this :)

**Comment by fkorotkov** [comment]
Should be working now. Yaml parsing is weird 😅
