### ISSUE TITLE
Add ability to specify 'image-family' instead of 'image' for FreeBSD

### ISSUE THREAD

**Issue by igsilya** [cirruslabs/cirrus-ci-docs#422]
# Description
Images in GCE are usually grouped into families. And it's possible to run VM by specifying `--image-family` instead of `--image` in `gcloud` command. This way GCE will start VM with the most recent image from the family. For example, `--image-family=freebsd-11-3-snap` will use the most recent stable image of 11.3 release like `freebsd-11-3-stable-amd64-v20190808`.
Right now it's only possible to run `freebsd_inastance` in GCE specifying the `image`. It'll be nice to have ability to specify `image-family` instead like this:
```
  freebsd_instance:
    matrix:`
      image_family: freebsd-11-3-snap
```

# Context
Related issue: https://github.com/cirruslabs/cirrus-ci-docs/issues/359
Docs:
- https://cloud.google.com/compute/docs/images#image_families
- https://cloud.google.com/sdk/gcloud/reference/compute/instances/create#--image-family

**Comment by jamesog** [comment]
I'd also like to use `image_family` for Debian images.

`image_family: debian-9` may have `image_name` set to something like `debian-9-stretch-v20190618`. Family would mean you can use the latest available image.

**Comment by fkorotkov** [comment]
PTAL #453. It's now available for both `freebsd_instance`s and `gce_instance`s.
