### ISSUE TITLE
windows containers performance (much worse than linux for my project)

### ISSUE THREAD

**Issue by ped7g** [cirruslabs/cirrus-ci-docs#426]
(I know for support the main channel is emails, but I'm in no hurry with this and maybe somebody outside of Cirrus labs will have some insight too)

I'm sort of baffled by the performance of the builds, for example: https://cirrus-ci.com/build/6311364785602560

What you are looking at (if you did click above):
gcc5/6/7/8 = linux container running:
* `make -j3` = building release version of the tool (processing roughly 25k LoC in C and C++ with no external dependencies, just standard libs) (takes on average about 10s)
* running through the full test suite (about 250 tests, producing text output in console, ANSI coloured, probably about 1k of lines of output) (takes on average about 5s)

configured as:
```
  container:
    matrix:
      image: gcc:5
      image: gcc:6
      image: gcc:7
      image: gcc:8
    cpu: 3
    memory: 1G
```

The "coveralls.io" build has another +10s because it's installing helper tool written in python with `pip` command, every time and the installer is *this* slow :( (and the build does produce also coverage data and uploads them, but that's quick, like +1s extra)

So far so good... but then the windows builds, one is done with MinGW gcc (`mingw32-make -j3`), using `bash, find, gunzip` tools from MSYS2, and installs `diffutils` extra with choco and running full test suite = this is essentially the same thing as gcc 8 linux build, with only few more steps extra (installing diffutils, configuring paths to MSYS tools). And it takes about 4 minutes on average. The container config is:
```
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
```

I did of course expect some degradation of performance because windows is not on par with linux on technology level (like FS, scheduler, etc..), but 4min instead of 15s, that's about 16x time slower... I don't think linux is **that** superior. :rofl:  I would expect like +20-30% or +100% at most.

Also the weird thing is, that just running the test suite takes almost 2 minutes (the Raspberry Pi0 can run the same test suite in 1:15), realistically the tool runtime on 1GHz x86 CPU for all the tests should be well under 20s (Pi0 is low power ARM v6, thus one+ minute). So I guess it's maybe the console output (~1k lines through bash + echo) which is taking so long? Or is that VM running so low on memory, that it's swapping all the time, no matter what (the tool itself when being run requires about 8-10MB of memory, i.e. nowhere near what the gcc did use when it was being built)? Or is the FS extremely slow, like running some antivirus on it?

I tried to reconfigure the windows containers with cpu/memory lines but didn't notice any changes in performance, no matter what values I tried (I put them under the os_version line).

My friend told me, that on his regular windows desktop the VS build takes 15s (like linux gcc) (I don't have personally any windows box to try out myself, but I would expect it being like this).

Any idea, what's going on, and why the windows builds are like 16x slower? Some tips, how to improve the setup?

**Comment by ped7g** [comment]
Ok, I see you tried CPU  4 + Memory 12G, and it went pretty much the same way.

Console output is about 100 lines from build vs 1k lines from tests, so I guess the slow console IO is not the culprit either.

So my top  suspicion is now the FS of the VM. Adding few hundreds of ms on each fopen/fclose would quite likely slow down both build and tests in a similar fashion (but I'm just random-guessing, the true issue may lay somewhere completely else). Isn't there some hidden AV in some virtualization layer? Isn't there some simple way to run all of this in ramdisk? Unfortunately my experience with this (VM and virtualization of everything 2-5 layers deep) stuff is very limited, I'm not sure what/how to do now to get better info. Maybe some performance trace of the build/tests to see where the time is spent, but this is windows kernel, so linux tools will probably not work for this. Hmmm.. yes, I'm just out of ideas.

**Comment by ped7g** [comment]
I tried to made the test-runner bash script console output "lighter", going from 67kB to 44kB and 686 lines to 575 lines, also internally removing about 100x `echo | tr` calls, and the execution time on windows went from 2:37 to 1:36, while the build time itself (no change in config) was 2:07 vs 1:57.
So the second VM instance seems to be somewhat faster, but IMO substantial part of that 1min save is coming from the lighter console output and not calling `tr` command often.

The `tr` part may be still somewhat FS related, although I would expect even historical OS to cache some things and find tr.exe binary instantly in every following call, so after this it seems rather the console I/O and `echo` itself is super slow.

I'm still not sure how it does manage to go from 5 seconds to 1:36 and I have difficult time to attribute all of that just to linux technological advantage, maybe there's something sub-optimal in the VM config ... or maybe the windows console I/O needs rewrite. But this feels very wrong to me, burning minutes of servers time on tasks which are supposed to be done in seconds. :/

If generally every windows build suffers from this (but their console IO is much smaller part of the tasks, so it's not so visible on other projects), then this can save hundreds of hours of server runtime, if somebody would figure out what's wrong and if there is some fix.

**Comment by fkorotkov** [comment]
We did some testing and saw that Windows is performing much better with SSDs so I've just enabled SSD disks for Windows Containers on Cirrus. Will close the issue, please reopen if you still see slow windows tasks.

**Comment by ped7g** [comment]
Refresh:
- (not related to this ticket, JFYI) I managed to adjust my build scripts to the new 2019 cmake images, so mingw builds now work again for me
- the linux gcc8 builds are ~12s, tests run are 8s, total ~25s: https://cirrus-ci.com/task/5087243603804160
- the windows mingw build is 53s (with couple of "where / --version" calls of tooling extra compared to linux script), test run is ~2.5min: https://cirrus-ci.com/task/6213143510646784

As far as I can tell, it's the slow console I/O while running the bash script which is launching the binary about 400+ times and diff-ing the results against expected file content.

I don't see any significant benefit from switch to SSD. I guess the compilation and launching binary **are** faster thanks to it, but that was contributing to total build time like 3-5sec at most, rest of the ~2min time is how slow the bash script runs in windows environment. And while I didn't re-try, I'm pretty sure the amount of `echo` in the test script makes the biggest impact, as before by shortening the test log by 50% the build times went from ~4min to ~2min (that was with fewer tests, since then the project has grown a bit). If you want me to confirm it, I can add extra `echo` line after each test, is should make the build time seriously worse in windows (while linux builds will probably not notice).

**Comment by ped7g** [comment]
@fkorotkov BTW, I don't see how to reopen this, maybe I'm blind, or I don't have rights to do it, or I'm missing something obvious, sry... tagging you in this comment instead. :)

**Comment by ped7g** [comment]
Looking through older numbers before the change to SSD, the mingw builds were actually nearing 7min before (but they were chocolatey installing diffutils, which is often extra minute), so current ~4min is significant boost, and I guess something like ~2min can be attributed to the SSD change, so it definitely did help a lot.

It just feels wrong that it takes 5x longer than linux, I didn't expect linux to be *that* much ahead, I would expect 2x at most.

**Comment by fkorotkov** [comment]
I'll release this change https://github.com/cirruslabs/cirrus-ci-agent/pull/94 tomorrow and we'll see if that will help.

**Comment by fkorotkov** [comment]
[Doesn't seem like it's helping](https://cirrus-ci.com/task/6634957751713792). 🤔

**Comment by edigaryev** [comment]
I think we've nailed the underlying issue in https://github.com/cirruslabs/cirrus-ci-agent/issues/128, so closing this.
