### ISSUE TITLE
Build status badges for tasks with space in name have "+"

### ISSUE THREAD

**Issue by dotdoom** [cirruslabs/cirrus-ci-docs#429]
# Expected Behavior

When a Build task contains a space in the name, status badge for it contains space, too.

# Real Behavior

The badge contains `+` (plus sign) in place of a space in task name:

![badge](https://api.cirrus-ci.com/github/dasfoo/delern.svg?branch=master&task=deploy%20(Play%20Store))

Transcript: `deploy+(Play+Store) | passing`.

# Related Info

Image URL: https://api.cirrus-ci.com/github/dasfoo/delern.svg?branch=master&task=deploy%20(Play%20Store)

**Comment by fkorotkov** [comment]
Sorry for the delay. It is fixed now. 🙌

**Comment by dotdoom** [comment]
Amazing, and works like a charm. Thank you!
