### ISSUE TITLE
How to debug failing builds interactively?

### ISSUE THREAD

**Issue by qris** [cirruslabs/cirrus-ci-docs#431]
I'm surprised this is not a FAQ: when a build fails, it's often difficult (or time-consuming) to get in a position to debug it. For example I have to download an Ubuntu 18.04 (for example) ISO image onto my laptop, create a VM, install it, check out the code, run the tests, then discover that they pass, so I have to work out what's different between my environment and the GCE image...

It would be great to have a command/script/utility that creates a GCE instance and runs all steps up to or including the tests, then leaves it running for me to SSH in and debug. Perhaps this is easy, but since I don't know GCE and it's pretty complex, I'm not even sure where to start. And I'd have to manually parse the `.cirrus.yml` file and copy/paste each step of the task into the new image, which wastes time that is charged by the second by GCE.

**Comment by fkorotkov** [comment]
Created #432 also #108 should help in case of Docker Containers.
