### ISSUE TITLE
Task SSH access

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#432]
# Description

It will be nice to be able to ssh to a running or failed task for debugging purpose.

# Context

#108 will help with reproducing Docker containers runs locally but there will be still an issue with VMs like FreeBSD one and OSX one.

**Comment by fkorotkov** [comment]
One option to be cloud and environment agnostic will be to integrate with https://www.teleconsole.com/, it's free and [written in Go](https://www.teleconsole.com/) so we can embed it in the [Cirrus CI Agent](https://github.com/cirruslabs/cirrus-ci-agent). So a `Re-Run with SSH` will create a task where the first step before `clone` instruction will use teleconsole to create an `ID` which a user will be able to use to connect to the task. Last step of this re-run task will just wait for the Teleconsole session to end or the task timeout which ever will occur first.

**Comment by sio** [comment]
I have found a workaround that works for now: https://github.com/TimeToogo/tunshell

It's somewhat similar to teleconsole mentioned above but allows for more privacy: no access information is published within CI log or CI job configuration.

Combining tunshell with `*_background_script` or `on_failure:` covers pretty much every use case for SSHing into CI runners for me. Also, they provide a web client to avoid installing new software on your local machine.

**Comment by probonopd** [comment]
Hi @fkorotkov I tried using teleconsole to debug issues with a task I am having, but it does not work (`getsockopt: connection refused`).

Is it disallowed e.g., by the firewall?

Detailed log:
https://api.cirrus-ci.com/v1/task/6452192104153088/logs/install.log

**Comment by probonopd** [comment]
And tunshell doesn't have a client for FreeBSD...

```
curl -sSf https://lets.tunshell.com/init.sh | sh /dev/stdin T ... ... eu.relay.tunshell.com
Unsupported system (FreeBSD)
```

**Comment by phil-blain** [comment]
tunshell now has a FreeBSD client. I just tried SSH-ing to a Cirrus-CI FreeBSD VM and it works !
