### ISSUE TITLE
Do not notify users when a failing job is being re-run automatically

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#433]
The "automatic re-run" feature is great to ignore infrastructure failures. That helps to reduce the noise to users. 

However the CI systems subscribing to CirrusCI webhooks still suffer from this noise. As an example webhooks can be used to notify failures on a Slack channel. Two messages will be sent, one for the failure, then one for the final result. The first message is useless and does not require any action from users.

The build status in the CirrusCI UI flips from Executing to Aborted and back too.

As an improvement I suggest to hide this intermediary failure to users. UX should be smooth. A solution implies:
* to complete the webhook payload with two boolean flags:
   * eligible to re-run, used for filtering.
   * is a re-run, used for statistics for instance (out-of-scope of this feature request).
* do not change the build status when the job is going to be re-run automatically.

**Comment by fkorotkov** [comment]
Logic of build status update was changed around summer 2019 to not flip on such failures. If a task fails and it's automatically re-runnable then build status is not updated.

For individual tasks there are now two additional fields with info about re-runs. See 738c18cde6c8c7a440987dacb82435d84fb1d631
