### ISSUE TITLE
Downloading .jar artifacts results in downloading .jar.html

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#437]
# Behavior

What should have happened is the file should be a Jar instead of HTML 

# Related Info

- [X] Website issue
  - Link to page: download api page
- [x] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Is it for a public repository? Could you please provide a link to the task? Also which browser are you using?

**Comment by RDIL** [comment]
1. Yes
2. Any commit on hyperiumjailbreak/hyperium ([link](https://github.com/hyperiumjailbreak/client/commits/master)) before Sep 2, 2019 since I broke it then
3. Tor (Firefox under the hood, but same behavior on both)

**Comment by RDIL** [comment]
This may be a mimetype issue, if the API doesn’t correctly set the mimetype to match the file extension, this could happen.

The proper mimetype should be `application/java-archive`.

This may not be the issue as I haven’t tested it yet, just assumed the api doesn’t have mimetypes hard coded.

**Comment by RDIL** [comment]
@fkorotkov yup, wrote https://github.com/RDIL/debugging-playground/blob/master/mimetypes.py to test this out, and printing out the headers results in https://cirrus-ci.com/task/5731758705737728?command=main#L2

**Comment by fkorotkov** [comment]
You can control content type via `type` field. Check #444 🙌
