### ISSUE TITLE
False-positive "Failed to decrypt some environment variables"

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#438]
The job https://cirrus-ci.com/task/5045480427356160 failed in the `clone` step with the error `Failed to decrypt some environment variables`. Logs show:
```
Using built-in Git...
Limiting clone depth to 50!
Fetching +refs/pull/63/head:refs/remotes/origin/pull/63...
Failed fetch: parse https://x-access-token:ENCRYPTED[!xxx!]@github.com/xxx/xxx.git: net/url: invalid userinfo!
```

A workaround to reduce noise would be to automatically re-run the job. Currently the job went green by manually restarting it.

Similar issue: #392

**Comment by fkorotkov** [comment]
Interesting! I see from the logs that there was a network issue that wasn't retried. Fixing it now. 👌 

BTW in this case the task [was automatically re-ran](https://cirrus-ci.com/task/5699747559505920) but only because `clone` failed. 😅

**Comment by fkorotkov** [comment]
The fix was deployed. So at least this particular scenario is covered now. Sorry for the inconveniences and thanks for reporting!
