### ISSUE TITLE
GCE Windows VM: Failure to download the startup script

### ISSUE THREAD

**Issue by dbolkensteyn** [cirruslabs/cirrus-ci-docs#44]
During my tests today, I came across this strange behaviour:
![cirrus-ui](https://user-images.githubusercontent.com/1132601/44476287-a1a29900-a637-11e8-81f7-5eca94c38a33.png)

The task stays in the `scheduled` state, and the `created since` keeps increasing. Typically, I observed that scheduling takes around 1 minute on my project.

So, digging into GCE:
![gce](https://user-images.githubusercontent.com/1132601/44476369-d1ea3780-a637-11e8-9da2-2685d9fef547.png)

Both instances of the matrix build seem up.

Looking at `cirrus-task-5717458405031936` serial port's logs:
```
Booting from Hard Disk 0...
2018/08/22 16:11:48 GCEWindowsAgent: GCE Agent Started (version 4.5.4@1)
2018/08/22 16:12:00 GCEMetadataScripts: Starting startup scripts (version 4.2.0@1).
2018/08/22 16:12:00 GCEMetadataScripts: Found windows-startup-script-ps1 in metadata.
2018/08/22 16:12:38 windows-startup-script-ps1: Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
2018/08/22 16:12:38 windows-startup-script-ps1: At C:\Windows\TEMP\metadata-scripts760610747\windows-startup-script-ps1.ps1:4 char:1
2018/08/22 16:12:38 windows-startup-script-ps1: + (New-Object System.Net.WebClient).DownloadFile('https://api.cirrus-ci ...
2018/08/22 16:12:38 windows-startup-script-ps1: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018/08/22 16:12:38 windows-startup-script-ps1:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
2018/08/22 16:12:38 windows-startup-script-ps1:     + FullyQualifiedErrorId : WebException
2018/08/22 16:12:38 windows-startup-script-ps1:  
2018/08/22 16:12:46 windows-startup-script-ps1: Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
2018/08/22 16:12:46 windows-startup-script-ps1: At C:\Windows\TEMP\metadata-scripts760610747\windows-startup-script-ps1.ps1:5 char:1
2018/08/22 16:12:46 windows-startup-script-ps1: + Start-Process -FilePath 'agent.exe' -ArgumentList '-task-id', '571745 ...
2018/08/22 16:12:46 windows-startup-script-ps1: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018/08/22 16:12:46 windows-startup-script-ps1:     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
2018/08/22 16:12:46 windows-startup-script-ps1:     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
2018/08/22 16:12:46 windows-startup-script-ps1:  
2018/08/22 16:12:46 GCEMetadataScripts: windows-startup-script-ps1 exit status 0
2018/08/22 16:12:46 GCEMetadataScripts: Finished running startup scripts.
```

This looks exactly like the kind of false-positives I am trying to run away from :) Would it be possible to let me bake this step into my VM image and so to avoid any kind of unreliable network downloads?

I'm going to leave this one running just to double-check that it will get killed by the 60 minutes timeout.

**Comment by dbolkensteyn** [comment]
It failed nicely and did clean up the instances after 15 minutes:
![nice-failure](https://user-images.githubusercontent.com/1132601/44476834-3d80d480-a639-11e8-8845-b1e921e7aa26.png)

**Comment by fkorotkov** [comment]
With Kubernetes Cirrus CI just mounts the agent as a volume. With VMs it had to download the agent. Unfortunately `WebClient` doesn't have any retries built-in. Will work on adding retries manually which will basically only try to download the agent if it's not yet presented. In that case if you'll bake the agent within the image there will be no attempt to download it. 👌
