### ISSUE TITLE
Allow opening builds and tasks in new window

### ISSUE THREAD

**Issue by dotdoom** [cirruslabs/cirrus-ci-docs#446]
# Description

Make Ctrl+click, middle-click and/or right-click+"Open in new tab/window" possible.

# Context

It's convenient to open a few builds side by side to compare (e.g. compare task running duration or build parameters). Today it's not possible because in the list of build or build tasks the items are not actual links -- they are clickable `<p>` / `<div>` elements with a JavaScript handler installed.

I hope it's not a limitation of the UI framework and can be worked around.

**Comment by fkorotkov** [comment]
Strange. It should be possible. Which OS and browser are you using?

**Comment by RDIL** [comment]
@dotdoom is right - it doesn't work in Firefox or Tor.

**Comment by dotdoom** [comment]
Google Chrome OS -- Version 76.0.3809.136 (Official Build) (64-bit)

**Comment by duckinator** [comment]
Yeah, confirmed here as well. As @dotdoom said, this is a direct result of Cirrus using clickable `<p>`/`<div>`/`<span>` tags instead of actual `<a>` tags.

**Comment by fkorotkov** [comment]
Just checked on macOS Firefox 69 that Cmd+Click opens a new tab as expected. Which OSes are you all using?

**Comment by RDIL** [comment]
Doesn't work on ChromeOS or Windows

**Comment by dotdoom** [comment]
Thank you!
