### ISSUE TITLE
Support "optional"/allowed-to-fail build tasks

### ISSUE THREAD

**Issue by DanTup** [cirruslabs/cirrus-ci-docs#45]
On Travis and AppVeyor you can have tasks that are allowed to fail. This is great for things like running tests against nightly builds of dependencies (for ex. I run the Dart Code tests against dev versions of Dart/Flutter and VS Code, but since they're more fragile, I don't want them to report failures in pull request statuses):

https://github.com/Dart-Code/Dart-Code/blob/master/.travis.yml#L15-L26

I can't find anything similar here, but it's a great feature. You could also abort all of the "allowed failure" tasks if any of the "required" tasks fail which may save some resources (there's no point running the optional ones if the build is known to be bad). You could possibly even lower the priority of optional tasks within a project (eg. run the required tasks for all of my branches before starting the optional ones).

**Comment by DanTup** [comment]
Great, thanks! If we put multiple of these, are they OR'd together?

```yaml
allow_failures: $DART_CHANNEL == 'dev'
allow_failures: $CODE_VERSION == 'insiders'
```

(assuming that would be the right way to have multiple)

**Comment by fkorotkov** [comment]
@DanTup it will actually override one with another. You need:

```yaml
allow_failures: $DART_CHANNEL == 'dev' || $CODE_VERSION == 'insiders'
```

**Comment by DanTup** [comment]
Gotcha, thanks!
