### ISSUE TITLE
Way to use container's `WORKDIR` as CIRRUS_WORKING_DIR

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#450]
By default, Cirrus modifies the working directory used inside any container to a temporary path. However, some containers may require the use of a particular working directory in order to function correctly. This can be worked around by manually setting `CIRRUS_WORKING_DIR` to the desired path, but this needs to be modified for each image and may be difficult information to obtain for certain images. It would be nice to be able to just use the default working directory for the image without needing to manually extract and re-specify the directory with `CIRRUS_WORKING_DIR`.

CodeFresh supports passing [the special keyword `IMAGE_WORK_DIR`](https://codefresh.io/docs/docs/codefresh-yaml/what-is-the-codefresh-yaml/#working-directories) when specifying the working directory of a CodeFresh freestyle step to use the default image working directory. Is there support for a similar kind of special keyword in Cirrus CI?

**Comment by fkorotkov** [comment]
Unfortunately right now `CIRRUS_WORKING_DIR` as you mentioned is the only way. 😢

Not sure if something like `IMAGE_WORK_DIR` will work for Cirrus since there are [Docker Pipes](https://cirrus-ci.org/guide/docker-pipe/) and each step of a pipe could have a different WORKDIR. 🤔

Which image are you using that requires a specific WORKDIR?

**Comment by connorbrinton** [comment]
Mostly I'm working with private images that include:
* A script (with a folder full of dependencies)
* A bunch of resources and
* An entrypoint which launches the script (`python script.py`)

The script/dependencies were written without much of a mind for Python packaging best practices or encapsulation 😬 Long-term I definitely want to modify these images so all scripts are executable, present in `PATH` and use working-directory insensitive paths, but there are some barriers which make it difficult to do that right now (mainly time) 😅

For now I'll just set `CIRRUS_WORKING_DIR` manually. Fortunately the `WORKDIR` isn't dynamic or anything, so hard-coding it should be fine 😄

**Comment by fkorotkov** [comment]
Got it. So in your case WORKDIR is not empty as well (contains a script) which might be problematic for the initial clone.

FYI #393 might be interesting for you too and seems it will need to use container's WORKDIR as well. Will think about how to make the use of WORKDIR transparent and at the same time without breaking current builds. 🤔

**Comment by connorbrinton** [comment]
Yup, I had to override `clone_script` with just the command `true`. And #393 would definitely be useful, especially for the images we build for unit/integration testing.

Thanks Fedor!

**Comment by fkorotkov** [comment]
Closing in favor of #393 since it will include it.
