### ISSUE TITLE
Cirrus failing to capture the right commit on force push

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#454]
https://github.com/hyperiumjailbreak/client/pull/189

# Expected Behavior

Builds shouldn't run on wrong commit (failing clone step)

**Comment by fkorotkov** [comment]
@RDIL could you please be a little more descriptive with the issue?

**Comment by fkorotkov** [comment]
Closing for now until there is enough information.

**Comment by RDIL** [comment]
https://cirrus-ci.com/build/5069405639147520
https://cirrus-ci.com/build/5162863120875520
https://cirrus-ci.com/build/5668080258121728

**Comment by fkorotkov** [comment]
How did you create these builds? What did you do in the console to create them?

**Comment by fkorotkov** [comment]
It looks like you created temporary branches for cherry-picks that got pushed and immediately deleted. That's why the clone failed 🤷‍♂

**Comment by RDIL** [comment]
Ah
