### ISSUE TITLE
Change GitHub conclusion of failed optional tasks

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#458]
If you have an optional tasks and it's failing the overall build status is still successful but the reporting [conclusion of a corresponding GitHub Check Run ](https://developer.github.com/v3/checks/runs/) is still `Failed` which results in a red status check. The conclusion should be `Neutral`.

**Comment by RDIL** [comment]
22 minute feature, I think thats a record

**Comment by fkorotkov** [comment]
one-liner + a test 🤷‍♂
