### ISSUE TITLE
Absolute paths for cache folders always cause misses in Windows containers

### ISSUE THREAD

**Issue by Snaipe** [cirruslabs/cirrus-ci-docs#460]
# Expected Behavior

Given this cache definition:

```yaml
meson-setup_cache:
  folder: C:\\Python
  populate_script: |-  
    choco install -y --no-progress python3 --params "/InstallDir:C:\Python"  
    pip install meson
```

I would expect `C:\Python` to be the directory where the cache is unpacked to.

I realize that the proper way to do this is to just make a docker image where this is preinstalled, but I'm currently experimenting a bit, away from a windows machine, and the docker hub does not support automated builds for windows images.

# Real Behavior

```
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call choco info -r python3 
python3|3.7.4
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 0 NEQ 0 exit /b 0 
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call (pip search meson   || VER  1>NUL)  | findstr /r /c:"^meson \([^)]+\)"   || VER1>NUL 
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 0 NEQ 0 exit /b 0 
Downloaded 32Mb.
Cache hit for meson-setup-61b4b925d56d34d21b5e1abb2bdfa46c43bdfa9c2e6b6ed9c6451676bfb964ad!
Failed to unarchive meson-setup cache because of C:\Python\C:\Python\DLLs: making directory: mkdir C:\Python\C:: The filename, directory name, or volume label syntax is incorrect.!
```

It seems that it tries to unpack the cache into `C:\Python`, but the archive itself contains the `C:\Python` path prefix rather than just the contents relative to it.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: (Windows)
  - Link: https://cirrus-ci.com/task/5652146046894080?command=meson-setup#L12
  - Task name: `Windows_task`
  - Script/cache name (if applies): `meson-setup`

**Comment by RDIL** [comment]
Hey @Snaipe!
Please see #459 - it explains this issue.
If you have any other questions, I'm here to help :)

**Comment by Snaipe** [comment]
Ah, I see, so the real bug here is the fact that `folder: Drive:\Anything` is bogus, but still "works"?

I see -- I'll just stop abusing the cache to make up for my own lazyness of setting up a Windows VM and pushing an image with the right software on it.

**Comment by RDIL** [comment]
@fkorotkov any idea why this behavior is happening?

**Comment by Snaipe** [comment]
Note that the [documentation](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction) is currently unclear on that aspect:

> The folder is a required field that tells the agent which folder to cache. It should be relative to the working directory, or the root directory of the machine (ex. node_modules or /usr/bin/bundler).

It really does seem like any absolute path is supposed to work.

**Comment by fkorotkov** [comment]
Seems like a Windows specific bug which is not related to #459. Will investigate. 🙌

**Comment by fkorotkov** [comment]
A fix was deployed a while ago after my investigation. Please reopen if it's not fixed for your example.
