### ISSUE TITLE
Support API token for RepositoryCreateBuildMutation

### ISSUE THREAD

**Issue by astronouth7303** [cirruslabs/cirrus-ci-docs#465]
`RepositoryCreateBuildInput.configOverride` in the GraphQL schema is just listed as a "String" with no indication of how it works or what I should put in there?

**Comment by fkorotkov** [comment]
Yeah. Can confirm it's not working for API token. Will fix it.

**Comment by fkorotkov** [comment]
Whoops. Forgot to close the issue. It was fixed.

**Comment by RDIL** [comment]
Good to see older issues being closed 👍
