### ISSUE TITLE
Cancel all jobs when branch is deleted

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#466]
# Description

Currently (from my experience), closing a PR or deleting a branch does not automatically cancel all associated Cirrus CI builds. It would be nice if they could automatically be cancelled to reduce load on the CI service and avoid needing to manually cancel each individual task.

# Context

I use Dependabot on a mono-repo, which has very many tasks for each build. However, sometimes Dependabot issues so many PRs that our CI nodes are overwhelmed by the load. When this occurs, we close the PRs to make sure we can focus on feature PRs (which prompts Dependabot to automatically delete the branch). However, all CI jobs continue to run, and we often need to cancel each task of each build individually because they hang under the load on the CI nodes.

**Comment by fkorotkov** [comment]
Thanks for a great suggestion, Connor! I've been thing recently about the bot situation. They sometimes just overwhelm everything. 😅

**Comment by fkorotkov** [comment]
The PR part is implemented now: when you close a PR all yet running tasks will be aborted.

**Comment by fkorotkov** [comment]
Oh. It was deployed a while ago. Forgot to close the issue.
