### ISSUE TITLE
Add environment variable CIRRUS_PULL_REQUEST

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#47]
The ID of the pull request should be available as an environment variable, for example `CIRRUS_PULL_REQUEST`. I suggest to not set the variable at all when no pull requests are open on the branch being built.

**Comment by fkorotkov** [comment]
@simonbrandhof you can use `CIRRUS_PR` [environment variable](https://cirrus-ci.org/guide/writing-tasks/#environment-variables). It won't be set for non-pr builds.

**Comment by simonbrandhof** [comment]
I feel stupid. Sorry for the noise.

**Comment by fkorotkov** [comment]
@simonbrandhof no worries! Cirrus CI docs can be improved :-)
