### ISSUE TITLE
Swap skipped and passed emojis in task details

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#470]
![Screenshot 2019-09-26 at 9 45 23 AM](https://user-images.githubusercontent.com/34555510/65693557-782a1d00-e042-11e9-89f4-d6db590b953c.png)

It will look better if passing is green, and skipped is white.

This doesn't really make sense right now.

**Comment by fkorotkov** [comment]
So Cirrus uses :heavy_check_mark:(`:heavy_check_mark:`) for Skipped tasks and :white_check_mark: (`:white_check_mark:`) for Successful.

**Comment by fkorotkov** [comment]
Which is this for me on macOS 👇

<img width="623" alt="Screen Shot 2019-09-26 at 10 08 43 AM" src="https://user-images.githubusercontent.com/989066/65695494-a65d2c00-e045-11e9-9628-ef82b2428899.png">
