### ISSUE TITLE
Git clone fails on Windows

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#471]
# Expected Behavior

Clone can succeed.

# Real Behavior

```
Failed to clone: open C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\liblumen_beam\src\beam\reader\chunk\aux.rs: The system cannot find the file specified.!
```

# Related Info

See https://cirrus-ci.com/task/5722868861632512

**Comment by fkorotkov** [comment]
Just a heads up. I've reproduced the issue on Windows here. The error is coming from Go when it makes a `syscall`. Continue investigating...

**Comment by fkorotkov** [comment]
BTW here is the repro https://github.com/fkorotkov/go-git-clone-windows-issue

**Comment by fkorotkov** [comment]
Created https://github.com/src-d/go-git/issues/1222 with `go-git`. @KronicDeth please don't remove `windows` branch for now ;-)

**Comment by swaldhoer** [comment]
You can not create a file `aux.<extension>` on Windows, and I assume this is the reason the `aux.rs` file is missing.

For a full list of files names that are not allowed on Windows see [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions). There maybe workarounds, but I do not know, if they break something.

**Comment by fkorotkov** [comment]
@swaldhoer thank you! Seem renaming fixed the issue! Wow, super grateful for your answer!
