### ISSUE TITLE
Artifacts upload hanging

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#472]
# Expected Behavior

Upload should either complete of timeout sooner

# Real Behavior

See https://cirrus-ci.com/task/6322750655823872

**Comment by simonbrandhof** [comment]
Hi Fedor, do you expect a fix soon? I ask the question because there's no "high priority" label. This bug breaks our builds.
Thanks, and good luck!

**Comment by fkorotkov** [comment]
It seems there were couple dozen tasks failed because of hanged GRPC streams in the last 24 hours. There were no recent changes to either Cirrus agent or the GRPC API service that communicates with the agent. I've implemented additional timeouts as a workaround plus implemented some small improvements to the streaming logic.

<img width="965" alt="Screen Shot 2019-09-27 at 10 41 10 AM" src="https://user-images.githubusercontent.com/989066/65780636-248a0300-e118-11e9-97c3-6c311b2f37e1.png">

(screenshot above shows tasks failed because of hard `Time out!`)

Keeping an eye on the metrics in the meantime before closing the issue.

**Comment by fkorotkov** [comment]
There were no such failures in the last 24 hours. Closing the issue now. 🙌
