### ISSUE TITLE
Cache upload timeouts

### ISSUE THREAD

**Issue by mathstuf** [cirruslabs/cirrus-ci-docs#478]
# Expected Behavior

What should have happened is ...

Cache upload succeeded.

# Real Behavior

What ended up happening was ...

Cache upload timed out? The remote wasn't responsive?

# Related Info

- [x] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

Failing runs can be seen here: <https://github.com/mathstuf/rust-keyutils/runs/245787749>.  AFAICT, the cache upload is just timing out. Is this something I'm doing wrong or is there something else going on here? Thanks.

**Comment by fkorotkov** [comment]
We should add a retry on the upload. 🤔 Seems like a transient network issue.

**Comment by simonbrandhof** [comment]
Same issue right now on multiple builds. Can it relate to https://github.com/cirruslabs/cirrus-ci-docs/issues/472? 
You recommend to enable retry, but:
- how to do that with `gradle_cache`?
- Cirrus internal network issues should be transparent to users if the retry is enough. The retry mechanism should be implemented in the upload native feature IMO.

**Comment by RDIL** [comment]
Same issue here, with all yarn/npm caches

**Comment by mathstuf** [comment]
Allowing cache uploads have `allow_failures: true` would also work.

**Comment by fkorotkov** [comment]
@simonbrandhof what do you mean by "upload native feature". Right now Cirrus indeed proxies all the cache uploads for security reasons to make sure:
1. VM or a container doesn't have your credentials
2. Make sure PRs can't write to production caches

I've tweaked the GRPC streaming uploads that are happening under the hood which should improve the situation. Plus I've made such upload failures non fatal the same way when Cirrus fails to download a cache it just populates it again so it seems makes sense to not fail on a failed cache upload.
