### ISSUE TITLE
Store build artifacts

### ISSUE THREAD

**Issue by rubengees** [cirruslabs/cirrus-ci-docs#48]
I recently tried Cirrus-CI after coming from Circle-CI.
One feature I'm missing (or at least I have not found it) is storing artifacts (for reference: [Circle-CI docs](https://circleci.com/docs/2.0/artifacts/)) after a build.

In my case I would like to store the `build/reports` folder of a `Gradle` build and be able to access it after the build through the web frontend. This would be especially usefull if my tests or static code analysis tools failed and the error is not printed to the console, since I have no way to see them without running the build locally.

Thanks in advance!

**Comment by paleozogt** [comment]
Artifacts are also supported by [GitLab CI](https://docs.gitlab.com/ce/user/project/pipelines/job_artifacts.html#defining-artifacts-in-gitlab-ci-yml).

**Comment by fkorotkov** [comment]
I've been thinking about adding an additional artifact instruction that can be used like this for storing a file or a single folder:

```yaml
check_task:
  script: ./gradlew check
  reports_artifact: 
    store: always
    path: build/reports
```

You'll be able to specify when to store an artifact: always, only on failure or only on success (default).

Plus having a link to the latest artifact on a branch like this for downloading: 

`/artifacts/github/ORGANIZATION/REPOSITORY/branch/BRANCH/ARTIFACT_NAME/<path within saved folder>`

**Comment by isavcic** [comment]
I'm baffled, to be honest: what should I do when I successfully build a Golang binary? Documentation on this is a bit lacking. How can I push that as a release to the Github repo? I've integrated the Cirrus CI app to the repo, I don't get it how this isn't available out of the box.

**Comment by fkorotkov** [comment]
Hi @isavcic, I'm very sorry for the inconveniences. Cirrus CI is a very small shop comparing to any other team behind a CI you are used to. Some features you may used to are missing but we are actively catching up! 

Because of your feedback I've added some environment variables that should help you with your release and also added [documentation](https://cirrus-ci.org/examples/#release-assets) on how to upload artifacts using them via a script. I've tested it on a simple Go project and it worked. Please let me know if it works for you and resolves your issue!

**Comment by isavcic** [comment]
@fkorotkov thank you very much!

**Comment by RDIL** [comment]
+1

**Comment by RDIL** [comment]
Looks like https://transfer.sh may work well for this.

**Comment by RDIL** [comment]
I would love to assist on working on this if there is a way.

**Comment by fkorotkov** [comment]
@RDIL, thank for volunteering! Will ping you once backend will be ready to collaborate on https://github.com/cirruslabs/cirrus-ci-web part. 🙌
