### ISSUE TITLE
Build not triggered when new tag pushed

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#481]
Recently, a maintainer merged a PR containing several commits, one of which is to signify a new release version.  Cirrus-CI properly triggered a new build for the branch upon merge.  While that was executing, the maintainer pushed tags, including one for the "middle" commit (of the PR).  

# Expected Behavior

Upon push of the new tag, a new build should have triggered with `$CIRRUS_TAG` set for all tasks - in addition to the one already running against the branch, for the merge event.

# Real Behavior

No builds were triggered which contained a properly set `$CIRRUS_TAG`

# Related Info

The PR merge (to master branch) was: https://github.com/containers/libpod/commit/e67e9e123cde595b6f869b068f7f16e1b9fe1850

The tag 'v1.6.1' pushed was: https://github.com/containers/libpod/commit/233d95f4f0a815f11d1c1ae9aba16781c4eb2700

I see two builds that happened on master:
1. For the merge-commit: https://cirrus-ci.com/build/5689345075314688
2. For the PR's head: https://cirrus-ci.com/build/5657594724614144

The merged PR's commits are: https://github.com/containers/libpod/pull/4177/commits
Note it was the first commit that was tagged, but the last commit (HEAD) that ran the build.

**Comment by cevich** [comment]
> @cevich creation time of such tag build will be timestamp of the last change on the branch. You can try a direct link: mmm, so it's possible I'm just not seeing it. I looked under https://cirrus-ci.com/github/<owner>/<repo>/<tag>

I don't see anything at 'https://cirrus-ci.com/github/containers/libpod/v1.6.1' (though note, this is ***also*** the name of a branch).  I believe the branch was created after the tags were pushed.

**Comment by fkorotkov** [comment]
How was the tag created? I've ran:

```
$ git tag 0.2
$ git push origin 0.2
```

And got a build created for the tag: https://cirrus-ci.com/build/5084350294523904

**Comment by cevich** [comment]
The workflow Matt (maintainer) used was:

1. Matt opens a PR with several commits in it (in some random order):
    a. Some other random but related change
    b. Bump version to x.y.z
    c. Release notes for x.y.z
2. Cirrus-CI ran on the PR, gives the all-green.
3. Matt hits the merge button.
4. Cirrus-CI ran on master, post-merge with 3 + 1 merge commit on top.
5. Matt tags commit "b" as "vX.Y.Z"
6. Matt did `git push --tags`

However, I believe steps 5/6 happened **while** the build in step 4 was still executing.  I looked and looked, but could not find a separate build triggered _only_ because of step 6.

**Comment by cevich** [comment]
Oh it's suppose to trigger a totally separate build on tag push.  Even better!  Thanks!

**Comment by fkorotkov** [comment]
The fix was deployed
