### ISSUE TITLE
Multiline scripts using | in YAML cause errors on WIndows containers

### ISSUE THREAD

**Issue by KronicDeth** [cirruslabs/cirrus-ci-docs#482]
# Expected Behavior

Using `|` should work on Windows.

# Real Behavior

Have to switch to single line scripts with `;` separating commands to make them work in both Windows, Linux and Mac.

# Related Info

https://cirrus-ci.com/task/5103080328134656?command=build#L420

- [x] Task issue
  - OS: Windows
  - Task name: liblumen_arena_test

**Comment by RDIL** [comment]
Interesting.  I can see why this is most likely happening, I believe the backend needs to have logic to split `\n`s into `;`s.

**Comment by KronicDeth** [comment]
I assumed it was a \n vs \r\n problem and the YAML parser/output isn’t OS specific

**Comment by fkorotkov** [comment]
There was an issue for Powershell specific cases. Now it's fixed and should work as expected. Thanks for reporting!

**Comment by KronicDeth** [comment]
I can confirm it is working for my Windows Powershell scripts now 👍
