### ISSUE TITLE
connection refused vs time out on FreeBSD

### ISSUE THREAD

**Issue by bagder** [cirruslabs/cirrus-ci-docs#483]
I run CI jobs on several different CI systems and Cirrus CI for [the curl project](/curl/curl) and I'm right now working on [a potential little change in how we handle timeouts during TCP connection](https://github.com/curl/curl/pull/4462).

A few of the tests we run attempts to do a TCP connect to 127.0.0.1 to a port number that isn't used - I've tried with 60000 and 2 and we want it to end with a **connection refused** which means that not service is listening on that port. Presumably, unless I do something, there is nothing listening on those ports.

The tool does a TCP connect. I want to verify that it handles a connection refused correctly.

But here's the thing: instead of connection refused, my connect attempts time out after 75 seconds on the Cirrus CI FreeeBSD machines.

I can't find any documentation explaining this nor how it can be changed. Can it be changed at all? Is there any TCP port that will result in connection refused? I'd love a little hint or pointer!

**Comment by fkorotkov** [comment]
Hey @bagder, I can't think of anything that Cirrus does that is different for Linux vs FreeBSD tasks. Network config should be the same. Also Cirrus is just using vanilla FreeBSD images that GCP has and I'm not sure if `blackhole` is enabled there but you can check it via `default net.inet.tcp.blackhole=0`. Found it here: https://github.com/golang/go/issues/28883

**Comment by bagder** [comment]
Thanks, I've now verified that the builds do indeed say `net.inet.tcp.blackhole: 2` and this perfectly explains the behavior I see!

**Comment by emaste** [comment]
It looks like only FreeBSD's GCE images had this setting. I've opened a FreeBSD review to remove the sysctls: https://reviews.freebsd.org/D41751
