### ISSUE TITLE
"task2" download artifact from "task1"

### ISSUE THREAD

**Issue by mpaladin** [cirruslabs/cirrus-ci-docs#484]
I have `task2` which depends on `task1` and would like to download `task1` artifact from `task2`, I tried the following without success:

```
curl --header "Authorization: Bearer $CIRRUS_API_TOKEN" \
  https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/$TASK_NAME/$PATH_TO_ARTIFACT
```

receiving

```
Error 401 Unauthorized
```

The token is correct as I can successfully run a graphql query and the url is correct as I can use it to download an artifact from my browser session.

What am I missing?

**Comment by fkorotkov** [comment]
Unfortunately, this endpoint doesn't support API token authorization. Will fix it.

**Comment by fkorotkov** [comment]
This should work now. BTW if you just want to share some files between tasks you can check [HTTP cache](https://cirrus-ci.org/guide/writing-tasks/#http-cache) that doesn't require authentication within tasks.

**Comment by mpaladin** [comment]
Thank you @fkorotkov, it works 👍 .

Thank you for the tip about [HTTP cache](https://cirrus-ci.org/guide/writing-tasks/#http-cache) .
