### ISSUE TITLE
Results not being properly sent to GitHub API

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#485]
# Expected Behavior

`Unit Tests` check in https://github.com/area4lib/area4/pull/198 should have been reported as a success

# Real Behavior

Still says pending

# Related Info

logs: https://cirrus-ci.com/task/5212595434291200

**Comment by fkorotkov** [comment]
Interesting. GitHub API returned `422 Unprocessable Entity` for the API request but doesn't provide any meaningful information about the failure. Just `Validation Failed`. Will try to investigate what happened there.

**Comment by fkorotkov** [comment]
Yeah, the error was in annotations. Made handling of them more error prone.

**Comment by RDIL** [comment]
Thanks!
