### ISSUE TITLE
Is it possible to use env variables in a task name?

### ISSUE THREAD

**Issue by DanTup** [cirruslabs/cirrus-ci-docs#49]
I use `matrix` to run tests on stable+dev versions of some dependencies, but I can't figure out how to include these in the `name` of the task so that it shows up nicely in the list.

Config looks like:

<img width="364" alt="screen shot 2018-08-27 at 1 11 23 pm" src="https://user-images.githubusercontent.com/1078012/44659060-d4171200-a9fa-11e8-915b-b18d1324e482.png">

I tried just putting `$CODE_VERSION` etc. into the name, but it just showed up literally:

![screen shot 2018-08-27 at 1 11 11 pm](https://user-images.githubusercontent.com/1078012/44659277-8cdd5100-a9fb-11e8-9e16-1ef78c1970b8.png)

**Comment by fkorotkov** [comment]
This should work now.
