### ISSUE TITLE
Font rendering problem

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#490]
# Expected Behavior

Font is neat.

# Real Behavior

Font is blurred:

![image](https://user-images.githubusercontent.com/6510020/66701146-a6298580-ed01-11e9-8287-1827977b1305.png)

# Related Info

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/#environment-variables

# Additional info

This is because `.md-sidebar` has `width: 12.1rem` and `.md-sidebar--secondary` has `    transform: translate(-100%)`.

Changing `rem` to `px` (in `width` or `translate`) resolves this problem:

![image](https://user-images.githubusercontent.com/6510020/66701175-1506de80-ed02-11e9-8cf6-a00bd93b624c.png)

Chromium 77, Linux, NVIDIA GTX 1060.

**Comment by RDIL** [comment]
Hi @AlexWayfer,
It looksl like this is an issue with the theme, not the docs on Cirrus's end.  You may want to open an issue upstream at [github:squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material).

**Comment by fkorotkov** [comment]
Do you see the same issue on https://squidfunk.github.io/mkdocs-material/?

**Comment by AlexWayfer** [comment]
> Hi @AlexWayfer,
> It looksl like this is an issue with the theme, not the docs on Cirrus's end. You may want to open an issue upstream at [github:squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material).

OK. Thank you. I didn't know can I contribute to theme or not (here is no info about using theme in this repo).

> Do you see the same issue on https://squidfunk.github.io/mkdocs-material/?

Yes. I'll create an issue (or PR) for the theme repo directly. Thank you.

**Comment by AlexWayfer** [comment]
Oh, it there is already: https://github.com/squidfunk/mkdocs-material/issues/1292

**Comment by fkorotkov** [comment]
@AlexWayfer thank you for finding the issue. Will also subscribe to it! 🙌

**Comment by AlexWayfer** [comment]
This will be as a part of `mkdocs-material v5`. Do we need to leave this issue open for upgrading `mkdocs`?

**Comment by AlexWayfer** [comment]
Confirming it's resolved, thank you. :clap:
