### ISSUE TITLE
GitHub checks reported from multiple builds

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#493]
# Expected Behavior

When multiple builds are executed in sequence (for example, commit build -> PR build), only results from the latest build should be reported to GitHub.

# Real Behavior

Dependabot PRs frequently result in mixed-up commit and PR build results in GitHub. Even though the PR build passes, GitHub still reports "Scheduled" for some tasks. The misreported tasks need to be re-executed to get proper results in GitHub.

# Related Info

- [ ] Task issue
  - OS: DockerLinux
  - Task name:
    - Cancelled build: https://cirrus-ci.com/build/5752755074891776
    - Successful build: https://cirrus-ci.com/build/5765266985713664

![Screenshot 2019-10-21 10 39 43](https://user-images.githubusercontent.com/1848731/67215220-1c5b7580-f3ef-11e9-96c6-9be9bda21990.png)

**Comment by RDIL** [comment]
Related: #473

**Comment by connorbrinton** [comment]
@RDIL agreed, that issue is somewhat related. In my case however, I don't mind the fact that Cirrus CI runs multiple pipelines on a branch. Actually, it's kindof nice if I only want to run certain tasks in a PR context, and not a commit context.

My specific issue is that if a new pipeline supersedes and autocancels an older pipeline, I only want to see GitHub status check results from the new pipeline 🙂

**Comment by RDIL** [comment]
Yeah I know, just pointing out that these issues are related in that they are both very similar, and as such they can be grouped.

**Comment by fkorotkov** [comment]
Hey @connorbrinton, which task you had to re-run to get the checks go green? Don't see any re-runs for https://cirrus-ci.com/build/5765266985713664 🤔

**Comment by connorbrinton** [comment]
I didn't actually re-run any checks in that particular instance 😅 I merged a PR that had green checks and Dependabot automatically rebased the PR with bad checks.

This happens fairly often though, so if there's no other PR to merge, I do have to actually re-run the checks. I'm afraid I don't have an example readily available though 😬

**Comment by fkorotkov** [comment]
Since it's happening fairy often for you. Could you please the next time post a link of a task that finished but a corresponding check is still yellow? I'll check the logs to see why it happened.

**Comment by connorbrinton** [comment]
Yup, I'll update here when it happens next 🙂

**Comment by fkorotkov** [comment]
Closing for now. Please re-open once you have a task I can investigate.

**Comment by connorbrinton** [comment]
Dependabot just did its weekly run, so I have a bunch of tasks for you to investigate now 🙂

**First PR:**
* Branch build: https://cirrus-ci.com/build/6303152113975296
* PR build: https://cirrus-ci.com/build/5193288457388032
* Misreported tasks:
  * Run Unit Tests:
    * GitHub displays "Queued -- waiting to run this check..."
    * Branch run: https://cirrus-ci.com/task/6330013896409088
    * PR run: https://cirrus-ci.com/task/4808719904276480

**Second PR:**
* Branch build: https://cirrus-ci.com/build/5704439293280256
* PR build: https://cirrus-ci.com/build/5661956832231424
* Misreported tasks:
  * Preview (Staging):
    * GitHub displays "Queued -- waiting to run this check..."
    * Branch run: https://cirrus-ci.com/task/5417744069033984
    * PR run: https://cirrus-ci.com/task/5272248931319808

**Comment by fkorotkov** [comment]
I've deployed an improvement to the locking mechanism for such race conditions. Thank you for the links! Let's see how it'll behave.

**Comment by connorbrinton** [comment]
@fkorotkov locking has worked much better over the past month 🙂 However I still run into this problem from time to time. Out of 9 Dependabot PRs created today, 1 of them is showing results from the branch build in GitHub:
* Branch build: https://cirrus-ci.com/build/6226052422041600
* PR build: https://cirrus-ci.com/build/5914370940338176

Both "Build and Push" and "Run Tests" (the only two tasks) are misreported on the PR page.

Have any changes been deployed recently affecting the locking mechanism, or is there anything in the logs that might explain why the wrong task status are reported?

Thanks! 😄

**Comment by RDIL** [comment]
Hey @connorbrinton, I would love to take a look and help out, but since the repo looks private, can you describe what you are seeing more in depth, or provide a screenshot (even if partially censored)?

(this is optional, you don't need to disclose this to me if you don't want to or can't, since I am not an employee at Cirrus Labs)

**Comment by connorbrinton** [comment]
Yup, can do @RDIL 🙂 I actually realized that a second PR (besides the one I mentioned above) also has misreported status checks. It's a mix of misreported and properly reported status checks, so it's more interesting:

![Screenshot 2019-12-16 12 17 56](https://user-images.githubusercontent.com/1848731/70928023-1dc7a980-1ffe-11ea-973c-ed777d9193e5.png)

Clicking on "Details" for each status check and opening the Cirrus CI page, the builds associated with each status check are:
* Deploy (Staging): https://cirrus-ci.com/build/5447007296028672
* Build Unit Tests: https://cirrus-ci.com/build/5447007296028672
* Preview (Staging): https://cirrus-ci.com/build/5447007296028672
* Promote Image to Prod: https://cirrus-ci.com/build/5447007296028672
* Run Unit Tests: https://cirrus-ci.com/build/5447007296028672
* Build and Push: https://cirrus-ci.com/build/6666649494618112

From just these URLs, we can tell that something's wrong, since the status checks should only show the results from a single build.

Opening build 5447007296028672, every single task is cancelled with the message "Auto-canceled because of a newer PR build!".

In build 6666649494618112, all tasks completed successfully and the manually triggered task is ready to be executed. However, because the wrong build results were reported to GitHub, the PR can't be merged ☹️

**Comment by RDIL** [comment]
Ah, so this is an issue with returning status checks.  I can understand why this could be flaky, since Cirrus may be getting confused with all the different builds and where to send status checks back to.

**Comment by fkorotkov** [comment]
It seems there was a race condition on GH side. Could you please confirm that on Checks tab you see two separate entries for Cirrus on the left hand side?

**Comment by connorbrinton** [comment]
Here's what I have for the first PR:

![Screenshot 2019-12-16 13 00 53](https://user-images.githubusercontent.com/1848731/70930895-4357b180-2004-11ea-8b00-e0faea161b12.png)

And the second PR:

![Screenshot 2019-12-16 13 01 48](https://user-images.githubusercontent.com/1848731/70930911-4b175600-2004-11ea-8f40-5742febec681.png)

**Comment by fkorotkov** [comment]
Interesting. Seems they've fixed it in the UI. From the logs I see two separate GH Check Runs:
1. For the canceled task: https://github.com/cirruslabs/cirrus-ci-docs/runs/350613260
2. For the PR task: https://github.com/cirruslabs/cirrus-ci-docs/runs/350613231

I cannot see the pages since the repo is private but you should be able to see it.

Anyways I know how it can be improved from the Cirrus side and I'm working on a fix.

**Comment by connorbrinton** [comment]
Yeah, it seems GH hides everything it doesn't think is the latest run. Here's what those links look like: 🙂

**Canceled task:**

![Screenshot 2019-12-16 13 16 24](https://user-images.githubusercontent.com/1848731/70931964-9e8aa380-2006-11ea-94a1-eecd3435132d.png)

**PR task:**

![Screenshot 2019-12-16 13 17 12](https://user-images.githubusercontent.com/1848731/70931975-a2b6c100-2006-11ea-857b-95d69c723a45.png)

Thanks for all of your hard work on Cirrus! 😄

**Comment by fkorotkov** [comment]
Got the change ready and will deploy first thing tomorrow morning since today is a code freeze because it's my birthday and want to minimize chances to be paged with tricky changes like this. 😅

**Comment by connorbrinton** [comment]
Sounds great, thanks @fkorotkov! 😄
