### ISSUE TITLE
list of working gcp image_name and image_project

### ISSUE THREAD

**Issue by williamtu** [cirruslabs/cirrus-ci-docs#497]
# Question
Hi,
at the GCP document page 
https://cloud.google.com/compute/docs/images
it lists having
    image_project: ubuntu-os-cloud
    image_name: ubuntu-1904

But when I put it in my .cirrus.yml, it shows the following error:
```
Failed to start: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1904'. The referenced image resource cannot be found.
```
I have to change to use 
 image_name: ubuntu-1904-disco-v20190417
and it works.

Where can I find the list of working image_name?
Thanks!

**Comment by fkorotkov** [comment]
You can either use `image_family: ubuntu-1904` instead of exact `image_name` to get the latest image of the family or use:

```bash
gcloud compute images list --project $ubuntu-os-cloud --no-standard-images
```

to list all available images.

**Comment by williamtu** [comment]
thank you
