### ISSUE TITLE
Clarify docs/marketing site: Github only?

### ISSUE THREAD

**Issue by kylecordes** [cirruslabs/cirrus-ci-docs#503]
This is a "feature request" for the documentation to clarify who the target market (today) is:

From reading around here and in the documentation, I get the impression that Cirrus today works only with Git repositories stored in Github.

Is that true? If so it would be great if it was obvious on the home page of the site: It's a CI tool for your projects on Github. (I think?)

(It seems a little odd, I'm used to a slightly older generation of tools were you could point them to an arbitrary source code repository. )

**Comment by RDIL** [comment]
This is true for now.  I have mixed opinions on adding an explicit notation in the docs however.

**Comment by kylecordes** [comment]
The current experience … is kind of awkward and confusing.

You click a button to try it out. Then slowly figure out that the only path to do so is the GitHub marketplace. Which is super cool if you happened to arrive looking for a GitHub add-on. But confusing if you arrived looking for CI for a thing not in GitHub.

Perhaps on the page where it offers to take you to the GitHub marketplace, right there will be a good place to capture the future interests of visitors whose code is not on GitHub? Let people sign up for a mailing list (right on that page) or something.

**Comment by RDIL** [comment]
That is a nice plan, but in the meantime we have #10 and #9

**Comment by fkorotkov** [comment]
@kylecordes good idea, there are more and more requests for other than GitHub support. Could you please describe your setup at the moment?

* How do you host Git repository? Or use some other VCS?
* Which tool do you use for code reviews?
* How do you prefer to get notifications from a CI? Emails, notifications, integration with some messenger, etc..

**Comment by kylecordes** [comment]
(I am responsible for an array of projects running on different infrastructure etc, but here is my use case at hand.)

I have a project happily running on BitBucket, which has features similar to GitHub (code review and more), plus integration with other Atlassian products - an ecosystem of connected, useful capabilities. All the collaborators, current and likely future, can trivially access this.

Bitbucket has a CI feature, “Pipelines”. Pipelines is Linux-only, and has a limited range of configurability around the size of hardware used to run CI. (BitBucket probably won't displace GitHub as the most popular, but it's not going away, either. Same for GitLab and 20 others ways of hosting a Git repo.)

My project at hand:

* Must also CI on Windows ASAP, hence here I am, looking around.
* Could benefit from CI on Linux on bigger VMs, trivially available on (for example) GCP or AWS.

Being able to plug in Cirrus, have it watch the Git repository, run builds, and send email (or perhaps chat) notifications of the results, would solve my problem at hand. (It's also pretty easy to get a webhook notification from BitBucket, to avoid polling.)

How many people have this same shaped problem? I don't know - but it does provide an avenue by which to get a "nose under the tent" on projects currently using a different CI system.

Of course, juggling priorities in a SaaS product is hard! (Been there, done that.)  I have no idea if effort spent supporting any non-GitHub use cases make sense for Cirrus.
