### ISSUE TITLE
incorrect reference to freebsd-11-3

### ISSUE THREAD

**Issue by Smattr** [cirruslabs/cirrus-ci-docs#504]
# Expected Behavior

To test on FreeBSD 11.3, [the docs](https://github.com/cirruslabs/cirrus-ci-docs/blob/master/docs/guide/FreeBSD.md) describe using `image_family: freebsd-11-3`. This should be a way to boot a usable FreeBSD 11.3 instance.

# Real Behavior

As documented in the comments to #359 (and as I discovered myself) the `freebsd-11-3` image will not boot and is unusable.

# Related Info

Commit dedf23532b3791820c6953d751730a2128bfe23d updated the docs to use the new `image_family` GCP option to specify an up to date FreeBSD image. The motivating issue, #422, specified what should have happened with 11.3 (`image_family: freebsd-11-3-snap`) however it wasn't explicitly called out as an exception so I think it was missed.

Can the docs be updated to reference the snap instead?

**Comment by fkorotkov** [comment]
@Smattr thanks for pointing out about the `-snap` version of `11-3`. Updated the docs in #505. PTAL
