### ISSUE TITLE
VSCode doesn't recognize YAML schema

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#507]
VSCode reports: `$ref '/definitions/windows_container' in https://cirrus-ci.org/ can not be resolved.(768)` on any `task` definition.

**Comment by fkorotkov** [comment]
Was it working before? The schema hasn't changed in a while https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/cirrus.json#L1395-L1429

**Comment by RDIL** [comment]
Actually it wasn't

**Comment by fkorotkov** [comment]
Then could you please provide your VSCode version and a plugins that you use use if any?

**Comment by RDIL** [comment]
VSCode `theia@latest` with plugins `java`, `python`, `scala`, and `markdown`

**Comment by fkorotkov** [comment]
Don't think it anything that Cirrus can fix. The schema is valid and work in IntelliJ.
