### ISSUE TITLE
Add `docker_builder` support for Windows-based images

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-docs#51]
Hello, just discovered the following problem, that with a basic `.cirrus.yml` setup containing the `docker_builder:` keyword it is not possible to build windows-based docker images. 

~~~{.yml}
docker_builder:
  only_if: $CIRRUS_BRANCH == 'master'
  env:
    DOCKER_USERNAME:  ENCRYPTED[...]
    DOCKER_PASSWORD: ENCRYPTED[...]
  build_script:
    - docker build --tag <...> .
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script:
    - docker push <...>
~~~

Is there a keyword that I forgot or is it not supported yet that cirrus is able to build windows-based (and maybe mac/darwin-based as well?) docker images?  Because the cirrus-ci build gives me the following error message: 

~~~{.sh}
Step 1/3 : FROM cirrusci/windowsservercore:2016
2016: Pulling from cirrusci/windowsservercore
// ...
image operating system "windows" cannot be used on this platform
~~~

**Comment by fkorotkov** [comment]
@ppaulweber I think `platform` and `os_version` can help you:

```yaml
docker_builder:
  platform: windows
  os_version: 2016
  only_if: $CIRRUS_BRANCH == 'master'
```

**Comment by ppaulweber** [comment]
@fkorotkov thank you for your fast reply!

perfect, it works
