### ISSUE TITLE
Linux tasks not running

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#512]
Couldn't find a status page to confirm, but it looks like Linux tasks are not running, while macOS tasks are:
https://cirrus-ci.com/build/5005733657051136

The linux tasks remained scheduled indefinitely (up to 24 minutes before pushing again with the same result)

**Comment by fkorotkov** [comment]
@mmcc007 it's not possible to have `+` in a Docker tag. Your image is configured incorrectly for Linux builds. Please use `v1.9.1-hotfix.6` instead of `v1.9.1+hotfix.6`. 🙌

**Comment by fkorotkov** [comment]
Related to https://github.com/flutter/flutter/issues/35470

**Comment by mmcc007** [comment]
Working now. Thanks for rapid response!
