### ISSUE TITLE
Only run task via API

### ISSUE THREAD

**Issue by SeanTAllen** [cirruslabs/cirrus-ci-docs#515]
# Description

I'm looking to be able to only run tasks when they are triggered by API. Not through any other means. I imagine this would be used as part of an `only_if` check for the task.

# Context

I'm trying to do a "scheduled" job for Pony nightly builds that get uploaded to Cloudsmith. As there is no "cron" support yet in Cirrus, this is what I was planning:

- GH action using "on schedule" that gets triggered once a day
- GH action sends API request to Cirrus to run the nightly build and upload task

Everything about this is very straightforward to me except for 1 thing.

How can I not have the task to build and upload not be triggered by anything except for the API call? I don't want it to run on pushes to any branch nor on PR.

**Comment by RDIL** [comment]
You could have your actual cirrus config do nothing, and then have the API calls overwrite the config with the real version...

**Comment by SeanTAllen** [comment]
@RDIL that sounds like a god awful hack to address what is, in the end, a workaround for a feature that isn't in place yet. We have tasks that Cirrus runs on PR. I have no idea how we would go about making that do nothing and then overwrite. I don't want to explore that idea. I'd rather not run the given job in CirrusCI if that is what was needed.

**Comment by fkorotkov** [comment]
As discussed in the support email I'll add CIRRUS_API_CREATED environment variable.

**Comment by SeanTAllen** [comment]
Thanks, @fkorotkov.

**Comment by LecrisUT** [comment]
Is this still working? I have tried to run this, but the tasks never get triggered when I submit builds:
```yaml
macos_arm64_task:
  name: Build macOS arm64 wheels.
  only_if: $CIRRUS_API_CREATED == "true"
```

```graphql
mutation CreateBuild($repoID: ID!) {
  createBuild(
    input: {repositoryId: $repoID, branch: $branch, clientMutationId: "test_mutation_id"}
  ) {
    build {
      id
      status
    }
    clientMutationId
    }
}
```
