### ISSUE TITLE
Ability to delete logs

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-docs#52]
Hello @fkorotkov, I've another issue I want to address by asking if it is possible in anyway to delete failed task build logs from https://cirrus-ci.com? E.g. a task build carries sensitive information and data due to a incorrect/invalid `.cirrus.yml` configuration setup.

**Comment by fkorotkov** [comment]
@ppaulweber could you please email support@cirruslabs.org with details about the task. Will take care of it manually but we need to implement such functionality for repository owners.

**Comment by ppaulweber** [comment]
Perfect, thank you! I'll send you a proper email right away containing the task reference link.

**Comment by fkorotkov** [comment]
Filtering out the secrets was added a while ago. Closing this issue since don't see if there is a separate need to delete logs.
