### ISSUE TITLE
Prioritize tasks with `allow_failures: false`

### ISSUE THREAD

**Issue by eksperimental** [cirruslabs/cirrus-ci-docs#524]
# Description
Give priority to tasks that do not accept failures,

As a second request, tasks with `allow_failures: true` and `skip_notifications: true`  should be executed after those with only ~`allow_failures: true`~`allow_failures: false`

# Context

There are tasks are do not make use of the `allow_failures` option, and need to wait for those with `allow_failures: true` to finish in order to start.
...

**Comment by fkorotkov** [comment]
It seems you can leverage `depends_on` for controlling the execution: https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies

**Comment by eksperimental** [comment]
It will not work, as the task names as generated dynamically  based on variables,
We only have 2 main tasks, and matrices.
How would that work in this situation?
https://github.com/elixir-lang/elixir/blob/1f62a456d126f106c5b357fe26cfbd557c7a7032/.cirrus.yml

**Comment by eksperimental** [comment]
Alternatively we could have a "weight" field, were we can push down the ones that we want to be executed later.

**Comment by RDIL** [comment]
I agree a weight field would be helpful

**Comment by fkorotkov** [comment]
Could you please elaborate why `allow_failues: true` need to be executed first? Haven't seen such a use case. 

In the menatime I think I know how the config should look like. Let me try it out and will send a PR.

**Comment by eksperimental** [comment]
> Could you please elaborate why `allow_failues: true` need to be executed first? Haven't seen such a use case.

LAST! not first. Sorry if I was not clear. Because those are the ones I care the less, and sometimes the ones that always fail

**Comment by eksperimental** [comment]
@fkorotkov sorry, there was a type in my text, I already corrected it.

**Comment by RDIL** [comment]
No, @eksperimental said it in the first sentence of the issue...

> # Description
> Give priority to tasks that do not accept failures,

**Comment by eksperimental** [comment]
> No, @eksperimental said it in the first sentence of the issue...
> 
> > # Description
> > Give priority to tasks that do not accept failures,

true, but the second paragraph was ambiguous as it had a typo

**Comment by fkorotkov** [comment]
Arbitrary weights will be a bit hard to implement but looks like a good candidate for a feature request for the future. ;-)

@eksperimental how would you describe such tasks that are OK to fail? Sanity checks?

**Comment by eksperimental** [comment]
In our case I would describe them as "nightly builds" and "maintenance branches"

**Comment by fkorotkov** [comment]
Created https://github.com/elixir-lang/elixir/pull/9585 to see if that works for you

**Comment by fkorotkov** [comment]
Closing this but please feel free to open a feature request about weights.
