### ISSUE TITLE
Regular Expression in auto_cancellation is not working

### ISSUE THREAD

**Issue by eksperimental** [cirruslabs/cirrus-ci-docs#526]
# Expected Behavior

`  auto_cancellation: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH !=~ 'v\d+\.d+.*'`

my branch is `v2.0`, and auto_cancellation is triggering.
see the live example
https://cirrus-ci.com/github/eksperimental/elixir/v2.0

**Comment by eksperimental** [comment]
Btw, what programming language are you using to evaluate the expressions?

**Comment by fkorotkov** [comment]
@eksperimental I think you are missing `\` before `d`. 😅

**Comment by eksperimental** [comment]
oh! how did I miss that one.
All good. it works now, thank you @fkorotkov
