### ISSUE TITLE
Add information for every task: Memory, CPU, Image, etc.

### ISSUE THREAD

**Issue by eksperimental** [cirruslabs/cirrus-ci-docs#529]
# Description

Add the memory, cpu and full name of the image that is being used. Even if the default values are used.

# Context
This comes from this PR,  where I was asked why did I choose that particular memory value. 
https://github.com/elixir-lang/elixir/pull/9599#pullrequestreview-322784949

The truth is that is the minimum, but I cannot tell what is the default value for it, in case I don't set any.

# Anything Else
any other field that I'm missing and that can be set and can be shown here would be useful

**Comment by fkorotkov** [comment]
Fixing in https://github.com/cirruslabs/cirrus-ci-web/pull/137
