### ISSUE TITLE
Missing environment variable to get base branch of pull requests

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#53]
Hi,

The base branch targeted by the merge of a pull request should be available through an environment variable, for example `CIRRUS_PR_BASE_BRANCH`. It should be unset or empty when build does not relate to a pull request.

The similar variable at Travis is `TRAVIS_BRANCH `, which has a special meaning when build is initiated from a pull request ([doc](https://docs.travis-ci.com/user/environment-variables)).

(contrary to #47 I double-checked that the variable does not exist yet!)

**Comment by simonbrandhof** [comment]
For information this variable would allow SonarQube and https://sonarcloud.io to analyze pull requests.

**Comment by fkorotkov** [comment]
Will add it as 'CIRRUS_BASE_BRANCH' later today since it can be just a push as well. You'll need to check for 'CIRRUS_PR' in that case as well to make sure it's a pr. Does it work for you?

**Comment by simonbrandhof** [comment]
Perfect, thanks.

**Comment by fkorotkov** [comment]
It is available now! Extra bonus is `CIRRUS_BASE_SHA` which point to the SHA from which a PR was created.
