### ISSUE TITLE
Filler word "simply" appears multiple times in documentation

### ISSUE THREAD

**Issue by sio** [cirruslabs/cirrus-ci-docs#537]
"Simply" appears multiple times in Cirrus documentation: https://github.com/cirruslabs/cirrus-ci-docs/search?q=simply&unscoped_q=simply

Most of the time that word does not add any meaning to the sentence and may be safely omitted. In some contexts that word may cause negative emotional response from readers. [This article](https://www.knowledgeowl.com/home/dont-say-simply-jim-fisher) contains a good description of all the problems with the word "simply"

I suggest to remove most of the current occurrences of that word from Cirrus docs.

**Comment by RDIL** [comment]
Agreed. I’ll take care of it.

**Comment by fkorotkov** [comment]
Fixed in #538. Thanks, @RDIL
