### ISSUE TITLE
Better handling of invalid docker image names

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-docs#540]
# Expected Behavior

If you provide an invalid Docker image name &mdash; in my case, I accidentally used `nodejs:current-buster-slim` instead of `node:current-buster-slim` &mdash; it would ideally fail quickly and tell you the image couldn't be found.

# Real Behavior

What ended up happening was it sat there for 15 minutes, then said this:

```
ImagePullBackOff: Back-off pulling image "nodejs:current-buster-slim"
```

Which... doesn't actually explain what the problem was! When debugging, I tried to use it locally, which gave this output which explained what was happening:

```
docker: Error response from daemon: pull access denied for nodejs, repository does not exist or may require 'docker login'.
```

# Related Info

(I'm not entirely sure how to fill out this section for this particular issue. Sorry about that!)

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: DockerLinux
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Changed message to more human friendly. The change will be auto-deployed in the next few hours.
