### ISSUE TITLE
Rename community cluster

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#542]
Right now, the way it is phrased, it sounds like you have two options:
* Use Cirrus on your own compute service
or,
* Have your builds run on the community cluster
I feel like the term "community cluster" doesn't match what it really is.  While it may be Cirrus's machine pool, it makes it *sound like* the place that everybody in the Cirrus CI community is stuck with, crammed together, which may need "compute credits" for your builds to be first in the aforementioned pool.

"Community cluster" doesn't explain a lot in its name and the docs don't really help.  I think "Cirrus CI's Machine Pool" sounds much better, and a lot less condescending.

**Comment by fkorotkov** [comment]
Or something like "Infrastructure managed by Cirrus Labs" since  there is an option to "Bring your own infrastructure". 🤔

**Comment by RDIL** [comment]
That works.  I also feel like for the sake of minimizing the bundle size, we should put the TLDR from the compute credit page on the docs.

**Comment by fkorotkov** [comment]
Rereading this issue I don't think Community Cluster term is not accurate

> sound like the place that everybody in the Cirrus CI community is stuck with, crammed together, which may need "compute credits" for your builds to be first in the aforementioned pool.

This ^^ exactly what it is. Community clusters are limited and used by everyone and compute credits can buy priority and access to additional capacity in case main pools of machines are overwhelmed by all the free builds from community.

Will keep the issue open to gather more feedback in case anyone what to comment about the clarity of Community Cluster term.
