### ISSUE TITLE
Github checks only showing subset of builds

### ISSUE THREAD

**Issue by tlambert03** [cirruslabs/cirrus-ci-docs#546]
Recently, our github checks have only been showing a subset of our cirrus checks.  I'm wondering if something changed in the implementation of the checks API at cirrus, or if we need to update our yml file instead.  Specifically: we have a build pipeline with 3 OSes and 2 python versions.  Github used to show all 6 checks, but now shows only 3 (one per os).

Here's an example of the checks in a github PR: https://github.com/tlambert03/napari/pull/1/checks?check_run_id=354838912

here's the corresponding build at cirrus:
https://cirrus-ci.com/build/6261573596741632

thanks!

## Expected Behavior

was expecting the full matrix expansion of OS & python version to show up in github checks.

## Real Behavior

only 1 check per OS shows in github

**Comment by fkorotkov** [comment]
Oh. Seems it's a side effect of additional fixes for #493 that got deployed this night (about 12 hours ago). Let me try to find out the issue.

**Comment by tlambert03** [comment]
ahh!  sorry I missed that issue.  Thanks for your help

**Comment by fkorotkov** [comment]
It was impossible of you to find the issue. 😅 I've identified the case that wasn't tested and therefore was missed during the internal refactoring which caused the regression. Just deployed a fix and new builds should appear accordingly. Sorry for the inconvenience!

**Comment by tlambert03** [comment]
thanks so much!  that did it!
