### ISSUE TITLE
Does HTTP cache persist between builds

### ISSUE THREAD

**Issue by abitrolly** [cirruslabs/cirrus-ci-docs#549]
https://cirrus-ci.org/guide/writing-tasks/#http-cache persists between tasks during one build. It is not clear if it persists between builds. Persistence between builds seems dangerous, because 3rd party PR can then poison cache with their own content.

**Comment by fkorotkov** [comment]
Yes, its's the same mechanism that [cache instruction](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction) is using.

**Comment by abitrolly** [comment]
> Tasks for PRs upload caches to a separate caching namespace to not interfere with caches used by other tasks.

Ok. That sounds save.
