### ISSUE TITLE
Git package install fails on freebsd-11-3-snap

### ISSUE THREAD

**Issue by seladb** [cirruslabs/cirrus-ci-docs#551]
My CI job was running fine and it suddenly stopped working. It fails when trying to install Git with this error message:

```
[1/29] Fetching git-2.24.1.txz: .......... done
pkg: cached package git-2.24.1: size mismatch, fetching from remote
[2/29] Fetching git-2.24.1.txz: .......... done
pkg: cached package git-2.24.1: size mismatch, cannot continue
Exit status: 3
```

This happens only in `freebsd-11-3-snap` image. The other FreeBSD image I'm using `freebsd-12-0` still runs ok.

Please find the CI script and failed job below.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: FreeBSD
  - Task name: https://cirrus-ci.com/task/5340716401688576
  - Script/cache name (if applies): https://github.com/seladb/PcapPlusPlus/blob/master/.cirrus.yml

**Comment by fkorotkov** [comment]
Seems the image got updated today:

```
NAME                                  PROJECT                FAMILY             DEPRECATED  STATUS
freebsd-11-3-stable-amd64-v20191226   freebsd-org-cloud-dev  freebsd-11-3-snap              READY
```

Google [recommends](https://forums.freebsd.org/threads/pkg-1-3-0-size-mismatch-cannot-continue.47444/) to try to run `pkg update` 🤔

**Comment by seladb** [comment]
Should I run `pkg update` from the CI job itself?

**Comment by fkorotkov** [comment]
Seems so. I'm trying it on a fork right now. Will create a PR if will work.

**Comment by fkorotkov** [comment]
Nope. Didn't work. 🤔

**Comment by seladb** [comment]
any suggestions on how to solve this? there are few PRs I'm trying to merge which fail because of this

**Comment by fkorotkov** [comment]
Seems `pkg update -f` helps with the install step https://github.com/seladb/PcapPlusPlus/pull/348

**Comment by seladb** [comment]
Seems to be working, thanks! In my case I actually don't have to install git, but I'll add the `pkg update -f` step anyway
