### ISSUE TITLE
Wish for a Cirrus master-status GitHub check

### ISSUE THREAD

**Issue by amirh** [cirruslabs/cirrus-ci-docs#554]
# Description
We find it useful to prevent users from merging PRs while the latest master CI status is not "success".

For example on `flutter/flutter` and `flutter/engine` this is enforced by a custom service that queries the master status of all relevant CI systems and publishes the status to all open PRs ([code here](https://github.com/flutter/cocoon/blob/27952e2aebc732bdb7cf01a89125b2d12fac816d/app_dart/lib/src/request_handlers/push_build_status_to_github.dart)).

For repositories where the only CI service is Cirrus (e.g `flutter/plugins`) it will be useful to have an off-the-shelf feature that publishes the Cirrus status on master to all open PRs.

**Comment by fkorotkov** [comment]
Might be a good candidate for a [Cirrus Action](https://github.com/cirrus-actions) to make it work with any App that uses Checks API. 🤔

**Comment by fkorotkov** [comment]
Fixed via https://github.com/cirrus-actions/branch-guard. You can try the configuration fro ReadMe.

**Comment by fkorotkov** [comment]
The action is now deprecated since it's not working properly with PRs from forks because of GitHub Actions restrictions. I've re-implemented the logic via GitHub App which is available here: https://github.com/cirruslabs/gh-submit-queue

**Comment by amirh** [comment]
🎉 

It shows as a private app when I try to install it:

![image](https://user-images.githubusercontent.com/1024117/76724882-bc50cd00-6709-11ea-9cd9-d6fa46c76f29.png)

**Comment by fkorotkov** [comment]
@amirh whoops! It's public now. 😅
