### ISSUE TITLE
Can't set badge for my project

### ISSUE THREAD

**Issue by giampaolo** [cirruslabs/cirrus-ci-docs#555]
Hello. I just discovered your great service. I would like to use it to test psutil project on FreeBSD. I am having troubles visualizing the badge. I am using:
https://api.cirrus-ci.com/github/giampaolo/psutil-cirrus-ci.svg
Thanks in advance for any help.

**Comment by fkorotkov** [comment]
You don't have any build for you default branch. Once you have a `master` build you'll see a badge. 

See https://api.cirrus-ci.com/github/giampaolo/psutil-cirrus-ci.svg?branch=cirrus-ci
