### ISSUE TITLE
Print a timestamp on each log line

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-docs#557]
If a task times out, it can be hard to tell which piece of the task led to the timeout.  For example, we're seeing timeouts of a task that does some git fetches and other downloads from the internet, but we're not sure which one is causing the timeout (e.g. if the first one took a lot of time leaving none for the later ones, or if the last one took a long time).

It'd be great if logs automatically prepended a timestamp.

**Comment by dnfield** [comment]
@fkorotkov - we're running into some issues that might be timing related again and this would be helpful. Any idea on whether this could be added?

**Comment by fkorotkov** [comment]
Created https://github.com/cirruslabs/cirrus-ci-agent/issues/67 to add it on the agent side

**Comment by JeremyRand** [comment]
Was this fixed by https://github.com/cirruslabs/cirrus-ci-docs/pull/754 , or is there anything remaining?

**Comment by fkorotkov** [comment]
Forgot to close the issue. @JeremyRand, thanks for reminding!
