### ISSUE TITLE
Cross platform, independent tasks to share volume

### ISSUE THREAD

**Issue by am11** [cirruslabs/cirrus-ci-docs#558]
I am trying to crossgen some .NET libraries for FreeBSD on Linux, such that:

1. Linux task will checkout sources and crossgen the managed parts of .NET runtime for FreeBSD on Linux.
  a. subsequently create a tarball out of artifacts
2. FreeBSD task, that depends on Linux task, will then execute and extract the tarball, build compile native components (using clang/gcc)
  a. subsequently create a tarball out of managed+native component
  b. push to GitHub releases

So far, what I have understood is that I would need to push the intermediate tarball (from 1a above) to an external/temporary storage (GitHub release) for sharing between interdependent tasks. However, reading this section: https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies, it sounds like we do not need to tar out artifacts (`1a` is unnecessary). Which of the following is true:

* Will FreeBSD task just see those artifacts in the mounted volume at the same location Linux task was seeing? CirrusCI mounts the volumes behind the curtain?
* Aforementioned doc section assumes we are on the same operating system (both FreeBSD or both Linux etc.), and we would need to incorporate external storage?

.. just trying to find out a clean solution and reduce moving parts. 😅

**Comment by RDIL** [comment]
I'm pretty sure it won't be mounted in the same location, and believe that if you did want to persist them between tasks, would need external storage.

**Comment by fkorotkov** [comment]
Hey @am11, Cirrus doesn't mount workspaces between tasks. Cirrus only does something similar for [Docker Pipes](https://cirrus-ci.org/guide/docker-pipe/).

In your case you'll need to use a temporary storage but it should no be necessary an external one. Cirrus has couple of options but I think 
 built-in [HTTP Cache](https://cirrus-ci.org/guide/writing-tasks/#http-cache) will work best for you. You can upload your tarball using `$CIRRUS_BUILD_ID` as a key from your Linux task and then download it using the same key from FreeBSD task.

**Comment by am11** [comment]
Thanks @fkorotkov! HTTP Cache approach worked.
