### ISSUE TITLE
Incorrect Bundler directory for cache

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#559]
# Expected Behavior

`/usr/local/bundle` directory for Bundler cache in the `writing-tasks` documentation page.

# Real Behavior

`/usr/bin/bundler` directory.

# Related Info

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/

**Comment by fkorotkov** [comment]
Don't hesitate to open a PR to fix the documentation. ;-)

**Comment by AlexWayfer** [comment]
I thought about this, but maybe you know a sacred meaning of this…

**Comment by AlexWayfer** [comment]
For example, I guess there is a separate directory for gems from git-source, which is triggering neighboring issue #560.

But if there will be a single directory with fixed installing — I'll fix the documentation myself.
