### ISSUE TITLE
Correct cache for git-gems from `Gemfile`

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#560]
# Expected Behavior

Repeatedly passing tasks for cache from `Gemfile` with gems from git sources.

# Real Behavior

Fails after cache-hit:

```
bundle exec rake
bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
Bundler::GitError: The git source git://github.com/AlexWayfer/flame.git is not yet checked out. Please run `bundle install` before trying to start your application
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git/git_proxy.rb:235:in `allowed_in_path'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git/git_proxy.rb:192:in `find_local_revision'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git/git_proxy.rb:64:in `revision'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git.rb:225:in `revision'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git.rb:93:in `install_path'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/path.rb:126:in `expanded_path'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/path.rb:163:in `load_spec_files'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git.rb:200:in `load_spec_files'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/path.rb:100:in `local_specs'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/source/git.rb:167:in `specs'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:758:in `block in converge_locked_specs'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:744:in `each'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:744:in `converge_locked_specs'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:247:in `resolve'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:170:in `specs'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:237:in `specs_for'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:226:in `requested_specs'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:108:in `block in definition_method'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:20:in `setup'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

# Related Info

- [x] Task issue
  - OS: DockerLinux
  - Task name: any
  - Script/cache name (if applies): Bundler (Ruby)

I have such config in `.cirrus.yml`:

```yaml
bundle_cache:
  folder: /usr/local/bundle
  fingerprint_script:
    - cat .cirrus*
    - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
    - ruby -v
    - cat Gemfile
    - cat *.gemspec
  populate_script: bundle update
```

And such `Gemfile`:

```ruby
# frozen_string_literal: true

source 'https://rubygems.org/'

gemspec

gem 'flame', github: 'AlexWayfer/flame'
```

And the task `bundle exec (rake)` account `Gemfile`, but I guess gems from `github` source lost for later runs, after the first.

Example: https://cirrus-ci.com/task/6256937859809280

Successful first run and failed second.

**Comment by RDIL** [comment]
What is your rubygems version?

**Comment by AlexWayfer** [comment]
> What is your rubygems version?

I guess, standard. You can see `.cirrus.yml` in the https://github.com/AlexWayfer/flame-flash

**Comment by AlexWayfer** [comment]
I've understood something: when we have a repo with `Gemfile`, any `bundle install` (or `update`) generates `Gemfile.lock`, and `bundle exec` will not work without `Gemfile.lock`. So, we should cache it alongside gems folder!

Can you please make `cache:folder` accepting array? For now it expects only strings: https://cirrus-ci.com/build/6341117088104448

**Comment by AlexWayfer** [comment]
The "Cache" documentation for now has example like `fingerprint_script: cat yarn.lock`, and it's appropriate for end-chain applications, but not for libraries. Libraries (on Ruby or JavaScript) in opinion of many people should commits dependencies (like `Gemfile` or `package.json`), but not locks (like `Gemfile.lock` or `package-lock.json` or `yarn.lock`). But we need for them when extracting cache.

**Comment by AlexWayfer** [comment]
For example, GitLab CI has `paths` inside `cache`: https://docs.gitlab.com/ee/ci/yaml/README.html#cachepaths

**Comment by RDIL** [comment]
Bundler actually recommends you commit your lockfile so you don’t need to
keep regenerating it.
-- 
- Reece Dunham

Software engineer.
Email: me@rdil.rocks
GitHub: https://github.com/RDIL

**Comment by AlexWayfer** [comment]
> Bundler actually recommends you commit your lockfile so you don’t need to keep regenerating it.

It's a new suggestion from Bundler team, but not the single option. You can see https://github.com/rubygems/bundler-site/pull/501

**Comment by AlexWayfer** [comment]
I've worked with repositories including `Gemfile.lock` file. There are too many conflicts on checkouts and pulls. Also gem maintainers should configure uncommon CI job, like daily, with `Gemfile.lock` deletion. Seems like a hack, work-around.

**Comment by fkorotkov** [comment]
@AlexWayfer thanks for finding the GitLab config. Update documentation in https://github.com/cirruslabs/cirrus-ci-docs/pull/573 for future researches. Sorry we didn't have enough expertise at the moment to help you right away. 😪

**Comment by AlexWayfer** [comment]
Thank you. I thought about such solution today and planned to test. I'll write results later (confirm or correct the solution).

**Comment by AlexWayfer** [comment]
It works, example: https://github.com/AlexWayfer/flame-flash/pull/34

Even after `git commit --amend` (it broke builds with previous config).
