### ISSUE TITLE
Logs get lost if task section was not expanded

### ISSUE THREAD

**Issue by am11** [cirruslabs/cirrus-ci-docs#561]
For example: https://cirrus-ci.com/task/6351885275758592

Expanding `install packages` node shows nothing, although the job ran for ~40 seconds; and download full log is 404: https://api.cirrus-ci.com/v1/task/6351885275758592/logs/install%20packages.log.

If we pre-expand all the tasks sections, then the logs are always persisted.

I have noticed this flakiness quite a few times.

**Comment by fkorotkov** [comment]
@am11 did you see it only on FreeBSD? Or also on Linux tasks?

**Comment by am11** [comment]
On Linux as well, even on the passing builds, e.g. https://cirrus-ci.com/task/5651143124582400, `checkout repos` logs are empty.

**Comment by RDIL** [comment]
It wouldn't have not kept the logs just because the drawer wasn't open.  Opening the drawer forces relay to fetch the logs, but they would have to be on the server in the first place for that to work, so it isn't not opening the drawers' fault.  My guess is the server didn't receive the logs from the container.

**Comment by am11** [comment]
Assuming each task runs in a separate container on Linux (and jail in FreeBSD)? Because in the previous link, if you expand other sections, you see the logs. So they get intermittently dropped at "task" boundary (not sure if that maps 1:1 with container or just a script output mapped to certain fd).

**Comment by am11** [comment]
This behavior is a slightly more mysterious. Even in the "expanded" accordion state, if we get to see the logs once, it is not guaranteed that they will persist. After refreshing the page the logs can go away, which is what happened here: https://cirrus-ci.com/task/4651506867634176. (it's basically a huge loss of effort and time) :(

**Comment by fkorotkov** [comment]
Logs streaming was rewritten since the issue to simplify the logic and make it more resilient for network failures. Please let me know if the issue persists.
