### ISSUE TITLE
cirrus-ci-agent leaves zombie/defunct children

### ISSUE THREAD

**Issue by sio** [cirruslabs/cirrus-ci-docs#564]
Looks like `cirrus-ci-agent` process cleans up after its children only if they were started by the agent itself. The grandchild processes that were passed on from terminated children are left in zombie state (`<defunct>`).

**Expected behavior** is for `cirrus-ci-agent` [to do a `wait(2)` promptly](https://en.wikipedia.org/wiki/Zombie_process) on any of its zombie children so they could be removed from the process table. Since it's being executed as PID 1, it must behave responsibly and clean up all the zombies. Alternative solution would be to allow users to run real init as PID 1, e.g. systemd, but that would probably complicate matters too much.

**Real Behavior** is lots of `<defunct>` process entries at the end of CI run.

---

Here is the smallest possible demo I could think of: [demo task](https://cirrus-ci.com/task/6243657065955328?command=demo#L12)

- We create a child (`bash`) and a grandchild (`/bin/sleep`) of `cirrus-ci-agent`
- The child dies first and `/bin/sleep` gets inherited by `cirrus-ci-agent` because it is PID 1
- When `/bin/sleep` terminates, it is left in zombie state because `cirrus-ci-agent` never calls `wait(2)` on it: 
```1   317 root       -     0 Z    12:46:45 [sleep] <defunct>```

This leads to an unreasonable failure of tasks that require termination of certain other processes started previously. For example, libvirtd can never cleanly shutdown the virtual machine ([process table](https://cirrus-ci.com/task/6022308091396096?command=kvm_debug#L50), [libvirtd error](https://cirrus-ci.com/task/6022308091396096?command=libvirtd#L11)) - because `qemu-kvm` is a zombie.

I wasn't sure where to submit this, it seems that the agent is not open source yet - feel free to forward this report to proper venue.

**Comment by sio** [comment]
[Related article](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/amp/) and correct terminology: zombie reaping. They also show a Python micro init that can be used as a solution example

**Comment by sio** [comment]
It seems that you use Docker as container runtime - that means there is a rather straightforward fix for this issue.

For quite a while `docker run` comes with `--init` flag that enables a micro init process inside the container - to mitigate issues exactly like this one. So the changes on your side might be as small as modifying the default container launch command. You'll probably want to make that optional though, e.g. with a key in `.cirrus.yml`

Unfortunately, there appears to be no workaround that users can implement themselves:

- Wrapping all commands in explicit bash sessions (as suggested by @fkorotkov in email) does not mitigate double-forking technique traditionally employed by Linux daemons to become owned by PID 1. Also, it does not help with the demo task, because orphan processes are always adopted by PID 1, not the next-grandparent-still-alive.
- PID 1 can not be replaced by user because container launch is not exposed in `.cirrus.yml`
- Injecting code into running PID 1 appears to be impossible (and that's probably for the better):
  - DLL injection is not possible because `cirrus-ci-agent` is built statically
  - ptrace injection is not possible because of kernel configuration (`/proc/kernel/yama/ptrace_scope = 1` and is not writeable)

**Comment by fkorotkov** [comment]
Fixed via setting [`shareProcessNamespace` for Kubernetes pods](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/)  Cirrus creates.

**Comment by sio** [comment]
Thank you very much! Both demo task and libvirtd now work correctly.

**Comment by fkorotkov** [comment]
Awesome! Thanks for finding it out and providing such a good case for reproducing! 🙌
