### ISSUE TITLE
Enforce timeout for cache fingerprint_script and populate_script

### ISSUE THREAD

**Issue by jmagman** [cirruslabs/cirrus-ci-docs#566]
# Expected Behavior

If cache instruction `fingerprint_script` or `populate_script` take longer than the timeout, the task should fail.

# Real Behavior

The task for more than an hour until it was killed.
https://cirrus-ci.com/task/5564829196877824

# Related Info

From flutter #hackers-infa discord channel:
@fkorotkov: "Yes, please create an issue for a timeout for fingerprint_script. Cirrus agent is not enforcing it."

**Comment by fkorotkov** [comment]
This should be fixed now
