### ISSUE TITLE
Re-try cache download/unarchiving on failure

### ISSUE THREAD

**Issue by jmagman** [cirruslabs/cirrus-ci-docs#567]
# Description

Re-run task or re-download if cache download/unarchiving fails.  Currently the task may fail in the cache step with unarchiving EOF failure.

# Context

Currently the task may fail in the cache step with unarchiving EOF failure.

# Anything Else

From flutter #hackers-infa discord channel:
@fkorotkov: "Also it seems reasonable to re-try downloading cache in case EOF before downloading all bytes. But this should not happen frequently and other Mac tasks seems downloaded this cache entry without issues."

**Comment by fkorotkov** [comment]
This should be fixed now

**Comment by christopherfujino** [comment]
Here's a linux example of the cache download failing twice https://cirrus-ci.com/task/6022821033803776?command=pub#L67

**Comment by fkorotkov** [comment]
I don't think it's freezable to try more than once. In your case it seems there is a race condition and Google Storage throws on read because some other tasks re-uploads a cache entry. Consider using #569
