### ISSUE TITLE
Windows container `Agent is not responding!`

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-docs#57]
Hello, I've the following problem: With the setting depicted below the task build always results into a `Failed in 43:43` state with the message  `Agent is not responding!`. My docker image (lets call it `foo/bar`) is based on `cirrusci/windowsservercore:2016` and is 7GB large. Any suggestions?

~~~{.yml}
# ...
win_task:
  depends_on: coverage
  windows_container:
    image: foo/bar
    os_version: 2016
    cpu: 4
# ...
~~~

I assumed that the agent cannot be started due to the huge docker image size, so I've tried a configuration parameter `disk: ...` but this results in another `Failed in 00:00` state with the message `FAILED_PRECONDITION: Unknown field disk on 'windows_container' YAML node!`. Why is it possible to set the `cpu:` parameter but not the `memory:` and `disk:` parameter just like with `linux` containers?

~~~{.yml}
# ...
win_task:
  depends_on: coverage
  windows_container:
    image: foo/bar
    os_version: 2016
    cpu: 4
    disk: 20
# ...
~~~

**Comment by fkorotkov** [comment]
@ppaulweber could you please provide an id of a task that failed? Most likely it's an issue with Azure not able to download the image and start it in time. Is it a public image by any chance?

**Comment by ppaulweber** [comment]
@fkorotkov yes it is public, e.g. the task id of this problem with [4717797846286336](https://cirrus-ci.com/task/4717797846286336). 
Is there a way to determine the Azure start-up problem? Logfiles etc.?

**Comment by fkorotkov** [comment]
@ppaulweber seem there is something funky with `PATH`. `powershell.exe` isn't found. Maybe https://github.com/casm-lang/casm-lang.container.windows/pull/1 will fix it? Seems you are missing `;` when extending `PATH`.

**Comment by ppaulweber** [comment]
@fkorotkov it worked. Thanks!
