### ISSUE TITLE
Checks annotations sent twice

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#570]
# Expected Behavior

Only sent once

# Real Behavior

Sent twice

# Related Info

https://github.com/cakebotpro/cakebot/pull/91

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
I've checked logs and Cirrus reported 5 annotations to GitHub APIs. Have a suspicion that this was related to a GitHub incident that was yesterday. Will close issue for now. 😪If you'll see another occurrences please reopen.

**Comment by RDIL** [comment]
It happened again in a private repository
