### ISSUE TITLE
docs as artifacts

### ISSUE THREAD

**Issue by kne42** [cirruslabs/cirrus-ci-docs#574]
We are experimenting with uploading built docs as artifacts so that developers can preview docs from PRs easily.

Two things would make this a lot nicer:
- add an option to not force download artifacts. this would allow html to be rendered in the browser instead of having to download the entire folder
- ability to flatten empty nested directories e.g. `docs/build/html` to just `docs`

**Comment by fkorotkov** [comment]
`allow html to be rendered` is tricky from a security perspective. We'll need a separate domain for that to work. 🤔 Do you use GitHub Pages?

And for the second part there is #548.

**Comment by RDIL** [comment]
@fkorotkov I like the idea, I'll buy one right now

**Comment by RDIL** [comment]
Trying to decide between `cirrus-artifacts.dev` or `cirrus-artifacts.app`

then again if you want to buy it thats perfectly fine

**Comment by RDIL** [comment]
Apologies if I'm coming off in a controlling way

**Comment by fkorotkov** [comment]
Yes, please don't buy domains with Cirrus in it. 😅🙃

**Comment by RDIL** [comment]
Ok
