### ISSUE TITLE
Support swap space

### ISSUE THREAD

**Issue by tsao-chi** [cirruslabs/cirrus-ci-docs#576]
# Description

Support swap space

# Context

One of my open source projects requires a lot of memory to build.

**Comment by fkorotkov** [comment]
@tsao-chi more than 24G!? 😅 😲

**Comment by fkorotkov** [comment]
When you bring your own infrastructure you can use up to 11TB of memory with for example [M2 machines on GCP](https://cloud.google.com/compute/docs/machine-types#m2_machine_types). Also macOS VM have 8G of RAM and support swapping.
