### ISSUE TITLE
Support pattern matching in condition "only_if"

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#58]
Extending the operators supported by `only_if` to regexp matching would allow to check branch naming conventions, for example:

```
build_task:
  only_if: $CIRRUS_BRANCH == 'feature/'*
```

**Comment by fkorotkov** [comment]
You can actually do it today with `=~` and `!=~` operators:

```
build_task:
  only_if: $CIRRUS_BRANCH =~ "feature/*"
```

**Comment by simonbrandhof** [comment]
Excellent. That deserves to be documented in https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution !
