### ISSUE TITLE
Feature Request: Hybrid Windows : Linux Container environments

### ISSUE THREAD

**Issue by pcj** [cirruslabs/cirrus-ci-docs#580]
Would like it is possible to have a hybrid setup where the main container is a linux container and have an additional windows container running as well.

Here's the scenario:

1. In my build task, I am cross-compiling a golang binary to a windows app.exe binary.
2. Placing the windows binary in the http cache.
3. Starting a linux container for cypress (which I am having no luck running in a windows container)
4. Starting a windows container.  Pulling the app.exe from the cache, running it, and exposing port 8080 (the app runs a webserver)
5. Cypress test hits the port 8080 on the additional (windows) container host

This way I can test the binary runs correctly on windows (at least, it's web server capabilities), but use the testing framework running on linux.

**Comment by fkorotkov** [comment]
I don't think we will support this case somehow natively. But right now you can try to use a Windows Docker Builder and start a linux container and a windows container to do it.
