### ISSUE TITLE
Support for CCTray XML format

### ISSUE THREAD

**Issue by bekh6ex** [cirruslabs/cirrus-ci-docs#588]
I've tried to find if Cirrus exports build state in [CCTray XML](https://cctray.org/v1/) format.
Couldn't find anything, so it seems to be either missing or not documented.

I think this feature might improve user experience a lot for both:
  * enterprise users 
    - who want to use their own build dashboards 
    - might be in process of migration from one CI to another and want to unify the the presentation of build results
  * Open Source developers
    - who maintain many projects that use different CI solutions
    - want constantly see the build state on their desktop using something like [CCMenu](http://ccmenu.org/)

**Comment by fkorotkov** [comment]
Nice format! I'm surprised I've never heard of it. It will be nice to support it for organizations and repositories via URLs like:

```
https://api.cirrus-ci.com/github/ORGANIZATION/cctray.xml
https://api.cirrus-ci.com/github/ORGANIZATION/REPO/cctray.xml
```

Will work on that later this week. @bekh6ex how are you planing to use it?

**Comment by bekh6ex** [comment]
I wanted to set it up for my personal project on the laptop.

But also, I've used things like [Nevergreen](https://github.com/build-canaries/nevergreen) or [BuildReactor](https://chrome.google.com/webstore/detail/buildreactor/agfdekbncfakhgofmaacjfkpbhjhpjmp) on quite some projects. 

It's rather widely supported across CI tools. See [find cctray](https://github.com/build-canaries/nevergreen/wiki/find-cctray) for example.

**Comment by bekh6ex** [comment]
It's really nice to have a big screen build monitor in the room that will play "sad sound" when the build fails so that everyone will be on to fixing it right away. 😄

**Comment by RDIL** [comment]
Hahaha, that sounds like a funny use case.  I agree this could be a great addition.

**Comment by bekh6ex** [comment]
> that sounds like a funny use case

Except being funny it is extremly useful, especially if the team is doing trunk-based development and commits 50+ times to master daily. On the last project I've worked on it improved our daily life drastically.

**Comment by RDIL** [comment]
No, I agree it sounds very useful, but also funny at the same time.
