### ISSUE TITLE
Missing environment variable to get commit message

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#59]
Exposing the commit message in an environment variable like `CIRRUS_COMMIT_MESSAGE` would allow to implement build skipping if commit contains label "[skip ci]".  That's a common pattern provided by CI services.

Example:
```
build_task:
  only_if: $CIRRUS_COMMIT_MESSAGE !=~ ".*\[skip ci\].*"
```

**Comment by fkorotkov** [comment]
Should work now:

```
build_task:
  only_if: $CIRRUS_CHANGE_MESSAGE !=~ '.*[skip ci].*'
```

But do you think it makes sense to add skipping of CI builtin to not over copy `only_if` to all the tasks?

**Comment by simonbrandhof** [comment]
Thanks.
And yes, it makes sense to natively support `[ci skip]` or `[skip ci]`.
