### ISSUE TITLE
Agent is not responding! on freebsd-12-1-snap image family

### ISSUE THREAD

**Issue by igsilya** [cirruslabs/cirrus-ci-docs#594]
# Expected Behavior

Job started successfully.

# Real Behavior

Job fails after some time in "scheduling" state with "Agent is not responding!" error.

# Related Info

- [ ] Task issue
  - OS: FreeBSD
  - image-family: `freebsd-12-1-snap`

- Few failed jobs:
  - https://cirrus-ci.com/task/5523594201530368
  - https://cirrus-ci.com/task/6208206804353024

At the same time image-family `freebsd-11-3-snap` works fine.
This happens starting from March 5.  Maybe the most recent `freebsd-12-1-stable-amd64-v20200305` is an issue.

**Comment by fkorotkov** [comment]
Seems they've just update the image. The latest available is `freebsd-12-1-stable-amd64-v20200305` built yesterday.

I've just tested and it seems the new image does not execute startup script which bootstrapsr Cirrus CI Agent. /cc @emaste

In the meantime you can rollback to `image: freebsd-12-1-stable-amd64-v20200227`

**Comment by RDIL** [comment]
I feel like these should be pinned on the backend and updated weekly or something by dependabot so this doesn't happen.

**Comment by igsilya** [comment]
BTW, broken `freebsd-12-1-stable-amd64-v20200305` was removed from google cloud.  Builds are OK now.

**Comment by fkorotkov** [comment]
@igsilya thanks for the update! 🙌
