### ISSUE TITLE
Support Android Lint artifacts

### ISSUE THREAD

**Issue by rciovati** [cirruslabs/cirrus-ci-docs#599]
# Description

In addition to junit, it would be nice to support [Android Lint reports](https://developer.android.com/studio/write/lint) so that Android developers can benefit from Github annotations.

**Comment by fkorotkov** [comment]
@rciovati do you have a public repo where you run such linting. I'd like to see an example of such report to add it to https://github.com/cirruslabs/cirrus-ci-annotations
