### ISSUE TITLE
Maximum artifacts size

### ISSUE THREAD

**Issue by mpaladin** [cirruslabs/cirrus-ci-docs#615]
# Question

It seems like that the maximum artifacts size is 1gb, is it possible to customize it? i.e. through an environment variable?

**Comment by RDIL** [comment]
Not currently, no.  You can split it in to different parts I suppose, but that would require some third party tools.

**Comment by fkorotkov** [comment]
@mpaladin what do you store in 1gb+ artifacts?

**Comment by mpaladin** [comment]
@fkorotkov C++ debug artifacts of a big project which don't necessarily deserve to go to a persistent repository but enough to be available at the build level for developers.

**Comment by fkorotkov** [comment]
@mpaladin is it for a public repository or a private repository? Do you use the community resources or bring your own infrastructure?

**Comment by mpaladin** [comment]
@fkorotkov private repository on own infrastructure on Google Cloud.

**Comment by fkorotkov** [comment]
Oh. In that case I think it will make sense to remove the limit since you'll pay directly to GCP and leave the limit for OSS projects that are running for free.

**Comment by mpaladin** [comment]
@fkorotkov sounds good!

**Comment by fkorotkov** [comment]
Forgot to close the issue. The change got deployed this week.
