### ISSUE TITLE
Support **/*.{js,ts} syntax in changesInclude function

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#618]
# Description

Right now parser is failing to parse `,` properly inside `""`.

# Context

https://github.com/cirruslabs/cirrus-ci-docs/pull/584#issuecomment-593728086

**Comment by fkorotkov** [comment]
Probably something like https://github.com/mkungla/bexp can be used around [here](https://github.com/cirruslabs/cirrus-cli/blob/f7cd05fc41ba75c7f1e22945411d6c67c7dc47c9/pkg/parser/bfunc.go#L77).

**Comment by edigaryev** [comment]
I think [this is already possible](https://github.com/cirruslabs/cirrus-cli/blob/84cb2317d37165e8651db03e50fac240145d6a25/pkg/parser/bfunc_test.go#L21-L24) after we've migrated our parser to Golang a long time ago.
