### ISSUE TITLE
Regression: IP Addresses of Community Clusters

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#620]
# Expected Behavior

[IP Addresses of Community Clusters](https://cirrus-ci.org/faq/#ip-addresses-of-community-clusters) should be accurate.

# Real Behavior

Infrastructure upgrades in December and January broke it: 
* New GKE cluster is not under a NAT 
* Not all Mac nodes are in MacStadium
* Mac nodes in MacStadium DC are not under a NAT anymore because NAT was not able to handle the load.

**Comment by bcecchinato** [comment]
Hello ! Any idea when this issue will be fixed ?

**Comment by fkorotkov** [comment]
Most probably this Sunday. There will an announcement today about some internal infrastructure changes. Doing some final validations at the moment.  🤞

**Comment by bcecchinato** [comment]
Nice ! Can wait for it :)

**Comment by fkorotkov** [comment]
All but macOS VMs and non-privileged Linux containers are now under the gcp.community.nat.cirrus-ci.com. Working on bringing non-privileged Linux under the NAT but macOS VMs won't be under any NAT due to limitations of the DC where the Mac hardware is located.

**Comment by fkorotkov** [comment]
This should be fixed for newly created tasks.
