### ISSUE TITLE
Not started tasks are marking as cancelled

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#622]
# Expected Behavior

Not started tasks (especially with `depends_on`) are marking as pending or something like this.

# Real Behavior

These tasks are marking as cancelled (and red).

# Related Info

![image](https://user-images.githubusercontent.com/6510020/78824107-7de7be80-79e6-11ea-8027-0dac764ee291.png)

- [x] Task issue
  - https://cirrus-ci.com/build/4682008706154496

**Comment by AlexWayfer** [comment]
Probably it's even not related to `depends_on`, in another repository without it:

![image](https://user-images.githubusercontent.com/6510020/78836243-674b6280-79fa-11ea-9005-544742d3d6e0.png)

https://cirrus-ci.com/build/6636288484835328

After a time these checks are successful:

![image](https://user-images.githubusercontent.com/6510020/78836297-80541380-79fa-11ea-866a-b1396e3790e3.png)

**Comment by connorbrinton** [comment]
@fkorotkov I've noticed this often as well. I think it has something to do with how branch tasks are auto-cancelled when a PR is opened. For some reason GitHub displays the status of the cancelled branch tasks rather than the execution state of the PR tasks initially :man_shrugging: Several of my colleagues have thought that the CI pipeline was totally broken because of this 😅

**Comment by fkorotkov** [comment]
@connorbrinton this is a separate use case. Could you please create a separate issue?

**Comment by fkorotkov** [comment]
Actually I think I misread the original issue and it's the same issue: 

1. you create a branch
2. Cirrus creates a Branch build
3. Cirrus parses and creates tasks
4. you create a PR
5. Cirrus Creates a PR build
6. Cirrus cancels the Branch build with tasks
7. UI shows canceled tasks from the build branch
8. Cirrus parses tasks for the PR build
9. Cirrus now updates UI back to running state

Need to skip step 7 in case of auto-cancelation.

**Comment by connorbrinton** [comment]
I think step 9 also isn't occurring properly, since the UI doesn't get updated until the tasks actually complete successfully. Skipping step 7 would fix the issue almost entirely though.

If step 7 is skipped, the only case where I think step 9 would change the UI state would be if one or more tasks in the branch build finished successfully before the PR was opened, in which case they would need to be reset to the running state

**Comment by fkorotkov** [comment]
Yeah, I meant skipping only in case of auto-cancelation. 👌

**Comment by AlexWayfer** [comment]
> Actually I think I misread the original issue and it's the same issue:
> 
> 1. you create a branch
> 2. Cirrus creates a Branch build
> 3. Cirrus parses and creates tasks
> 4. you create a PR
> 5. Cirrus Creates a PR build
> 6. Cirrus cancels the Branch build with tasks
> 7. UI shows canceled tasks from the build branch
> 8. Cirrus parses tasks for the PR build
> 9. Cirrus now updates UI back to running state
> 
> Need to skip step 7 in case of auto-cancelation.

Can I set-up somehow to run builds only for PRs (not their branches) and `master` branch?

**Comment by fkorotkov** [comment]
You can use

only_if: $CIRRUS BRANCH == 'master' ||  $CIRRUS_PR != ''

**Comment by AlexWayfer** [comment]
> You can use
> 
> only_if: $CIRRUS BRANCH == 'master' || $CIRRUS_PR != ''

Thank you. :heart:

**Comment by fkorotkov** [comment]
Skipping of GH UI update on such auto-cancelation cases was deployed. Please let me know if you'll see any issue again.

**Comment by connorbrinton** [comment]
@fkorotkov I just saw this again with the last PR I opened. Here's a screenshot:

![Screenshot 2020-04-16 16 35 26](https://user-images.githubusercontent.com/1848731/79504231-8badcd00-8000-11ea-9afd-152824ce7482.png)

And here are the build links (let me know if you want task links too):
* Branch build: https://cirrus-ci.com/build/5786496623968256
* PR build: https://cirrus-ci.com/build/5160502791766016

What's strange is that the integration tests task didn't seem to have its branch cancellation reported. Or maybe the new state (queued) was reported after the cancellation was reported to GH 🤷‍♂️

**Comment by AlexWayfer** [comment]
Seems resolved for me now in https://github.com/AlexWayfer/formalism/pull/48

It was failing at the morning by the way.

**Comment by AlexWayfer** [comment]
Scheduled:

![image](https://user-images.githubusercontent.com/6510020/85796606-e3745d00-b742-11ea-9a97-643cfabeb1b1.png)

GitHub displays as "cancelled":

![image](https://user-images.githubusercontent.com/6510020/85796629-ebcc9800-b742-11ea-9184-a94a70480e0d.png)

**Comment by fkorotkov** [comment]
I think it's a similar to [this issue](https://github.community/t/actions-and-check-runs-are-not-updated-upon-a-re-run/14598/6) this is what happens:

* you open a PR
* Cirrus cancels the tasks
* GitHub gets updates
* Cirrus runs a new tasks and sends updates to GitHub
* But GitHub doesn't update

**Comment by AlexWayfer** [comment]
> I think it's a similar to [this issue](https://github.community/t/actions-and-check-runs-are-not-updated-upon-a-re-run/14598/6) this is what happens:
> 
> * you open a PR
> * Cirrus cancels the tasks
> * GitHub gets updates
> * Cirrus runs a new tasks and sends updates to GitHub
> * But GitHub doesn't update

Got it, thank you! Liked/subscribed/waiting…

**Comment by fkorotkov** [comment]
There were some optimizations done since the original issue. Please reopen if it still occures.
