### ISSUE TITLE
Container name conflict

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#624]
# Expected Behavior

Task executes as expected within Kubernetes Cluster.

# Real Behavior

`CreateContainerError`, resulting from:
```
Error response from daemon: Conflict. The container name
"/k8s_main_cirrus-ci-task-6286447862874112_cirrus-ci_7edac6a5-7b34-11ea-bcfc-42010a8a0031_0"
is already in use by container
"30bdfd156269d6c0da433a5f13d919b05eb35be1f7d8adc261e482f1dede91c8". You have to remove
(or rename) that container to be able to reuse that name.: CreateContainerError
```

# Related Info

- [x] Task issue
  - OS: DockerLinux on GKE
  - Task name: https://cirrus-ci.com/task/6286447862874112

**Comment by connorbrinton** [comment]
Confusingly, clicking the "Cancel" button for the task seems to somehow fix the problem. After clicking "Cancel" a red banner is shown, saying "Task was canceled!". But at the same time, the task starts to execute, resulting in the following unusual view:

![Screenshot 2020-04-10 10 52 44](https://user-images.githubusercontent.com/1848731/78999873-8856a500-7b19-11ea-89cf-3fb3b5025373.png)

**Comment by RDIL** [comment]
That's quite strange.  Was this a docker builder?  

Also is that RAM amount normal? 😆

**Comment by fkorotkov** [comment]
@connorbrinton where did you see the `CreateContainerError`? In your GKE dashboard?

**Comment by connorbrinton** [comment]
@RDIL Nope, it wasn't a Docker build, just running a previously built image as a container 🤷‍♂️

I think the memory value looks the way it is because I've defined my memory request as `2000Mb`, which gets rendered to `2000Mi` in Kubernetes. The `Mi` indicates power-of-two units, so it's not quite a Gigabyte (a full gigabyte would be `2048Mi`. Definitely a little strange though :laughing:

@fkorotkov Yup, I saw the `CreateContainerError` in my GKE dashboard for the pod with the same task ID (`cirrus-ci-task-<id>`)

**Comment by fkorotkov** [comment]
I think I know what was happening: 

Task 5160547956031488 (`build_and_push`)  build the image in DinD and finished, your `test` task started and got scheduled on the same node as `build_and_push` before Cirrus removed a pod for `build_and_push`. Still not clear why the Docker daemon returned it. Are both of the tasks are privileged containers?

And seems you canceled right at the time the task started executing causing the collision because of race condition.

**Comment by connorbrinton** [comment]
> Are both of the tasks are privileged containers?

Nope, just the `build_and_push` Docker daemon container is privileged (using [this recipe](https://cirrus-ci.org/guide/docker-builds-on-kubernetes/) from the docs).

> And seems you canceled right at the time the task started executing causing the collision because of race condition.

Actually, I have a second task where the same thing happened:
https://cirrus-ci.com/task/4856268984680448

In the first task, I cancelled 42m and 48s after the pod was scheduled, and in the second task I cancelled 47m and 3s after the pod was scheduled. I think it would be pretty unlikely for _both_ of those to be due to a race condition, though I guess it's technically possible 🤔

**Comment by fkorotkov** [comment]
I've tweaked a little bit how pods with additional containers are being removed. Let's see if that helps. 🤔

**Comment by fkorotkov** [comment]
Hey @connorbrinton, have you seen the issue occur again or my tweak helped?

**Comment by connorbrinton** [comment]
I haven't seen it again, so it seems to have helped :+1: Many thanks! :smile:
