### ISSUE TITLE
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2

### ISSUE THREAD

**Issue by dpo** [cirruslabs/cirrus-ci-docs#625]
I hope this is the right place to post this issue.

I'm building Julia software on FreeBSD using Cirrus and https://github.com/ararslan/CirrusCI.jl. Starting in the past few days, I've been getting this kind of failure on CirrusCI in the "install phase" of the build:
```
sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
-                                                     4905  B 8585 kBps    00s
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
repository FreeBSD has no meta file, using default settings
Fetching packagesite.txz: .......... done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
pkg: Repository FreeBSD load error: meta cannot be loaded No error: 0
Unable to open created repository FreeBSD
Unable to update repository FreeBSD
Error updating repositories!
Exit status: 3
```

Example: https://cirrus-ci.com/task/6087836260630528?command=install

Any ideas what's happening?

Thanks!

**Comment by fkorotkov** [comment]
I've seen similar reports. There is something wrong with the image that we don't maintain. Could you please try `freebsd-12-0-release-amd64`?

**Comment by dpo** [comment]
Thank you for the quick response! I'm already using `freebsd-12-0-release-amd64` but `freebsd-12-1-release-amd64` appears to be working!
