### ISSUE TITLE
Clone authentication failures

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#627]
# Expected Behavior

My pipeline ends with a "Deploy to Staging" task, which must be manually triggered. Yesterday my PR was approved, but I delayed triggering the deployment until today (20 hours later). I expected the deployment to proceed without a problem, starting by cloning the repo and then executing the deployment script.

# Real Behavior

I'm getting an authentication failure in the `clone` stage of my task. Here's the full error shown in the Cirrus CI logs:
```
Using built-in Git...
Fetching +refs/pull/30/head:refs/remotes/origin/pull/30...
Fetch failed: authentication required!
Re-trying to fetch...
Failed fetch: authentication required!
```

# Related Info

- [x] Task issue
  - OS: Linux on GKE
  - Tasks:
    - Initial task: https://cirrus-ci.com/task/5820355931537408
    - Automatic retry #1: https://cirrus-ci.com/task/5534599644184576
    - Automatic retry #2: https://cirrus-ci.com/task/6231991240622080
    - Manual retry: https://cirrus-ci.com/task/5858095003860992
  - Script/cache name (if applies): `clone_script`

**Comment by connorbrinton** [comment]
Actually, I'm starting to see this error in _all_ of our builds, regardless of whether or not they're delayed. I checked, and the Cirrus CI app is still installed in GitHub. Any idea why this error might have suddenly started?

Here are some more example tasks:
- https://cirrus-ci.com/task/5942458502610944
- https://cirrus-ci.com/task/5379508549189632

**Comment by fkorotkov** [comment]
@connorbrinton already investigating and I think I found the issue. Deploying a fix right now. Sorry for the inconvenience!

**Comment by fkorotkov** [comment]
Should be fixed now. There was a bug that cached some repositories as public so auth token wasn't provided to Cirrus Agent.
