### ISSUE TITLE
Regression: Prebuild tasks are reported to GitHub but never updated

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#630]
I have a number of tasks that use Dockerfile as an environment: https://github.com/newsboat/newsboat/blob/master/.cirrus.yml#L132-L138 This means that every task is split in two: first a Docker image is "prebuilt", then my commands are executed in a container created from the prebuild image.

(BTW "Dockerfile as environment" is literally *the* feature that made me move to Cirrus CI. Thank you for coming up with it and implementing it!)

# Expected Behavior

Prebuild tasks are *not* visible in the tasks list on GitHub. That's how it was just yesterday: https://github.com/newsboat/newsboat/runs/606438665

I would also be okay with them showing, but being updated as they finish on Cirrus.

# Real Behavior

Prebuild tasks are now visible in the tasks list on GitHub: https://github.com/newsboat/newsboat/runs/608267380 What's worse, they're never updated on GitHub even though they're updated on Cirrus: https://cirrus-ci.com/build/5006660351557632

This is inconvenient because GitHub now looks like all builds are in progress (yellow dot next to commits) even though the builds have already finished (and GitHub should display a green check mark).

**Comment by fkorotkov** [comment]
Indeed! I was optimizing how things are reported when there are 50+ tasks to mitigate an issue with GitHub API and tests didn't catch it. This should be fixed now. 👌

**Comment by Minoru** [comment]
Confirm fixed: (almost) all green on Github, no prebuild jobs https://github.com/newsboat/newsboat/issues/36#issuecomment-339421200 Thanks for a prompt response!

Interestingly, one of the tasks was never updated on GitHub, but I assume it's just a random glitch. Will report separately if I see if happening a lot.

**Comment by fkorotkov** [comment]
Which task was never updated? Your comment refers to a PR from 2017 when Cirrus wasn't around 😅

**Comment by Minoru** [comment]
Oh, sorry, wrong link. I meant this one: https://github.com/newsboat/newsboat/runs/608571872

**Comment by Minoru** [comment]
Or rather this one, which points specifically at the task: https://github.com/newsboat/newsboat/runs/608571880 Corresponding Cirrus task has long finished running https://cirrus-ci.com/task/6218980704649216

**Comment by fkorotkov** [comment]
Interesting. Looks like a weird GH bug. It created this run https://github.com/newsboat/newsboat/runs/608571857

**Comment by fkorotkov** [comment]
@Minoru I think I know what happened and just deployed a fix for that use case.

**Comment by Minoru** [comment]
Aww shoot, gotta finish my new PR faster to test the fix now :D

**Comment by Minoru** [comment]
Yep, all good now: https://github.com/newsboat/newsboat/runs/609094807 (except I broke all the builds T_T)

**Comment by fkorotkov** [comment]
Glad to hear it! Thanks for reporting the issue and sorry for the inconviniences!
