### ISSUE TITLE
Dockerfile caching should ignore comments & newlines

### ISSUE THREAD

**Issue by ened** [cirruslabs/cirrus-ci-docs#631]
# Description

Currently, this Dockerfile:

```
# https://github.com/cirruslabs/docker-images-flutter/blob/master/.cirrus.yml
FROM cirrusci/flutter:1.17.0-3.2.pre

RUN sdkmanager ndk-bundle
RUN sdkmanager 'cmake;3.10.2.4988404'
RUN sdkmanager 'ndk;20.0.5594570'
```

Will generate a different cache ID than this one:

```
FROM cirrusci/flutter:1.17.0-3.2.pre
RUN sdkmanager ndk-bundle
RUN sdkmanager 'cmake;3.10.2.4988404'
RUN sdkmanager 'ndk;20.0.5594570'
```

Even though they are semantically the same.

# Context

This would improve performance if multiple projects use the same, but slightly differently commented, Dockerfiles.

**Comment by fkorotkov** [comment]
Right now hash is MD5 from the contents of the Dockerfile plus `docker_arguments` if any. I don't think it's worth the optimization since some people use comments to invalidate the image and try the latest versions of packages/libraries/etc.

**Comment by ened** [comment]
Sounds reasonable.
