### ISSUE TITLE
Automatically skip execution if commit message contains "[ci skip]" or "[skip ci]"

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#64]
Execution of tasks should be disabled if the message of HEAD commit contains `[ci skip]` or `[skip ci]`. That allows to remove the complex condition from all the tasks:
```
only_if: $CIRRUS_CHANGE_MESSAGE !=~ '.*\[skip ci\].*' || $CIRRUS_CHANGE_MESSAGE !=~ '.*\[ci skip\].*'
```

**Comment by fkorotkov** [comment]
Though the same. It should work now 🙌
