### ISSUE TITLE
Documented email notification workflow is unusupported by Github

### ISSUE THREAD

**Issue by bbannier** [cirruslabs/cirrus-ci-docs#641]
# Expected Behavior

The docs [currently document](https://cirrus-ci.org/guide/notifications/#email-action) a `.github/main.workflow` which is not supported by Github anymore. Instead, all actions need to use YAML format.

It would be great if Cirrus CI could officially document a supported way for triggering email notifications. The current documentation leads users down a rabbit hole.

I am especially wondering whether [cirrus-actions/email](https://github.com/cirrus-actions/email) can still be integrated, or whether one would require another tool.

# Real Behavior

The documentated approach does not work and is not triggered by Github Actions.

# Related Info

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/notifications/#email-action
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by bbannier** [comment]
Is this something Cirrus would be interested in providing, or should I prepare to look for a solution myself?

**Comment by fkorotkov** [comment]
Indeed it wasn't updated in a while. I've created #643 to deprecate this action and instead rely on GitHub Action's own email notification so you won't need to struggle with a custom SMTP host.

**Comment by bbannier** [comment]
Thanks for the update @fkorotkov, this is useful.
