### ISSUE TITLE
Add `[skip cirrus]`

### ISSUE THREAD

**Issue by abitrolly** [cirruslabs/cirrus-ci-docs#642]
Sometimes I want to skip Cirrus CI only and keep other automation running for a certain commit.

# Context

There is a similar request for actions, listing support for `[skip ...]` tag for different services.
https://github.community/t5/GitHub-Actions/GitHub-Actions-does-not-respect-skip-ci/m-p/43398/highlight/true#M5366

**Comment by fkorotkov** [comment]
Created a PR to add this functionality. Will be merged in less 12 hours. Thank you for the suggestion! 🙌

**Comment by fkorotkov** [comment]
This should be working now.
