### ISSUE TITLE
"Cancel all tasks" button

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#645]
Sometimes a bad push happens (wrong config, syntax error, ...) and a failure on all machines is predictable. It would be nice to have a simple button to cancel all tasks so that resources are preserved and machines can instead be used to work on other pending tasks.

**Comment by RDIL** [comment]
Duplicate of https://github.com/cirruslabs/cirrus-ci-web/issues/117#issue-497259376
