### ISSUE TITLE
Builds not starting

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#652]
# Expected Behavior

A push to a PR starts a number of tasks on Cirrus CI, and after about half an hour, all of them finish.

# Real Behavior

One of the PRs to my project is stuck waiting for tasks to execute: https://cirrus-ci.com/build/5448590329905152 I manually restarted one of the tasks and that didn't change a thing: https://cirrus-ci.com/task/6029023820120064

# Related Info

The issue seem to affect only Linux, since macOS and FreeBSD builds finished fine.

[My cirrus.yml](https://github.com/newsboat/newsboat/blob/0083cade350975648987aa8bd89e756d2dec0c8d/.cirrus.yml) haven't changed in almost a month, and there were many successful builds in that period.

**Comment by fkorotkov** [comment]
You hit an edge case [the new scheduler](https://medium.com/cirruslabs/new-cpu-based-limits-for-cirrus-ci-b0dcd82f4615) didn't account for. Verified the issue and working on a fix. Will be fixed ASAP, sorry for the inconviniences.

**Comment by fkorotkov** [comment]
Deployed a fix and can see tasks are scheduling for you now. Once again sorry for the inconveniences!
