### ISSUE TITLE
Build stucked in "trigger state" with use_static_ip feature

### ISSUE THREAD

**Issue by bcecchinato** [cirruslabs/cirrus-ci-docs#655]
# Expected Behavior

Since the addition of the use_static_ip feature, my build is stucked when launched.

# Real Behavior

You can compare these builds :
* https://cirrus-ci.com/task/5472846652637184 => Stucked in "trigger" state
* https://cirrus-ci.com/task/5101259436851200 => Task ran but failed because IP is not allowed on my side

# Related Info

I think this is related to https://github.com/cirruslabs/cirrus-ci-docs/pull/653. Maybe I did misunderstood the way to use the feature :)

**Comment by fkorotkov** [comment]
Should be fixed now. 512Mb memory was too low and resulted in an invalid config
