### ISSUE TITLE
Colors refactor broke some UI elements

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#656]
![Screenshot 2020-06-12 at 9 36 55 AM](https://user-images.githubusercontent.com/34555510/84508491-5afcb380-ac90-11ea-9e85-29136777e276.png)
![Screenshot 2020-06-12 at 9 37 46 AM](https://user-images.githubusercontent.com/34555510/84508505-63ed8500-ac90-11ea-8a9e-06985685456c.png)

**Comment by fkorotkov** [comment]
Which browser is it?

**Comment by RDIL** [comment]
Chrome - interestingly enough, before the colors refactor on MUI 4.9.x and 4.10.x, it doesn't happen, but after the colors refactor, it happens on MUI 4.10.x but not 4.9.x so I am pinning the version.

**Comment by fkorotkov** [comment]
Works for me on 4.10.2
