### ISSUE TITLE
Some tasks of the cancelled build start again

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#659]
# Expected Behavior

I push a new branch, and Cirrus starts building it. Then I submit a PR from that branch to that same repo; Cirrus cancels the previous build and starts a new one. **The old build stays cancelled, no tasks in it run anymore**.

# Real Behavior

Here's the first build: https://cirrus-ci.com/build/5809815391830016 As of this writing, the following tasks are running, **even though they say they were cancelled by a newer PR build**:
- https://cirrus-ci.com/task/5696095462359040
- https://cirrus-ci.com/task/5977570439069696
- https://cirrus-ci.com/task/6681257880846336
- https://cirrus-ci.com/task/5766464206536704

Here's the second build: https://cirrus-ci.com/build/4706397558407168

There are two problems with this:
1. the first build doesn't stay cancelled, and wastes resources. About a month ago Cirrus was using a more efficient strategy and newer built from commits that were already built;
2. the first build might interfere with GitHub build status: if it finishes a task before the second build does, GitHub will say that the task is finished. At some point, GitHub might think that all tasks are finished, whereas in reality the second build is still running. If I merge the PR then, the second build will be cancelled, and GitHub will change the "green tick" to "red cross", indicating that not all of the tasks finished before the merge.

# Related Info

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: DockerLinux (but I'm not sure this is Docker-specific)
  - Task name: see links above
  - Script/cache name (if applies):

**Comment by Minoru** [comment]
Hi! Sorry to pester you, but the problem persists. I'm not asking for an immediate solution, just want to make sure this hasn't fallen through the cracks (as usually issues are responded to quickly here).

**Comment by fkorotkov** [comment]
This sometimes happens because of a race condition between two services: one that schedules a task and the other that get's a notification about new GitHub events that can cause cancelation. Need to add additional synchronization for that case but it should be pretty rare since, for example, you need to do two pushes one after another within a second or two.

**Comment by Minoru** [comment]
Hmm. The two builds I linked were created *one minute* apart, so perhaps there's something else going on?

**Comment by fkorotkov** [comment]
@Minoru seems it was an issue with the datastore Cirrus uses and eventual consistency of queries. For the tasks you mentioned there was a lag in updates for queries. I've made the query slower but strongly consistent for the logical part which caused the issue.
