### ISSUE TITLE
Add branch to the cirrus task url result

### ISSUE THREAD

**Issue by keyonghan** [cirruslabs/cirrus-ci-docs#661]
# Description

Issue https://github.com/flutter/flutter/issues/53943

# Context

make it clear/easy to see test results of specific branch of same sha.

# Anything Else

...

**Comment by keyonghan** [comment]
@fkorotkov Could you please share how to link to the url with branch info?

**Comment by fkorotkov** [comment]
@keyonghan just add `?branch=master` to the link after SHA. For example, https://cirrus-ci.com/build/flutter/flutter/66eb92e6259687c6e3434e9c76842b0848775c6b?branch=master which will link to a `master` branch build instead of a `dev` branch build.
