### ISSUE TITLE
URL to the latest successful artifact per task

### ISSUE THREAD

**Issue by sio** [cirruslabs/cirrus-ci-docs#663]
I'm trying to understand how to reliably access the latest artifacts generated by a particular task.

At first glance it seems straightforward (as per [docs](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction)): `https://api.cirrus-ci.com/v1/artifact/github/<USER OR ORGANIZATION>/<REPOSITORY>/<TASK NAME>/<ARTIFACTS NAME>/<PATH>`. 

But for more complex CI setup it turns out to be not so simple. If a more recent build for the same repo omits both the task that generated artifacts and `*_artifacts` instruction that saves the artifacts, the URL above will return 404 even though the artifacts are still there, they still are from the latest run of that task, just not from the latest build in this repo.

Example:
- Build [6184526642675712](https://cirrus-ci.com/build/6184526642675712) contains a [`build-packer-image`](https://cirrus-ci.com/task/6550084412243968) task. That task generates some artifacts
- The following artifact URL is valid immediately after that build: https://api.cirrus-ci.com/v1/artifact/github/sio/.cirrus-ci-jobs/build-packer-image/image/packer/debian10/output/guest-image.qcow2
- Artifact URL goes 404 after the next successful build ([6045406209507328](https://cirrus-ci.com/build/6045406209507328)) even though there is neither `build-packer-image` task nor `*_artifacts` definition in that build.

Is there a way to construct an URL that will always point to the latest artifacts of `build-packer-image` task even after completing some newer builds without that task?

**Comment by fkorotkov** [comment]
URLs are per build so if you use `skip_if` for some tasks than the latest URL won't work as you described. At the moment there is no way to have a link pointing to the latest run of a task.

**Comment by fkorotkov** [comment]
We are not planning to add such links since it will break a contract that all artifacts from a link come from a single build.
