### ISSUE TITLE
FreeBSD: "fail to clone"

### ISSUE THREAD

**Issue by billziss-gh** [cirruslabs/cirrus-ci-docs#664]
A FreeBSD build reports that the clone step failed, although the build is reported as successful.

Clone log:
```
Using built-in Git...
Cloning refs/heads/master...
Failed to clone: repository already exists!
```

# Expected Behavior

- I expected the clone step to succeed.
- I also expected the whole build to fail if the clone step failed.

# Real Behavior

- The clone step failed for an unspecified reason.
- The build succeeded nevertheless.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: FreeBSD
  - [YAML file](https://github.com/billziss-gh/cgofuse/blob/0c9df8e61a54c0a28ba1ec85c85d9b27cf81ec16/.cirrus.yml)
  - [GitHub build report](https://github.com/billziss-gh/cgofuse/runs/835800940)
  - [Cirrus build report](https://cirrus-ci.com/task/5727744170393600)

**Comment by fkorotkov** [comment]
Seems the task actually worked and [ran `build`](https://cirrus-ci.com/task/5727744170393600?command=build#L13) but the task state is very weird. Will investigate.

**Comment by billziss-gh** [comment]
I am just wondering if there was any chance to look into this.

FYI, I just ran a new FreeBSD [build](https://cirrus-ci.com/build/5678256600907776) and noticed the following.

I observed the build while it was running and the `clone` step completed correctly and was shown "green". Then the `install` and `build` steps also succeeded and shown "green". At this point the whole build was successful and shown "green" as well.

I then closed that window and a few minutes later opened a new one to look at the results of the same build. The build was now changed to show the `clone` step as "red". The successful clone messages are gone and it now shows:

```
Using built-in Git...
Cloning refs/tags/v1.4.0...
Failed to clone: repository already exists!
```

I also note that https://api.cirrus-ci.com/github/billziss-gh/cgofuse.json?branch=master&script=build&task=freebsd shows the build as "aborted".

**Comment by fkorotkov** [comment]
@billziss-gh that is some weird behaviour. Looks like the agent just started to run the task over again and failed since clone was already performed. I don't see how it quite possible especially if I check [agent debug logs for the task](https://api.cirrus-ci.com/v1/task/6446003849003008/logs/cirrus-agent-logs.log). Have you seen the issue more than once?

**Comment by billziss-gh** [comment]
@fkorotkov 

The last build where the `clone` step is shown as successful was https://cirrus-ci.com/task/4953869270646784. This build happened about 11 weeks ago, according to the Cirrus CI logs. (That build failed at the `install` step with `pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2`, but this is probably not relevant to our discussion.)

The next build was done 3 weeks ago and exhibits the discussed problem with the `clone` step: https://cirrus-ci.com/task/4988094648680448

Both of these builds were done using the image freebsd-12-0 (although I am now using the freebsd-12-1 image).

Perhaps something changed in the Cirrus CI FreeBSD infrastructure in the `time frame between 11 weeks ago and 3 weeks ago, i.e. sometime between May 7 and July 2?

**Comment by fkorotkov** [comment]
@billziss-gh  Seems something did change in how FreeBSD VMs are getting shutdown and it affected tasks with a custom working directory. I've deployed a change that should prevent it from happening.

**Comment by billziss-gh** [comment]
@fkorotkov do you want me to trigger a build to test and report results?

**Comment by billziss-gh** [comment]
I just reran build https://cirrus-ci.com/task/5187885722763264 and things seem to work correctly now. Thank you for the fix!
