### ISSUE TITLE
Dynamic Variable From API?

### ISSUE THREAD

**Issue by rymesaint** [cirruslabs/cirrus-ci-docs#665]
# Question
Is there any feature that cirrus could accept variable from api like github does? Because i search on documentation is only about environment variable.

**Comment by fkorotkov** [comment]
Hey @rymesaint, what do you mean by "variable from api"? Could you please elaborate on it?

**Comment by rymesaint** [comment]
in github i can use the payload data when triggering jobs like example below to get data from api json data.

https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event

```
- name: Building app file
      run: flutter build appbundle --flavor ${{ github.event.client_payload.flavor }} -t lib/main_${{ github.event.client_payload.file_target }}
```

**Comment by RDIL** [comment]
Where does this data come from on GH’s end?

**Comment by rymesaint** [comment]
> Where does this data come from on GH’s end?

it's come from API

 here some sample JSON data

```
{
    owner: "rymesaint",
    report: "flutter_clock",
    event_type: "build-app", // its the event for triggering
    client_payload: { // this where i can get the data to give so i can make it custom
        flavor: 'dev',
        file_target: 'dev.dart'
    }
}
```

**Comment by fkorotkov** [comment]
Hey @rymesaint, unfortunately at the moment Cirrus can't be triggered on any webhook event but it will in the near future (hopefully 3 months) once we'll support Starlark config (see my comment here https://github.com/cirruslabs/cirrus-ci-docs/issues/496#issuecomment-644872742).

At the moment you can try to use [Cirrus API](https://cirrus-ci.org/api/) and use `createBuild` mutation to pass a custom `.cirrus.yml` for different flavors.
