### ISSUE TITLE
Weird task names with variable

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#674]
# Expected Behavior

"Test on linux", "Test on darwin".

# Real Behavior

![image](https://user-images.githubusercontent.com/6510020/87543530-96363c00-c6ad-11ea-831e-540444169dcc.png)

# Related Info

- [x] Task issue
  - OS: DockerLinux, macOS
  - Task name: `Test on $CIRRUS_OS`
  - Script/cache name (if applies): see at links below.

https://cirrus-ci.com/build/6466879940198400

https://github.com/filewatcher/filewatcher/pull/131

**Comment by RDIL** [comment]
Looks like it matched `$CI` instead of `$CIRRUS_OS`.

**Comment by RDIL** [comment]
Try wrapping it in curly braces

**Comment by AlexWayfer** [comment]
I think, it should stop match by non-word symbols, something like `/(\$[A-Z_])[^A-Z_]/` (not sure about digits in env var names).

**Comment by AlexWayfer** [comment]
> Try wrapping it in curly braces

Doesn't help.

![image](https://user-images.githubusercontent.com/6510020/87558619-fd5deb80-c6c1-11ea-95c7-4305ebaca00f.png)

https://cirrus-ci.com/build/5242492406726656

https://github.com/filewatcher/filewatcher/compare/44ba1e6ebcdd87da4b1a411cad5cbda4f576ddeb..62abdae9ec4d462db680b497f356d803e1d8470c

**Comment by fkorotkov** [comment]
The issue was that $CIRRUS_OS variable wasn't available at parsing time. I've added a test and fixed the issue. Should be available in ~1 hour.

**Comment by AlexWayfer** [comment]
Thank you!

**Comment by AlexWayfer** [comment]
I confirm it fixed:

![image](https://user-images.githubusercontent.com/6510020/88535129-15aefe00-d012-11ea-973e-d29c3f6d84bf.png)
