### ISSUE TITLE
Display "artifacts" in task steps

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#676]
# Description

It's non-intuitive when you have `rubocop_artifacts` step in the `rubocop` task and in the CI interface it looks like just "rubocop":

![image](https://user-images.githubusercontent.com/6510020/87667418-f80ca980-c772-11ea-969e-b85a99566e20.png)

"rubocop"… what?

I think, CI should display a full name, like "rubocop artifacts".

Work-around is ugly, it can be `rubocop_artifacts_artifacts`.

**Comment by RDIL** [comment]
I have been working on this for a while now, I'll give it another go now.

**Comment by RDIL** [comment]
@fkorotkov what is the TaskCommandType `EXIT` for?
