### ISSUE TITLE
Environment variable missing in Docker

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#677]
I want to conditionally skip a task, so I set an environment variable and test it (search for "DONT_RUN_CLIPPY" in [this PR](https://github.com/newsboat/newsboat/pull/1100/files)).

# Expected Behavior

Tasks with env. var set to "1" skip the Clippy check.

# Real Behavior

[On macOS](https://cirrus-ci.com/task/5409397385986048?command=clippy#L1), `echo` shows that the variable is set, and `test` helps skip the Clippy check.

[In Docker](https://cirrus-ci.com/task/4705709944209408?command=clippy#L1), `echo` shows that the variable is **not** set, and `test` runs the check. The header of that build mentions "… DONT_RUN_CLIPPY:1 …", so it's not clear why the variable is not visible to `echo`.

# Related Info

Both builds are running exactly the same script: it's defined elsewhere, and is referenced by those two builds via YAML anchors.

I see [conditionals were mentioned before](https://github.com/cirruslabs/cirrus-ci-docs/issues/28) on this issue tracker, but it doesn't seem to be related to this one.

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: DockerLinux
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Commented here: https://github.com/newsboat/newsboat/pull/1100/files#r456071351

**Comment by Minoru** [comment]
Yup, [that was it](https://cirrus-ci.com/task/5312816456400896). Thanks once again!
