### ISSUE TITLE
Add CIRRUS_USER_PERMISSION environment variable

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#68]
That represents access level of a user who initialized the build.

**Comment by gspencergoog** [comment]
What values can it have?

**Comment by fkorotkov** [comment]
It will mimic this GitHub endpoint: https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level

So the values will be one of `admin`, `write`, `read`, `none`.

**Comment by gspencergoog** [comment]
Sounds great.

**Comment by fkorotkov** [comment]
This was actually added a while ago. 😅
