### ISSUE TITLE
latest artifact archive download doesn't work with non-master default branch

### ISSUE THREAD

**Issue by carlwgeorge** [cirruslabs/cirrus-ci-docs#687]
# Expected Behavior

> By default, Cirrus looks up the latest successful build of the default branch for the repository but the branch name can be customized via `?branch=<BRANCH>` query paramter.

Per the [documentation](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) quoted above, I expected https://api.cirrus-ci.com/v1/artifact/github/iusrepo/tmux3/el7/results.zip to give me an archive of the artifacts from task https://cirrus-ci.com/task/4579973635768320.

# Real Behavior

That link returns a 404.  On other repos with a default `master` branch, the equivalent link works as expected.  This repo is different in that it has a default `main` branch.  Adding `?branch=main` to the URL works, but I expected that not to be necessary since `main` is the default on this repo.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: CentOS 7
  - Task name: el7
  - Script/cache name (if applies): n/a

**Comment by fkorotkov** [comment]
Indeed! Sorry about that, should be fixed now in this endpoint.
