### ISSUE TITLE
Recognize `.cirrus.yaml`

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#689]
# Description

Please, add support of `.cirrus.yaml` configuration files.

`.yaml` is recommended by YAML standard: https://yaml.org/faq.html

![image](https://user-images.githubusercontent.com/6510020/89322587-19372a80-d68d-11ea-8794-99b329111fce.png)

# Context

I've created a repository with a `.cirrus.yaml` file and Cirrus CI integration and there is no Cirrus CI triggers.

**Comment by fkorotkov** [comment]
Seems like most of the CI do use `*.yml`. I think it's better to leave it as is for consistency. What do you think?

**Comment by AlexWayfer** [comment]
> What do you think?

YAML asks to use `.yaml` "when possible", as mentioned above.

If you think that it's possible — it's better to support the standard's recommendations, I think. Like `.cirrus.y{a,}ml` glob.

If it's hard for you, [like for RuboCop](https://github.com/rubocop-hq/rubocop/issues/1572), you can close it.

But it's weird when you have `*.yaml` and `*.yml` files in your project. And I think we should stick to recommendations of the format. And allow variations when it's possible. Yes, `.yml` is very popular, unfortunately, but if we can (in a some project) support both of extensions — I think we should to.

**Comment by fkorotkov** [comment]
This should work now

**Comment by AlexWayfer** [comment]
> This should work now

I finally confirm, thank you.
