### ISSUE TITLE
GraphQL API reported internal server error with HTTP 200

### ISSUE THREAD

**Issue by sio** [cirruslabs/cirrus-ci-docs#691]
GraphQL API server reported internal server error via JSON payload in HTTP 200 response.
I'm not absolutely sure this is a bug, but the behavior seemed counter-intuitive at best.

Here is the log: https://gitlab.com/libvirt/libvirt/-/jobs/670297678 
Error payload states: `[{'message': 'Internal Server Error(s) while executing query'}]`

The conclusion above might not be obvious from the log because a third-party API client was used (cirrus-run). That client handles non-200 HTTP responses in a different way, that particular exception may have been raised only if the payload arrived with HTTP 200.

I'm not an expert, and maybe it's a general practice for GraphQL servers to wrap internal server errors into successful HTTP response. In my opinion 5xx would've been more appropriate.

**Comment by fkorotkov** [comment]
Hey @sio, yeah, it's how GraphQL works: always returns a 200 and if there were errors then `errors` field will be populated.

**Comment by sio** [comment]
Ah, everything is ok then. Thanks for clarifying!
