### ISSUE TITLE
Docker cache does not detect image ARG change via indirection

### ISSUE THREAD

**Issue by bbannier** [cirruslabs/cirrus-ci-docs#692]
Given the following:
```
$ cat .cirrus.yml
environment:
  E: foo

foo_task:
  container:
    dockerfile: Dockerfile
    docker_arguments:
      - FOO: $E
  env:
    EE: foofoo
  cat_script:
    - cat /foo

$ cat Dockerfile
FROM alpine
ARG FOO
RUN echo $FOO > /foo
```

Changing the value of `E` in `.cirrus.yml:2` does not trigger a rebuild of the CI image. If `foo_task.container.docker_arguments.FOO` would contain a literal value instead of referencing `E` the image would be rebuilt.

Since this indirection seems supported in the first place (i.e., an initial build succeeds), I would also have expected it to work with the Docker cache; else disallowing it completely via some validation would be better than silently ignoring the change.

**Comment by malena-ebert-sonarsource** [comment]
Are there any news on this issue?

I would like to use this feature in matrix builds.

**Comment by fkorotkov** [comment]
This should be fixed now and values of docker_arguments will be evaluated with task environment variables.

**Comment by real-or-random** [comment]
Am I right that by setting `docker_arguments: $CIRRUS_BUILD_ID` I could effectively force a new docker build for every CI run?

**Comment by fkorotkov** [comment]
@real-or-random, yaeh, should work. Brilliant idea!
