### ISSUE TITLE
Mask encrypted values in more obvious way

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#693]
# Description

When executing a task, Cirrus-CI modifies the output to mask any encrypted values that happen to appear in command/script output.  As of the opening of this issue, the masking string is literally `SECRET`.

# Context

Masking with the literal string `SECRET` has confused at least two of my team members on separate occasions.  They mistakenly believed the mask-string was being passed instead of the value they had encrypted (esp. while debugging).  Since this has caught two people off-guard, I'm willing to bet there's a third and a fourth and ... who haven't opened up a feature request :smile: 

# Anything Else

I suggest using a different masking string that is much more obvious as coming from Cirrus-CI and not the task itself.  Some suggestions:

* `<<MASKED>>`
* ``[...]`
* `(CIRRUS-CI:HIDDEN)`

**Comment by fkorotkov** [comment]
@cevich see https://github.com/cirruslabs/cirrus-ci-agent/pull/34

**Comment by cevich** [comment]
Oh fantastic! Thanks!
