### ISSUE TITLE
git no longer works in FreeBSD 13

### ISSUE THREAD

**Issue by infrastation** [cirruslabs/cirrus-ci-docs#695]
# Expected Behavior

FreeBSD 13 used to work as expected in [Cirrus CI configuration for tcpdump](https://github.com/the-tcpdump-group/tcpdump/blob/master/.cirrus.yml) until August 7 ([the last successful run](https://cirrus-ci.com/task/5992710161039360)).

# Real Behavior

On August 7 FreeBSD 13 stopped working because git installed with pkg started to have linking problems ([the first unsuccessful run](https://cirrus-ci.com/task/5419461400330240)):
```text
ld-elf.so.1: /usr/local/bin/git: Undefined symbol "regcomp@FBSD_1.6"
```

FreeBSD 11 and 12 continue to work as before. Other repositories that do not install git with pkg continue to work with FreeBSD 13.

**Comment by fkorotkov** [comment]
I'm not sure what's going on here since we don't maintain the images. Members of FreeBSD community do create and maintain these images on GCP. Quick Googling didn't help much with the issue. 

@emaste, maybe you saw some similar reports?

**Comment by emaste** [comment]
Sigh, sorry folks - I'll look into it.

**Comment by infrastation** [comment]
Thank you. In case it helps, it is not a goal to test the latest snapshots of FreeBSD, so if it would be simpler to switch this Cirrus configuration to release images, that would be fine. The reason why it uses the snapshots is because these were the only working image names I could quickly figure out during the setup without becoming a customer of GCP.

**Comment by emaste** [comment]
What's happening here is that the package builds for 13-CURRENT and the base image snapshots aren't coupled, and the packages were actually built for a slightly newer base system version than the snapshot. This issue _should_ be gone with the latest base system snapshot - I'd greatly appreciate knowing if this is the case, or if it's still broken.

We're discussing short term workarounds in case this happens again, as well as build system changes to ensure it doesn't.

**Comment by infrastation** [comment]
Re-running the Cirrus CI task right now still results in the same error, for example: https://cirrus-ci.com/task/5676629479391232
I am not sure which version of `freebsd-13-0-snap` it is using though. If you want to get specific diagnostic output from within the task, just let me know which commands.

**Comment by fkorotkov** [comment]
Seems working without `pkg update -f` but still takes very long time and has weird logs. See https://cirrus-ci.com/task/4778135017226240?command=install#L3

**Comment by infrastation** [comment]
Commit the-tcpdump-group/tcpdump@96c4db3 had added `pkg update -f` to work around the failing FreeBSD 11 task in February 2020. The FreeBSD 11 issue was as follows:
```text
pkg install -qy git autoconf
pkg: cached package git-2.25.0: size mismatch, fetching from remote
pkg: cached package git-2.25.0: size mismatch, cannot continue

Exit status: 3
```
(The Cirrus CI task is [this](https://cirrus-ci.com/task/5445257491906560), but for some reason it no longer displays the log, but a [copy](https://github.com/the-tcpdump-group/tcpdump/runs/430319534) had survived elsewhere.)

Would it be more appropriate to switch to some stable images or maybe drop FreeBSD 11 and the workaround from the matrix?

**Comment by infrastation** [comment]
On a related note, I was going to declare the FreeBSD 13 task in `.cirrus.yml` OK to fail until there's a proper solution in place, and from the documentation it seems the condition in `allow_failures` can only use variables, which cannot tell which element of the expanded matrix the current task is for. In other words, this is not possible. Is this correct?

**Comment by arrowd** [comment]
That's right, it is a FreeBSD problem and has nothing to do with Cirrus CI. CURRENT is a bleeding edge branch and breakages such this happen. I'm sure it will be fixed once the image get upgraded to the new snapshot.
