### ISSUE TITLE
changesInclude fails with java.util.regex.PatternSyntaxException on negative results

### ISSUE THREAD

**Issue by abn** [cirruslabs/cirrus-ci-docs#696]
# Expected Behavior
We, [recently updated `.cirrus.yml`](https://github.com/python-poetry/poetry/commit/e0b00a4e3dfcacb1cd7708b46a61cd361e086efc#diff-0f7067c31caedf7df2739c9b07efa122R6) to use the following `skip` condition.

```yaml
      skip: "!changesInclude('.cirrus.yml', '**.{py,json,lock,toml}')"
```

On cases where `changesInclude` should return `True` the task is correctly not skipped. However, in cases where `changesInclude` returns `False`, task should be skipped.

# Real Behavior
This does not happen, and the build fails unexpectedly.

```
Error while loading tasks: FAILED_PRECONDITION: java.util.regex.PatternSyntaxException: Missing '} near index 6 '**.{py ^!
```

Failing build: https://cirrus-ci.com/build/4966129615503360

# Related Info
- [Configuration Change](https://github.com/python-poetry/poetry/commit/e0b00a4e3dfcacb1cd7708b46a61cd361e086efc#diff-0f7067c31caedf7df2739c9b07efa122R6)
- [Test Pull Request](https://github.com/python-poetry/poetry/pull/2808)
- [Failing Build](https://cirrus-ci.com/build/4966129615503360)

**Comment by abn** [comment]
Could be related to #618

**Comment by fkorotkov** [comment]
Yeah, look like #618. Sorry about that! YAML parser that Cirrus uses is not the smartest in some edge cases.
