### ISSUE TITLE
Request: $CIRRUS_CHANGE_TITLE, containing only commit subject

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-docs#698]
# Description

Requesting a new envariable, possibly named `$CIRRUS_CHANGE_TITLE` or `_SUBJECT`, containing only the first (subject) line of the git commit.

# Context

`$CIRRUS_CHANGE_MESSAGE` contains the entire git commit message and is typically used to conditionally enable/disable tasks:
```yml
    only_if:  $CIRRUS_CHANGE_MESSAGE !=~ '.*FOO:BAR'
```
This is typically understood (at least by this naïve user) to mean "put FOO:BAR in your PR title". However, it actually triggers if `FOO:BAR` appears _anywhere_ in the commit message, not just in the subject.

**Comment by fkorotkov** [comment]
Should work now 👌
