### ISSUE TITLE
Add more links to kick off builds

### ISSUE THREAD

**Issue by yschimke** [cirruslabs/cirrus-ci-docs#7]
people like clicking things to confirm suspicions

e.g. let me start a new build from here

![image](https://user-images.githubusercontent.com/231923/34536709-f209b048-f0bd-11e7-8834-885dabfb42af.png)

**Comment by fkorotkov** [comment]
@yschimke do you want to `Re-Run` whole builds from here?

**Comment by yschimke** [comment]
I want to kick off a master build.  I don't care if it's redundant.  If my build failed for some transient reason, I want some big red button to kick off a master build.

https://en.wikipedia.org/wiki/Placebo_button

**Comment by cevich** [comment]
I'd add that this feature would be nice for ALL builds.  Sometimes we like to re-run all tasks even if they passed previously (on  PR, or branch).  Currently this is possible only by pressing "re-run" on each task manually.  This is handy for helping to spot "fakes" (tests that fail on certain occasions, possibly externally-dependent).  Difficult if lots of clicking is required.

**Comment by fkorotkov** [comment]
Was fixed via https://github.com/cirruslabs/cirrus-ci-docs/issues/90#issuecomment-489638090
