### ISSUE TITLE
Add Auto Cancellation and Confitional Execution at the entire workflow level

### ISSUE THREAD

**Issue by drautureau-sonarsource** [cirruslabs/cirrus-ci-docs#70]
Auto Cancellation and Conditional Execution are tasks features.
Having the ability to provide them for the entire workflow would be painless (no need to Copy/Paste them for each task) if we want to have the same behavior for each task of a workflow.

**Comment by fkorotkov** [comment]
Made it possible to have `allow_failures`, `auto_cancellation`, `skip_notifications`, `use_compute_credits` and `timeout_in` in the top level. The change should be auto deployed in ~1 hour.
