### ISSUE TITLE
See log for aborted builds

### ISSUE THREAD

**Issue by probonopd** [cirruslabs/cirrus-ci-docs#700]
# Question

My job exceeded build time but I suspect this is only because something went wrong. I have this suspicion because the actual CPU usage was zero for most of the task running time, as I can see in the web interface.

![image](https://user-images.githubusercontent.com/2480569/92304851-1d9f7d80-ef82-11ea-8c2e-bd5955a946d3.png)

Unfortunately the log tells me absolutely nothing, except that the time was exceeded.

```
./build.sh
Timed out!
```

How can I get at the log of what happened in the task up to the point where the time was exceeded?

Example:
https://api.cirrus-ci.com/v1/task/4906304592412672/logs/main.log

**Comment by fkorotkov** [comment]
If you see `Timed out!` this means there were not logs from running `./build.sh` 🤔

**Comment by fkorotkov** [comment]
Maybe you can add something like `set -o verbose` to the script to see if any lines are executed?

**Comment by probonopd** [comment]
Thanks, I am using `sh -x ./build.sh | tee log.txt`.

I now see logs in the web interface during the build. (On my local machine this is not needed...)
