### ISSUE TITLE
Red cross on GitHub keeps being displayed when failed build is re-run

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#701]
Currently when resetting a failed ci run, GitHub will keep displaying the red cross for a failed build. It would be nice if a yellow dot was displayed for a (re-)running build, like on Travis CI or Appveyor CI, ...

**Comment by fkorotkov** [comment]
Unfortunately this is a known issue on GitHub's side. Please upvote https://github.community/t/actions-and-check-runs-are-not-updated-upon-a-re-run/14598

**Comment by MarcoFalke** [comment]
Maybe an "upstream" label could make sense here, as this is not Cirrus' fault?

**Comment by fkorotkov** [comment]
@MarcoFalke good idea! 👌

**Comment by ericoporto** [comment]
Not sure if the same error, but I have a task that finished fine after being rescheduled and ran, but the GitHub still indicates yellow, like if the task is still running.

You can see the invalid "running" yellow check here: https://github.com/adventuregamestudio/ags/pull/1201

**Comment by fkorotkov** [comment]
@ericoporto there was 502 in your case:

```
Failed to update check run for adventuregamestudio/ags@8dbc628df7968bee15f915e61638c8007bbe9335 for task 6678292431372288: INTERNAL: Internal GitHub failure: 502
```

And there was a bug in retry logic. Just pushed a fix which should be deployed within an hour. As for the task's yellow check there is no way to poke it manually expect a new commit. Sorry for the inconvenience!

**Comment by ericoporto** [comment]
Thanks! Sorry, thought it was a similar issue, thank you for the fix! Amazing work on the CI! ❤️
