### ISSUE TITLE
Create a msys2 mirror on cirrus for reduce install bandwidth pressure.

### ISSUE THREAD

**Issue by lygstate** [cirruslabs/cirrus-ci-docs#702]
# Description

A description of the new feature
Installing packages in msys2 with default mirror a rather slow
refer to 
https://cirrus-ci.com/task/4641597973331968
# Context

Reasoning/context behind this request
If cirrus can host a msys2 mirror on cirrus server, then we can reduce the install time
# Anything Else

...

**Comment by RDIL** [comment]
Please add some more context to the issue.

**Comment by fkorotkov** [comment]
You can probably use [Dockerfile as CI environement](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment) feature to workaround the slowness.
