### ISSUE TITLE
Tests are not triggered sometimes

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#703]
Sometimes on a force-push, the tests are not triggered when they should have.

Example (only appveyor and travis run, not cirrus ci):

![Screenshot_2020-09-09 test Run rpc_txoutproof py even with wallet disabled by MarcoFalke · Pull Request #19922 · bitcoin bi](https://user-images.githubusercontent.com/6399679/92586166-31a2f200-f296-11ea-8913-d9b6e8d32860.png)

https://github.com/bitcoin/bitcoin/pull/19922#event-3744887689

**Comment by fkorotkov** [comment]
That's weird. I can see that Cirrus got contents of `.cirrus.yml` successfully, parsed it and found no tasks to start. This usually happens when there are `only_if` statements but in your case there are none of them. I've added logging of file contents that Cirrus got from GitHub in such cases with no tasks after parsing. Could you please ping me here once you see the issue again and I'll check the new logs? Sorry for the inconveniences!

**Comment by fkorotkov** [comment]
I'll close the issue for now. Please reopen if you'll see the issue.

**Comment by MarcoFalke** [comment]
Another one:

https://github.com/bitcoin/bitcoin/pull/20030

![Screenshot_2020-09-28 validation Remove useless call to mempool- clear() by MarcoFalke · Pull Request #20030 · bitcoin bitc](https://user-images.githubusercontent.com/6399679/94474161-8b2f7a00-01cd-11eb-9654-46e648c467a3.png)

**Comment by fkorotkov** [comment]
Thank you! It seems it was created on GitHub, I can even generate the link: https://github.com/bitcoin/bitcoin/pull/20030/checks?check_run_id=1178225937

But the same check runs are not showing on on the check runs tab. 🤔  Posted to GitHub community about that: https://github.community/t/check-runs-created-but-not-visible-in-ui/134728

**Comment by MarcoFalke** [comment]
Maybe an "upstream" label could make sense here, as this is not Cirrus' fault?

**Comment by MarcoFalke** [comment]
We are now seeing this more often. On about half of all opened pull requests. E.g. https://github.com/bitcoin/bitcoin/pull/20760

Does Cirrus use a GitHub trigger that is less reliable than the triggers that other CI solutions use?

**Comment by fkorotkov** [comment]
Cirrus uses the same webhooks as any other CI (except GitHub Actions probably). There is a mechanism of injesting webhook events in a Pub/Sub instead of directly processing them for resilience. It should be pretty reliable when GH is not having issues of delivering the events. Let me check logs for the PR.

**Comment by fkorotkov** [comment]
I can see that everything is working as expected except the parser parses 0 tasks from the `.cirrus.yml`. Let me dig a little more into it (unfortunately Cirrus doesn't save the config it used for build creation).

**Comment by fkorotkov** [comment]
From the limited logs Cirrus had I only can assume that GH API didn't return the merged version of the config even thought I can see it right now: https://api.github.com/repos/bitcoin/bitcoin/contents/.cirrus.yml?ref=pull/20760/merge

Maybe the merged version is not available right away? Not sure, but I've added additional logs so please try to force push and see if the issue appears again. Or please give me a link to a newer PR (starting from now) that has the issue and I'll check the new logs.

**Comment by MarcoFalke** [comment]
The merged one is only available when `mergable == True`, see https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#get-a-pull-request

> The value of the mergeable attribute can be true, false, or null. If the value is null, then GitHub has started a background job to compute the mergeability.

**Comment by fkorotkov** [comment]
Yeah, but it's not the case for your PR. I was wondering if there is a delay while GH is "computing" the merged version if they don't do it on the fly.

**Comment by MarcoFalke** [comment]
Yes, as long as `mergable == None` (on average maybe ~5 seconds), there won't be any merged state.

**Comment by fkorotkov** [comment]
Interesting! I wonder what the contents API returns. If 404 then it will explain the behaviour. I put a log statement to get the return code. But seems in any case we'll need to add waiting for `mergable` when the setting to use a merged config file is set. Seems in the meantime you'll need to change the setting back to use the config from the same SHA.

**Comment by MarcoFalke** [comment]
I presume it will be 404 for newly created pulls and an outdated content for existing, but recently pushed-to pulls. At least that is what I've been observing.

**Comment by fkorotkov** [comment]
Cirrus now waits for `mergable` filed being initialized with either `false` or `true` before parsing the configuration **only** for repositories with the config resolution strategy set to the merge one.

**Comment by MarcoFalke** [comment]
We haven't seen the original issue recently, so maybe this was fixed by upstream GitHub https://github.com/cirruslabs/cirrus-ci-docs/issues/703#issuecomment-700241227

Closing for now
