### ISSUE TITLE
run fails, but shows no logs

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#708]
We are seeing a lot of failed builds with no logs either:

* E.g. https://cirrus-ci.com/task/5328126735548416

**Comment by RDIL** [comment]
I just got this issue with a passed build, https://cirrus-ci.com/task/5304638918361088

**Comment by RDIL** [comment]
@MarcoFalke it says that your build failed due to the agent not responding, which as said by the docs is either because of the community cluster or an out-of-memory error.

**Comment by fkorotkov** [comment]
@MarcoFalke sorry for the inconveniences! When agent dies it doesn't upload logs in the end of execution. I've added a mechanism to recover and persist at least some logs that got streamed in case of such agent failures. Usually this happens on OOM but it doesn't look like it so I'm not sure what is causing the agent error. Hopefully recovered logs of the future tasks will help.
