### ISSUE TITLE
Wrong value in $CIRRUS_BRANCH on pull requests of same repository

### ISSUE THREAD

**Issue by simonbrandhof** [cirruslabs/cirrus-ci-docs#71]
The variable `CIRRUS_BRANCH` is ambiguous. On pull requests the value is `pull/{id}`, for example `pull/123`, instead of the real branch name. When the pull request is initiated from the same repository, `CIRRUS_BRANCH` should be the branch name.

**Comment by fkorotkov** [comment]
This should be working correctly for PRs from branches of the same repository. For PRs from forks it will be still `pull/{id}`
