### ISSUE TITLE
"User is too new to use Community clusters! Please check with support!"

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#710]
A GitHub user just submitted [a PR to my repo](https://github.com/newsboat/newsboat/pull/1215), but [Cirrus CI refused to build it](https://cirrus-ci.com/task/5872100466491392) with an error of "User is too new to use Community clusters! Please check with support!". The GitHub user in question indeed registered just two days ago.

I don't see any mention of this limitation anywhere in [the ToS](https://cirrus-ci.org/legal/terms/#your-cirrus-ci-user), nor can I find it by searching the docs.

My question is: what is the limit exactly? How many days should I wait before re-starting the builds for that PR?

**Comment by fkorotkov** [comment]
Hey @Minoru, the condition is 3 days since we had issues with people creating fake accounts and mining crypto. I'll relax the condition to 8 hours since we haven't seen that many crypto mining attempts lately.
