### ISSUE TITLE
Cirrus CI cache are too slow

### ISSUE THREAD

**Issue by lygstate** [cirruslabs/cirrus-ci-docs#712]
# Expected Behavior
Looks at
https://cirrus-ci.com/task/4546339608461312

When I am using xz file, it's only consume
about 3 minutes, but with cache, it's costing more than 5 minutes

What should have happened is ...

# Real Behavior

What ended up happening was ...

# Related Info

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
@lygstate https://github.com/cirruslabs/cirrus-ci-agent/pull/49 got deployed so we'll see if there is an issue with download speed or the unarchiving process. Please post a link to a new task (created after this comment) with the slowness.

**Comment by lygstate** [comment]
I resolved the issue by zip the file myself.
This task is the procedure that slow
https://cirrus-ci.com/task/4899553256144896

**Comment by fkorotkov** [comment]
There is a cache miss though: https://cirrus-ci.com/task/4899553256144896?command=msys2#L125

I think it might be related to a large size of the archive and it containing a lot of files. Created https://github.com/cirruslabs/cirrus-ci-agent/issues/50 to improve archiving performance.
