### ISSUE TITLE
Anyway to remove bad generated cache?

### ISSUE THREAD

**Issue by lygstate** [cirruslabs/cirrus-ci-docs#713]
# Expected Behavior
I didn't found the cache clean instruction at
https://cirrus-ci.org/guide/writing-tasks/#cache-instruction

What should have happened is ...

# Real Behavior

What ended up happening was ...

# Related Info

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
You can either change the fingerprint or give me the cache key and repository name and I'll manually remove it.

This functionality is planned for #379

**Comment by fkorotkov** [comment]
Closing for now since haven't heard back and the underlying issue is covered by #379
