### ISSUE TITLE
Do not cancel tasks if new ones are set to be skipped

### ISSUE THREAD

**Issue by probonopd** [cirruslabs/cirrus-ci-docs#714]
# Expected Behavior

When a build is skipped (e.g., due to a `only_if: $CIRRUS_TAG != 'continuous'` directive), then already-running builds should not be cancelled

# Real Behavior

When a build is skipped (e.g., due to a `only_if: $CIRRUS_TAG != 'continuous'` directive), then already-running builds are cancelled

# Related Info

- [x] Task issue
  - OS: FreeBSD
  - Task name:
  - Script/cache name (if applies): https://github.com/furybsd/furybsd-livecd/blob/master/.cirrus.yml

# Background information

My task uploads, after the test has succeeded, build artefacts to GitHub Releases. In order to do so, the task creates a new tag (called "continuous") to which the artefacts are uploaded.

As soon as the new tag (called "continuous") gets created by the task, Cirrus CI kills the running task, resulting in the upload to fail. This is despite that I am specifically excluding the "continuous" tag from being run using `only_if: $CIRRUS_TAG != 'continuous'`.

(As a crude workaround, I have for now changed my task not to create "continous" tags but re-use the existing one, which is really less than optimal because artefacts are now uploaded to an old tag that does not match the actual sha of the code that has been built.)

**Comment by probonopd** [comment]
Once this is working properly, one should be able to remove the `-replace` flag from

https://github.com/furybsd/furybsd-livecd/blob/45b493536b7c6eb6e44543dce762850ebd948979/.cirrus.yml#L46.

**Comment by fkorotkov** [comment]
I think you can mark the upload task to be auto canceled with [`auto_cancellation` field](https://cirrus-ci.org/guide/writing-tasks/#auto-cancellation-of-tasks)

**Comment by probonopd** [comment]
Well, I'd like to keep auto cancellation as such, but my point is that if the subsequent release is set to be skipped by Cirrus CI, then the running build should not be cancelled. In other words, only when the subsequent build is not skipped should the running one be cancelled.

**Comment by fkorotkov** [comment]
Oh, this should be fixed as of October 13th. Forgot to close the issue.

**Comment by probonopd** [comment]
Thank you very much @fkorotkov, appreciate it.
