### ISSUE TITLE
regex operator (=~) seems to be anchoring

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-docs#715]
# Expected Behavior

```yaml
foo_task:
    skip: "$CIRRUS_CHANGE_TITLE =~ 'CI:DOCS'"
```
I would expect that a PR with `CI:DOCS` in the title would skip `foo_task`

# Real Behavior

Task was not skipped. Adding `.*` prefix and suffix to my expression is what makes Cirrus skip the task:
```yaml
foo_task:
    skip: "$CIRRUS_CHANGE_TITLE =~ '.*CI:DOCS.*'"
```

# Related Info

This is counterintuitive for anyone familiar with regular expressions: their default behavior is to trigger on any appearance of the expression in the string; anchoring requires explicit `^` (beginning of string) or `$` (end of string) characters.

The `=~` operator is briefly mentioned in webdocs under [supported operators](https://cirrus-ci.org/guide/writing-tasks/#supported-operators) but its behavior is not actually documented.

It is possible that someone somewhere is relying on the current behavior, making it impossible for you to change it. If so, at least please make it very clear in your documentation how `=~` works.

**Comment by fkorotkov** [comment]
PTAL at #716
