### ISSUE TITLE
Wildcards in only_if seem not to work

### ISSUE THREAD

**Issue by probonopd** [cirruslabs/cirrus-ci-docs#717]
# Expected Behavior

What should have happened is that 

```
  only_if: $CIRRUS_TAG != 'continuous*'
```

and/or

```
  only_if: $CIRRUS_TAG != continuous*
```

skips any tags with `continuous...`

# Real Behavior

What ended up happening was that those do not get skipped; resulting in my case in an infinite loop of builds being triggererd.

# Related Info

* https://github.com/helloSystem/ISO/blob/aee9f4d5b247bb8e2734a98874173f146503d7bd/.cirrus.yml#L15
* https://github.com/helloSystem/ISO/blob/a407481abb5c8da8f759951535a99d82b3b13a1e/.cirrus.yml#L15

"Infinite loops":

![image](https://user-images.githubusercontent.com/2480569/95904329-a5558480-0d97-11eb-9270-fa794008bec0.png)

**Comment by fkorotkov** [comment]
Did you mean `!=~` instead of `!=` like `$CIRRUS_TAG !=~ 'continuous.*'`

**Comment by probonopd** [comment]
What does ` !=~` mean? I am not familiar with this syntax. I meant to say "skip if the tag starts with..."

**Comment by RDIL** [comment]
`!=~` should mean 'not about equal to'

**Comment by probonopd** [comment]
Thanks a lot, let me try it.

**Comment by probonopd** [comment]
```
only_if: $CIRRUS_TAG !=~ 'continuous*'
```

Also seems __not__ to work, as `continuous-hello` still gets run.

**Comment by probonopd** [comment]
Based on https://github.com/cirruslabs/cirrus-ci-docs/issues/715 I figure that I need REGEX, e.g.,

```
only_if: $CIRRUS_TAG !=~ 'continuous.*'
```

Will test that now.

**Comment by fkorotkov** [comment]
@probonopd did it work for you?

**Comment by probonopd** [comment]
@fkorotkov yes it seems to have worked. Thank you very much. Maybe it could be clarified in the documentation?

**Comment by fkorotkov** [comment]
Great! I think it is already covered by `=~` documentation that it expects a Regex so a dot is needed. A glob like syntax might be an interesting addition. Should be probably a part of https://github.com/cirruslabs/cirrus-cli/issues/45

**Comment by probonopd** [comment]
Indeed, here:

https://cirrus-ci.org/guide/writing-tasks/#supported-operators
