### ISSUE TITLE
Unclear "bytes size exceeded" error during artifact upload

### ISSUE THREAD

**Issue by bbannier** [cirruslabs/cirrus-ci-docs#721]
We seem to [reproducibly see the following error message during artifact upload](https://cirrus-ci.com/task/5499423486640128?command=packages#L0-L6):

```
Uploading 1 artifacts for /tmp/cirrus-ci-build/build/spicy-*.tar.gz
Error from upload stream: rpc error: code = FailedPrecondition desc = Bytes size limit reached!
Failed to upload artifacts: failed to upload artifact file /tmp/cirrus-ci-build/build/spicy-linux.tar.gz: EOF
Re-trying to upload artifacts...Uploading 1 artifacts for /tmp/cirrus-ci-build/build/spicy-*.tar.gz
Error from upload stream: rpc error: code = FailedPrecondition desc = Bytes size limit reached!
Failed to upload artifacts again: failed to upload artifact file /tmp/cirrus-ci-build/build/spicy-linux.tar.gz: EOF
```

In a local test the file in question was ~ 100M big.

We use a pretty straight-forward artifact setup:
```
packages_artifacts:
  path: build/spicy-*.tar.gz
  type: application/gzip
```

Since I was unable to come up any hits during a search, what does this error message mean and what can we do to make this pass again?

**Comment by fkorotkov** [comment]
There is a limit of 1G for the total artifacts size. Instead of a PR I accidentally committed clarification directly in cf749ea. Also created https://github.com/cirruslabs/cirrus-ci-agent/issues/60 to log what sizes the agent sees for the artifacts.

**Comment by MarcoFalke** [comment]
Looks like this is fixed?
