### ISSUE TITLE
Error while loading tasks: INVALID_ARGUMENT: Failed to parse tasks: INVALID_ARGUMENT: parsing error: script only supports 'ps: ' helper syntax for Powershell!

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#722]
# Expected Behavior

When I push, I expect the builds to trigger.

# Real Behavior

Right now, I am getting the following error even though I didn't make changes to [my .cirrus.yml](https://github.com/newsboat/newsboat/blob/e1fa59cff6cd7ac7c36ea66776966c1019ad2211/.cirrus.yml) for a week:

> Error while loading tasks: INVALID_ARGUMENT: Failed to parse tasks: INVALID_ARGUMENT: parsing error: script only supports 'ps: ' helper syntax for Powershell!

# Related Info

- [ ] Website issue
  - Link to page: 
- [x] Task issue
  - OS: all of them
  - Task name:
  - Script/cache name (if applies): https://github.com/newsboat/newsboat/blob/e1fa59cff6cd7ac7c36ea66776966c1019ad2211/.cirrus.yml
  - Build: https://cirrus-ci.com/build/5258895478226944

**Comment by sio** [comment]
I have encountered the same errors in the past hour.

I have not made any changes to my `.cirrus.yml` in a few days. Last successful build was started at 12:23 UTC today.

**Comment by fkorotkov** [comment]
Sorry for the inconveniences! We are updating the parser and the error slipped though. Rolled back the change. Please try to re-trigger builds.

**Comment by Minoru** [comment]
Re-triggering in the web interface didn't help. Pushing a new commit didn't help either: https://cirrus-ci.com/build/5002538476896256

**Comment by sio** [comment]
Does not work yet: https://cirrus-ci.com/build/5834857613885440

Did I try to soon?

**Comment by fkorotkov** [comment]
Seems didn't propagate. Poked manually and re-triggered @sio's build to make sure now it works.

**Comment by kinke** [comment]
Thx for the quickfix, seems to work now when retriggering.

**Comment by sio** [comment]
Works now! Thank you!

>

**Comment by fkorotkov** [comment]
Great, sorry for the inconveniences. We are migrating from a Kotlin parser to a Go parser and this error slipped though from the new Go parser even though it should've been silently ignored since right now Go parser is in "shadowing" mode to achieve 100% compatibility.
