### ISSUE TITLE
Availability of older macOS images

### ISSUE THREAD

**Issue by ckreibich** [cirruslabs/cirrus-ci-docs#726]
# Question

Hi! [This page](https://cirrus-ci.org/guide/macOS/#list-of-available-images) lists currently available macOS images. Does this mean that you actively remove older ones, or do those continue to be available without support? I'm asking because the wording in #88 suggests that multiple releases might be available. Thanks!

**Comment by fkorotkov** [comment]
Copying my email reply to @rsmmr:

> Right now only Catalina images left after a migration in the beginning of this year. But on the bright side the migration now allows us to persist more images then before so even when Big Sur images will become available later this year we don't plan to drop support for Catalina images.

**Comment by ckreibich** [comment]
Thanks! Very helpful.
