### ISSUE TITLE
cache is never uploaded ("Some other task has already uploaded cache entry")

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#727]
It seems that caches are never uploaded for our repos. For example: https://cirrus-ci.com/task/6360227811426304?command=Upload%20%27ccache%27%20cache#L3

Thus, fetching the cache will fail. https://cirrus-ci.com/task/6360227811426304?command=ccache#L1

The error message "some other task has already uploaded" doesn't make sense because our taks names are unique, so there shouldn't be another task that has already uploaded the cache.

**Comment by fkorotkov** [comment]
Created https://github.com/cirruslabs/cirrus-ci-agent/pull/78 to log which task is claimed to upload the entry.

Unfortunately, it seems the existing meta information is screwed because of caching on server side so I can't figure out which task is claimed to upload the entry. Will let you know when https://github.com/cirruslabs/cirrus-ci-agent/pull/78 will be deployed so we can troubleshoot further.

**Comment by fkorotkov** [comment]
The change got deployed so new caches will have proper metadata so we'll be able to track the issue. Let's see what logs will yield.

**Comment by MarcoFalke** [comment]
For example this task https://cirrus-ci.com/task/6247049978970112?command=Upload%20%27ccache%27%20cache#L3 refers to a pull request having already uploaded: https://cirrus-ci.com/task/6087896912363520

Though, the pull request hasn't uploaded anything either.

**Comment by fkorotkov** [comment]
That's my bad. This task shows the corrupted metadata because of caching that I was talking about. This claim is wrong. Just deployed the server side change to fix it. Sorry about the noise!

**Comment by slycelote** [comment]
I have the same issue... Check any Ubuntu jobs here: https://cirrus-ci.com/github/slycelote/caide-cpp-inliner
Let me know if my config is incorrect, or what I can do to investigate.

**Comment by fkorotkov** [comment]
@slycelote Fixed your issue in https://github.com/cirruslabs/cirrus-ci-agent/pull/80 and it just got deployed so new tasks should be able to download caches.

**Comment by slycelote** [comment]
@fkorotkov Thanks!

**Comment by MarcoFalke** [comment]
This seems to be fixed. Closing for now.
