### ISSUE TITLE
Environment variables from kubernetes secrets

### ISSUE THREAD

**Issue by blankenshipz** [cirruslabs/cirrus-ci-docs#729]
# Description

We're using a private Kubernetes cluster for running our builds; It would be great if we had the ability to specify environment variables in task containers from Kubernetes Secrets. 

It also would be useful to have the ability to specify specific Service Account for the task so that specific tasks have isolated access to certain secrets. 

# Context

We'd like the ability to setup automated credential rotation for our build secrets, the current workflow of committing an encrypted secret to the build script becomes tedious at scale. 

# Anything Else

Thanks!
...

**Comment by fkorotkov** [comment]
Add a mutation that allows to update values of a particular encrypted variable see https://github.com/cirruslabs/cirrus-ci-web/commit/868cd790f51702de75313c3c30596a2aed2d059c. This will allow to update things like `gcp_credentials` without the need to update `.cirrus.yml`.

**Comment by blankenshipz** [comment]
@fkorotkov This is great! If I understand correctly we should be able to use the graphql endpoint now to create and update encrypted variables? 

Is there documentation about how to interact with this API?

**Comment by fkorotkov** [comment]
@blankenshipz you won't be able to create a variable with an arbitrary name but you'll be able to update an existing one that belongs to your organization (the one with `!`s like `ENCRYPTED[!abc!]`). You can find API documentation here: https://cirrus-ci.org/api/. Please let me know if you'll have any issues.

**Comment by fkorotkov** [comment]
Closing since now there is a mutation which can update the secret. Please reopen if you still need Kubernetes secrets.
