### ISSUE TITLE
Long wait in `triggered` state for Windows-based container image task

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-docs#73]
Hello, I'm just wondering why a Windows-based container image task has always a really long trigger state before it gets scheduled and executed? We talk here about a stay in the "triggered" state over 22 minutes. Is this a pre-defined setting? 

An [example task](https://cirrus-ci.com/task/6518550428647424) is given in the screenshot below and marks  the "triggered" state timing:

![issue](https://user-images.githubusercontent.com/6830431/46008362-ce295500-c0bc-11e8-87d6-cb12b2fc9de6.png)

**Comment by fkorotkov** [comment]
In this particular case, it just took that long for Azure to schedule a container. Azure API is a little bit different then other providers. When scheduling on Azure an API call is blocking until the Azure does validations and schedules the container.

It can also be related to a container size. In your case it's 10 GB of compressed layers. One thing you can try is to reduce the image size by reducing about of layers (just do one RUN command to install everything).

**Comment by ppaulweber** [comment]
@fkorotkov I understand, in this case I'll try to reduce the container image size, thanks!
