### ISSUE TITLE
Cloning a repo using https://docs.fastlane.tools/actions/match/

### ISSUE THREAD

**Issue by sderungs99** [cirruslabs/cirrus-ci-docs#730]
# Question
Hi,

Is there any documentation how fastlane's match can be run with cirrus ci? I am struggling with being authenticated properly when the repo is trying to be cloned.

So far, I have:
added this script prior to executing the fastlane match task: 
```
git config --global url."https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github".insteadOf https://github
```

and 

added a new github (read-only) user to the repo that holds the certificates and added the password into the MATCH_PASSWORD environment variable like so:
```
MATCH_PASSWORD: ENCRYPTED[2daa383a60a84c13dd9d6386326447aa8a38dcc96eab3e90be82cbbd846e00a23500283858fc1d5cbb288e6b9d8d293a]
```

With all this, I am still getting following error:
```
[16:40:08]: Cloning remote git repo...
[16:40:08]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
Cloning into '/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/d20201113-42024-126epn8'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/bytecrumbs/certificates/'
[16:40:09]: 
Exit status: 128
[16:40:09]: 
Error cloning certificates repo, please make sure you have read access to the repository you want to use
[16:40:09]: 
Run the following command manually to make sure you're properly authenticated:
[16:40:09]: 
$ git clone https://github.com/bytecrumbs/certificates /var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/d20201113-42024-126epn8
```

Maybe I am missing something? Do I need to setup an SSH key somehow, maybe? And if so, how would I do that? Many questions... :-)

Thanks for your help!

**Comment by RDIL** [comment]
Is the repository public?

**Comment by sderungs99** [comment]
No, it's a private repo where the certs for App Store are stored.

Following the match documentation, I have created a read only user on that repo, which is the one that is now trying to clone the repo and is getting the authentication error.

**Comment by RDIL** [comment]
I've also had difficulties trying to get Cirrus to use a different Git auth token/method.  I don't remember exactly what I did, but I'll see if I can look back to provide more guidance.

**Comment by fkorotkov** [comment]
`CIRRUS_REPO_CLONE_TOKEN` only has access to the repository you build originates from (it's a limitation/feature of GitHub Apps to only have access to a particular repository). If you want to clone another private repository you'll need to use another token.

**Comment by ios-dev-bytecrumbs** [comment]
Hi, yes, I got it working by creating a separate token and use that with something like this:

git config --global url."https://x-access-token:${A-DIFFERENT-TOKEN-THAT-HAS-ACCESS-TO-THE-REPO}@github".insteadOf https://github

I think this issue can be closed now.

**Comment by sderungs99** [comment]
Sorry, i created the above comment not realising that I was logged in with a different user :-) I'll close the issue.
