### ISSUE TITLE
CI doesn't trigger for specific branch (PR)

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#736]
# Expected Behavior

There are CI runs, maybe fails, maybe even config parsing errors.

# Real Behavior

Nothing.

Manual build:

https://cirrus-ci.com/build/6375902672060416

![image](https://user-images.githubusercontent.com/6510020/100807966-54334a00-3444-11eb-9b07-6b87858cee5f.png)

After refreshing this page:

![image](https://user-images.githubusercontent.com/6510020/100807988-5f867580-3444-11eb-9889-904cd30f9b91.png)

# Related info

https://github.com/AlexWayfer/alexwayfer.name/pull/59

**Comment by fkorotkov** [comment]
I think you need to change `.cirrus.yml` to `.cirrus.yaml` in `only_if` conditions. 🤔

**Comment by AlexWayfer** [comment]
> I think you need to change `.cirrus.yml` to `.cirrus.yaml` in `only_if` conditions.

Thank you, forgot about it in this project, it fixed.

I'm going to close this issue, but UI (like "page not found") can be better for such cases (manual launch).
