### ISSUE TITLE
Tasks with 3 CPUs fail

### ISSUE THREAD

**Issue by erikarvstedt** [cirruslabs/cirrus-ci-docs#737]
Example: https://cirrus-ci.com/task/5717987971825664. 
Error message: `Failed to start an instance: INVALID_ARGUMENT: Bad Request`
The corresponding task has the config
```
container:
  cpu: 3
```

**Comment by fkorotkov** [comment]
This is related to the `kvm` flag. Because of that the task is backed by a GCE VM which requires even number id vCPUs except a case with a single CPU. Please use 2 or 4 CPUs. I'll see how to propagate the error mesage better.

**Comment by fkorotkov** [comment]
Library that Cirrus uses does not provide extra error message about such errors so I documented the caveats in #738. PTAL.
