### ISSUE TITLE
Set secrets (environment variables) outside repository

### ISSUE THREAD

**Issue by k0ekk0ek** [cirruslabs/cirrus-ci-docs#739]
# Description

Secured variables (secrets) stored with the service, outside the repository.

# Context

My team has a number of contributors that all develop in their own forks and issue PRs to add features. This has worked very well for us so far, because we can insist all checkboxes are green before accepting a piece of work. Each person uses the same `.cirrus.yml` to keep things easy. I'd like each of these people to have access to a set of compute services to speed up builds. The problem is that each member of the team must add custom secured variables while testing/working in their repository and than drop the changes again to issue a PR. It's a minor nuisance for sure, but I think it would be a great feature to be able to write in the `.cirrus.yml` a script to use `do-stuff -token $SECRET_TOKEN` and have the `SECRET_TOKEN` variable stored with Cirrus CI. That way we can keep the logic as-is, but have each user fill in their own token to access (compute) services.

# Anything Else

It might just be as easy as setting the variables as a YAML compatible header before parsing?

**Comment by k0ekk0ek** [comment]
That's exactly what I intended, except that I'd like for the variable in the repository settings to also be secure, but I guess I can just encrypt them like with other variables?

**Comment by fkorotkov** [comment]
Yeah, that will work. It will be a simple way to override `env` for every task. I'll work on this feature next week. 👌

**Comment by fkorotkov** [comment]
Just wanted to update you that server side changes are in place for the this feature and the rest is just to add UI for that. Will do it tomorrow and will update you once everything is deployed.

**Comment by k0ekk0ek** [comment]
Nice @fkorotkov! Much appreciated.
