### ISSUE TITLE
Manual tasks

### ISSUE THREAD

**Issue by mattlorey** [cirruslabs/cirrus-ci-docs#74]
Looked through the docs and didn't see anything for doing manual tasks, preparing everything for a deploy but making the actual deploy a manual task that someone has to click a button.  Gitlab has a "when" parameter: https://docs.gitlab.com/ee/ci/yaml/#when-manual

Are there plans for something like this?  Or maybe it already exists?

**Comment by RDIL** [comment]
![A9DF77A1-D8A9-4524-A141-6B8FF7F56B8C](https://user-images.githubusercontent.com/34555510/57224025-0c351280-6fd6-11e9-8885-f81f0bb48055.png)
I think it’s happening 😯

**Comment by fkorotkov** [comment]
PTAL at #291 and try it out. ;-)
