### ISSUE TITLE
Cache size limit documentation?

### ISSUE THREAD

**Issue by JeremyRand** [cirruslabs/cirrus-ci-docs#742]
I got the mesage `cache is too big! Skipping caching...` on the "Upload cache" step when experimenting with large caches.  Is there any documentation on the cache size limit?  E.g. size in bytes, is some kind of compression applied before checking the size, is the limit on a per-cache or per-task basis?  Seems like the FAQ entry that covers other limits would be a logical place to document this.

**Comment by fkorotkov** [comment]
It means it's larger than 2 gigabytes after Cirrus agent tared and gzipped it. The resulting archive is too big. Fixing the message reporting here: https://github.com/cirruslabs/cirrus-ci-agent/pull/91

What are you caching that it is so large?

**Comment by fkorotkov** [comment]
Will close for now but please let me know about your experiments with large cache sizes.

**Comment by JeremyRand** [comment]
Thanks for the clarification @fkorotkov.  I was caching a fairly large Git repo so that I wouldn't need to clone it on each build.  I suspect that I can work around this by doing a shallow clone and/or only cloning a single branch; I just wasn't sure what size I needed to be targeting.

**Comment by fkorotkov** [comment]
You can do a shallow clone by setting 'CIRRUS_CLONE_DEPTH'. See documentation here: https://cirrus-ci.org/guide/writing-tasks/?h=+envir#behavioral-environment-variables

**Comment by JeremyRand** [comment]
@fkorotkov I assume that only works for cloning the repo that the build is attached to?  In my case, the build is for a repo that mostly contains metadata for other repos, each of which gets cloned by a build system.  (It's using the same build system that Tor Browser uses.)  I already filed a bug with the Tor Browser devs yesterday asking for support for shallow clones in their build system, so hopefully that'll result in a fix.

**Comment by fkorotkov** [comment]
Yeah, only for the attached repo. Is it a GitHub issue with Tor folks? I'd like to subscribe!

**Comment by JeremyRand** [comment]
@fkorotkov These are the relevant issues I filed:

https://gitlab.torproject.org/tpo/applications/rbm/-/issues/40009
https://gitlab.torproject.org/tpo/applications/rbm/-/issues/40010

And also this one which is tangentially related:

https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/40186

If you're curious, my intended goal is to use Cirrus as a co-signer for software that's built reproducibly with Tor Browser's build system, so that anyone who wants to compromise the binaries would need to compromise both the devs' build machines and the Cirrus infrastructure, rather than just the former (thus adding some extra security).  (I'm a Namecoin developer; we use Tor Browser's build system, and I sometimes contribute to Tor Browser as well.)

**Comment by fkorotkov** [comment]
Wow! Looks awesome! Getting the clone time from 30 minutes to just 7! 👏 7 minutes still sounds a bit too long, maybe it's possible to clone repos in parallel if the build system doesn't do it already. But still... 4 times faster clones!

**Comment by JeremyRand** [comment]
> If you're curious, my intended goal is to use Cirrus as a co-signer for software that's built reproducibly with Tor Browser's build system, so that anyone who wants to compromise the binaries would need to compromise both the devs' build machines and the Cirrus infrastructure, rather than just the former (thus adding some extra security). (I'm a Namecoin developer; we use Tor Browser's build system, and I sometimes contribute to Tor Browser as well.)

I gave a presentation at Tor Demo Day three days ago about this.  @fkorotkov if you're curious, I'll post a link here to the video once it's public (hopefully early next week).  The Tor guys are super enthusiastic about this.  :)

**Comment by fkorotkov** [comment]
Will gladly checkout the video once it's available. Thank you!
