### ISSUE TITLE
Sharing a cache between Linux and Windows tasks?

### ISSUE THREAD

**Issue by JeremyRand** [cirruslabs/cirrus-ci-docs#747]
Is there a way to share a cache between Linux and Windows tasks?  I'm using the `fingerprint_script` option to make the key independent of Linux/Windows and dependent on an environment variable, but it looks like the key is not actually solely dependent on the output of the fingerprint script; it looks like the key is being computed from the script contents itself as well as its output.  This is problematic since the Linux script is Bash while the Windows script is Batch, so the script contents will not be identical (even though they produce the same output).

Curious if there's some easy trick I've missed.

**Comment by fkorotkov** [comment]
Yeah, the Windows part is a bummer. I only saw people sharing caches for Linux/macOS/FreeBSD tasks where the outputs are the same. I've created https://github.com/cirruslabs/cirrus-ci-docs/issues/748 which will solve the issue in the future. In the meantime you'll have to use separate caches, is that OK for you?

**Comment by JeremyRand** [comment]
> In the meantime you'll have to use separate caches, is that OK for you?

@fkorotkov So, my intended use case here is to cross-compile something on a Linux container for a Windows target, and then test the resulting binaries on a Windows container.  Sharing the cache seemed like the most straightforward way to move the binaries from the Linux container to the Windows container.  Is there another way to do this?

**Comment by JeremyRand** [comment]
I see that the HTTP Cache feature seems to let me pick the key explicitly, rather than computing it based on a hash.  Could I just pick some arbitrary string as the key, and then use the HTTP Cache feature to share the caches between Linux and Windows?  (Maybe there's a better way; happy to hear suggestions.)

**Comment by fkorotkov** [comment]
HTTP cache will work. You can also use [Artifacts](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) and download an artifact from your Windows task.

**Comment by JeremyRand** [comment]
@fkorotkov Hmm, am I doing this right?  I copied the key name from the Cirrus UI for the Linux container (`Cache hit for bin-a5916563e1182ba0467f2288172b55cca0ce73b4a1be2eaf5c00d3aaccc5f9fb!`), and in the Windows container then did this:

~~~
curl -o idist.tar.gz http://127.0.0.1:12321/bin-a5916563e1182ba0467f2288172b55cca0ce73b4a1be2eaf5c00d3aaccc5f9fb
tar -xf idist.tar.gz
~~~

Unfortunately, I get this error output from `tar`:

~~~
tar: Archive entry has empty or unreadable filename ... skipping.
tar: Removing leading '/' from member names
tar: Error exit delayed from previous errors.
~~~

Is Cirrus's caching code storing as `tar.gz`, or is there some other encoding that I need to account for?

**Comment by fkorotkov** [comment]
It's a tar.gz but it uses Go's implementation: https://github.com/cirruslabs/cirrus-ci-agent/blob/master/internal/targz/targz.go. You can upload a binary directly to the cahe via POST from the Linux task.

**Comment by JeremyRand** [comment]
Weird that Go's implementation would be incompatible with the bsdtar implementation used in Windows.  But okay, I guess I'll try uploading via curl as well.

**Comment by JeremyRand** [comment]
Yep, works great if I do both the upload and download with curl.  Also doing it this way means I don't need to worry about hashing things, I can just use a human-readable key.

**Comment by JeremyRand** [comment]
@fkorotkov By the way, I can't verify this for certain since I never got bsdtar to decompress Go's tar.gz files, but I'm pretty sure the docs are wrong on how the key is constructed.  The "HTTP Cache" section of the "Writing Tasks" docs says that the key is a SHA1 hash.  AFAICT that's not accurate, it's actually of the form `${Name}-${SHA256}`.  If I'm correct, can that be fixed in the docs?

**Comment by fkorotkov** [comment]
Indeed! Please see https://github.com/cirruslabs/cirrus-ci-docs/pull/749
