### ISSUE TITLE
Badge not working 

### ISSUE THREAD

**Issue by vinferrer** [cirruslabs/cirrus-ci-docs#764]
# Question

Hi I just finished setting up my tests in cirrus CI. I wanted to add the badge before merging in the main repo but it seems like there is a problem:
![image](https://user-images.githubusercontent.com/38909338/104838899-07a1b200-58be-11eb-93e5-885a68f9ef5e.png)

https://github.com/vinferrer/phys2bids

The Cirrus CI build does not appear as passed or successful, Could this be because we haven't  merge to the main repo yet?
This is how I setup my badge in the readme
[![Build Status](https://api.cirrus-ci.com/github/physiopy/phys2bids.svg)](https://cirrus-ci.com/github/physiopy/phys2bids)

**Comment by fkorotkov** [comment]
Hey @vinferrer, the badge is based on the latest build for your default branch so if you haven't merged the PR there is no build for the default branch. You can verify that the badge is working by adding ?branch=my-branch query parameter.
