### ISSUE TITLE
Windows task fails but doesn't appear in red and the task continues executing commands

### ISSUE THREAD

**Issue by vinferrer** [cirruslabs/cirrus-ci-docs#765]
# Question

Hi , I was checking my jobs and I realized that even if there are errors in my windows jobs, the cirrus-CI webpage shows them as done correctly. For example this one: https://cirrus-ci.com/task/6202306100199424
Is there a way to correct this behavior? it would be annoying to have to check manually everytime if windows jobs are working properly

**Comment by fkorotkov** [comment]
That's weird. This is how Cirrus Agent generates a PS script to execute https://github.com/cirruslabs/cirrus-ci-agent/blob/master/internal/executor/cmd_windows.go#L63-L78 and it deliberately sets `ErrorActionPreference`. Does your Makefile make any changes that can chnage how Powershell reports exit code?

**Comment by vinferrer** [comment]
not at all: https://github.com/vinferrer/phys2bids/blob/master/Makefile . If you notice the work should stop before the makefile in the populate_enviroment_cache script

**Comment by vinferrer** [comment]
Maybe is not detecting the error from ``pip``? that's the first command that should trigger failure

**Comment by vinferrer** [comment]
Could you comment when you have more info about this? I am gonna need to keep track of windows jobs for the moment

**Comment by fkorotkov** [comment]
I'm actually trying to investigate it. It does look like an issue with EXEs and Powershell as I found in this [Stackoverflow issue](https://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error). I don't see any Powershell specific things that you do so could you please try to remove `SHELL: powershell` environment variable?

**Comment by vinferrer** [comment]
Let me try, I am gonna open a new branch for this

**Comment by vinferrer** [comment]
I just open a new branch and delete the ``SHELL:powershell`` from some of the tests, now those tests are failing, but from completely different reasons than before. Right now the job is not detecting ``pip``:
failing job: https://cirrus-ci.com/task/6232965623578624
cirrus ci yml: https://github.com/vinferrer/phys2bids/blob/c00253263653c92e96909d850ef0818a0fdcbb43/.cirrus.yml#L47

**Comment by vinferrer** [comment]
I managed to fix my tests without using ``powershell``. If you want we can close this issue

**Comment by fkorotkov** [comment]
@vinferrer glad it worked. Sorry I wasn't that helpful. 😪
