### ISSUE TITLE
Example for how to allow manual trigger of master-only tasks

### ISSUE THREAD

**Issue by bbannier** [cirruslabs/cirrus-ci-docs#766]
We are using a sizable Cirrus config for a C++ project where we use a slimmed down set of tasks unless we run against on `master` (via `only_if: $CIRRUS_BRANCH == 'master'`); this is primarily intended to speed up PR builds.

This simplistic setup has shortcomings:

1. from a PR it is not immediately clear which task where skipped due to `only_if`
2. if one wants to run `master`-only tasks against suspect PRs one is required to manually modify `.cirrus.yml` which needs to be rolled back before merging; a successful status will not be visible after the merge anymore

Additionally, we also certain tasks as manual if they are currently broken (via `trigger_type: manual`). Ideally it would be possible to make `only_if: $CIRRUS_BRANCH == 'master'` tasks effectively `trigger_type: manual` in non-`master` builds, but it is not clear to me how to accomplish this.

It would be great if the documentation could contain an example on how to accomplish this.

**Comment by fkorotkov** [comment]
@bbannier you can use `skip: $CIRRUS_BRANCH != 'master'`. This way tasks will be created but will be skipped which means the'll appear in the UI differently and one can manually re-run a skipped tasks which will result in actual execution of it.

Will that work for you?

**Comment by bbannier** [comment]
@fkorotkov, thanks for the hint, I had completely missed that, and it seems indeed exactly for what I am looking for here.

TBH, I find the naming of these attributes slightly unfortunate as `only_if` and `skip` are not opposites at all; while `skip` seems to control task execution, `only_if` seems to control task visibility (which can lead to tasks being skipped), so one would use the former for use cases like mine, and the later more for use cases like e.g., deployments or similar.

**Comment by fkorotkov** [comment]
Yeah,it's for historical reasons. 'only_if' was in the beginning and after a while 'skip' and 'skip_notifications' were added that can replicate 'only_if' behavior. Will take a look how to clarify it in the documentation. 🤔
