### ISSUE TITLE
Difference between cirrus-cli and cirrus-ci-agent?

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#767]
According to https://cirrus-ci.org/guide/persistent-workers/#configuration, the cirrus-cli can be used to register a persistent worker (e.g. aarch64 bare metal) with Cirrus CI and use it inside the `.cirrus.yml`. However, the readme of https://github.com/cirruslabs/cirrus-ci-agent  mentions that the cirrus-ci-agent can also be used (beside running locally) to supply bare metal to Cirrus CI. Thus, I am wondering what the difference between the two is.

**Comment by fkorotkov** [comment]
PTAL at https://github.com/cirruslabs/cirrus-ci-agent/pull/97. Does it help? 😄

**Comment by MarcoFalke** [comment]
Yes, thanks!
