### ISSUE TITLE
Dockerfile as a CI environment fails at push

### ISSUE THREAD

**Issue by vinferrer** [cirruslabs/cirrus-ci-docs#768]
Hi there I was trying to build a linux image from a dockerfile to use as a enviroment, but it failed at push:
dockerfile:  https://github.com/vinferrer/peakdet/blob/cirrus/.ci/miniconda3
task: https://cirrus-ci.com/task/4611487861833728

**Comment by fkorotkov** [comment]
Hey @vinferrer,

Sorry about that! We just updated the base image and the new major Docker version removed some deprecated features completely. Fixed via https://github.com/cirruslabs/vm-images/commit/59d95c79b83559f9ee16dc5e47986248c38968f8 and re-run your task and now it's passing.
