### ISSUE TITLE
macOS tasks fail to start: CPU requirements are too high: 2.0

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#769]
# Expected Behavior

macOS tasks start (as usual).

# Real Behavior

macOS tasks don't start, showing an error instead: "CPU requirements are too high: 2.0". Here are a couple that failed: https://cirrus-ci.com/task/6583204805083136 and https://cirrus-ci.com/task/4753617456463872

My .cirrus.yml doesn't contain any CPU requirements for macOS, because the defaults (2 CPUs, 8 GB RAM) were always fine for me.

Tasks for other platforms start just fine.

There were no changes to my .cirrus.yml, and I've seen macOS tasks succeed just an hour before: https://cirrus-ci.com/task/6732426199171072

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: macOS
  - Task name: "macOS Big Sur, Clang, Rust 1.49.0" and "macOS Catalina, GCC, Rust 1.46.0"
  - Script/cache name (if applies): I don't think it applies, but here it is just in case: https://github.com/newsboat/newsboat/blob/e99e52d61b2454dc490dc080fc578f2206855d61/.cirrus.yml#L92-L152

**Comment by Minoru** [comment]
Looks like the problem was transient. A newer build of a different PR [spawned a task just fine](https://cirrus-ci.com/task/6677082824507392), and defaulted to 12 CPUs and 24 GB RAM.

**Comment by fkorotkov** [comment]
Yeah, it was a bad deploy. Fixed it quickly. 👌

**Comment by fkorotkov** [comment]
Sorry about that!

**Comment by Minoru** [comment]
Cool! While I have you attention: what bearing does this change have on limits for OSS projects? OSS used to be limited to 2 CPUs on macOS; will the limit be raised to 12 CPUs now?

**Comment by fkorotkov** [comment]
Yeah, it was 2 cores with hyper threading and now it's 3x resources. You can check details here https://medium.com/cirruslabs/new-macos-task-execution-architecture-for-cirrus-ci-604250627c94

**Comment by ericoporto** [comment]
Hey, I am hitting it too, but I am still on Mojave, and I noticed that the docs only mention BigSur and Catalina, is this related or is it something else?

**Comment by fkorotkov** [comment]
@ericoporto could you please provide a task id where you see it? This `CPU requirements are too high: 2.0` was a bad deploy yesterday and was failing for around 20 minutes.

**Comment by ericoporto** [comment]
Yes, it's here: https://cirrus-ci.com/task/6339070814060544

It was building this PR: https://github.com/adventuregamestudio/ags/pull/1189

**Comment by fkorotkov** [comment]
Yeah, it was during the outage period. Re-ran your task and it's now executing. Sorry for the inconvenience!

**Comment by ericoporto** [comment]
Thank you!
