### ISSUE TITLE
Add an item to the user guide on testing rebased?

### ISSUE THREAD

**Issue by cmyr** [cirruslabs/cirrus-ci-docs#77]
This is probably easy to do with a script, but I thought it might be useful if it was mentioned in the guide somewhere?

When using CI for PRs, I would like to set up a task that rebases the branch on master and runs checks against the result. I feel like in many instances this is more important than whether the branch can pass tests on its own.

**Comment by fkorotkov** [comment]
There might be some issues in case there were changes to `.cirrus.yml`. We are thinking about a functionality when you can comment something like `@cirrus-ci rebase` which will do it for a PR. Or even `@cirrus-ci submit` which will rebase, wait for all checks to pass (not only Cirrus CI) and only then automatically merge a PR.

**Comment by cmyr** [comment]
yea, both of those would definitely be helpful!

**Comment by fkorotkov** [comment]
Reading should be possible now via a GitHub Action: https://github.com/cirrus-actions/rebase
