### ISSUE TITLE
Time issue on macOS Big Sur images?

### ISSUE THREAD

**Issue by timwoj** [cirruslabs/cirrus-ci-docs#772]
We're seeing a curl error related to certificate timestamp validity on all of our Big Sur builds right now. We attempt to download some files during the build, and curl claims that the certificate isn't valid yet. This same file downloads fine for all of our other non-BigSur tasks and I'm able to download it from multiple of my own machines without issues.

# Expected Behavior

File should download via curl without failures.

# Real Behavior

curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Could not get https://data.zeek.org/traces/2009-M57-day11-18.trace.gz.md5sum, skipping download.

# Related Info

See https://cirrus-ci.com/task/6552092061990912 for one of the failures.

- [x] Task issue
  - OS: macOS Big Sur
  - Task name: macos_big_sur
  - Script/cache name (if applies): N/A

**Comment by fkorotkov** [comment]
It's interesting. Is it always happening or it's transient?

 There was this issue but I've fixed it in https://github.com/cirruslabs/cirrus-cli/pull/246 by always syncing time.

Do you mind adding:

```bash
date
sudo sntp -sS time.apple.com
date
```

to your `ci/macos/prepare.sh` script so we can see the time that VM thinks it has set.

**Comment by timwoj** [comment]
```
Tue Jan  5 11:05:32 PST 2021
+2071735.571603 +/- 0.000717 time.apple.com 17.253.26.125
Tue Jan  5 11:05:32 PST 2021
```

Looks like it still thinks it's the beginning of January.

**Comment by fkorotkov** [comment]
@timwoj just update the agents with https://github.com/cirruslabs/cirrus-cli/pull/264. Should be more bulletproof now.

**Comment by timwoj** [comment]
Yep, looks resolved. Thanks for the quick turn-around.
