### ISSUE TITLE
macOS: Disable System Integrity Protection

### ISSUE THREAD

**Issue by smx-smx** [cirruslabs/cirrus-ci-docs#773]
# Description

Please disable or add an option to control System Integrity Protection (SIP) on macOS runners

# Context

I'm developing a tool that uses mach debugger ports to attach to other processes and debug them
I currently cannot run regression tests on Cirrus CI because SIP is enabled

> csrutil status
System Integrity Protection status: enabled.

# Anything Else

It looks like Appveyor ships images with SIP disabled: https://www.appveyor.com/updates/2020/06/07/

Thanks

**Comment by fkorotkov** [comment]
Do you use an Xcode image or the base image?

**Comment by smx-smx** [comment]
I tried with the xcode image

**Comment by fkorotkov** [comment]
But which one you need? I'll try to update the `big-sur-base` in the next few days and once Xcode 12.5 will be released it should pick it up for `big-sur-xcode-12.5`.

**Comment by smx-smx** [comment]
Right now i'm using `big-sur-xcode-12.4`, so it should be good

**Comment by fkorotkov** [comment]
SIP is now disabled on `big-sur-base` and will be on `big-sur-xcode-12.5` once Xcode 12.5 is released.
