### ISSUE TITLE
What does "Config resolution strategy" do?

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/cirrus-ci-docs#775]
# Question
What does "Config resolution strategy" do? I can't find documentation on it.

**Comment by fkorotkov** [comment]
Will think where to put it in the docs and in the meantime you can check my comment here https://github.com/cirruslabs/cirrus-ci-docs/issues/662#issuecomment-742832180 which should explain the options. Please let me know if it's not clear.

**Comment by real-or-random** [comment]
Ha, it was our parent project asking for that option of course. 

I think I get what this is doing but `Target Branch` was replaced by `Merge for PRs` (which is indeed better if this does what I believe it does). 

Am I right that `Merge for PRs` applies only to the config and not to the rest of the repo? So we'd still need the workaround in https://github.com/cirruslabs/cirrus-ci-docs/issues/662#issuecomment-653901809 to run CI on the merged code instead of on the PR branch?

**Comment by fkorotkov** [comment]
Yeah. Only for the config. IMO it's a tricky question for tasks especially when there are dependencies. Always using the merged version can result in tasks using different versions of source code.

Imagine, there is task `foo` and `bar` which depends on `foo` and while `foo` was executing there was a new commit to the target branch. In this case `bar` will pick up the new commit.

Ideally, I wish there was a way to do a rebase upon PR creation and before any tasks is executed.

**Comment by fkorotkov** [comment]
Closing as answered.

**Comment by real-or-random** [comment]
> Will think where to put it in the docs 

Is this done? (Just checking, feel free to close but I thought it's a good idea to keep this open as a reminder.)

**Comment by fkorotkov** [comment]
@real-or-random for cloning merged code please subscribe to #791
