### ISSUE TITLE
How to transfer files between tasks

### ISSUE THREAD

**Issue by davidbailey00** [cirruslabs/cirrus-ci-docs#776]
# Question

I would like to transfer files between two tasks of the same build pipeline. From the docs, I can see that it's possible to [create dependencies](https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies) although it doesn't appear that this transfers files between related tasks automatically.

I can see it's also possible to [create artifacts](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) from a task, although there doesn't seem to be support for transferring artifacts between tasks either.

Is this possible, and if so how would I go about doing it?

**Comment by fkorotkov** [comment]
@davidbailey00 what kind of artifacts are you talking about? For caches and similar temporary things [`cache` instruction](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction) is suitable or even using [HTTP cache](https://cirrus-ci.org/guide/writing-tasks/#http-cache) directly.  If you want to test some binary artifact (saw some folks quickly cross-compiling in Linux containers and do some sanity checks on Windows) then you might just use[`artifacts` instruction](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) and download artifacts via URLs to the [current build artifacts](https://cirrus-ci.org/guide/writing-tasks/#current-build-artifacts). 

Will one of these options work for you?

**Comment by davidbailey00** [comment]
Thanks, I've now switched to using artifacts to transfer files ([link to my config](https://github.com/davidbailey00/notion-linux-builder/blob/main/.cirrus.yml)), as documented under "URLs to the artifacts" - I think it could help to have some examples of this as well as just docs providing the URLs.

However, now I'm having an issue where the `build_result.zip` file is empty, even though `ls build` shows two files, and Cirrus itself states `Uploading 2 artifacts for /tmp/cirrus-ci-build/build/*` - I'm not sure if this is a bug or something I'm doing wrong?

**Comment by davidbailey00** [comment]
Ah, I think the problem is that Cirrus only looks for files when considering artifacts and so I either need to change my glob to end with `**/*` to pick up all files, or switch to using caching instead.

**Comment by davidbailey00** [comment]
My config is working as required now so closing this issue - thanks for your help @fkorotkov!
