### ISSUE TITLE
Not working with public custom Docker images

### ISSUE THREAD

**Issue by davidbailey00** [cirruslabs/cirrus-ci-docs#779]
eg: https://cirrus-ci.com/task/6336904234795008

# Expected Behavior

The build starts successfully

# Real Behavior

The build fails each time with the following messages:

```
Failed to start an instance! Failed to pull null image! Repository does not exist or may require authentication.
Container errored with 'ImagePullBackOff: Back-off pulling image "davidbailey:notion-linux-builder"'
```

[This Docker image](https://hub.docker.com/r/davidbailey/notion-linux-builder) is public, so should not need any authentication.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: DockerLinux
  - Task name: build_app
  - Script/cache name (if applies): n/a

**Comment by edigaryev** [comment]
Perhaps you need to specify the image as `davidbailey/notion-linux-builder`, instead of `davidbailey:notion-linux-builder`?

**Comment by davidbailey00** [comment]
Ah, thank you for the spot! Oops...
