### ISSUE TITLE
`reupload_on_changes` is not enabled by default

### ISSUE THREAD

**Issue by davidbailey00** [cirruslabs/cirrus-ci-docs#783]
## Expected Behavior

Cirrus docs state:

> `reupload_on_changes` is an optional field that can specify whether Cirrus Agent should check if contents of cached `folder` have changed during task execution and re-upload a cache entry in case of any changes. `reupload_on_changes` option is enabled by default and Cirrus Agent will detect additions, deletions and modifications of any files under specified `folder`.

I have the following config: https://github.com/davidbailey00/notion-linux/blob/60599da/.cirrus.yml

Based on the docs, I would expect changes to `aptly_cache` and `rpm_repo_cache` to be detected and uploaded.

## Real Behavior

https://cirrus-ci.com/task/6044436188626944?command=Upload%20%27aptly%27%20cache#L0

> Skipping change detection for aptly cache!

https://cirrus-ci.com/task/5481486235205632?command=Upload%20%27rpm_repo%27%20cache#L0

> Skipping change detection for rpm_repo cache!

Therefore,

> `reupload_on_changes` option is enabled by default

is not true.

# Related Info

This is a (tick one of the following):

Unclear if the docs are incorrect and the behaviour is correct, or vice versa

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/#cache-instruction
- [x] Task issue
  - See above

**Comment by fkorotkov** [comment]
Please check #784 if it clarifies the options.

**Comment by davidbailey00** [comment]
Thanks, I've just added some suggestions to fix typos but looks good :)
