### ISSUE TITLE
GraphQL API Feature: Indicate build trigger type

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#788]
I'm trying to setup some basic pass/fail scripted monitoring of Cirrus-CI jobs that were triggered by Cirrus-cron.  I noticed in the schema, that the `Task` type has `triggerType` (automatic or manual).  It would be helpful to have something similar on the `Build` type, indicating how it was triggered (push, cron, or manual).  That way my monitoring script can paging through recent builds, but have an easy way to only focus on those triggered by cron.

**Comment by fkorotkov** [comment]
There is now `source` field which can be either "github", "cron" or "api". See https://github.com/cirruslabs/cirrus-ci-web/blob/21dd4e61efa7e881f336b699e0d5b726620f4757/schema.graphql#L119

**Comment by cevich** [comment]
Fantastic! Thanks! :birthday:
