### ISSUE TITLE
Merge PR to its destination branch before parsing CI config and executing build

### ISSUE THREAD

**Issue by yogurtearl** [cirruslabs/cirrus-ci-docs#791]
# Description

Add a (default) option to checkout and merge a branch to its destination branch **for PR builds** before you parse the .cirrus.yml

After the PR has been merged to its destination branch, then you parse the .cirrus.yml and do whatever executions need to be done. 

# Context

The goal of a PR build is to make sure that merging the PR doesn't break anything. 
Merging to the destination branch before parsing the `.cirrus.yml` makes the PR build closer to what the post merge build will be. 

Merging before you parse the `.cirrus.yml` because the unmerged `.cirrus.yml` on a PR might reference things that are deleted or changed after the merge. 

Also, if the docker images are changed in the destination branch, you will want to make sure builds can still succeed inside the new images.

# Anything Else

Ideally this would be the default with an option to opt out. 

Many other CI systems have a default behavior similar to this: 
- You can turn this off in GH actions: https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit
- Travis CI: https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built
- Bitrise: https://medium.com/@bitrise/git-clone-step-revised-on-bitrise-more-stable-and-more-reliable-ddc2e043607f?_branch_match_id=781735949155432941

**Comment by Minoru** [comment]
I believe this can be achieved by setting "Config resolution strategy" to "Merge for PRs". This [is not documented yet](https://github.com/cirruslabs/cirrus-ci-docs/issues/775), but https://github.com/cirruslabs/cirrus-ci-docs/issues/662#issuecomment-742832180 has an explanation of all the options.

**Comment by fkorotkov** [comment]
@yogurtearl the only caveat here is that Cirrus agent won't clone a merged version of the branch. I've been debating whether make the agent automatically clone merged version of the sources if resolution strategy set to *Merge for PRs* or introduce a new [behavior environment variable](https://cirrus-ci.org/guide/writing-tasks/#behavioral-environment-variables) that will control it.

**Comment by rptb1** [comment]
Please see https://github.com/cirruslabs/cirrus-ci-docs/discussions/1110#discussioncomment-4916241 for our requirement for this: we want two builds on each pull request, like other CIs.

Please see https://github.com/cirruslabs/cirrus-ci-docs/discussions/1110#discussioncomment-4917295 for our current workaround (just one build for each pull request though).

Please also note https://github.com/cirruslabs/cirrus-ci-docs/discussions/1110#discussioncomment-4922977 which mentions the [GitHub merge queue beta](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) which may also be relevant to this issue and require changes to support.

Thanks.

**Comment by edigaryev** [comment]
> Looks like there were two merged pull requests, so I wonder if this was already fixed or if more work is needed?

This is indeed already fixed, thanks for the nudge!

Note that the changes only improve the workflow with `Merge for PRs` config resolution strategy, the `Latest from default branch` resolution strategy requires merging the changes against the default branch, but this functionality is not yet available on GitHub.

**Comment by real-or-random** [comment]
Thanks for the fixes. 

I'm not entire sure if it solves the problem entirely. For example [here](https://cirrus-ci.com/task/5325306236502016?logs=clone#L211), the log message indicates that the checked out commit is b160ddd00f9ccc37696b0fdf268d76ad85146453, which is still on the PR branch.  In other words, it's *not* the merge commit that is checked out. And we would still need our manual `merge_base` script (see right below "Clone").

**Comment by edigaryev** [comment]
> For example [here](https://cirrus-ci.com/task/5325306236502016?logs=clone#L211), the log message indicates that the checked out commit is b160ddd00f9ccc37696b0fdf268d76ad85146453, which is still on the PR branch. In other words, it's _not_ the merge commit that is checked out.

Thanks for noticing this!

The `"Merge for PRs" config resolution strategy enabled, skipping hard reset to preserve the merge commit` line indicates that the new logic works, you can check it by running `git log`.

The `Checked out b160ddd00f9ccc37696b0fdf268d76ad85146453 on pull/1329 branch` message is actually misleading, will improve it in the agent.
