### ISSUE TITLE
Gradle remote caching doesn't appear to work

### ISSUE THREAD

**Issue by yschimke** [cirruslabs/cirrus-ci-docs#8]
https://cirrus-ci.com/build/5726749002301440

Seems to still download all dependencies

![image](https://user-images.githubusercontent.com/231923/34537212-a075d91c-f0bf-11e7-9434-6016b2c8ae7f.png)

**Comment by yschimke** [comment]
Configured here https://github.com/yschimke/oksocial/blob/master/settings.gradle

**Comment by fkorotkov** [comment]
@yschimke seems your project is pure Kotlin and they've just added caching support for Gradle in `1.2.20`. And you are using `1.2.10`.

Here is a related issue: https://youtrack.jetbrains.com/issue/KT-15753

**Comment by yschimke** [comment]
Nice 
![image](https://user-images.githubusercontent.com/231923/34553653-a6d4b9a2-f120-11e7-88c3-4c010c76fcad.png)
