### ISSUE TITLE
curl: (16) Error in the HTTP2 framing layer

### ISSUE THREAD

**Issue by jmagman** [cirruslabs/cirrus-ci-docs#805]
## Expected Behavior

`curl` downloads from requested URL

## Real Behavior
```
Downloading Dart SDK from Flutter engine cd0e54348b61499bf22dc4546b5a7ed06b0c743c...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 45  198M   45 90.6M    0     0   124M      0  0:00:01 --:--:--  0:00:01  124M
100  198M  100  198M    0     0   146M      0  0:00:01  0:00:01 --:--:--  146M
curl: (16) Error in the HTTP2 framing layer
```
https://cirrus-ci.com/task/5064329080864768?command=upgrade#L784

# Related Info
Not sure what version of `curl` is being used on that image, this may be https://github.com/curl/curl/issues/3750.

**Comment by fkorotkov** [comment]
Provided task is running your custom image where you have full control over curl version. I don't see how it a Cirrus issue sine you also can reproduce with LUCI.

**Comment by jmagman** [comment]
> Provided task is running your custom image where you have full control over curl version.

Sorry, didn't realize that was the backend now.  So much has changed recently!  Thanks for the update.
