### ISSUE TITLE
Consider switching the default working directory

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#814]
Right now the default working directory is set to `/tmp/cirrus-ci-build`. For non-privileged containers running in GKE it translates into an `emptyDir` being mounted to `/tmp` for the task execution. This can lead to a weird warning messages. For example, it was reported that in some cases Bundler can print a warning like this:

```console
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
```

The proposal is to  mount `/tmp/cirrus-ci` instead and use `/tmp/cirrus-ci/working-dir` like Cirrus CLI is doing right now: https://github.com/cirruslabs/cirrus-cli/blob/e0adb15f7fcd01c8c19855025b90e5aac9e37bd9/internal/executor/platform/unix.go#L19-L25

# Concerns

Concern is that there might be cache entries which has absolute paths. This change might corrupt these caches.

# Alternatives

Alternatively we can : 

1. Switch the CLI to be consistent with the cloud and ignore the warnings.
2. Ignore until there are more reports of weirdness. It's been like that from the beginning and it's the first report in 3+ years.

**Comment by edigaryev** [comment]
> The proposal is to mount `/tmp/cirrus-ci` instead and use `/tmp/cirrus-ci/working-dir`

I'm not sure this would help:

1. Kubernetes still mounts `/tmp` with world-writable permissions by default:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: check-tmp-rights
spec:
  containers:
    - name: check-tmp-rights
      image: debian:latest
      command: ["/bin/sleep", "infinity"]
```

```
% kubectl exec -it check-tmp-rights -- /bin/ls -ld /tmp
drwxrwxrwt 2 root root 4096 Mar 29 00:00 /tmp
```

(that's on GKE's `1.20.4-gke.2200` — the most recent Kubernetes version available at this moment)

2. Bundler [specifically checks](https://github.com/rubygems/rubygems/blob/6ebda1df79f660d5e4ed4269b362c229a8770667/bundler/lib/bundler/vendor/tmpdir/lib/tmpdir.rb#L33) `/tmp`'s permissions and there's https://github.com/rubygems/rubygems/issues/4466 for that.

**Comment by fkorotkov** [comment]
How about the first alternative then? Make the CLI consistent with the cloud?

**Comment by edigaryev** [comment]
> How about the first alternative then? Make the CLI consistent with the cloud?

```
% docker run -it --rm debian:latest ls -ld /tmp
drwxrwxrwt 2 root root 4096 Mar 26 03:00 /tmp
```

I think it should already be consistent with the cloud because Docker sets the same world-writable `/tmp` permissions as Kubernetes does.

Haven't tested with Bundler, but it's code kinda implies that it'll issue a warning too.

**Comment by fkorotkov** [comment]
I meant the path of the working directory. If I recall correctly CLI always overrides `CIRRUS_WORKING_DIR` 🤔

**Comment by leshik** [comment]
@fkorotkov I see this with bundler as well in the WebUI.
