### ISSUE TITLE
A way to manually retrigger a build

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/cirrus-ci-docs#816]
# Description

Some button to re-trigger an entire build

# Context

I ran into this in this PR here:
https://github.com/bitcoin-core/secp256k1/pull/889  

What happened is that there was an old build, then we merge some fixes to .cirrus.yml (on master) and now I can't retrigger the build to run on the new Cirrus config.

 * I tried closing and opening the PR but then I just get the cached results. 
 * I could restart all tasks manually but this doesn't yield the desired result because the config has changed.
 * I could ask the author to rebase but that's not elegant.
 * I could create a new PR with the same branches but that's not elegant either.
  

# Anything Else

One could in fact argue that the cache of PR builds should be invalidated when the target branch changes. (Not saying this should automatically retrigger a build. But when a new build is triggered, it shouldn't use the cached results if the target branch has changed.) A nice side effect of this is that closing and opening the PR will be a working hack.

**Comment by fkorotkov** [comment]
There is no single button for doing so but you can create a build manually for `pull/889` "branch":

<img width="1136" alt="Screen Shot 2021-03-18 at 9 36 47 AM" src="https://user-images.githubusercontent.com/989066/111635145-943cf380-87cd-11eb-989c-94f5760ba789.png">

I believe this should do what you want. 🤔

**Comment by real-or-random** [comment]
Ah nice! I didn't know that `pull/889` works as a "branch" here. So that's not perfect but good enough as a workaround. The build name is "API build for null" and GitHub now lists the tasks from both builds. So it's not a retrigger but an additional build. But yes, this does the job in the end.

**Comment by fkorotkov** [comment]
Yeah, there is no way to "re-trigger" to override the build similar to how a task re-run is an individual task rather then a replacement (some other CIs just replace it so you miss the old failure information).

I'll close the issue since the workaround seems do the job.
