### ISSUE TITLE
Clarification on caching

### ISSUE THREAD

**Issue by mattlorey** [cirruslabs/cirrus-ci-docs#82]
The docs say the following:

> Tasks for PRs upload caches to a separate caching namespace to not interfere with caches used by other tasks. But such PR tasks can read all caches even from the main caching namespace for a repository.

Is this done automatically?  Can I explicitly read from the main caching namespace and explicitly write to a PR specific namespace?

I am running into issues due to what I believe is a shared cache between PRs but I'm not sure it it's hard to debug without access to what is cached or being able to purge cache.

My ideal scenario would be
 - Initial task in workflow checks cache - first for the PR specific and if that isn't populated fall back to the main cache
 - Initial task write to PR specific cache, if any changes
 - Subsequent task pull only from the PR specific cache

Is this possible?

**Comment by fkorotkov** [comment]
So the current logic for PR task cache writes is pretty simple: each cache key is prefixed with `pr/` **automatically**.

For reads the logic is a bit more complex: a task tries to download a cache by `pr/KEY` key before trying to download by `KEY`.

Looks like your ideal scenario, doesn't it?

**Note** that caches are shared between all PRs. To have a unique cache key for each PR you can try to add `$CIRRUS_PR` number of a PR to `fingerprint_script` of a cache.

**Comment by mattlorey** [comment]
The result of the `fingerprint_script` determines the `KEY`, correct?

So if I added the `$CIRRUS_PR` to that, it would never match the main cache.

That might be an okay solution for now, ideally I'd be able to use the main cache to prime the PR cache so to speak, but it should only be the first time a PR is built that the cache would be empty.

I'll some more testing with this knowledge, thanks!

**Comment by fkorotkov** [comment]
> So if I added the $CIRRUS_PR to that, it would never match the main cache.

Yeah. That's true. 

I'll keep the issue open. Don't hesitate to ask more question. In the meantime will think how documentation can be improved.

**Comment by fkorotkov** [comment]
Not sure how to improve the docs at the moment. Will close the issue. Please let me know if you have an idea how it can be improved.

**Comment by petertrr** [comment]
Hello! I stumbled upon this thread with a similar issue.

I find it a really important detail that PR caches share the same namespace, not a dedicated namespace per PR. This was not obvious to me from the current docs.

**Comment by petertrr** [comment]
Sure, but I _think_ I faced a case where a dependent task was getting a cached file from another PR instead of a task from the same build, which led to an error. I solved it by making `fingerprint_script` more specific, but this also disables the opportunity to start the first build of a new PR with the cache from the default branch.
