### ISSUE TITLE
Support specifying image by family in `compute_engine_instance`

### ISSUE THREAD

**Issue by riccardomurri** [cirruslabs/cirrus-ci-docs#826]
# Description

It would be nice to be able to specify the image to use in a task that runs on a `compute_engine_instance` by family only -- that is, pick the latest image available in the family.

I have tried this configuration:

```
task:
  name: Install Tests
  # Try running command
  test_script: |
    set -e
    pip install -e .
    myscript --version
    echo "OK: successfully installed."
    exit 0
  compute_engine_instance:
        image_project: centos-cloud
        image: centos-7
```

However it fails with this error: `Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'projects/centos-cloud/global/images/centos-7'. The referenced image resource cannot be found.`

I gather that referencing an image by family requires a different (or additional) API call to fetch the actual image name to be used.

# Context

I would like to use this for installation tests: i.e., check that new versions of the software can be installed with the current/latest version of the base OS.  In other words, check that the latest update from e.g. Ubuntu does not break the installation procedure.

**Comment by fkorotkov** [comment]
It's possible. You need to prefix image with 'family/'. In your case family/cantos-7.
