### ISSUE TITLE
User is too new to use Community clusters! Please check with support!

### ISSUE THREAD

**Issue by 69sauraj** [cirruslabs/cirrus-ci-docs#829]
User is too new to use Community clusters! Please check with support!
Whenever I try to trigger build this happens, also building with j8 and j10 leading my repository to be blocked, will the blocked repository be unlocked ? Please give me solution.

**Comment by fkorotkov** [comment]
This is a part of our effort to fight crypto miners who create users automatically and start mining crypto. You user should be good to go. Sorry for the inconveniences!
