### ISSUE TITLE
Badges for Tasks

### ISSUE THREAD

**Issue by hilbix** [cirruslabs/cirrus-ci-docs#83]
There are badges for the complete CI run.  But there are no badges for the tasks.

Think about having one build for Linux, MacOS and Windows, and the MacOS fails.  Then the complete build fails, while the individual tasks for Linux and Windows are OK.

The suggestion is to add some additional query parameter like `task=<TASK NAME>` to address a task.
This should be a second query parameter in parallel to `branch=<BRANCH NAME>` of course.

Notes:

- By making tasks failure tolerant, one can express "warnings" this way (a bit clumsy, but it works).  For example the "codestyle_task" can be failure tolerant and gets a red badge in case these checks fail.  But the overall compile stays green, as this is only cosmetic.

- If you are on it, perhaps you can add another query parm `script=<SCRIPT NAME>` to make badges for scripts, too.  Green: script ok,  Red: script fail,  Gray: script did not run because Task was stopped before

The latter is interesting to reduce the overhead.  Instead having N tasks to check for N such warnings, I can have one error tolerant Task with N scripts.

Until Scripts are failure tolerant (see #55) you will only get a red badge for the first warning, but this is better than nothing.

**Comment by M-Adoo** [comment]
badges for task is really useful.

**Comment by fkorotkov** [comment]
@hilbix should be working now: https://cirrus-ci.org/guide/writing-tasks/#embedded-badges

**Comment by RDIL** [comment]
Yes!!!  Thanks for this 🙏😃
