### ISSUE TITLE
Artifact doesn't contain merged content from all artifacts

### ISSUE THREAD

**Issue by seladb** [cirruslabs/cirrus-ci-docs#833]
## Expected Behavior

I have this task: https://github.com/seladb/PcapPlusPlus-Deploy/blob/8cc052c8ce4b35d84411731d27a9014906b6feae/.cirrus.yml#L66
That has a matrix of build tasks. After every build the task uploads the content of  `package/${TARGET}/${API}` as an artifact.

Then I have another task: https://github.com/seladb/PcapPlusPlus-Deploy/blob/8cc052c8ce4b35d84411731d27a9014906b6feae/.cirrus.yml#L104
That depends on the previous task, downloads the artifact `temp_package.zip` and does some final touches before uploading the final artifact.
According to the documentation I'd expect that `temp_package.zip` will contain the merged content from all the tasks in the build matrix:
> Note that if several tasks are uploading artifacts with the same name then the ZIP archive from the above link will contain merged content of all artifacts

## Real Behavior

Unfortunately `temp_package.zip` contains only the content of one of the build tasks in the matrix: https://cirrus-ci.com/task/5923770729758720

Is there anything I'm missing here?

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
I think there is an issue with conflicts inside your resulting archive and for some reason library that is used for generating the archive just stopped after the first conflict instead of reporting it. I think if you'll remove `package/include/` from the archives then the resulting archive will contain all the files as expected.

**Comment by seladb** [comment]
Thank you so much for your quick help! I removed the `package/include` directory from the artifact and now everything works as expected

**Comment by trombik** [comment]
@fkorotkov do you mean that each artifact must not contain same file name? i.e. all path must be unique?

**Comment by fkorotkov** [comment]
@trombik yes, otherwise it's not clear which file should override which. 🤷
