### ISSUE TITLE
Richer "env" variable support

### ISSUE THREAD

**Issue by bjlittle** [cirruslabs/cirrus-ci-docs#840]
## Description

This is related to the recently closed issue https://github.com/cirruslabs/cirrus-ci-docs/issues/837 [@fkorotkov]

I'd like to be able to create richer environment variables, if possible.

My use case is primarily concerned with Linux containers, e.g., naturally, I want to do the following,
```
env:
  CONDA_OVERRIDE_LINUX: "$(uname -r | cut -d'+' -f1)"
```
However, this isn't supported as the environment variable value is not interpreted. So at the moment I'm forced to perform an `export` within a `script` instead e.g.,
```
script:
  - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
```

## Context

The motivation here is to have a computed value for **common** environment variable, that can be defined **once** but then shared **many** times. As opposed to the proliferation of the same `export` statement per `script`. 

I realise that the implications of this may be significant - unless there is another pattern that you could recommend here, as best practice?

Many thanks! :smile: 

## Example

An example `.cirrus.yml` file of where I'm applying the `CONDA_OVERRIDE_LINUX` pattern using `export` is https://github.com/bjlittle/iris/blob/fix-cirrus-ci-and-mpl/.cirrus.yml

...

**Comment by fkorotkov** [comment]
GH Actions has a mechanism for [sending commands via logs](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions). They used to allow `set-env` and `add-path` commands but it [caused a CVE](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

Now a recommended way for actions is to use an [Environment File](https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files). I wonder if we need to adapt a similar pattern via `$CIRRUS_ENV` file. @edigaryev, what do you think?

**Comment by fkorotkov** [comment]
@edigaryev if you are concerned about `pipe`s, then it should be fine since working directory is preserved between stages. If `$CIRRUS_ENV` will be inside `$CIRRUS_WORKING_DIR` then it should be fine.

**Comment by edigaryev** [comment]
> @edigaryev if you are concerned about `pipe`s, then it should be fine since working directory is preserved between stages. If `$CIRRUS_ENV` will be inside `$CIRRUS_WORKING_DIR` then it should be fine.

It's not just about `pipe`'s, it's about declaring a complex environment variable **once** for all **tasks**, which may run in different containers and VMs, if I understood this feature request right.

**Comment by fkorotkov** [comment]
> As opposed to the proliferation of the same export statement per script.

I understood @bjlittle issue as duplication of setting env vars for each `_script` 🤷.

**Comment by edigaryev** [comment]
> > As opposed to the proliferation of the same export statement per script.
> 
> I understood @bjlittle issue as duplication of setting env vars for each `_script` 🤷.

Me too, but this:

```yaml
env:
  CONDA_OVERRIDE_LINUX: "$(uname -r | cut -d'+' -f1)"
```

...kinda implies that it should work for all tasks, which may run in different containers and VMs, assuming this is a root `env` node.

Perhaps @bjlittle will clarify this a bit?
