### ISSUE TITLE
cctray.xml gives Error 500

### ISSUE THREAD

**Issue by probonopd** [cirruslabs/cirrus-ci-docs#841]
## Expected Behavior

What should have happened is that CCTray integration works as it used to.

## Real Behavior

What ended up happening was that CCTray integration is flaky/broken since a week or so.

For example,

```
FreeBSD% LANG=C wget "https://api.cirrus-ci.com/github/helloSystem/ISO/cctray.xml" 
--2021-04-10 22:10:27--  https://api.cirrus-ci.com/github/helloSystem/ISO/cctray.xml
Resolving api.cirrus-ci.com (api.cirrus-ci.com)... 35.190.41.13
Connecting to api.cirrus-ci.com (api.cirrus-ci.com)|35.190.41.13|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-04-10 22:10:27 ERROR 500: Internal Server Error.
```

## Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [X] Task issue
  - OS: FreeBSD
  - Task name: helloSystem/ISO
  - Script/cache name (if applies): helloSystem/ISO

**Comment by fkorotkov** [comment]
Should be fixed now. Sorry for the inconvenience. It was a JVM issue where an update of a library stopped bringing a transitive dependency which was used in runtime. Weirdly, the dependency was available in tests.

**Comment by probonopd** [comment]
Thank you very much for restoring it so quickly.
