### ISSUE TITLE
Ability to include additional yaml files into .cirrus.yml

### ISSUE THREAD

**Issue by magreenbaum** [cirruslabs/cirrus-ci-docs#848]
Right now we have a very large `.cirrus.yml` file that we would like to be able to break apart related templates and tasks into separate files that could then be included in the main `.cirrus.yml` file. It would be nice to have for easier readability and keeping related tasks together. 

Would it be possible to add functionality to include other yaml files?

```
include: 
  - dev.yml 
  - qa.yml
  - prod.yml
  - tests.yml 
```

**Comment by fkorotkov** [comment]
Forgot to mention that Starlark configuration can be [tested](https://github.com/cirruslabs/cirrus-cli/blob/master/STARLARK-TEMPLATING.md#testing). See how we test the [Golang templates](https://github.com/cirrus-templates/golang).

**Comment by magreenbaum** [comment]
Thanks for this info. I'm planning to give Starlark a try in one of our repos. 
The immediate downside I see for us is that switching to Starlark for all of our projects will take some time. 

Is it possible to load yaml files using Starlark's module loading?

**Comment by fkorotkov** [comment]
You can have YAML config and Starlark config together. They will be merged. Next week we'll release an IntelliJ plugin which should help with writing the configs. If you want to be one of the first to try it out, we can talk over your specific use case over emails and I'll walk you though the setup. Will be a great case study for us to witness someone trying the Starlark for the first time.

**Comment by fkorotkov** [comment]
Can be achieved via #1053
