### ISSUE TITLE
Tasks running though I stopped all jobs from website in pesistent worke

### ISSUE THREAD

**Issue by Apon77** [cirruslabs/cirrus-ci-docs#854]
## Expected Behavior

Hi dear, persistent worker should be stopped all jobs when we abort the job from website

## Real Behavior

I have some AOSP compilation ongoing on persistent worker, suddenly sever acts slower, when I check server status with `top` command, I saw there are still process which are actually not running on cirrus-ci.com website,
Is there any workaround I can properly kill process when jobs are aborted or failed in website?? I am not using isolation
Thank you

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [ ] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Closing it as the mechanism was improved in cirruslabs/cirrus-cli#383 and there there is Docker isolation available too
