### ISSUE TITLE
task labels in webhook payload

### ISSUE THREAD

**Issue by xavierbourguignon** [cirruslabs/cirrus-ci-docs#86]
Notifications via webhooks is a great addition to cirrus-ci.
However, we use matrix to launch some tasks and the label added by the matrix is not present in the payload for a task, therefore it's impossible to know which task is executed.

Would it be possible to add the labels for a task ?

**Comment by fkorotkov** [comment]
I think it will be good to have! Added `uniqueLabels` field with a list of uniquely identifying labels which should help you in case of tasks with the same name.
