### ISSUE TITLE
Ensure that webhooks payload comes from CirrusCI

### ISSUE THREAD

**Issue by drautureau-sonarsource** [cirruslabs/cirrus-ci-docs#861]
It is currently not possible to ensure that webhook payload comes from CirrusCI.

As an example GitHub provides some security settings to provide this feature:
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks#secret
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks#ssl-verification

Would it be possible to implement such security features?

**Comment by drautureau-sonarsource** [comment]
> BTW what kind of logic do you have for processing events? If you simply execute some HTTP requests you might consider using [Cirrus Hooks](https://cirrus-ci.org/guide/programming-tasks/#hooks) which will execute the HTTP requests within Cirrus.

This is a great feature that fit my need: I can easily implement authentication for my Payload URL and improve security

**Comment by fkorotkov** [comment]
You can take a look how `graphql` module executes POST requests to Cirrus API here: https://github.com/cirrus-modules/graphql/blob/70107847d28f59df918985d5a79fc4e5510b4fd7/lib.star#L55-L79

**Comment by edigaryev** [comment]
>https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks#secret

A quick workaround is to make the webhook URL itself contain the secret, e.g.:

```
https://example.com/webhook?token=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

...and then check the `token` parameter in your app.
