### ISSUE TITLE
Tests keep failing due to `Forbidden!Configured service account doesn't have access`

### ISSUE THREAD

**Issue by keyonghan** [cirruslabs/cirrus-ci-docs#871]
Related issue: https://github.com/flutter/flutter/issues/85149

Context:
We have multiple repos: flutter/flutter, flutter/engine, flutter/plugins, etc. 
Our cirrus secrete expired last week, and we updated the secrete on Monday, and all tests started working fine.
This morning, the repo flutter/engine started failing due to
```
❗ Failed to start: UNKNOWN: API response 403: Failure executing: POST at: https://104.154.203.67/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:anonymous" cannot create resource "pods" in API group "" in the namespace "default".
```
All other repos are working fine. So we are assuming the key is valid.

Could you please help check if anything happened from cirrus side? Thanks!

**Comment by fkorotkov** [comment]
The issue was that the GKE cluster was 1.19 version but `Basic authentication` was enabled. Disabling it fixed the issue.
