### ISSUE TITLE
Add capability to skip changes that only touch certain paths

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#873]
# Description

I'd like to have a function, let's call it `changesOnlyAffect`, which I can use as follows:

```yaml
build_task:
  skip: "changesOnlyAffect('doc/**')"
  script: …
```

The upshot is that the task is skipped if changes only touch files under _`doc`_. If changes touch some other file, say _`tests/main.cpp`_, the task should run.

One way to look at it is:
- `skip: "!changesInclude(…)"` makes me enumerate the paths that trigger the task; if none of them are changed, the task is skipped
- `skip: "changesOnlyAffect(…)"` will give me a way to enumerate the paths that this task ignores; if any other path is changed, the task is ran

Another way to look at it is:
- `skip: "!changesInclude(…)"` is fail-closed: if the path is not in the list, the task is skipped
- `skip: "changesOnlyAffect(…)`" is fail-open: if the path is not in the list, the task is executed

Note that the only way to express one function in terms of the other is to know which paths exist: if I have directories _`foo`_, _`bar`_, and _`baz`_, then `!changesInclude('foo/**', 'bar/**')` is equivalent to `changesOnlyAffect('baz/**')`. This is a nice property, but it's useless in practice because adding a new directory to the repo can lead to updating every call to `changesInclude`.

# Context

I want Cirrus to skip C++ compilation for PRs that only change docs or localization files (_`doc`_ and _`po`_ directories). However, my project's source is not confined to a single _`src`_ directory: some files are right in the root of the repo. I could write a long `changesInclude` call, enumerating everything *except* _`doc`_ and _`po`_, but it's bothersome. I could also refactor my project, but it's even more bothersome. It'd be nice if Cirrus could have a ready-made function for this.

**Comment by Minoru** [comment]
I'm sorry to nag, but it feels like this issue fell through the cracks. I'm not impatient or anything, just want to make sure this was seen.

**Comment by fkorotkov** [comment]
Yeah, it slipped through the notifications. I think having a `changesIncludeOnly` variation that checks for the exact match in the list of affected files is useful for your case:

```yaml
build_task:
  skip: changesIncludeOnly('docs/**')
```

**Comment by fkorotkov** [comment]
@edigaryev is on PTO so he'll take a look early next week. 👌

**Comment by fkorotkov** [comment]
Actually will fix it via https://github.com/cirruslabs/cirrus-cli/pull/438. @edigaryev PTAL post factum once your are back.

**Comment by fkorotkov** [comment]
`changesIncludeOnly` is available in YAML configuration, @Minoru please give it a try. We need to add `changes_include_only` to Starlark as well and then we can close the issue.

**Comment by Minoru** [comment]
I'm probably using this wrong. I edited my .cirrus.yml in the master branch, then created a new branch and made [a commit that only touches po/newsboat.pot](https://github.com/newsboat/newsboat/commit/adce0a89f0ddccdd046a8037c4f65d040972930f). Surprisingly:
- [the ".po files" job](https://cirrus-ci.com/task/5569789797072896) was skipped [even though it shouldn't have been](https://github.com/newsboat/newsboat/blob/adce0a89f0ddccdd046a8037c4f65d040972930f/.cirrus.yml#L464)
- many compilation tasks, [e.g. this one](https://cirrus-ci.com/task/6554952215560192), ran [even though they should have been skipped](https://github.com/newsboat/newsboat/blob/adce0a89f0ddccdd046a8037c4f65d040972930f/.cirrus.yml#L182)

I don't see any bugs in #438, so I'm pretty sure that the problem is in my config. But I don't see it. Do you?

**Comment by Minoru** [comment]
Oh, apparently `**` in Cirrus globs only matches directories. I changed rules from `doc/**` to `doc/*`, and now [things work as I expect them to](https://github.com/newsboat/newsboat/commit/fbb5dd29af35e967aef76a1347c722fe11603dd5).

**Comment by Minoru** [comment]
I'm continuing my tests, and it looks like `**` matches *one or more* directories. So if I want to ignore the entire _doc_ directory (along with the subdirectories), I have to write two patterns: `doc/*` and `doc/**/*`.

**Comment by Minoru** [comment]
Okay, I got it working. Everything's performing great, thanks for the useful feature!
