### ISSUE TITLE
Bundled Homebrew version is too old

### ISSUE THREAD

**Issue by bbannier** [cirruslabs/cirrus-ci-docs#878]
Cirrus macos machines include Homebrew which is great. However the bundled Homebrew version is old and uses Homebrew bintray bottle locations which are not live anymore (see https://github.com/Homebrew/discussions/discussions/691). The Homebrew change to move bottle downloads from bintray to Github packages is https://github.com/Homebrew/brew/pull/11070 which first appeared in homebrew-3.1.0. Cirrus macos machines seem to come with homebrew-2.7.1.

## Expected Behavior

The following script should install the Homebrew LLVM package from a precompiled bottle (expected Homebrew default behavior) when run from a Cirrus macos job.

```
brew install llvm
``` 

## Real Behavior

Executing the script either leads to a hard failure since the remote returns `403 Forbidden`, or some other failure status which causes the package to be compiled from source (which takes long and could lead to e.g., Cirrus timeouts down the line).

A possible workaround seems to be to first run

```
brew update
```

This seems to update Homebrew sufficiently so it can use the new, correct bottle locations. This step however takes considerable time (~5min).

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: macOS
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Which macOS VM are you using? `big-sur-xcode-12.5` has a new enough version of brew.

**Comment by bbannier** [comment]
> Which macOS VM are you using? `big-sur-xcode-12.5` has a new enough version of brew.

I validated that I see this with `catalina-base`. I also seem to see this with `big-sur-base`, but haven't explicitly validated it.

**Comment by rsmmr** [comment]
What would be the recommendation here? All our tests based on `catalina-base` and `big-sur-base` are currently breaking. Should we switch to the `*-xcode-12.5` versions?

**Comment by bbannier** [comment]
Is there any plan to fix these macos images so that the bundled Homebrew is actually usable?

**Comment by fkorotkov** [comment]
`big-sur-base` image got update to the latest macOS 11.6 and all the up-to-date packages. Please give it a try. We'll build a new xcode image with Xcode 13 RC in the next couple of days.

**Comment by bbannier** [comment]
Like I commented in https://github.com/cirruslabs/osx-images/issues/37#issuecomment-919862885, we really need working Homebrew on all supported macos images.

**Comment by fkorotkov** [comment]
We are planning to deprecate Big Sur and Catalina VMs in early 2023. Monterey and Ventura VMs have up-to-date versions of Homebrew and getting constantly updated.
