### ISSUE TITLE
mojave-base macOS image doesn't work

### ISSUE THREAD

**Issue by foolip** [cirruslabs/cirrus-ci-docs#88]
https://cirrus-ci.org/guide/macOS/ points to https://github.com/cirruslabs/osx-images, which lists mojave-base and mojave-xcode-10.0 as known VM images.

However, that image doesn't work in Cirrus CI, as shown in this failed run:
https://cirrus-ci.com/task/5118555781595136

```
Failed to start: UNKNOWN: Template with name mojave-base not found!
```

**Comment by fkorotkov** [comment]
It's not yet deployed. There was a last minute issue with Command Line Tools. Doing some final validation and will deploy today/tomorrow.

At the moment please continue using `high-sierra-base` images. Sorry for the inconvenience.

**Comment by foolip** [comment]
Thanks for looking into this! Is there some place where the currently supported images are documented, given that there can be a delta from the page that your documentation links to?

**Comment by fkorotkov** [comment]
I will update the docs with the list of images. Right now it's just 4:

1. high-sierra-base
2. high-sierra-xcode-9.4
3. high-sierra-xcode-9.4.1
4. high-sierra-xcode-10.0

`mojave-base` and `mojave-xcode-10.1` are under the way.

**Comment by foolip** [comment]
Cool, thank you!
