### ISSUE TITLE
Upload caches right after they've been populated

### ISSUE THREAD

**Issue by leshik** [cirruslabs/cirrus-ci-docs#880]
# Description

Please consider adding a possibility to upload caches right after they've been populated.

# Context

Right now, caches are uploaded at the end of the tasks only after all other tests were completed successfully. But in the case there's some change in the code that breaks some of the steps, and no caches are present, then on every consequent commit caches are unnecessary rebuilding. Instead, they should be built once and then reused.

# Anything Else

While one could wrap caches into the `always` statement, there's a danger a broken cache will be uploaded if the operation doesn't succeed.

**Comment by fkorotkov** [comment]
Uploading right away will only work with the assumption that only `populate_script` created the cache. There are some cases when it's not true:
1. `populate_script` is actually optional and some further `script`s can actually create the cached `folder`.
2. `reupload_on_changes` flag is specifically for cases when the cache can be updated and Cirrus compares hashes of files to see if the files inside `folder` have changed.

I think to not introduce new behaviour we should just support `always` approach:

```yaml
always:
  foo_cache:
    ...
```

In such a way that [`UploadCacheInstruction`](https://github.com/cirruslabs/cirrus-ci-agent/blob/52c5604581b1263517a7bc92d0a17fd33398465e/internal/executor/executor.go#L372) will have the same behavior as `CacheInstruction` and will just check that the corresponding `CacheInstruction` succeeded.

**Comment by leshik** [comment]
Suppose there's an issue in the middle of e.g. `Gemfile`, such as some gem is no longer available from `rubygems`, or the Github repository that ceased to exist. This way we end up with the half-built bundle, which is broken but is still uploaded (because of `always`), and next time we get a cache hit, and the only way to fix the broken build is to manually drop the cache.

**Comment by fkorotkov** [comment]
> check that the corresponding CacheInstruction succeeded

This will basically check that the `populate_script` succeeded.

Another option might be to add `UploadCacheInstruction` right after `CacheInstruction` if and only if `fingerprint_sciprt is not empty AND reupload_on_changes == false`. @leshik, what do you think?

**Comment by leshik** [comment]
That would be great.

**Comment by fkorotkov** [comment]
The initial adea behind uploading in the end was to ensure to upload caches that works for the task in case a person is experimenting with the contents. Introducing the `fingerprint_sciprt is not empty AND populate_sciprt is not empty AND reupload_on_changes == false` logic seems a bit too magical IMO. I think we can introduce a helper for the parser like `upload_caches` for users to explicitly require to upload caches at some point in the task execution process:


```yaml
task:
  foo_cache:
    ...
  bar_cache:
    ...
  upload_caches:
    - foo
    - bar
  script: ...
  # other buissness
```

If `upload_caches` is not defined then the behavior will be as it is now: upload in the very end.

**Comment by edigaryev** [comment]
New `upload_cache` instruction proposed by @fkorotkov above is now generally available on Cirrus Cloud.

Documentation: https://cirrus-ci.org/guide/writing-tasks/#manual-cache-upload
