### ISSUE TITLE
Setting a task's `name` generates a warning

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#885]
## Expected Behavior

When the `name` field is used to give a task a more nicely formatted name, no warnings should be displayed. This field is documented on the [Writing Tasks](https://cirrus-ci.org/guide/writing-tasks/) page, so it should be possible to use it without warnings.

## Real Behavior

When the `name` field is used to give a task a more nicely formatted name, warnings are displayed on the build page.

For example, if we have the following task:

```yaml
BuildAndPush_task:
  name: Build and Push
  ...
```

The build page will show the following warning:

<img width="484" alt="Screen Shot 2021-07-15 at 11 13 11 AM" src="https://user-images.githubusercontent.com/1848731/125812290-908b11da-53b5-460c-9fb7-1cbf17004b75.png">

This is because the `parsingResult.issues` field for the `Build` loaded from the backend includes warnings for each task that has an overridden name.

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.com/build/5938419659440128

**Comment by RDIL** [comment]
In general, I would personally advise against using both the name field and syntactic sugar, as the priority of which is actually used could be changed in the future or interpreted differently by different programs.

**Comment by fkorotkov** [comment]
It's a result of this issue https://github.com/cirruslabs/cirrus-cli/issues/427 which was created because a user use `BuildAndPush` in `depends_on` rather then `Build and Push`.

@edigaryev should we add a bit more explanation. Or a fix suggestion like use `task:` instead of `BuildAndPush_task`?

**Comment by connorbrinton** [comment]
Got it, I didn't realize it's possible to not include a "syntactic sugar" name. Looking at [the docs history](https://github.com/cirruslabs/cirrus-ci-docs/commit/9c1e660f50cb75a015bcc798d510d8fe72ba2a6b) I'm not sure how I didn't know that :joy:

I agree that some additional explanation (or maybe a link to the docs?) with the warning message might be helpful

Thanks! 😄
