### ISSUE TITLE
Possibly misleading "issues found when parsing configuration"/recommendation messages

### ISSUE THREAD

**Issue by abravalheri** [cirruslabs/cirrus-ci-docs#887]
Hello, guys, sorry to bother with an issue :P 
I really like using CirrusCI and I think everything you do for the opensource community is simply amazing. Thank you very much for all the support.

I just would like to report something that might be a bit misleading, specially for users that don't have experience with YAML (please ignore if you don't think it is a problematic behaviour):

I noticed Cirrus is starting to display issues/warnings for tasks with an explicit `name`: https://cirrus-ci.com/build/5661872285286400.

![Cirrus Warning](https://user-images.githubusercontent.com/320755/126515434-424ee532-d92e-4d1f-a562-509e2d1ab241.png)

More specifically everytime I define a `name` attribute with a more verbose and descriptive/nice to read name for a task, Cirrus recommend me to change the YAML key the task is associated with to a simple "task" string.
The problem is that, if I have more than one task and I rename all of them to "task" they will end up overwriting each other (or at least this is how I understand standard YAML implementations work, you can see an example bellow - please let me know if I am wrong and Cirrus uses a different parsing behaviour)

![Example translating YAML to JSON](https://user-images.githubusercontent.com/320755/126514807-5e782cfc-b7ff-4ecb-bed5-fbd61fda6806.png)
*Example translating YAML with repeated keys to JSON via https://www.json2yaml.com/convert-yaml-to-json - the tasks overwrite each other and just the last one is left*

## Expected Behavior

I would argue that using `name` for providing a more descriptive/nice to read name while maintaining a unique YAML key for the task is not a reason for generating a warning/issue.

In fact it can be misleading and influence users to change their configs to a wrong configuration that does not work as intended.

## Real Behavior

Cirrus currently displays issues/warnings and ask users to rename all tasks with an explicit `name` to a simple "task" string. This is not appropriate because the tasks might end up overwriting each other.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: all
  - Task name: all tasks with an explicit `name`

**Comment by fkorotkov** [comment]
Hey @abravalheri, thank you for the kind words and descriptive issues.

The roots of the warning originates from https://github.com/cirruslabs/cirrus-cli/issues/427 where a user did use a wring name in the `depends_on` field and was confused why in your case `typecheck` won't work but instead you need to use `typecheck (Linux 3.8)`.

Cirrus is using a bit more relax YAML parser that allows multiple keys. For example, for `task`s and especially for a `matrix` like this:

```yaml
container:
  matrix:
    image: node:latest
    image: node:lts
```

The warning just warns about the potential issue with name. That the task is named twice and that the name from `name` field will override the name from `*_task` notation.

**Comment by abravalheri** [comment]
Thank you very much for the clarification @fkorotkov.

That is also a bit confusing 😅 
The YAML specs seem to [require keys to be unique to consider a document valid](http://yaml.org/spec/1.2/spec.html#key):

> The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique. 

> JSON's RFC4627 requires that mappings keys merely “SHOULD” be unique, while YAML insists they “MUST” be. Technically, YAML therefore complies with the JSON spec, choosing to treat duplicates as an error. In practice, since JSON is silent on the semantics of such duplicates, the only portable JSON files are those with unique keys, which are therefore valid YAML files.

> Since YAML mappings require key uniqueness...

Which makes some linters (such as the `check-yaml` hook on [pre-commit](https://pre-commit.com/) to throw errors when I change the `.cirrus.yml` to comply with the warnings' suggestions and try to commit:

```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

Traceback (most recent call last):
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/check_yaml.py", line 63, in main
    load_fn(f)
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 122, in get_single_data
    return self.construct_document(node)
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 132, in construct_document
    for _dummy in generator:
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 722, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 446, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 264, in construct_mapping
    if self.check_mapping_key(node, key_node, mapping, key, value):
  File "/home/abravalheri/.cache/pre-commit/repoaikvnq27/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in ".cirrus.yml", line 3, column 1
found duplicate key "task" with value "{}" (original value: "{}")
  in ".cirrus.yml", line 75, column 1
```

I suppose I will have to give up YAML linting...

**Comment by abravalheri** [comment]
Please notice the warnings also appear when using Starlak and returning a dictionary from `main` (example: https://cirrus-ci.com/build/5051180951797760).

Returning a full dict is useful when we want to include top level elements other than tasks (e.g. `pipe`, `env`, `docker_builder`)

**Comment by fkorotkov** [comment]
I've created https://github.com/cirruslabs/cirrus-cli/issues/444 to add functionality to ignore such lint-like issues. And in the meantime I've [changed the logic to auto-expand the issues only on errors and not warnings](https://github.com/cirruslabs/cirrus-ci-web/commit/fd4f08e07b8551f8ab02bccc1ab9aa1938875127).

**Comment by abravalheri** [comment]
Thank you very much @fkorotkov.

I was looking into an alternative also: embrace completely the repeated keys and use Starlark to produce them, but them I run into the limitations of the allowed values for `main` (either a list of task dicts or a top level instructions dict, which in Starlark cannot contain repeated keys).
So I ended up proposing yet another PR https://github.com/cirruslabs/cirrus-cli/pull/445 😝
