### ISSUE TITLE
Starlak docs indicate `script` helper can be used with a single argument

### ISSUE THREAD

**Issue by abravalheri** [cirruslabs/cirrus-ci-docs#889]
Cirrus' [starlak guide](https://cirrus-ci.org/guide/programming-tasks/#writing-starlark-scripts) seem to indicate that `script` helpers can be invoked with only one argument, as shown in the example (taken from the docs):

```python
load("github.com/cirrus-modules/helpers", "task", "container", "script")

def main(ctx):
  return [
    task(
      instance=container("debian:latest"),
      instructions=[script("make")]
    ),
  ]
```

```yaml
# Expected output
task:
    container:
      image: debian:latest
    script: make
```

By looking at the [implementation](https://github.com/cirrus-modules/helpers/blob/59171b596e197112b13fdd7fc31a774b6f02dc94/lib.star#L33:L36), currently the `script` helper would produce something similar to:
```python
{"make_script": []}
```

I have created a PR on the `cirrus-modules` that should make the helper behave as documented:
https://github.com/cirrus-modules/helpers/pull/5

(Sorry, I ended up developing it on top of [a previous PR](https://github.com/cirrus-modules/helpers/pull/4) that adds another few instructions for powershell/background scripts, windows containers and macos/freebsd instances. Please let me know if you prefer to just have a PR with a single commit targeting only the `script` helper).

**Comment by fkorotkov** [comment]
I'be merged your PR. Thank you! 🙌
