### ISSUE TITLE
pull_request in notifications

### ISSUE THREAD

**Issue by xavierbourguignon** [cirruslabs/cirrus-ci-docs#89]
in notifications, I would like to know if the build has been triggered from a branch or a PR

from a branch, the build payload is great:
```
"build": {
    "id": 5767495879229440,
    "branch": "{branch_name}",
    "changeIdInRepo": "cdae94bc350a65abed02a2b3c9b7263a6a96a8ad",
    "changeTimestamp": 1541147155000,
    "status": "COMPLETED"
  }
```

from a PR, it could be:
````
  
"build": {
    "id": 5767495879229440,
    "pull_request": "pull/{PR_id}",
    "changeIdInRepo": "cdae94bc350a65abed02a2b3c9b7263a6a96a8ad",
    "changeTimestamp": 1541147155000,
    "status": "COMPLETED"
  }
```

**Comment by fkorotkov** [comment]
Added `pullRequest` integer filed. It will be presented if it's a build for a PR. Change should be auto-deployed soon. Will make sure it's properly propagated this time. 😅
