### ISSUE TITLE
The [skip ci] option shouldn't count as CIRRUS_LAST_GREEN_CHANGE

### ISSUE THREAD

**Issue by leshik** [cirruslabs/cirrus-ci-docs#891]
# Description

Don't use git commit sha for the `CIRRUS_LAST_GREEN_CHANGE` env variable if `[skip ci]` option was used.

# Context

Right now it's possible to work around the failed build by just updating e.g. `README.md`, and setting `[skip ci]` in the commit message. This breaks setups that use the `CIRRUS_LAST_GREEN_CHANGE` env to e.g. lint only changed files, or in case the suite is skipped completely if there are no changes to some specific files.

**Comment by fkorotkov** [comment]
Skipped builds should be ignored now while calculating last green build.
