### ISSUE TITLE
Dockerfile as a CI environment: custom PATH arg

### ISSUE THREAD

**Issue by JeremyRand** [cirruslabs/cirrus-ci-docs#893]
# Description

When using a Dockerfile as a CI environment, it would be useful to be able to specify the `PATH` argument that gets passed to `docker build`.  (Currently it always uses the Git repository root.)

# Context

We already have Dockerfiles that expect to be built with a `PATH` argument that's a subdirectory of the Git repo; we'd like to be able to reuse these Dockerfiles on Cirrus without modifying them.

# Anything Else

If this is already supported, it would be nice for it to be documented with example syntax.

**Comment by fkorotkov** [comment]
Just to clarify. You mean building the `dockerfile` in a custom working dir and not from the repository root as the `pwd` for the `docker build`?

**Comment by JeremyRand** [comment]
> Just to clarify. You mean building the `dockerfile` in a custom working dir and not from the repository root as the `pwd` for the `docker build`?

That's correct.  The manpage for `docker build` has an optional argument called `PATH`, which defaults to the output of `pwd` if it's omitted.  So yeah, I think we're talking about the same thing -- I'd like that argument's value to be customizable.

**Comment by fkorotkov** [comment]
You can try to use `CIRRUS_DOCKER_CONTEXT` variable that will specify a custom working dir for the Docker pre-built.
