### ISSUE TITLE
Inline dockerfile directive

### ISSUE THREAD

**Issue by abravalheri** [cirruslabs/cirrus-ci-docs#897]
Cirrus [docs](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment) describes a technique to "increase effectiveness" of tasks, by using custom docker images (that can be cached).

The downside of that approach is that we need to write a separated `Dockerfile`.
It would be nice to be able to define the `Dockerfile` inline (as a YAML string).

# Context

I believe in the majority of the cases, Cirrus users just want to add a few packages/CLI tools instead of creating a completely custom image. Therefore an inline `Dockerfile` can be quite handy and easier to maintain (if you want to write a new task step and need a different CLI tool, you can just scroll up and add it to the inline `Dockerfile`).

An hypothetical example would be

```yaml
docs_task:
  container:
    dockerfile_content: |
      FROM python:3.9-buster
      RUN apt-get update && apt-get install -y git enchant
  test_script: ...
```

Please notice `dockerfile_content` is just a suggestion. It could be anything actually (e.g. `inline_dockerfile`, `dockerfile_contents`, etc...)

# Anything Else

Lately, I have been playing with Starlark configs for CirrusCI, and the nicest thing in Starlark is the ability of re-using/sharing tasks between repositories. I haven't tried yet, but I suppose that when sharing a Starlark task that uses a `dockerfile` directive, the path for the file is resolved in the final/target repository that is being evaluated in the Cirrus CI, not the repository where the Starlark task is defined. This would mean that tasks using the `dockerfile` directive cannot be easily shared using Starlark, right?

If this assumption is true, I think being able to define the `Dockerfile` contents inline would improve "shareability" of tasks written in Starlark.

I suppose that one alternative would be having a `fs.write` function available in Starlark. This way we could just write a `Dockerfile` in the disk that could be then be used in the task.

**Comment by fkorotkov** [comment]
We think this will be an over complication of the feature. If images should be sharable it seems they are not repository specific and it's better then to share them as a standalone images on Docker Hub or GitHub Packages.
