### ISSUE TITLE
Support AArch64 FreeBSD VMs

### ISSUE THREAD

**Issue by emaste** [cirruslabs/cirrus-ci-docs#906]
# Description

Add FreeBSD/arm64 VM instances.

# Context

We have an interest in building and testing FreeBSD itself, as well as downstream projects, on AArch64/arm64. Downstream projects of particular interest are languages, runtimes, and toolchains (go, jdk, python, etc.)

# Anything Else

FreeBSD provides AWS VM images for Graviton instances.

Some links:
- https://aws.amazon.com/about-aws/whats-new/2021/02/aws-graviton2-based-m6g-c6g-r6g-instances-available-additional-regions/
- https://klarasystems.com/articles/the-next-level-freebsd-on-arm64-in-the-cloud/

**Comment by fkorotkov** [comment]
FYI we've added `architecture` field to custom VMs so if there is an arm64 FreeBSD image on GCP than you can already use it.

**Comment by probonopd** [comment]
> if there is an arm64 FreeBSD image on GCP

So I think we need to check with Google Cloud Platform whether they have an arm64 FreeBSD image now.

Having to separately check which images are available via Google Cloud Platform has always stuck me as annoyingly complicated; could a page be made on https://cirrus-ci.com/ that would show the images available via Google Cloud Platform?

**Comment by asomers** [comment]
> I don't think it is possible unless you need to fix gVNIC problem. the gVNIC network interface driver is still cause kernel panic

Link please?

**Comment by koobs** [comment]
> > I don't think it is possible unless you need to fix gVNIC problem. the gVNIC network interface driver is still cause kernel panic
> 
> Link please?

likely https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279410

resolved and mfc'd cc @delphij
