### ISSUE TITLE
White screen 

### ISSUE THREAD

**Issue by Apon77** [cirruslabs/cirrus-ci-docs#907]
## Expected Behavior

It should show logs properly 

https://cirrus-ci.com/task/5543084311183360

## Real Behavior

But it's not showing logs and showing white screen.. 

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page:
- [ ] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Fixed via https://github.com/cirruslabs/cirrus-ci-web/commit/830c0345b4059c7dcf801214c985348186862199

**Comment by Apon77** [comment]
> Fixed via [cirruslabs/cirrus-ci-web@830c034](https://github.com/cirruslabs/cirrus-ci-web/commit/830c0345b4059c7dcf801214c985348186862199)

Great!
Thank you.
