### ISSUE TITLE
Increasing max timeout_in

### ISSUE THREAD

**Issue by trombik** [cirruslabs/cirrus-ci-docs#912]
# Description

Increasing max `timeout_in`.

# Context

cirrus-ci generously offers free tier for opensource projects (and FreeBSD support) without monthly quota. I appreciate it. as a porter of FreeBSD packages, I had been looking for a solution to test my ports in CI. now it is possible to run [poudriere](https://github.com/freebsd/poudriere) on cirrus-ci. one of my port is a toolchain for embedded device; GCC and its friends. I am trying to workaround the two-hours-per-task limit by dividing the build process with `matrix`. however, when a single build takes more than two hours, there is no option to workaround. I guess that the hard-limit is to kill hanged jobs, or to prevent abuses. probably, i am one of minority that need longer `timeout_in`.

# Anything Else

thanks for supporting FreeBSD.

**Comment by RDIL** [comment]
Is there no way to split the compute load across multiple tasks in the build?

**Comment by trombik** [comment]
@RDIL that's what exactly I did. I need to build four GCC toolchains in the CI. with `matrix`, you can split it, but when one GCC build takes more than two hours, then, no. to workaround the limit, i also enabled parallel make in the build, which makes debugging difficult (log lines are mixed). i can live with this downside for now, but what if cross-compiling for different arch on QEMU? the overhead is quite noticeable.

i do understand there should be a limit, and do know it would be too much asking if i asked this to build web browser (takes days on my build machine). from my experience, i can think of quite a few projects that take more than two hours to build.

probably, this use-case is rare. but there are, certainly, projects that need longer `timeout_in`.

**Comment by RDIL** [comment]
Hmm, that does sound problematic.  You will probably need to wait for the verdict of somebody who works at Cirrus.

**Comment by fkorotkov** [comment]
@trombik does it take more than 2 hours even with 8 CPUs?

**Comment by trombik** [comment]
@fkorotkov with parallel build (make -j8), no, it does not. the problem is, the output from each make is mixed, and you often have to run `make -j1` to see what exactly is failing.

okay, another question: does `timeout_in` apply to "restart task with terminal access"? if no, i can workaround the limitation by the following workflow:

* the CI runs and fails
* manually run the failed task with terminal access
* run the build process without parallelism (make -j1) to see where the error happens

**Comment by trombik** [comment]
turned out that the terminal session is closed somehow after unknown time period. after running a command to build, the session terminated and was removed.

**Comment by trombik** [comment]
looks like the terminal is killed after 600 sec

```
Waiting for the terminal session to be inactive for at least 600.0 seconds
```

**Comment by fkorotkov** [comment]
Closing since we are not planning to change the timeout limits for now. Note that tasks using compute credits doesn't have the timeout limitation.
