### ISSUE TITLE
artifacts returns `Error from upload stream: rpc error: code = Unknown desc = `

### ISSUE THREAD

**Issue by trombik** [cirruslabs/cirrus-ci-docs#913]
## Expected Behavior

What should have happened is `artifacts` uploads files.

## Real Behavior

What ended up happening was ...

the following snippet:

```yaml
  packages_artifacts: |
    path: "packages/All/binutils-esp32ulp*"
    type: application/octet-stream
```
ends up with:

```
Error from upload stream: rpc error: code = Unknown desc = 
```

the pattern matches a file, `binutils-esp32ulp-2.28.51.20191205.txz` and the file is there. interestingly, similar `artifacts` just works (`/tmp/cirrus-ci-build/logs/*.log`)

see the log at https://cirrus-ci.com/task/5852421034344448?logs=packages#L1

# Related Info

i am in no way a go expert, but, after following the source, i found `grpc-go` included suspicious PR in v1.38.1, while the agent is using 1.38.0.

https://github.com/grpc/grpc-go/releases/tag/v1.38.1

> internal/transport: do not mask ConnectionError (#4561)

https://github.com/grpc/grpc-go/pull/4561

maybe related?

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS:  FreeBSD
  - Task name: `build_task`
  - Script/cache name (if applies): `packages_artifacts`

**Comment by trombik** [comment]
@edigaryev was it deployed?

**Comment by edigaryev** [comment]
> @edigaryev was it deployed?

It is now. Can you re-run it to see if anything changed?

**Comment by trombik** [comment]
the same job reports the same error message. aside from the issue, it's interesting that while the library reports the error, but the UI says none.

**Comment by trombik** [comment]
as pointed out in the PR, it was `|` that caused the issue.

wrong:

```yaml
  packages_artifacts: |
    path: "packages/*"
```

correct:

```yaml
  packages_artifacts:
    path: "packages/*"
```
