### ISSUE TITLE
Task was canceled while scheduling was delayed 

### ISSUE THREAD

**Issue by trombik** [cirruslabs/cirrus-ci-docs#917]
## Expected Behavior

the task executes.

## Real Behavior

the task was canceled while scheduling was delayed. 

https://cirrus-ci.com/task/6609847861903360

three issues:

* the reason, why the task was canceled, is not shown
* although it says "Scheduling was delayed due to a concurrency limit on community tasks", there was no other tasks (double-checked)
* no way in the UI to see which task is currently running in which repository

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x ] Task issue
  - OS: FreeBSD
  - Task name: publish
  - Script/cache name (if applies): N/A

**Comment by trombik** [comment]
indeed, it does... i never noticed the icon. what about "no way in the UI to see which task is currently running in which repository"?

**Comment by fkorotkov** [comment]
Yeah, there is an existing feature request for that #355
