### ISSUE TITLE
System time on `big_sur_base` VM is one week behind

### ISSUE THREAD

**Issue by bbannier** [cirruslabs/cirrus-ci-docs#918]
## Expected Behavior

I expect the system time in all tasks to be somewhat correct so that e.g, build systems based on timestamps correctly work locally, or e.g., cert timestamps are okay.

## Real Behavior

Looking at the time on VMs started for `big_sur_base` `os_x_instance`s, it seems to lag one week behind.

This causes issues with external resources when during downloads certificates from the future are encountered which cannot be validated, see e.g., zeek/zeek#1791.

* * *

This currently also  causes issues when building a CMake project with a Homebrew-installed `cmake`: due to a recent release of the Homebrew artifacts the files in that package currently have timestamps like

```
$ admin@admins-Mac build % ls -l /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in
-rw-r--r--  1 admin  admin  2979 Sep 20  2021 /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in
```

The build setup generated by CMake is timestamped with the local time:

```
$ admin@admins-Mac build % ls -l build.ninja 
-rw-r--r--  1 admin  staff  585891 Sep 13 18:17 build.ninja
```

Due to that such builds are always outdated and try to reconfigure themselves until the build setup is newer than all inputs:

```
ninja explain: output build.ninja older than most recent input /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in (1631582225469588131 vs 1632156232000000000)
```

* * *

There are probably more scenarios affected by this.
 
# Related Info

- [ ] Website issue
- [x] Task issue
  - OS: macOS

**Comment by fkorotkov** [comment]
It was a side effect of https://github.com/cirruslabs/osx-images/issues/38. It should be fixed now.
