### ISSUE TITLE
Bug: Search-text interpreted as regex pattern

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#92]
I was expecting the ``=~`` operator to treat the RHS as the pattern and LHS as the regex.  However, 
when using ``only_if: $CIRRUS_CHANGE_MESSAGE =~ 'something'``, if my PR description contains markdown (for example: ``***something***``), cirrus will give this error:

```
FAILED_PRECONDITION: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 997 ...cut...other...pr...text...
 ***something*** ^
```

The error suggests LHS is being interpreted as a regex pattern which is highly undesirable.

**Comment by cevich** [comment]
Real-world Example (will expire in 90-days): https://cirrus-ci.com/build/6309390627897344

**Comment by fkorotkov** [comment]
Just pushed a fix to master and it should become available within an hour. 🙌

**Comment by cevich** [comment]
@fkorotkov OMG you're too fast.  You won't even let me workaround the problem before you fix it :grinning:

**Comment by fkorotkov** [comment]
It was a quick fix! Better not to lay aside such low hanging fruits. 😅 BTW it's been deployed now.
