### ISSUE TITLE
GitHub API rate limit exceeded while config parsing

### ISSUE THREAD

**Issue by timwoj** [cirruslabs/cirrus-ci-docs#928]
## Expected Behavior

The task should have cloned the repo from git and run the build.

## Real Behavior

What looks like an error contacting Github to download the Dockerfile for the build:

```
failed to retrieve "ci/ubuntu-18.04/Dockerfile": failed to communicate with the GitHub API: GET https://api.github.com/repos/zeek/zeek/contents/ci/ubuntu-18.04/Dockerfile?ref=181ab51b120f2ec88619a26fe841dbccb5643776: 403 API rate limit exceeded for installation ID 5795895. [rate reset in 19m35s]
```

I ran a build immediately before this with nearly the exact same .cirrus.yaml, except using the normal `container` configuration and it started up correctly.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker (Ubuntu 18.04, `arm_container` instance)
  - Task name: `ubuntu18_task`
  - Task log: https://cirrus-ci.com/build/5861328276422656

**Comment by fkorotkov** [comment]
Interesting. We'll take a look shorty (cc @edigaryev). But in the meantime I have some bad news about `dockerfile` support for Arm containers. It's not yet supported (see #900).

**Comment by fkorotkov** [comment]
Closing the issue for now. Please reopen or comment if the issue will re-appeare.
