### ISSUE TITLE
monterey-xcode alias doesn't work

### ISSUE THREAD

**Issue by ckreibich** [cirruslabs/cirrus-ci-docs#936]
## Expected Behavior

According to [the macOS docs](https://cirrus-ci.org/guide/macOS/) this should work:

```
macos_instance:
  image: monterey-xcode
```

## Real Behavior

Cirrus [shows](https://cirrus-ci.com/task/5839558697811968):
```
Persistent worker failed to start the task: Parallels isolation failed: failed to create VM
cloned from "monterey-xcode": Parallels VM operation failed: failed to get info for VM
with "monterey-xcode" UUID or name: Parallels command returned non-zero exit code:
"Failed to get VM config: The virtual machine could not be found. The virtual machine
is not registered in the virtual machine directory on your Mac."
```
The VM gets off the ground if I use `monterey-xcode-13.1`.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: macOS
  - Task name: macos_monterey_task

**Comment by fkorotkov** [comment]
That should be working now. Sorry for the inconviniences!
