### ISSUE TITLE
Docker image prebuilds fail for images using glibc 2.34

### ISSUE THREAD

**Issue by ckreibich** [cirruslabs/cirrus-ci-docs#937]
## Expected Behavior

Images using the standard Fedora 35 image should work in Cirrus.

## Real Behavior

The container runs but the first symptom of trouble is that dnf is unusable. This looks as follows:

```
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64&countme=1 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
```

Example [here](https://cirrus-ci.com/task/4883949815070720).

# Related Info

This looks like a transient name resolution problem, but it's not. It's a symptom of [this glibc issue](https://github.com/moby/moby/pull/42836), tracked in a few different places. Docker on the Cirrus machine running the image prebuild needs to be updated prior to the build. If I re-run the prebuild with terminal access (I _love_ this feature!) then
- I can reproduce the problem: a `docker run -it fedora:35` drops me in a container that exhibits the problem. That's because Fedora 35 [has glibc 2.34](https://bugzilla.redhat.com/show_bug.cgi?id=1988199).
- An `apt-get update && apt-get upgrade docker` on the builder VM (pulling Docker from 20.10.9 to 20.10.10) fixes the problem: a subsequent `docker run -it fedora:35` produces a working container.

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker

**Comment by fkorotkov** [comment]
@ckreibich, thank you for the investigation! This commit https://github.com/cirruslabs/vm-images/commit/b3e4ad973c0430f63069b511042b0343dbd6098e should've rebuilt the VM used for Docker Builder and the prebuilt tasks.

**Comment by ckreibich** [comment]
Thank you for the quick turnarounds!
