### ISSUE TITLE
Ability to distinguish between files and directories in Starlark

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#938]
# Description

Currently Cirrus CI's Starlark support provides three filesystem-focused functions:
* `fs.exists`
* `fs.read`
* `fs.readdir`

Notably, it is an error to call `fs.read` on a directory and it is also an error to call `fs.readdir` on a file.

Since Starlark doesn't support exception handling (try/except), this means that it's not currently possible to recursively iterate over all of the files in a repository, since it's impossible to predict if calling `fs.readdir` will succeed or fail.

It would be great to have a function `fs.isdir`, that indicates whether the given filepath is a directory or not.

# Context

I'm working on developing organization-wide Starlark helpers to automatically generate Cirrus CI tasks based on the files present in each repository. In order to minimize the amount of work that other repository maintainers need to perform, I'm hoping to find a way to automatically choose which tasks to run based on the files present in the repository. The location of individual files is unpredictable, so I can't just test a fixed path to determine whether or not a task should be included.

# Anything Else

A workaround is to create many tasks (regardless of whether or not they're needed) and have the first step of each task determine whether or not the task is necessary based on the files in the repository, and set a variable indicating the result of that test. Then, by having all other script lines only execute if that variable is true, the same effect can be achieved.

This workaround isn't ideal though, since it requires lots of unnecessary tasks in many projects and complicates task code with conditional execution logic.

Another workaround is to have project maintainers pass in the set of relevant filepaths in their repositories to determine which tasks should be executed. While this list is likely to become out-of-date over time, I think it's probably the best option for now

**Comment by fkorotkov** [comment]
@connorbrinton `fs.isdir` should be available now. We've also added some extra caching to minimize GitHub API calls in use cases similar to yours when you walk the directories.

Having a generic organization level module that generates common tasks is exactly one of the use cases we've added Startlark support for. Please let me know if you'll have any issues/questions while working on this so we can improve support/documentation.

**Comment by connorbrinton** [comment]
> Please let me know if you'll have any issues/questions while working on this so we can improve support/documentation.

Hi @fkorotkov, I do have some feedback to share, though I'm not sure if this is the right place to share it. I'm happy to delete this comment and move it elsewhere if there's somewhere better for it 🙂

I've been trying to set up a shared Starlark module for my organization for the past month on and off, and ultimately have decided that the complexity of this approach would outweigh its benefits (at least for my organization). Most of the fundamental issues I ran into are related to the Starlark configuration language itself. Some of the major issues I ran into include:
* No `while` loops (in the default configuration), which means I can't iterate over an indefinite number of files in a repository--I have to iterate over a fixed number of filepaths and raise an error if I haven't checked every filepath.
* Related to the above, Starlark doesn't have exceptions or exception handling, so errors must be manually propagated up the stack and checked at every level.
* For some reason I wasn't able to get local imports to work from within the `cirrus-modules` repository, so I had to put everything in a single file
* Starlark is similar enough to Python that its lack of basic Python syntax features introduces friction in the development process. Some syntaxes unexpectedly only work in specific situations, such as calling with `*args`, which only works if only a _single_ variadic argument is passed to the function. Passing more than one variadic argument results in a Starlark syntax error.
* Standard library missing important functions such as filepath manipulation and text processing.

To get around some of these issues, I wrote the following helpers:
```starlark
###################
# General Helpers #
###################
load("cirrus", "re")

def merge_dicts(*args):
    merged = {}
    for arg in args:
        merged.update(arg)

    return merged


def merge_iterables(*args):
    merged = []
    for arg in args:
        merged.extend(arg)

    return merged


def posix_join(*components):
    # If we didn't get anything, return an empty string
    if not components:
        return ""

    # If we have just one component, return it
    if len(components) == 1:
        return components[0]

    # Normalize all components based on their position
    first_component = components[0].rstrip("/")
    last_component = components[-1].lstrip("/")
    middle_components = [component.strip("/") for component in components[1:-1]]

    # Combine all normalized components
    normalized_components = [first_component] + middle_components + [last_component]

    # Join them together
    joined = "/".join(normalized_components)

    return joined


def slugify(text):
    # Replace runs of non-alphanumeric (plus period, underscore and dash) characters with dashes
    dashed = re.sub("[^a-zA-Z0-9._-]+", "-", text)

    # Remove any leading or training dashes
    trimmed = re.sub("^-+|-+$", "", dashed)

    return trimmed
```

I also wrote a bunch of helpers for creation of tasks specific to my organization, which I had hoped would nicely abstract away unimportant concerns and simplify CI configuration files, but I found that `.cirrus.star` files ended up larger and more complex than the equivalent `.cirrus.yml` files.

Overall I found the process too cumbersome to roll out throughout my entire organization.

Going through this exercise though has helped me recognize some alternatives that I think would work well for my organization though. They may not work well for all organizations, but the two ideas I have in mind are:
* The ability to import YAML from a common repository (`cirrus-modules`?) within `.cirrus.yml` files, along with extensions to the Cirrus DSL to conditionally enable tasks based on repository properties (i.e., "does it have files matching this glob pattern?")
* The ability for an initial task to create new tasks. I'm imagining this would work by having the initial task output a YAML file in the `.cirrus.yml` format, which the Cirrus CI agent would parse and ask the backend to "add" to the existing build in progress. This would allow users to choose whatever language they're most comfortable with for task generation. 

  Presumably the decision to use Starlark was partially informed by its halting guarantees so that people didn't do annoying things like run cryptominers in the backend as part of configuration generation. By having tasks create other tasks, the issue can be sidestepped by using the same controls you use to prevent running tasks from abusing computing resources. Presumably there should be some recursion limit, which could probably be just 1 (only statically defined tasks can create dynamically defined tasks).


Hopefully some of these thoughts and feedback are useful! 🙂
