### ISSUE TITLE
Ability to load Starlark modules from private repositories

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#942]
# Description

It would be nice if it were possible to import Starlark modules from private repositories.

# Context

I'm developing a set of Starlark helper modules for my organization. They include sensitive information about our infrastructure setup, like the Docker image registry we use, the artifact registry we use, how we organize our service accounts, etc. Even with this information, attackers wouldn't be able to access any of our data without credentials, which we protect using Cirrus CI encrypted variables. However, we would prefer not to have this infrastructure information publicly available.

At the same time, we want to use shared Starlark modules to simplify CI configuration across all of our repositories. Currently we haven't been able to find a way to keep our shared Starlark modules private while also sharing them across multiple repositories (without code duplication).

# Anything Else

We're able to work around this while developing locally by using a git submodule pointing to the private helpers repository, but the Cirrus CI cloud service doesn't recurse into the submodule to retrieve the helpers. This workaround does, however, help us use the `cirrus` command-line tool to validate our configurations.

In the `cirrus` command-line tool, it seems to me that the code that would need to be modified to support authentication [is located here](https://github.com/cirruslabs/cirrus-cli/blob/84cb2317d37165e8651db03e50fac240145d6a25/pkg/larker/loader/git/git.go#L90-L109).

My personal priority ordering of aspects of this feature (from most to least important) would be:
1. Support in Cirrus CI's cloud orchestration service for authentication to other repositories to which Cirrus CI already has access
2. Support in the `cirrus` command-line tool for the easiest subset of authentication techniques to implement (maybe SSH private key authentication)
3. Support in the `cirrus` command-line tool for all `git` authentication methods, inheriting configuration from `git` itself as much as possible

**Comment by fkorotkov** [comment]
Right now, Starlark evaluator [uses `CIRRUS_REPO_CLONE_TOKEN`](https://github.com/cirruslabs/cirrus-cli/blob/88d761a583dad30491271d92219277bd577ba4e6/internal/evaluator/evaluator.go#L99) which is an [installation access token](https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app) for a particular repository. I think it makes sense to still use it for public repositories because of security reasons. But for private repositories we can start using a token that is not scoped and has access to all repositories.

**Comment by edigaryev** [comment]
> 1. Support in Cirrus CI's cloud orchestration service for authentication to other repositories to which Cirrus CI already has access

This might work for small organizations, but for an organization that has members with different access scopes to its repositories this provides a rather subpar solution in terms of security.

Would adding a [deploy key](https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys) to the private repositories of interest and passing it's private part to the Starlark via an environment variable work for you?

**Comment by connorbrinton** [comment]
> This might work for small organizations, but for an organization that has members with different access scopes to its repositories this provides a rather subpar solution in terms of security.

Is the threat model here that someone with access to repository A, but not repository B, might be able to load Starlark modules from repository B? Or I suppose that they could potentially look at Starlark error messages to probe the existence of particular files or something maybe. Or maybe there would be error messages revealing file contents. I can understand that concern.

> Would adding a deploy key to the private repositories of interest and passing it's private part to the Starlark via an environment variable work for you?

Only if it's possible to provide multiple deploy keys to a single Starlark invocation. I can imagine having Cirrus CI helpers and general Starlark helpers in separate repositories, and want to be able to handle loading chains like `Project` -> `Cirrus CI Helpers` -> `Starlark Helpers`

Potentially another way to alleviate this security concern would be to only allow users to load Starlark modules from a limited set of repositories configured by the Cirrus CI administrator. The implementation of this feature would probably be complex, so a potentially easier alternative would be to establish a specific repository name within organizations that other projects can access by default, similar to [how Renovate uses the `renovate-config` repository name](https://docs.renovatebot.com/config-presets/#organization-level-presets).

**Comment by fkorotkov** [comment]
@connorbrinton I like the renovate approach and was thinking about a similar thing but didn't know someone else is doing it. Thanks for pointing the renovate case. In that light, what do you thing of `cirrus-modules` name for a similar repository? It can be either public or private. 🤔

**Comment by connorbrinton** [comment]
@fkorotkov `cirrus-modules` sounds good to me!

**Comment by fkorotkov** [comment]
@connorbrinton `cirrus-modules` it is. We've identified a small issue with module loading which needs to be addressed first. But in the next couple of days we'll fix that and add support for `cirrus-modules`.
