### ISSUE TITLE
[question] How to control what package repository to use for FreeBSD?

### ISSUE THREAD

**Issue by yurivict** [cirruslabs/cirrus-ci-docs#943]
It appears to use the quarterly package repository by default, for example for [this .cirrus.yml](https://github.com/horizon-eda/horizon/blob/master/.cirrus.yml#L2).

I couldn't find in the documentation how to switch to the main (non-quarterly) package repository.

**Comment by fkorotkov** [comment]
Cirrus is using FreeBSD VMs that are available on Google Cloud. Maybe @emaste know the answer about how to switch the repo. 🤔

**Comment by emaste** [comment]
I pinged some folks on IRC to discuss a canonical way to do this but I think we don't have one yet. As @fkorotkov says this is really a FreeBSD question not a Cirrus question.

I have seen some projects modify the repo config in .cirrus.yml. Here's one example I found just now:
https://github.com/newsboat/newsboat/blob/8963a85b7382daeee74043b86b423739a711cde9/.cirrus.yml#L41
```
    install_script:
        # Make sure we use the same package repository for all images. Snapshots
        # (like 11.3-STABLE) default to latest, while releases default to quarterly.
        - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf        
        - pkg update -f
        - pkg upgrade -y
        - pkg install -y rust gmake rubygem-asciidoctor pkgconf stfl curl json-c ncurses openssl sqlite3 gettext-tools libxml2
```

**Comment by yurivict** [comment]
Ok, thanks.
