### ISSUE TITLE
Does [skip ci] still work?

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#948]
I just created a pull, but I had to manually cancel: https://github.com/bitcoin/bitcoin/pull/23731/checks

docs: https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution

**Comment by fkorotkov** [comment]
It's a caveat of a PR build. For PR builds `CIRRUS_CHANGE_MESSAGE` is set to "title + body" of the PR. In your case it doesn't contain `[skip ci]` and therefore was not skipped.
