### ISSUE TITLE
Cirrus CI hangs on scheduled.

### ISSUE THREAD

**Issue by rk134** [cirruslabs/cirrus-ci-docs#954]
## Expected Behavior

What should have happened is task should have continued as normal.

## Real Behavior

What ended up happening was task hangs on scheduled.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page: 
- [x] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name: Linux, custom docker image.
  - Link: https://cirrus-ci.com/task/6020032927891456

**Comment by fkorotkov** [comment]
The task is using th maximum amount of CPUs which results in longer scheduling times as described here in "Scheduling Times on Community Cluster" section here: https://cirrus-ci.org/guide/linux/
