### ISSUE TITLE
What mean to connect automatically cirrus-ci

### ISSUE THREAD

**Issue by erichirlemann** [cirruslabs/cirrus-ci-docs#96]
Willing to monitor the builds run by cirrus-ci, how to get an automaton to be authenticated on Cirrus-CI and let it run few GraphQL queries?
This automaton has a user & token to connect GitHub, how could it continue its path to get `cirrursUserID`  and `cirrusAuthToken`?

**Comment by fkorotkov** [comment]
There is no official API guidelines for such automations yet but it's coming next Monday! You'll be able to create an access token for your organization and use to interact with the API.

At the moment you can still get `cirrursUserID` and `cirrusAuthToken` from cookies by simply login as this user of your automation in a browser. It's not that convenient but as I mentioned the real API integration is coming next Monday.

**Comment by dbolkensteyn** [comment]
Any news on this @fkorotkov ? :)
