### ISSUE TITLE
doc improvement / bug: starlark doesn't have access to repo-level environment variables

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#962]
Hi,

Trying to work around  #960 I tried to do the conditional evaluation of environment variables from starlark. Unfortunately that doesn't work either.

I configured two environment variable overrides, FOO_DEV and FOO_MAIN, and then tried to set FOO from .cirrus.star depending on env['CIRRUS_BRANCH'].

## Expected Behavior

I expected FOO_DEV/_MAIN to be available in env.

## Real Behavior

I got an error accessing FOO_DEV/MAIN. As it turns out no environment variables, besides the ones cirrus sets itself, are available from .cirrus.star::main().

ISTM that that greatly reduces the usefulness of .cirrus.star as that'd prevent interacting with any services requiring secrets or such.

## Workaround

In this specific case I can work around the issue by returning ('env', {'FOO': '$FOO_MAIN'}) from .cirrus.star. Which then will be evaluated as part of the .cirrus.yml.

**Comment by edigaryev** [comment]
Sorry, this was closed automatically because the PR fixing this was merged. I'm going reopen this again until this gets deployed.

/cc @fkorotkov

**Comment by fkorotkov** [comment]
Has been just rolled out.
