### ISSUE TITLE
Bug: $CIRRUS_BRANCH is changed on tags

### ISSUE THREAD

**Issue by dschier-wtd** [cirruslabs/cirrus-ci-docs#963]
Today, I wanted to set up a small scenario like this:

- run simple tests on a branch
- run complex tests on main
- run integration tests on main with a tag

Unfortunately, the variable CIRRUS_BRANCH is changed to the tag number, if a tag is assigned. For example:

```
only_if:
  $CIRRUS_BRANCH != $CIRRUS_DEFAULT_BRANCH
```

The above will run for each tag AND PR/branch. Furthermore, one is not able to identify, if a tag is on the main branch or on some other branches.

## Expected Behavior

- $CIRRUS_BRANCH shows the branch where the tag is located
- $CIRRUS_TAG is solvable on the main branch

## Real Behavior

- $CIRRUS_BRANCH points to a "tag branch" and not the actual branch where the tag is provided.
- $CIRRUS_BRANCH is changed when a tag is used

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker

I would love to support you with more details, if needed.

**Comment by dschier-wtd** [comment]
Some minor additions, hopefully they are helpful.

### Screenshot

![image](https://user-images.githubusercontent.com/6490538/150679080-3c0384d0-a290-47db-858c-fc915ada4f75.png)

### Debug

Running a build with terminal access on a tagged release, I was able to check some environment variables.

- $CIRRUS_TAG is empty on the build on main
- $CIRRUS_BRANCH is $CIRRUS_TAG on the build that is named like the tag
- clicking the branch link in the CIRRUS-CI web interface also leads to a 404 GitHub page

**Comment by fkorotkov** [comment]
This should be working as you expected now. 🙌

**Comment by dschier-wtd** [comment]
This is awesome. I have tested in my pipelines, and it works like a charm. Thanks a lot for the quick fix.
