### ISSUE TITLE
Create Persistent Worker Pool

### ISSUE THREAD

**Issue by stupid-kid-af** [cirruslabs/cirrus-ci-docs#964]
Create Persistent Worker Pool

Create button is not working

I got this error
![image](https://user-images.githubusercontent.com/54206927/150512324-28d8296c-29d9-436e-aa56-fbd53a60bdc1.png)

**Comment by stupid-kid-af** [comment]
Any help????

**Comment by edigaryev** [comment]
Hello! Thanks for reporting this.

This issue will be addressed by https://github.com/cirruslabs/cirrus-ci-web/pull/428.

I've also had to close https://github.com/cirruslabs/cirrus-ci-web/issues/427 because it's a duplicate.

**Comment by stupid-kid-af** [comment]
Is it solved?

**Comment by edigaryev** [comment]
> @edigaryev Is it solved? For me it isn't Many bugs are there generated encrypted key but after reload nothing updates

Closing as worker pool creation should be working now.

Can you clarify a bit more what issues are you experiencing with the encrypted keys?
