### ISSUE TITLE
arm_container jobs do not show console outputs

### ISSUE THREAD

**Issue by adelton** [cirruslabs/cirrus-ci-docs#965]
My x86_64 job https://cirrus-ci.com/task/5817930305765376 shows the console output for all instructions (tasks).

A simple change `container` -> `arm_container` in https://github.com/adelton/mod_authnz_pam/commit/ad92b97ac677a48705ac17bdc0e6186036ecef6b causes https://cirrus-ci.com/task/6279458247147520 to miss all console outputs. The Download Full Logs button is present but for example https://api.cirrus-ci.com/v1/task/6279458247147520/logs/clone.log says
```
{"code":13,"message":"INTERNAL"}
```

Being able to see console output even for `arm_container` would be really useful.

**Comment by fkorotkov** [comment]
There is an infrastructure issue around S3 buckets. I've manually fixed it for you repository while we are working on a long term solution.

**Comment by fkorotkov** [comment]
The underlying issue was resolved. Thank you for reporting and sorry for the inconveniences!
