### ISSUE TITLE
Enable IPv6 for ARM cluster

### ISSUE THREAD

**Issue by carllerche** [cirruslabs/cirrus-ci-docs#969]
IPv6 is not currently enabled for the ARM cluster (ref: https://github.com/tokio-rs/tokio/pull/4450). IPv6 has been enabled for EKS recently (ref: https://github.com/aws/containers-roadmap/issues/835#issuecomment-1006804864). It sounds like you will need to create a new cluster and migrate all workloads to it.

**Comment by fkorotkov** [comment]
There were some hick-ups when I tried to recreated the cluster. Seems we'll first need to move to Terraform for the infra config. Our first version of the cluster was manually created and not quite reproducible. 😢

**Comment by taiki-e** [comment]
(The situation here may have changed with [the switch of ARM Linux runners from AWS to GCP](https://twitter.com/cirrus_labs/status/1668724692969046017).)

**Comment by fkorotkov** [comment]
Yeah, it should be supported now. @taiki-e thank you for the note!
