### ISSUE TITLE
Cryptic failure

### ISSUE THREAD

**Issue by kne42** [cirruslabs/cirrus-ci-docs#97]
Our [task](https://cirrus-ci.com/task/5664458229678080) failed with no message. We were running `pytest` on a `PyQt5` suite and it failed mid-process with no exceptions raised or anything.

This is an excerpt of the output:
```
pytest -v
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.0.0, py-1.7.0, pluggy-0.8.0 -- /root/conda/bin/python
cachedir: .pytest_cache
rootdir: /tmp/cirrus-ci-build, inifile:
collecting ... collected 2 items
gui/app/tests/test_napari_application.py::test_application_type 
```

Does this mean that the entire shell/machine crashed or something?

**Comment by fkorotkov** [comment]
@kne42 looks like the shell script returned with exit code `1` since `0` would've be success any other exit code would've be printed in the logs. Have you tried to rerun it?

**Comment by fkorotkov** [comment]
@kne42 could you please try to re-run again, another user had some similar unexpected errors because of containers running out of memory. For that, Cirrus CI just got a feature to detect Out Of Memory exceptions. I wonder if it will detect it on your builds. If not, I'll take a closer look.

**Comment by kne42** [comment]
Same problem occurs, unfortunately.

**Comment by kne42** [comment]
Thanks for checking this out @fkorotkov! Yeah, that gives me a pretty good idea of where to start looking for solutions :)

**Comment by fkorotkov** [comment]
Will close the issue for now. Please let me know when you'll find the issue and if Cirrus CI can help in detecting that kind of issues automatically.

**Comment by kne42** [comment]
I tried spinning up a Docker image and got a more detailed error message when using a Python prompt:
```python
root@ae839644616b:/tmp/napari-gui/gui/app# python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtWidgets import QApplication
>>> app = QApplication([])
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```
Seems to be an issue regarding running X11 applications in a linux Docker container.

Another error surfaces when trying to use the IPython `%gui` magic:
```python
root@ae839644616b:/tmp/napari-gui/gui/app# ipython
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %gui qt5

/root/conda/lib/python3.6/site-packages/IPython/terminal/pt_inputhooks/qt.py:22: UserWarning: The DISPLAY or WAYLAND_DISPLAY environment variable is not set or empty and Qt5 requires this environment variable. Deactivate Qt5 code.
  'The DISPLAY or WAYLAND_DISPLAY environment variable is '
```

**Comment by kne42** [comment]
Solved by following this guide: http://elementalselenium.com/tips/38-headless

**Comment by fkorotkov** [comment]
Interesting. Do you need to run something like `Xvfb`?

Here is an example how Puppeter project is using it: https://github.com/GoogleChrome/puppeteer/blob/master/.cirrus.yml#L9

```yaml
xvfb_start_background_script: Xvfb :99 -ac -screen 0 1024x768x24
```

**Comment by fkorotkov** [comment]
Awesome! Seems it was `Xvfb`! Glad you've found it!
