### ISSUE TITLE
repository settings for only users with admin rights

### ISSUE THREAD

**Issue by Apon77** [cirruslabs/cirrus-ci-docs#978]
Dear Sir,
I have a feature request. 
Is it possible to allow only allow admin users of a repository to go to its setting page in cirrus website so that write users can not change "Config resolution strategy" or "Require approval for builds from users without write permissions" ?

If yes please tell how, if no please implement this feature, it will be helpfull when a repository is written by many users. 

Thank you for your great ci service.

**Comment by fkorotkov** [comment]
I guess this might be a part of #76 but we don't have any plans to work on it right now.

For now if a user can push to a repository then it has almost full access to it. In case when you want to reduce user access I'd suggest to consider switching to [fork-based workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow).
