### ISSUE TITLE
Choco 429 error

### ISSUE THREAD

**Issue by JeremyRand** [cirruslabs/cirrus-ci-docs#991]
## Expected Behavior

Choco should work without errors.

## Real Behavior

Choco requests result in `The remote server returned an error: (429) Too Many Requests.`  E.g. https://cirrus-ci.com/task/6249218498101248?logs=choco#L8

# Related Info

It looks like Cirrus infrastructure IP ranges are hitting limits imposed by Choco infrastructure, causing 429 errors to randomly be returned when Cirrus instances try to issue Choco requests.  (This is happening enough that I often have to retry tasks a few times to get them to go through without 429 errors.)   I assume Choco has some procedure for requesting higher limits for shared infrastructure IP ranges; might be worth doing that.

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Windows
  - Task name:
  - Script/cache name (if applies):

**Comment by fkorotkov** [comment]
Indeed! Default for [the `use_static_ip`](https://cirrus-ci.org/faq/#ip-addresses-of-community-clusters) was flipped for the custom VMs so you were getting rate limited. Fixed it and now tasks should get unique IPs.

**Comment by JeremyRand** [comment]
Yes, is fixed, thanks!  :)
