### ISSUE TITLE
ld-elf.so.1: /usr/local/lib/perl5/5.32/mach/CORE/libperl.so.5.32: Undefined symbol "strerror_l@FBSD_1.6"

### ISSUE THREAD

**Issue by dwsteele** [cirruslabs/cirrus-ci-docs#994]
## Expected Behavior

The test should succeed.

## Real Behavior

```
cd .. && perl ${CIRRUS_WORKING_DIR}/test/test.pl --no-gen --make-cmd=gmake --vm=none --vm-max=2 --no-coverage --no-valgrind --module=command --test=backup
2022-04-13 21:33:27.285 P00   INFO: test begin on amd64 - log level info
2022-04-13 21:33:27.357 P00   INFO: configure build
ld-elf.so.1: /usr/local/lib/perl5/5.32/mach/CORE/libperl.so.5.32: Undefined symbol "strerror_l@FBSD_1.6"
```
See also https://cirrus-ci.com/task/4783572081967104?logs=main#L3

This was working a few days ago and even the last commit that worked now fails with this error. I could only find one hit for this issue which indicates it is (perhaps) a kernel issue: https://github.com/OpenSMTPD/OpenSMTPD/issues/1169

Was the FreeBSD 12.2 image updated recently?

Here is the task:
```
freebsd_12_task:
  freebsd_instance:
    image_family: freebsd-12-2
    cpu: 4
    memory: 4G

  install_script: pkg install -y bash git postgresql-libpqxx pkgconf libxml2 gmake perl5 libyaml p5-YAML-LibYAML rsync

  script:
    - cd .. && perl ${CIRRUS_WORKING_DIR}/test/test.pl --no-gen --make-cmd=gmake --vm=none --vm-max=2 --no-coverage --no-valgrind --module=command --test=backup

  debug_script:
    - ls -lah ${CIRRUS_WORKING_DIR}
```

# Related Info

This is a (tick one of the following):

- [X ] Task issue
  - OS: FreeBSD

**Comment by fkorotkov** [comment]
We don't manage the images but [it seems FreeBSD 12.2](https://www.freebsd.org/releases/). is not supported any more. Could you please try 12.3?

**Comment by dwsteele** [comment]
I can definitely do that, but might be good to have a clearer message when using an unsupported OS image. This cost me a fair amount of time in debugging.

**Comment by dwsteele** [comment]
OK, going to 12.3 or 13.0 works. Thanks!
