### ISSUE TITLE
Last build log

### ISSUE THREAD

**Issue by 5u623l20** [cirruslabs/cirrus-ci-docs#998]
# Description

What's the best way to get the last log of a task of a matrix?

# Context

I am trying to create a dashboard where we will have badges linked to the last buildlog of a particular task of a matrix. Tried to check the cctray format which only shows the lastlog of the main branch and not other branches. :(

**Comment by fkorotkov** [comment]
You will probably need to use [Cirrus GraphQL API](https://github.com/cirruslabs/cirrus-ci-web/blob/ac69239f452d44585c7b76bb325a3408de26d746/schema.gql#L965). Or you might try to change the task name as well as part of your matrix and then you can use the regular badge.
