### ISSUE TITLE
Check out branch even for PRs 

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#999]
# Description

Currently Cirrus CI fetches and checks out the code for PRs and branches in two different ways ([see code here](https://github.com/cirruslabs/cirrus-ci-agent/blob/b55ebe7c399dfd3ac68fb8d7eac5b031a9985f37/internal/executor/executor.go#L583-L673)). As a result, commands like `git rev-parse --abbrev-ref HEAD` or `git branch --show-current` give the branch name for branch builds, but not PR builds. We use this command to annotate our Kubernetes manifests with the source branch name, but it only works for branch builds. Additionally, some of the third-party tools we use run similar commands to retrieve branch information.

While we could change our internal tooling to use environment variables like `BRANCH` or `CIRRUS_BRANCH`, we can't modify our third-party tools to leverage these environment variables. It would be great if the Cirrus CI agent were able to set the currently checked out branch both for branch and PR builds somehow.

# Anything Else

Here are some logs from a branch build and a PR build for the same branch 🙂 

Branch build:
```
Cloning refs/heads/connorbrinton-test-git-environment...
...
Checked out eb0f0526b60cbd259a71923b9f9de1aed7d93065 on connorbrinton-test-git-environment branch.
```

PR build:
```
Fetching +refs/pull/142/head:refs/remotes/origin/pull/142...
...
Checked out eb0f0526b60cbd259a71923b9f9de1aed7d93065 on connorbrinton-test-git-environment branch.
```

**Comment by fkorotkov** [comment]
Closing this since we can't change the behaviour because of PRs from forks but there is a workaround if you sure there will be no such PRs.
